### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#1]
- [x] Debug - Return proper debug pages.
- [x] StaticFiles - Static file serving.
- [x] Routing - Request routing.
- [ ] Broadcast - Pub/Sub style broadcast.
- [ ] StrictASGI - Ensure ASGI compliance.
- [ ] Proxy - HTTP Proxying.
- [ ] CSRF, CORS, Sessions.

**Comment by jordaneremieff** [comment]
I had previously been refactoring the old uvitools into the new ASGI spec [here](https://github.com/erm/asgitools/tree/master/asgitools) that could help serve as a reference for some of these. There is also a base middleware implementation [here](https://github.com/erm/afiqah/blob/master/afiqah/middleware.py) that seems to work well, it based on the middleware in Channels [here](https://github.com/django/channels/blob/master/channels/middleware.py) and the guidelines in the spec [here](https://asgi.readthedocs.io/en/latest/specs/main.html?highlight=middleware#middleware).

**Comment by jordaneremieff** [comment]
May not specifically relate to middleware, but a GINO extension for Starlette may be something to look into: https://github.com/fantix/gino

**Comment by lovelydinosaur** [comment]
Okay, instead of this catch-all issue, let's take anything we want up in a specific issue/pr.
