### ISSUE TITLE
StaticFiles directory argument should take a PathLike instead of a str

### ISSUE THREAD

**Issue by kevinastone** [Kludex/starlette#1004]
It would be preferable to allow the `StaticFiles` app to use an `os.PathLike` so you can also provide `pathlib.Path` instances.  I can work on a PR if there's agreement.

**Comment by lovelydinosaur** [comment]
Sure thing, yup!

**Comment by Yobmod** [comment]
Hi, I know this is closed, but can the same be done for 'Jinja2Templates'?
