### ISSUE TITLE
set_cookie samesite

### ISSUE THREAD

**Issue by spencerfornaciari** [Kludex/starlette#1016]
Hey,
I've been working on setting the cookie in a response, and it worked, but I noticed in my javascript console that it had a warning saying that samesite was set to none. I remember the doc said it was to default to lax, but for whatever reason that wasn't working. No biggie I though, I'll just manually set it. When I go to set the samesite value I get an error despite it listing it as an option.

This is what I'm doing but it gives me an error. Removing samesite works.
`response.set_cookie("Test Token", "Some value", max_age=None, expires=None, path="/", domain=None, secure=False, httponly=False, samesite="lax")`

**Comment by ackinc** [comment]
Hello,

I'm not seeing this behaviour (cookie's samesite attribute defaulting to 'none' instead of 'lax') with starlette v0.14.2

```
def login(request):
    response = PlainTextResponse('Logged in')
    response.set_cookie('token', 'abc')
    return response

app = Starlette(debug=True, routes=[
    Route('/login', login)
])
```

^ The above results in the following set-cookie header in the login response: `set-cookie: token=abc; Path=/; SameSite=lax`

**Comment by euri10** [comment]
indeed, `lax' is the default
