### ISSUE TITLE
#792 only solve FileResponse encode problem,but still not work in StreamResponse

### ISSUE THREAD

**Issue by CyberQin** [Kludex/starlette#1019]
#792  do solve a pure FileResponse, but what i am doing is return StreamResponse and cumtom header,chinese fileName is still report error.
`response=StreamingResponse(
        r,
        media_type='application/vnd.google-earth.kmz',
        headers={
            "Content-Disposition": "attachment; filename={}.kmz".format(code)
        }
    )`

**Comment by em92** [comment]
Try this instead:
```python3
response=StreamingResponse( r, media_type='application/vnd.google-earth.kmz', headers={ "Content-Disposition": "attachment; filename*=utf-8''{}.kmz".format(code) } )
```

**Comment by CyberQin** [comment]
> Try this instead:
> 
> ```python
> response=StreamingResponse( r, media_type='application/vnd.google-earth.kmz', headers={ "Content-Disposition": "attachment; filename*=utf-8''{}.kmz".format(code) } )
> ```

the same result, i read the source code of response.py.
#792 change code in FileReponse function, won't affect Reponse and StreamReponse function. 
streamresponse still run code below, and encode('latin-1') cause the problem
`raw_headers = [
                (k.lower().encode("latin-1"), v.encode("latin-1"))
                for k, v in headers.items()
            ]`

**Comment by abersheeran** [comment]
https://tools.ietf.org/html/rfc6266#section-5 @HQDragon You need to look at the RFC, the ASCII encoding of the header is a must.

另外，我怎么突然感觉使用 starlette 的中国人变多了。是 fastapi 的原因？

**Comment by em92** [comment]
Sorry, I forgot to wrap filename using quote.
```python
from urllib.parse import quote
response=StreamingResponse( r, media_type='application/vnd.google-earth.kmz', headers={
    "Content-Disposition": "attachment; filename*=utf-8''{}.kmz".format(quote(code))
} )
```

**Comment by CyberQin** [comment]
> https://tools.ietf.org/html/rfc6266#section-5 @HQDragon You need to look at the RFC, the ASCII encoding of the header is a must.
> 
> 另外，我怎么突然感觉使用 starlette 的中国人变多了。是 fastapi 的原因？

I will try next time,  i use js-file-download do  downlowd job for now.
确实是因为fastapi的问题

**Comment by CyberQin** [comment]
> Sorry, I forgot to wrap filename using quote.
> 
> ```python
> from urllib.parse import quote
> response=StreamingResponse( r, media_type='application/vnd.google-earth.kmz', headers={
>     "Content-Disposition": "attachment; filename*=utf-8''{}.kmz".format(quote(code))
> } )
> ```

thank you, it worked
