### ISSUE TITLE
[FEATURE] Extend HTTPException

### ISSUE THREAD

**Issue by Fogapod** [Kludex/starlette#1025]
`HTTPException` currently is very minimal and only provides customization of status code and `detail` field.
`HTTPException` could inherit from `Response` and provide same customization capabilities. Aiohttp exceptions work this way and it's very convenient.

**Comment by abersheeran** [comment]
The HTTPException in starlette is used to process a certain status code uniformly, such as a uniform 403/404/500 page.
If you need more response information, you should use Response.

**Comment by Kludex** [comment]
This issue didn't attract much attention over those 1.5 years, so I'll be closing it.

The current way to handle the exceptions already cover this use case.

If new arguments are introduced, I don't mind reopening this issue.
