### ISSUE TITLE
Improve Documentation on Writing Custom ASGI Middleware and BaseHTTPMiddleware

### ISSUE THREAD

**Issue by erewok** [Kludex/starlette#1029]
In light of the issues and PRs relating to `BaseHTTPMiddleware` we need to improve the documentation on this middleware class and give some good guidance on how to write custom middleware. Documentation on this should include the following:

- A warning not to use `BaseHTTPMiddleware` with `StreamingResponse` or `FileResponse` endpoints.
- A note on how background will be evaluated with respect to `BaseHTTPMiddleware`.
- Instructions on how to write custom ASGI Middleware with example code (can be based on an [example from the codebase](https://github.com/encode/starlette/blob/master/starlette/middleware/authentication.py#L14)).
- A gentle suggestion to favor custom ASGI Middleware over subclassing `BaseHTTPMiddleware`.

See related issues and PRs:

- #919 
- #1012 
- #1022 
- #1028

**Comment by Kludex** [comment]
I think we should also document on how to create middlewares without `BaseHTTPMiddleware`.
