### ISSUE TITLE
More 'extras' installation targets

### ISSUE THREAD

**Issue by DrPyser** [Kludex/starlette#1032]
Hi!

The setup.py defines a `full` `extra_requires` target for installing starlette with all extra dependencies. 
https://github.com/encode/starlette/blob/c566fc6c819f0d565f8cff432351fe009e83d866/setup.py#L51-L62

This is nice if you want all extra dependencies, but I doubt that's the case for many people?

In my case, I'm only interested in the session middleware. 
I have to manually specify the extra dependency in my requirements along with starlette, even though I don't directly depend on it.
It would be nice to define `extra_requires` entries for the separate features as well, so that one can do `pip install starlette[session]` without needing to know which extra libraries are used for the feature(which could change in the future).

```
    extras_require={
        "full": [
            "aiofiles",
            "graphene",
            "itsdangerous",
            "jinja2",
            "python-multipart",
            "pyyaml",
            "requests",
            "ujson",
        ],
        "session": [ "itsdangerous" ],
        ...
    },
```

I could provide a PR.

**Comment by Kludex** [comment]
More than a year later, the number of extra dependencies shrank:

https://github.com/encode/starlette/blob/c8b9581e371968b4da42d0f2de01e4028d71ac3c/setup.py#L45-L53

I don't think adding more options here is needed, each feature will need only one requirement:
- `itsdangerous`: `SessionMiddleware`
- `jinja2`: templating
- `python-multipart`: form data
- `pyyaml`: schemas
- `requests`: `TestClient`

I think if we had something more complex, 2 requirements per feature or some markers around the requirements, we could add this, but as it's now, I think it's fine to install each one depending on what you want.

That being said, I'll close this issue. If anyone feels like we should come back to this discussion, feel free to create another issue or talk with us on our Gitter chat.
