### ISSUE TITLE
Exception handlers registration behavior

### ISSUE THREAD

**Issue by uriyyo** [Kludex/starlette#1034]
Should `Starlette` raise an exception when there are exception handlers for `500` status code and for `Exception` class?

For instance, in this case, only one of those handlers will be called.
```python
def handler_for_500(req, exc):
    ...

def handler_for_exception(req, exc):
    ...

app = Starlette(
    exception_handlers={
        500: handler_for_500,
        Exception: handler_for_exception,
    }
)
```

So my question - is this expected behavior or it is a bug?

**Comment by aminalaee** [comment]
Probably too late to help, but for the record, yes only one of them will be called.
Following `Starlette` initialization:

https://github.com/encode/starlette/blob/0081d46d85c71e8a8e35852104488d36e0e577fc/starlette/applications.py#L73-L86

So the second one will override `error_handler` but won't guarantee which one.

**Comment by Kludex** [comment]
The first question was not answered :thinking: 

> Should Starlette raise an exception when there are exception handlers for 500 status code and for Exception class?

I guess that was more the goal of the issue.

**Comment by aminalaee** [comment]
I thought this was the main goal 😄 
> So my question - is this expected behavior or it is a bug?

Anyway I think it wouldn't hurt to check if an `error_handler` is already set, and if so, throw a runtime warning. I can do a quick draft to get some feedback.

Or we could also set the first `error_handlder` and ignore any other after that.

**Comment by Kludex** [comment]
> Or we could also set the first error_handlder and ignore any other after that.

That's just transferring the _problem_.

I don't think we do any sacrifice doing the check, as we'll run it once, but... Is it necessary?

Well, it's been a year, let's ask the issuer. @uriyyo after more than a year, what are your thoughts about this issue? Do you think doing the check is still necessary?

**Comment by aminalaee** [comment]
Sorry I didn't explain that clearly.
What I meant is that we could consider a full stop with a `RuntimeError`, or have a warning saying already have an `error_handler` and ignore it.
 
Totally agree, let's wait for feedback.
