### ISSUE TITLE
[Bug (?)] UploadFile: 'SpooledTemporaryFile' object has no attribute 'seekable'

### ISSUE THREAD

**Issue by mlaradji** [Kludex/starlette#1036]
I'm not sure this is a bug. I might be missing something. It seems that `UploadFile.file` is missing the `seekable` attribute, which prevents it from being used in `httpx`.

#### To Reproduce (quick)
```python
import starlette.datastructures
starlette.datastructures.UploadFile("hello").file.seekable # AttributeError
```
#### Where does it arise?
```python
import starlette.datastructures
import httpx
file = starlette.datastructures.UploadFile("hello").file
httpx.post("https://google.com", files={"file": file}) # AttributeError: 'SpooledTemporaryFile' object has no attribute 'seekable'
```

#### Is it a bug?
The reason why I think this might be a bug or good to add is that, for the example I provided, it is very easy to fix:
```python
import starlette.datastructures
import httpx
file = starlette.datastructures.UploadFile("hello").file
file.seekable = lambda: True
httpx.post("https://google.com", files={"file": file}) # Should return 405 Method Not Allowed
```
I'm not sure if this has any unintended consequences.

Another reason I think it's a bug is that `tempfile.TemporaryFile` has the attribute `seekable`.

**Comment by wearp** [comment]
This is an [outstanding issue in Python](https://bugs.python.org/issue26175), which looks to have stalled. 

In summary, looking at the docs, it's fair to assume that `tempfile.TemporaryFile` behaves exactly like `Tempfile.SpooledTemporaryFile`. However, this is not the case. `TemporaryFile` returns an "_io.BufferedRandom" which implements the expected "file-like" interface [.readable, .seekable, ...etc]. `SpooledTemporaryFile` does not.

If you need a quick fix, calling `read()` could work:

```python
import starlette.datastructures
import httpx

spooled_tmp_file = starlette.datastructures.UploadFile("hello").file
file_as_bytes = spooled_tmp_file.read()
httpx.post("https://google.com", files={"file": file_as_bytes})
```

**Comment by mlaradji** [comment]
Hi @wearp. Thanks for your informative reply. Using `read()` will work for my use case; though it's not ideal for very large files.

I will close this issue as it seems to be a deep issue in Python. Thanks @wearp for your help.
