### ISSUE TITLE
Have mypy check types on test code

### ISSUE THREAD

**Issue by JayH5** [Kludex/starlette#1045]
As we do in other encode projects, we should run mypy against our test code to make sure the type annotations in the project work well when the project is actually used.

We do this not by adding type annotations to all the tests (as this is often not very useful for test code) but rather by using mypy's `check_untyped_defs` option. We usually have a mypy config like:

```ini
[mypy]
disallow_untyped_defs = True
ignore_missing_imports = True

[mypy-tests.*]
disallow_untyped_defs = False
check_untyped_defs = True
```

As of writing, enabling `check_untyped_defs` for the tests directory results in a lot of mypy errors which need to be fixed.

**Comment by graingert** [comment]
> ignore_missing_imports = True

is very bad. It's better to

`import some_annotated_thing # type: ignore` 

because `ignore_missing_imports` can lead consumers to accidentally use unexported types, 

also `# type: ignore` can have xfail behavior with:

https://mypy.readthedocs.io/en/stable/command_line.html?highlight=warn#cmdoption-mypy-warn-unused-ignores

**Comment by JayH5** [comment]
> is very bad.

I'd say that is an overstatement. There are various flags to make mypy stricter, yes, but we don't use all of them right now. There's a balance between having things "perfect" and the cost of implementation/maintenance.

There's room for improving mypy, but let's keep this issue specifically about the improvement of `check_untyped_defs = True` on for tests.

**Comment by rohitkg98** [comment]
There is a test in [test_datastructures.py#342](https://github.com/encode/starlette/blob/master/tests/test_datastructures.py#L342) which calls update on a MultiDict with None. None is not a permitted type in update. Should I instead make it permitted by making the type signature as `Union[Optional[MultiDict], ...rest of the types]`?

**Comment by JayH5** [comment]
> There is a test in test_datastructures.py#342 which calls update on a MultiDict with None.

It's not clear to me why that behaviour exists and I can't see any use of it anywhere else in the codebase. I think it should be fine to remove that test case unless someone knows why it's there?
