### ISSUE TITLE
How to edit response headers in pure ASGI middleware?

### ISSUE THREAD

**Issue by tomwojcik** [Kludex/starlette#1046]
I'm rewriting [my middleware](https://github.com/tomwojcik/starlette-context/blob/c31b0575b9b9f91aa0b1194e0347bb1a25c1c86e/starlette_context/middleware.py#L15) to pure ASGI. 

As `BaseHTTPMiddleware` follows the DRF pattern it has access to the response object in the `dispatch` method.
Your built in middlewares often do something with the response but it's usually because those responses are created in those 
 middlewares (error middleware etc).
I believe `SessionMiddleware` does something with the response headers (which is what I want to alter) but I struggle to understand what's happening there.

https://github.com/encode/starlette/blob/8729e9fc6964fe0299f67b13658a61c65af2b25b/starlette/middleware/sessions.py#L67-L73

Could anyone please hint me on how to add a response header in pure ASGI middleware?

Obviously I'd rather do things the old way. I'm changing it only because you started to discourage the use of `BaseHTTPMiddleware`. 

So far I came up with this but I have no idea how to access the response headers in this flow.

```python3
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):  # pragma: no cover
            await self.app(scope, receive, send)
            return

        _starlette_context_token: Token = _request_scope_context_storage.set(
            await self.set_context(scope)
        )

        try:
            await self.app(scope, receive, send)
        finally:
            _request_scope_context_storage.reset(_starlette_context_token)

```

Linking to #1029 as it's docs-related.

**Comment by jordic** [comment]
You need to create a new send, that wraps the original one, providing the headers you want, and finally calling the initial send. 
Look at https://github.com/encode/starlette/blob/master/starlette/middleware/sessions.py#L50

**Comment by tomwojcik** [comment]
I managed to achieve what I wanted but the docs are still lacking.

Thanks @jordic

**Comment by eirikur-nc** [comment]
If anyone ends up here while searching for how to do this, here's an example. 

```python
from starlette.datastructures import MutableHeaders
from starlette.types import ASGIApp, Message, Receive, Scope, Send


class CacheDisablingMiddleware:
    def __init__(
        self,
        app: ASGIApp,
    ) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        async def send_with_cache_control_header(message: Message):
            if message["type"] == "http.response.start":
                headers = MutableHeaders(raw=message["headers"])

                # Only disable caching if there is no existing Cache-Control header
                if not headers.get("Cache-Control"):
                    headers.append("Cache-Control", "no-store, must-revalidate")
            await send(message)

        await self.app(scope, receive, send_with_cache_control_header)
```
