### ISSUE TITLE
fix Unraisable ResourceWarnings

### ISSUE THREAD

**Issue by graingert** [Kludex/starlette#1050]
Hrm..we should probably fix these 🤔 curious that they all seem to be warnings for `family=AddressFamily.AF_UNIX`

_Originally posted by @JayH5 in https://github.com/encode/starlette/pull/1040#discussion_r484068578_

**Comment by graingert** [comment]
it looks like various objects are not used in context managers, or pass on the `__exit__` to their super class

**Comment by JayH5** [comment]
Possibly related: #947, #948
