### ISSUE TITLE
Unused worker parameter to WSGIMiddleware

### ISSUE THREAD

**Issue by cancan101** [Kludex/starlette#1061]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

The `WSGIMiddleware` `__init__` takes in a parameter, `workers` that is unused:
https://github.com/encode/starlette/blob/8dac5c2c7c986121f57c6741f01b1df300eb5faa/starlette/middleware/wsgi.py#L56-L59

### To reproduce

static inspection of source code

### Expected behavior

Either use the parameter, or mark it as deprecated.

### Actual behavior

no indication that the parameter is unused.

### Debugging material
n/a

### Environment
n/a

### Additional context
n/a

**Comment by euri10** [comment]
actually I think if memory serves correctly that it is used by uvicorn to setup the number of threads, feel free to reopen if that's not the case

**Comment by cancan101** [comment]
The `WSGIMiddleware ` implementation in uvicorn does appear to use this value (whereas starlette does not)
https://github.com/encode/uvicorn/blob/e77e59612ecae4ac10f9be18f18c47432be7909a/uvicorn/middleware/wsgi.py#L56-L59:
```python
class WSGIMiddleware:
    def __init__(self, app, workers=10):
        self.app = app
        self.executor = concurrent.futures.ThreadPoolExecutor(max_workers=workers)
```

**Comment by euri10** [comment]
I may be off about that but I think the WSGIMiddleware here is just here for testing purposes, so yes the workers kwarg isnt used, doenst mean it should be removed though

**Comment by cancan101** [comment]
re: used for testing, that isn't clear either. For example, [fastapi recommends using `WSGIMiddleware`](https://fastapi.tiangolo.com/advanced/wsgi/#using-wsgimiddleware) to mount a "WSGI application, for example, Flask, Django, etc." Their middleware is [just an import of the starlette middleware](https://github.com/tiangolo/fastapi/blob/e77ea635777d2494690ba3eb62bd005b9edeefde/fastapi/middleware/wsgi.py).

**Comment by cancan101** [comment]
Can we reopen this?
