### ISSUE TITLE
scope["server"] can be None

### ISSUE THREAD

**Issue by gdamjan** [Kludex/starlette#108]
From https://asgi.readthedocs.io/en/latest/specs/www.html#connection-scope

> server: A two-item iterable of [host, port], where host is the listening address for this server as a unicode string, and port is the integer listening port. Optional, defaults to None.

https://github.com/encode/starlette/blob/master/starlette/datastructures.py#L11 doesn't handle that option, it assumes scope["server"] is always a two-pair

**Comment by lovelydinosaur** [comment]
Good catch, thanks!
