### ISSUE TITLE
File upload -> 'rename'

### ISSUE THREAD

**Issue by doublex** [Kludex/starlette#1093]
Problem: Uploading huge file (GB) via http `PUT`.
After uploading the file should be stored using a cheap `rename` operation.
`SpooledTemporaryFile()` prevents renaming (we have to read and write the whole file.

Feature request: Add an option to use `NamedTemporaryFile()` instead.

**Comment by abersheeran** [comment]
I try it. Use `os.replace`/`os.rename` to save file form a `NamedTemporaryFile`. File will be deleted after file closed. 

Related links: 
- https://docs.python.org/zh-cn/3/library/tempfile.html#tempfile.NamedTemporaryFile
- https://docs.python.org/zh-cn/3/library/os.html#os.replace
