### ISSUE TITLE
Custom executor in run_in_threadpool

### ISSUE THREAD

**Issue by raphaelauv** [Kludex/starlette#1094]
As is asking https://github.com/encode/starlette/issues/980 for customizing the default executor and set a specific number of threads.

I would like to use a **ProcessPoolExecutor** and not a **ThreadPoolExecutor** since I have a CPU expensive compute operation and I don't want my main process ( starlette ) to be stuck with the GIL when this operation occur.

What do you think about this new feature ?

**Comment by lovelydinosaur** [comment]
For now I'd probably recommend that you handle the handover into the `ProcessPoolExecutor` directly yourself. For instance, have a standard async handler, that then dispatches to the executor.

That will allow you to control which endpoints invoke the process pool, and means we don't need core changes within Starlette itself to support the use-case.

**Comment by raphaelauv** [comment]
Thank for your answer @tomchristie  , I will do it myself since it's not a necessary change for starlette.
