### ISSUE TITLE
[Bug&Question]Responses encode using utf-8

### ISSUE THREAD

**Issue by icyw123** [Kludex/starlette#1098]
https://github.com/encode/starlette/blob/029882ee88e21495360c2290147a16f0af96ef81/starlette/responses.py#L70
source code:
`
raw_headers = [
    (k.lower().encode("latin-1"), v.encode("latin-1"))
    for k, v in headers.items()
]
`
Now all encode strings used in responses  are latin-1, but in my app, I want to response a streamingresponse with a CJK character filename. I have to change all 'latin-1' to 'utf-8' in this file. Is there anything wrong if I change it to 'utf-8' and why 'latin-1' must be used here. Sorry for my poor English

**Comment by Almyk** [comment]
I have the same issue, and found this:
https://github.com/encode/starlette/blob/029882ee88e21495360c2290147a16f0af96ef81/starlette/responses.py#L39
and changed all latin-1 occurences to ```self.charset```.
I don't know why it is strictly using latin-1 as encoding. They said in a closed issue (#425) that they have implemented to use whatever charset is set in ```Content-Type``` header, but it doesn't seem like it.

**Comment by abersheeran** [comment]
The HTTP Header encoding must be latin-1, which is an RFC standard. Charset configures the encoding of the response body.
