### ISSUE TITLE
Make FileResponse.chunk_size variable

### ISSUE THREAD

**Issue by postelrich** [Kludex/starlette#1100]
`FileResponse.chunk_size` is currently hardcoded to 4096. I was testing file transfer and noticed rather slow speeds compared to using scp to get the file. I increased the chunk_size and saw the speeds I was expecting. This should be configurable from `FileResponse.__init__`.

**Comment by lovelydinosaur** [comment]
Rather than making it configurable, I'd suggest we start by just improving the default. HTTPX uses 64k read sizes, which we selected based on actual download speed data. That's probably a better starting point for Starlette's file responses too.

**Comment by unnonouno** [comment]
Hi, I found the same issue when I'm using FastAPI. Do you have a plan to change the default chunk size?
