### ISSUE TITLE
Route priority and redirect_slashes inconsistency

### ISSUE THREAD

**Issue by qw-in** [Kludex/starlette#1105]
### Describe the bug

By default, `Router` will redirect requests that do not include the trailing slash. This behaviour breaks when adding, for example, `Route('/{path:path}')`. 

### To reproduce

```py
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route, Mount


async def items(request):
    return JSONResponse({'items': [1, 2, 3, 4]})


async def wildcard(request):
    return JSONResponse({'wildcard': True})


app = Starlette(
    debug=True,
    routes=[
        Mount('/items', routes=[Route('/', items, methods=['GET'])]),
        # Notice the behaviour of `/items` when adding and removing the below route
        Route('/{path:path}', wildcard, methods=['GET']),
    ],
)
```

### Expected behavior

When `Route('/{path:path}', wildcard, methods=['GET']),` is included, higher priority routes still function as expected. Specifically `GET /items` will still return a `307`.

### Actual behavior

When `Route('/{path:path}', wildcard, methods=['GET']),` is included, `GET /items` returns `{ wildcard: true }`

### Context

It is very confusing to add a lower priority route and have it break higher priority existing routes. Just to be more confusing it seems like it can even change the behaviour of methods the added wildcard route does not handle ('POST' for example).

**Comment by hillairet** [comment]
I suspect it's because of the automatic redirect on `/items` that is not hit if the wildcard one catches it ...
