### ISSUE TITLE
405 on all methods

### ISSUE THREAD

**Issue by mhenrichsen** [Kludex/starlette#1119]
### Checklist

- [ X] The bug is reproducible against the latest release and/or `master`.
- [X ] There are no similar issues or pull requests to fix it yet.

### Describe the bug
No matter what kind of REST call (GET, POST), the method always returns 405 Method not Allowed.

### To reproduce
```
from starlette.applications import Starlette
from starlette.routing import Route
from starlette.responses import JSONResponse
import uvicorn
import asyncio


async def model_predict(request):

    return JSONResponse({'hello': 'world'})


routes = [
    Route('/predict', model_predict, methods=['GET'])
]

app = Starlette(debug=True, routes=routes)

if __name__ == "__main__":
    uvicorn.run(app, host='0.0.0.0', port=8000)

```

### Expected behavior
Should return hello world

### Actual behavior
Returns 405 Method not Allowed

### Debugging material

NOTE:
INFO:     Started server process [4920]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:52065 - "POST /predict HTTP/1.1" 405 Method Not Allowed
### Environment

- OS: 
Py version: 3.7 & 3.8
Starlette version: 0.13.8 & 0.14.1

**Comment by JKAkabo** [comment]
Hello @mhenrichsen 
I reproduced your code and I got the expected response `{"hello": "world"}`.
Kindly check the client you're using to make the request to ensure that you're actually making a `GET` request. Because I don't see any `GET` request in your logs.

**Comment by espositofulvio** [comment]
Your route definition allows only 'GET'

Route('/predict', model_predict, **methods=['GET']**)

but uvicorn log only shows a POST request, hence the method not allowed response. Try changing the route definition:

```Route('/predict', model_predict, methods=['GET','POST'])```
