### ISSUE TITLE
GraphQL integration does not work w/ graphl-core versions > 2

### ISSUE THREAD

**Issue by mecampbellsoup** [Kludex/starlette#1144]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When following the [Starlette GraphQL docs](https://www.starlette.io/graphql/#sync-or-async-executors) regarding GraphQL integration, if you install `graphql-core` versions > 2 (i.e. non-[legacy core library](https://github.com/graphql-python/graphql-core-legacy)), you will see that the module `graphql.execution.executors.asyncio.AsyncioExecutor` no longer exists.

I asked about this in the [GraphQL core project](https://github.com/graphql-python/graphql-core/issues/121#issuecomment-787559191) and they indicated that as of `graphql-core >=3` the executors had been discarded as they were now async by default, roughly speaking (I'm paraphrasing, please see the issue I linked to for context).

I didn't see any open issues regarding support for the new `graphql-core` versions - is this in the works, by any chance? The legacy project is now unsupported.

### Environment

- OS: Linux (by way of minikube)
- Python version: 3.9.0
- Starlette version: 0.13.16

### Additional context

https://github.com/graphql-python/graphql-core/issues/121
https://github.com/graphql-python/graphql-core-legacy

**Comment by Kludex** [comment]
Starlette deprecated built-in GraphQL support.

Check #1135 for more details.
