### ISSUE TITLE
Add EmptyResponse class

### ISSUE THREAD

**Issue by declaresub** [Kludex/starlette#1178]
HTTP responses with status codes 1xx, 204, 205, and 304 are special cases.  1xx, 204, 304 responses must not include a message body.  The empty message body for 205 responses can be handled in a few ways, but the only one that would make sense for Starlette would be to add a Content-Length header with value 0.

Currently it is not at all obvious to users how to implement these responses.  Starlette can make it explicit with the addition of an EmptyResponse class that does the right thing for each of the status codes cited above.

The "right thing" differs by status code. The key difference is 

* 1xx, 204: must not have a Content-Length header
* 205: should have Content-Length: 0
* 304: may have a Content-Length header if the value equals the length of the corresponding 200 response that could have been sent.

Thus, an EmptyResponse object should ensure no Content-Length header in the first case, ensure Content-Length: 0 in the second case, and pass along a Content-Length header if supplied in the third case; here it is the caller's responsibility to get the value right.

In all cases, an EmptyResponse object would send an 'http.response.body' event with body: b'', more_body: False so that the ASGI server knows to begin sending the response.

The addition of an EmptyResponse class should resolve at least one open issue (https://github.com/encode/starlette/issues/1099).

**Comment by JayH5** [comment]
Initially I wasn't sure about this, but I'm warming up to the idea of an explicit `EmptyResponse` that handles these common cases correctly. So:
1. _"The "right thing" differs by status code."_: do we have some RFCs we can point to as proof?
2. I'd be up for reviewing a PR for this, or may give it a try myself if/when I find time.

**Comment by declaresub** [comment]
Here are links to the relevant RFCs.

1xx: https://datatracker.ietf.org/doc/html/rfc7231#section-6.2
204: https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.5
205: https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.6
304: https://datatracker.ietf.org/doc/html/rfc7232#section-4.1
content-length header: https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2

I would also be willing to take a crack at implementing an EmptyResponse class.

**Comment by lovelydinosaur** [comment]
Closing in favour of #1397
