### ISSUE TITLE
routes property returns None

### ISSUE THREAD

**Issue by old-syniex** [Kludex/starlette#1182]
### Checklist

- [X ] The bug is reproducible against the latest release and/or `master`.
- [ X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Elastic apm tries to collect information regarding the route by accessing routes property.
the implementations of BaseRoute such as Route, Mount says the return type is `typing.List[BaseRoute]`.
In case that the app doesn't have "routes" it will return None.

### Expected behavior

routes property will return empty list

### Actual behavior

routes property will returns None

### Debugging material
```python
@property
    def routes(self) -> typing.List[BaseRoute]:
        return getattr(self.app, "routes", None)
```

### Environment

- OS: Linux
- Python version: 3.9.4
- Starlette version: 0.14.2

**Comment by lovelydinosaur** [comment]
I can't replicate the issue you're describing?...

```python
>>> from starlette.applications import Starlette
>>> s = Starlette()
>>> s.routes
[]
```
