### ISSUE TITLE
Test client drops WebSocket query parameters

### ISSUE THREAD

**Issue by frankie567** [Kludex/starlette#1187]
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When using the method `websocket_connect` of `TestClient` to connect to a WebSocket, query parameters passed through the `params` argument are dropped.

It works if query parameters are hard-coded directly in the URL.
### To reproduce

```py
from starlette.testclient import TestClient
from starlette.websockets import WebSocket


async def app(scope, receive, send):
    assert scope['type'] == 'websocket'
    websocket = WebSocket(scope, receive=receive, send=send)
    await websocket.accept()
    await websocket.send_json(dict(websocket.query_params))
    await websocket.close()


def test_app():
    client = TestClient(app)
    with client.websocket_connect('/', params={"foo": "bar"}) as websocket:
        data = websocket.receive_json()
        assert data == {"foo": "bar"}  # Fails
```

### Expected behavior

The query parameters should be kept when passing them through the `params` argument.

### Actual behavior

The query parameters are dropped.

### Debugging material

The issue probably comes from the [prepare_url method in requests](https://github.com/psf/requests/blob/f6d43b03fbb9a1e75ed63a9aa15738a8fce99b50/requests/models.py#L373-L378). Indeed, if it detects a scheme different than `http`, it stops the URL preparation and thus drops the parameters.

The solution could be to encode them manually in `websocket_connect`, at the beginning:

https://github.com/encode/starlette/blob/d26f44b4aeaec63ae8ce0a4f34dea7439da48012/starlette/testclient.py#L434-L437

### Environment

- OS: macOS 11.3.1
- Python version: 3.7.10
- Starlette version: 0.14.2
- Requests version: 2.25.1

### Additional context

Since it works when directly putting them in the URL string, it's not a big deal; but I thought it could be worth documenting it since it puzzled me for quite some time.

**Comment by vladNed** [comment]
Is anyone working on this issue ? I would like to try and work on it.
