### ISSUE TITLE
The time returned by the request is different from the server time

### ISSUE THREAD

**Issue by rrsyycm** [Kludex/starlette#1193]
date Wed Jun  2 21:09:10 CST 2021
Date: Wed, 02 Jun 2021 13:07:50 GMT

**Comment by Kludex** [comment]
I'm closing this for housekeeping.

Feel free to recreate the issue following our [GitHub issue template](https://github.com/encode/starlette/issues/new?assignees=&labels=&template=2-bug-report.md).
