### ISSUE TITLE
Allow insertion of routes with higher priority than existing ones.

### ISSUE THREAD

**Issue by nickovs** [Kludex/starlette#1196]
## Is your feature related to a problem? Please describe.

It would be helpful to have a clean way to insert new routes and mounts at the front of the route list. Specifically, if one has a Starlette app created by a library and that app includes a catch-all route (i.e. `"/{path:path}"`) then currently it is impossible to add any more specific routes without delving into the internals of the router (e.g. `app.routes.insert(0, new_route)` ).

An example of a situation where this is a problem is when trying to add additional routes to an application created with [JustPy](https://github.com/elimintz/justpy). JustPy creates its Starlette app, complete with a catch-all route, when the library is imported, making it impossible to add an API for the app without direct manipulation of the route table.

## Describe the solution you would like.

Ideally `Router.add_route()` and `Router.mount()` (and possibly their corresponding reflections in the `Starlette` class) should have a flag, defaulting to `False`, to indicate that the route should be added with highest priority instead of lowest priority.

## Describe alternatives you considered

One alternative to expanding the API would be to explicitly document that direct manipulation of the list value in the `Starlette.routes` property is allowed. Doing this currently works, but it depends on the current implementation of the routing system and will break if that design were to change significantly. Adding the flag to the `mount()` and `add_route()` methods would allow for changes under the hood without breaking code.

## Additional context

My use case is specifically to do with trying to add additional routes to an application built with [JustPy](https://github.com/elimintz/justpy), but there are likely other libraries that behave in similar ways.

**Comment by Kludex** [comment]
This behavior is documented: https://www.starlette.io/routing/#route-priority

You can change the order on which you mount or add routes for your use case, can't you?

**Comment by nickovs** [comment]
@Kludex The problem is that JustPy creates the Starlette instance and adds its own routes before I get a change to touch the object, and one of those routes is a catch-all route. As a result, by the time I get to see the application any new routes added to the end will never be called. Inserting my routes to the front of the route list works fine, but it relies on manipulating an internal data structure. Having an official way to insert new routes at the front of the list would solve this case and be generally helpful when the user of the Starlette instance is not the creator of that object.

**Comment by Kludex** [comment]
As I said, you can mount that JustPy application:

```python
routes = [
    Route('/something', your_route), 
    Mount('/another', routes=just_py.routes),
]
```

**Comment by nickovs** [comment]
@Kludex Sorry, that suggestion was not at all clear in your first comment. Yes, I could potentially do that, and then add a route that redirects `/` to `/another` so that the application shows up at the route, except that there is currently a bug in JustPy which means that it won't work when it's not the root-level application (but I could fork and fix that).

Having said all that, is there a strong case for *not* providing more flexible insertion of routes into Starlette?

**Comment by Kludex** [comment]
> Having said all that, is there a strong case for not providing more flexible insertion of routes into Starlette?

Well, I guess it's more about not adding unnecessary complexity.

Also, as you said, it's a bug on `JustPy` that is in our path here. I guess your initial solution (`app.routes.insert(0, new_route)`) should take place here. :thinking: 

I'm closing this issue, but we're open to reconsideration if someone makes a compelling case.

**Comment by WolfgangFahl** [comment]
@Kludex  and @nickovs  - a few weeks i started being a maintainer of justpy and i am trying to fix the justpy problem.
JustPy used to have a cut&paste solution and add a "last" parameter to make sure the "catch all" route is added with lowest priority. The
```
routes = [
    Route('/something', your_route), 
    Mount('/another', routes=just_py.routes),
]
```
Isn't feasible for us at this point because many tutorial examples showed a different way to add routes and the decorator approach might be still in use a lot in the wild. My main problem at this point is that i could simply override the decorator since the decorator calls routes.add_route instead of  self.add_route. I had to override the decorator like this:
```python
 def route(
        self,
        path: str,
        methods: typing.Optional[typing.List[str]] = None,
        name: typing.Optional[str] = None,
        include_in_schema: bool = True,
    ) -> typing.Callable:  # pragma: nocover
        """
        We no longer document this decorator style API, and its usage is discouraged.
        Instead you should use the following approach:

        routes = [
            Route(path, endpoint=..., ...),
            ...
        ]

        app = Starlette(routes=routes)
        """

        def decorator(func: typing.Callable) -> typing.Callable:
            self.add_route(
                path,
                func,
                methods=methods,
                name=name,
                include_in_schema=include_in_schema,
            )
            return func

        return decorator
```
and still i don't have a proper solution for the precedence problem. It would be much easier if both the decorator problem and the priority handling would be added upstream.
the culprit line is just 

self.routes.append(route) ... it would be good to also allow for a "prepend". Otherwise the workaround is awkward since there is no information hiding and the router and all the technical details need to be exposed downstream.

```
def add_route(
        self,
        path: str,
        endpoint: typing.Callable,
        methods: typing.Optional[typing.List[str]] = None,
        name: typing.Optional[str] = None,
        include_in_schema: bool = True,
    ) -> None:  # pragma: nocover
        route = Route(
            path,
            endpoint=endpoint,
            methods=methods,
            name=name,
            include_in_schema=include_in_schema,
        )
        self.routes.append(route)
```

**Comment by WolfgangFahl** [comment]
I am currently trying this (IMHO ugly) approach:
```python
super().add_route(path,route,methods,name,include_in_schema)
        if name: 
            if name=="justpy_homepage":
                routes= self.router.routes.copy()
                last=routes[len(routes)-1]
                routes.remove(last)
                routes.insert(0,last)
                self.router.routes=routes
                pass
            else:
                JpRoute(path=path,endpoint=route,name=name)
        pass
```

**Comment by Kludex** [comment]
There's still no compelling case to reconsider the previous decision.

**Comment by manatlan** [comment]
Hi @WolfgangFahl 
Same need !

But ended with (subclassing): 
```python
    def add_route(self,*a,**k):
        """ insert route at the beginning ;-) """
        super().add_route(*a,**k)
        self.router.routes.insert(0, self.router.routes.pop() )
```

it's more pythonic
