### ISSUE TITLE
Routing app refinements

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#12]
* Include `HEAD` if `GET` is in `methods`.
* Set `Allow` header on responses.
* Respond to OPTIONS with 200 responses.

**Comment by jordaneremieff** [comment]
Would it make sense to extend the routing app with a simple convenience decorator? I replaced the routing in Afiqah using the Starlette routing components - could we have something like [this](https://github.com/erm/afiqah/blob/master/afiqah/routing.py) and [this](https://github.com/erm/afiqah/blob/master/afiqah/app.py#L33) here?

Example usage:

```python
@app.route("/")
def home(scope):
    return HTMLResponse("<h1>Hello</h1><p>World</p>")
```

**Comment by lovelydinosaur** [comment]
@erm I reckon so, yup.
