### ISSUE TITLE
Starlette docs has dead links, broken sitemap and missing redirection for http://

### ISSUE THREAD

**Issue by tomwojcik** [Kludex/starlette#1212]
It's not a bug with Starlette itself but I think it's the best way to let you know about the problem.

1. When you google `starlette exceptions` the first result is [https://www.starlette.io/exceptions/](https://www.starlette.io/exceptions/) which 404s. The correct URL would be [https://www.starlette.io/exceptions.html](https://www.starlette.io/exceptions.html).
2. Broken sitemap. `loc` is empty.
```
<url>
<loc>None</loc>
<lastmod>2021-06-23</lastmod>
<changefreq>daily</changefreq>
</url>
```

3. No proper HTTP -> HTTPS redirection.  http://starlette.io/ doesn't work.

These 3 issues combined make it more difficult to find proper sections of your docs using search engines.

**Comment by ArcLightSlavik** [comment]
^ This broke FastAPI docs that link to Starlette

**Comment by JayH5** [comment]
Thanks for the report. The broken links should now be fixed and I have a PR open to fix this for the next release as well.

The HTTPS redirect is not something I have permissions to fix but I'll try follow up with someone who does.

**Comment by ArcLightSlavik** [comment]
@JayH5 Thanks for fixing it so quickly 😄
