### ISSUE TITLE
Cannot define a custom HEAD handler in HTTPEndpoint

### ISSUE THREAD

**Issue by theblazehen** [Kludex/starlette#1221]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I am unable to set a custom head method for a HTTPEndpoint

### How to reproduce

Python:
```python
from starlette.applications import Starlette
from starlette.routing import Route
from starlette.responses import Response
from starlette.endpoints import HTTPEndpoint

class TestHandler(HTTPEndpoint):
    async def head(self, request):
        print("Called head")
        return Response("head")

    async def get(self, request):
        print("Called get")
        return Response("get")

routes = [
    Route("/", TestHandler),
]

app = Starlette(routes=routes)
```
Then run uvicorn, and call `curl -XHEAD localhost:8000/` and `curl -XGET localhost:8000/`

You will see in uvicorn logs, both times the get handler gets called.
```
Called get
INFO:     127.0.0.1:53438 - "HEAD / HTTP/1.1" 200 OK
Called get
INFO:     127.0.0.1:53440 - "GET / HTTP/1.1" 200 OK
```

### Expected behavior

When calling the HEAD method, it should invoke the head() function

### Actual behavior

When calling the HEAD method, it invokes the get() function

### Environment

- OS: Linux
- Python version: Python 3.9.5
- Starlette version: 0.15.0

### Additional context

The issue is caused by the following code:
https://github.com/encode/starlette/blob/master/starlette/endpoints.py#L26

It should see if there is a head method, and if so, don't call the get method when head is requested

Eg. linked issues, or a description of what you were trying to achieve. -->

**Comment by graingert** [comment]
does this work?

```python
    async def head(self, request):
        print("Called head")
        return Response("head")

    async def get(self, request):
        if request.method.lower() == "head":
            return await self.head(request)

        print("Called get")
        return Response("get")
```

**Comment by theblazehen** [comment]
Yes, that works. 

I've pushed a more general fix to a PR. Just need to sort out some formatting issues for tests to pass, then it should be good.
