### ISSUE TITLE
Typing differences between Starlette and Uvicorn

### ISSUE THREAD

**Issue by Gascognya** [Kludex/starlette#1249]
uvicorn.run(app) need typing: 'ASGIApplication'
[(the asgiref package)](https://github.com/django/asgiref/blob/main/asgiref/typing.py)

it's difference from typing of `Starlette.__call__(self, scope: Scope, receive: Receive, send: Send) -> None`

SO, IDE check and display a waring, about app
 `uvicorn.run(app, host="127.0.0.1", port=8080)`

**Comment by JayH5** [comment]
This issue is because we haven't solved #1217.

**Comment by Kludex** [comment]
If someone is eager, feel free to take over my PR. I don't feel like working on it any time soon.

**Comment by Kludex** [comment]
Even if the story is different, this is fundamentally the same as #1217.

For that reason, and housekeeping, I'm closing this issue.

Thanks for reporting it @Gascognya ! :)
