### ISSUE TITLE
Routing interfaces for `Router` and `Starlette` should match.

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#125]
We should probably hide away `Path` and `Include` as implementation details for now, and instead focus on making the app and router interfaces match up.

Eg:

```python
app = Router()

@app.route('/')
async def homepage(...):
    ...
```

or...

```python
app = Router()

app.mount('/admin', AdminApp)
app.mount('/articles', BlogArticles)
```

This'll mean that a `Router` instance strictly gives you a subset of the functionality that a `Starlette` instance offers.

Refs #122

**Comment by alexbotello** [comment]
I'll go ahead and work on implementing this when I get a chance.

Initial thoughts on tackling this would be to transfer the function logic into the `Router` class. `Starlette` can then wrap them in it's interface like so:
```python
def add_route(...)
    self.router.add_route(path, route, methods=methods)

def add_websocket_route(...):
    self.router.add_websocket_route(path, route)
```
