### ISSUE TITLE
SessionMiddleware may create malformed cookie

### ISSUE THREAD

**Issue by g-e-r** [Kludex/starlette#1259]
### Describe the bug

The cookie created may include "=" and be wrongly formatted, ignored by the browser.

### To reproduce

starlette/starlette/middleware/sessions.py:55
data = b64encode(json.dumps(scope["session"]).encode("utf-8"))

E.g. when scope["session"] = {"a":"bc"}
data becomes "eyJhIjogImJjIn0="
which generates a wrong cookie, ignored by the browser.

### Expected behavior

Equals sign should not be included in the cookie.

### Actual behavior

Equals sign might be included in the cookie.

### Environment

Python 3.9.6
MacOS
Starlette Version: 0.14.2

### Additional context

Actual cookie generated was something like this:

session=gICAgIH1cbiAgICB9XG59In0=.YQ5bnw.jlYF8N3XGf8tYCGDzrnZzW4BHPA; path=/; Max-Age=1209600; httponly; samesite=lax

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/1259">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/1259/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/1259/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
Bug confirmed.

Thanks for the PR, but I think we'd want to opt for the same strategy as other web frameworks, i.e. just quote it. 

You can see how Flask does here: https://github.com/pallets/werkzeug/blob/347fdbb055c86efe1fd49546bd524cde4b98c103/src/werkzeug/_internal.py#L327-L338

Note: Not really sure about what I said.

**Comment by g-e-r** [comment]
> Bug confirmed.
> 
> Thanks for the PR, but I think we'd want to opt for the same strategy as other web frameworks, i.e. just quote it.
> 
> You can see how Flask does here: https://github.com/pallets/werkzeug/blob/347fdbb055c86efe1fd49546bd524cde4b98c103/src/werkzeug/_internal.py#L327-L338
> 
> Note: Not really sure about what I said.

 The current cookie format is very close to [RFC 7515](https://www.rfc-editor.org/rfc/rfc7515.txt), the only issue seeming to be the "=" sign.
[RFC 7515](https://www.rfc-editor.org/rfc/rfc7515.txt) Appendix C suggests using data.split('=')[0] - 

SessionMiddleware can only possibly create malformed cookies with an equal, what do you think?

**Comment by allezxandre** [comment]
According to [RFC 7515 Sections 3](https://www.rfc-editor.org/rfc/rfc7515#section-3):

> In both serializations, the JWS Protected Header, JWS Payload, and JWS
   Signature are base64url encoded, since JSON lacks a way to directly
   represent arbitrary octet sequences.

with Base64url Encoding defined in Section 2 as:

>    Base64 encoding using the URL- and filename-safe character set
      defined in [Section 5 of RFC 4648](https://www.rfc-editor.org/rfc/rfc4648#section-5) [[RFC4648](https://www.rfc-editor.org/rfc/rfc4648)], **with all trailing '='
      characters omitted** (as permitted by [Section 3.2](https://www.rfc-editor.org/rfc/rfc7515#section-3.2)) and without the
      inclusion of any line breaks, whitespace, or other additional
      characters.  Note that the base64url encoding of the empty octet
      sequence is the empty string.  (See [Appendix C](https://www.rfc-editor.org/rfc/rfc7515#appendix-C) for notes on
      implementing base64url encoding without padding.)

(emphasis mine)

To match the RFC, shouldn't Starlette use Python's `base64.urlsafe_b64encode` instead of `base64.b64encode`?

**Comment by allezxandre** [comment]
It appears `base64.urlsafe_b64encode` also pads with `=` at the end, and cannot decode content if it's missing, so that wouldn't work.

**Comment by allezxandre** [comment]
@Kludex Do you have any thoughts on the PR I submitted for this issue?

**Comment by Kludex** [comment]
The whole discussion here is about "how to not have an equal sign on the token", but I can't actually reproduce what the OP said: "the browser ignores the rest of the token".

I'll close this issue, since I can't reproduce. Also, given the time this issue exists, if this was really a problem, I would have expected more reactions.

If someone can show me a browser that does what the OP reported, we can reopen this.
