### ISSUE TITLE
StaticFiles support for directories other than "statics"

### ISSUE THREAD

**Issue by bram2000** [Kludex/starlette#1265]
### Checklist

- [/] There are no similar issues or pull requests for this yet.
- [X - tried to get feedback but no replies] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

I want to be able to serve static files from arbitrary locations within a python package but I can't because currently it looks in a `statics` folder which is hardcoded.

## Describe the solution you would like.

I'd like to be able to pass as a parameter the path within the python package to look in for the static files.

## Describe alternatives you considered

I've considered changing the location of my packaged files to `statics` but this will have knock on effects across other systems, and `statics` itself is non-standard as far as I can tell.

**Comment by BeatSlayer** [comment]
That's already supported.

Check the docs here: https://www.starlette.io/staticfiles/

**Comment by bram2000** [comment]
> That's already supported.
> 
> Check the docs here: https://www.starlette.io/staticfiles/

I don’t think it is. I want to use the `package` argument but specify a directory within that package instead of being forced to use `statics`

**Comment by stephane** [comment]
@bram2000 yes, I don't know why this directory is hard-coded.
https://github.com/encode/starlette/blob/master/starlette/staticfiles.py#L76
Do you think the `directory` argument could be used?

There is also a copy/paste issue in the following assert message:
https://github.com/stephane/starlette/commit/4795244701298033169bcf1c0840e2badbd07dda

~~The line https://github.com/encode/starlette/blob/master/starlette/staticfiles.py#L56 prevents me to use a symbolic link for my static files...~~ Thank you@HanDDol

**Comment by HanDDol** [comment]
> The line https://github.com/encode/starlette/blob/master/starlette/staticfiles.py#L56 prevents me to use a symbolic link for my static files...

@stephane 
In my case, i added `check_dir=FALSE` in StaticFiles constructor and it works.

**Comment by stephane** [comment]
@HanDDol oh, you're right! How could I have missed it? :rofl:

**Comment by paulmsmith** [comment]
I've just hit this issue. I've tried the `check_dir=False` suggestion from @HanDDol but that didn't work for me. Do you have an example @HanDDol?

I think @bram2000's suggestion would be idea to account for packages that don't follow the 'statics' convention. (if it is a convention).

**Comment by paulmsmith** [comment]
I found that by simply creating an empty directory called `statics` inside the dependancy this then worked and seemed to allow me to reference things in `static` within the dependancy. This feels like bug to me and as @bram2000 said, would be helpful if you could pass a parameter specifying the directory within a dependancy you need to include things from.

**Comment by florimondmanca** [comment]
Hi folks, we're considering #1350 and the following API to address this use case…

```python
routes=[
    ...
    Mount('/static', app=StaticFiles(packages=['bootstrap4', ('mypackage', 'dist')]), name="static"),
]
```

That is, we'll be able to specify a root directory to look into as a 2-tuple `(<package_name>, <dir>)` form, where the single string `"<package_name>"` uses the current default, `"statics"`.

Any thoughts or comments welcome on the PR before we move on and merge. :-)
