### ISSUE TITLE
Starlette is not typed to an ASGIApplication → Type check warning in PyCharm with FastAPI and Uvicorn

### ISSUE THREAD

**Issue by eshfield** [Kludex/starlette#1296]
**The problem:**
PyCharm gives ugly type check warning when I try to run FastAPI app with uvicorn programmatically passing to `uvicorn.run()` the application instance of the FastAPI class.

I have created the issue in the FastAPI repository and they say the problem is since FastAPI extends from Starlette the issue is that Starlette is not typed to an `ASGIApplication`, i.e. fix must be done in the Starlette code:
https://github.com/tiangolo/fastapi/issues/3927

**Steps to reproduce:**
Copy and paste to PyCharm the example code from the official FastAPI documentation [Debugging → Call](https://fastapi.tiangolo.com/tutorial/debugging/?h=uvicorn#call-uvicorn) uvicorn
PyCharm will highlight the `app` argument at the last line `uvicorn.run(app, host="0.0.0.0", port=8000)` with warning:
`Expected type 'Union[Type[ASGI2Protocol], (Union[HTTPScope, WebSocketScope, LifespanScope], () -> Awaitable[Union[HTTPRequestEvent, HTTPDisconnectEvent, WebSocketConnectEvent, WebSocketReceiveEvent, WebSocketDisconnectEvent, LifespanStartupEvent, LifespanShutdownEvent]], (Union[HTTPResponseStartEvent, HTTPResponseBodyEvent, HTTPServerPushEvent, HTTPDisconnectEvent, WebSocketAcceptEvent, WebSocketSendEvent, WebSocketResponseStartEvent, WebSocketResponseBodyEvent, WebSocketCloseEvent, LifespanStartupCompleteEvent, LifespanStartupFailedEvent, LifespanShutdownCompleteEvent, LifespanShutdownFailedEvent]) -> Awaitable[None]) -> Awaitable[None], str]', got 'FastAPI' instead`

**Comment by Kludex** [comment]
Duplicated #1249

PR is welcome. :)
