### ISSUE TITLE
TestClient is not triggering on_startup events or on_shutdown events

### ISSUE THREAD

**Issue by Kolumbs** [Kludex/starlette#1298]
### Is your feature related to a problem? Please describe.

TestClient provides interface to make requests to Starlette app. What I expect is that also on_startup events and on_shutdown events are triggered when invoking TestClient.
I want to test incoming requests that depend on the on_startup functions being called by Starlette app.

## Describe the solution you would like.

```
with TestClient(app) as client:
    # on_startup functions called
    client.get('/')
    # on_shutdown functions called
```

or at least on_startup is called in this code snippet:
```
from starlette.applications import Starlette
from starlette.testclient import TestClient

app = Starlette(
    debug=True,
    on_startup=[lambda: print('Startup')],
    on_shutdown=[lambda: print('Shutdown')],
)

client = TestClient(app)
```

## Describe alternatives you considered
I require on_startup async functions to be called for database initialization (Postgres Engine) and in this scenario I can't use TestClient anymore

**Comment by Kludex** [comment]
You can create a fixture with "function" scope, can't you? :thinking:

**Comment by Kolumbs** [comment]
Not sure if I got your point. But what I can do is manually trigger those events when exposing app.state

```python
import asyncio
from starlette.applications import Starlette
from starlette.testclient import TestClient

async def startup():
    print('Startup')

async def shutdown():
    print('Shutdown')

app = Starlette(
    debug=True,
    on_startup=[startup],
    on_shutdown=[shutdown],
)

app.state.startup = startup
app.state.shutdown = shutdown

async def main():
    await app.state.startup()
    TestClient(app)
    await app.state.shutdown()

asyncio.run(main())

```

**Comment by Kolumbs** [comment]
But if I go into more subtle cases, like using Unittest for testcases. Below I construct manually the on_startup and on_shutdown events of the Starlette app:
```python
  1 import asyncio
  2 import unittest
  3 
  4 from starlette.applications import Starlette
  5 from starlette.testclient import TestClient
  6 from starlette.routing import Route
  7 from starlette.responses import PlainTextResponse
  8 
  9 async def startup():
 10     print('Startup')
 11 
 12 async def shutdown():
 13     print('Shutdown')
 14 
 15 async def root(request):
 16     print(asyncio.get_running_loop()._thread_id)
 17     return PlainTextResponse('Hello, world!')
 18 
 19 routes = [Route('/', root)]
 20 
 21 app = Starlette(
 22     debug=True,
 23     routes = routes,
 24     on_startup=[startup],
 25     on_shutdown=[shutdown],
 26 )
 27 
 28 app.state.startup = startup
 29 app.state.shutdown = shutdown
 30 
 31 class Test(unittest.IsolatedAsyncioTestCase):
 32 
 33     async def asyncSetUp(self):
 34         await app.state.startup()
 35 
 36     async def test(self):
 37         print(asyncio.get_running_loop()._thread_id)
 38         client = TestClient(app)
 39         a = client.get('/')
 40 
 41     async def asyncTearDown(self):
 42         await app.state.shutdown()
```
I would get here different asyncio event loop ids:
`Startup
140302361790272
140302343075584
Shutdown
`
Now in this scenario nothing bad happens out of it, but using Postgres engine async dispose method as shutdown event would get me into troubles. I cannot dispose items created within Starlette app, as those are in different asyncio loop (created within TestClient init stage). That is why it would be better if TestClient also handles on_startup and on_shutdown events in its loop.

**Comment by Kludex** [comment]
This is what I meant:
```python
import pytest
from starlette.testclient import TestClient

from app.main import app

@pytest.fixture()
def client():
    return TestClient(app)
    
def test_endpoint(client: TestClient):
    res = client.get("/")
    assert res.status_code == 200
```

**Comment by Kolumbs** [comment]
ok, yes it is almost the same. Basic problem comes down to the fact that if I do something with async, those will be out of the same async loop.

so in your case i still cannot get into the loop that TestClient creates for the app.

```python
@pytest.fixture()
async def client():
    await do_some_startup_here() # will be done but in another async loop
    return TestClient(app) # anything here inside will go with different async loop
```

**Comment by Kolumbs** [comment]
Made a very primitive hack in testclient.py for  `class _ASGIAdapter`

```python
        try:
            with self.portal_factory() as portal:
                response_complete = portal.call(anyio.Event)
                async def rcv(): pass # mock send of lifespan message to Starlette app
                async def snd(msg): pass # mock receive of message from app
                portal.call(self.app, {"type": "lifespan"}, rcv, snd) # call lifespan
                portal.call(self.app, scope, receive, send)
        except BaseException as exc:
            if self.raise_server_exceptions:
                raise exc
```
Of course not implementation as such, but maybe something along those lines can be done?

**Comment by Kolumbs** [comment]
I am sorry after reading more closely the code of TestClient there is already implementation of what I need:
```python
with TestClient(app) as client:
    client.request("GET", "/")
```
this will do the startup and shutdown events

**Comment by Kludex** [comment]
Thanks for coming back and closing it! :)

**Comment by roma-guru** [comment]
Thx to @Kolumbs for the recipe, maybe context manager usage should be reflected in [TestClient](https://www.starlette.io/testclient/) docs.

**Comment by Kludex** [comment]
PR welcome to improve the docs about it.

**Comment by aminalaee** [comment]
There's an example here: https://www.starlette.io/testclient/#selecting-the-async-backend
Do you think it should be one in the first example too?

**Comment by Kludex** [comment]
I think it should mention the information about the lifespan events
