### ISSUE TITLE
FileResponse Stream continues streaming after http.disconnect

### ISSUE THREAD

**Issue by idotobi** [Kludex/starlette#1301]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

While downloading a file provided via `FileResponse` the starlette application continues "sending" chunks even if the client aborts.
This is the same bug as I found reported and fixed for StreamResponse. References:
 - issue in Fastapi repo: https://github.com/tiangolo/fastapi/issues/1342
 - fixing PR in starlett repo: https://github.com/encode/starlette/pull/839

### To reproduce

```python
async def stream_file_response(request: Request) -> FileResponse:
    bg = BackgroundTask(...)
    return FileResponse(
        path=PATH, filename="example.png", background=bg
    )

###############################################################3

response = requests.get(
    f"http://{HOST}:{PORT}/file",
    stream=True,
)
response.close()
```

For details see following PR.

### Expected behavior

FileResponse is also listening for http.disconnect and aborts stream if client disconnects.

### Actual behavior

The application doesn't start with the backgroundtask right away, but continues sending all the cunks first until finished.

### Debugging material

See `tests/test_response_abort.py` in following PR.

### Environment

- OS: Linux Arch
- Python version: Python 3.9.7
- Starlette version: master, 0.15.0

### Additional context

n.a.

**Comment by Kludex** [comment]
Bug confirmed. PR welcome.

**Comment by lovelydinosaur** [comment]
I'm not convinced we need to handle this.

Every existing WSGI application has this same constraint, and... it's okay.

We send these ASGI messages and they just fall off into void. Granted, we'd save some resources in the disconnect case if we handled this, but in exchange for that we need to add more complexity, and in fact *use* more resources to check for this case.

**Comment by idotobi** [comment]
Sure, that's a reasonable decision. Just to be sure that the consequences are clear:

 1. There's a slight inconsistency between `StreamResponse` and `FileResponse` (the fist one listening for disconnect the other one not).
 2. There's no way for a starlette server to know whether a file was completely sent or not (in case of disconnect).

The second one would have been my usecase :sweat_smile:.

**Comment by lovelydinosaur** [comment]
1. Yes that'a very good point. With `StreamResponse` we support a use case that WSGI doesn't really have, of being able to stream a response *indefinitely*. For example this allows us to support SSE (Server Sent Events) - which are similar to WebSockets, but simpler, and can stream data in one direction only. We *do* need to handle disconnects if we want to be able to support that kind of usage.
2. Correct.
