### ISSUE TITLE
StreamReader not reading all chunks in aioboto3 s3 get_object response

### ISSUE THREAD

**Issue by scattym** [Kludex/starlette#1310]
### Checklist

- [ X] The bug is reproducible against the latest release and/or `master`.
- [ X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Passing a web.StreamReader returned from AioBoto S3 get_object() function to a StreamingResponse results in a hung connection. I can't yet tell if this is because of an incompatibility between the StreamingResponse and the aiohttp web.StreamReader, or if this is a bug.

### To reproduce

```python
import logging
import aioboto3
from starlette.applications import Starlette
from starlette.responses import StreamingResponse
from starlette.routing import Route

logger = logging.getLogger(__name__)

async def read_bytes(s3_obj):
    chunk_size = 1024
    async with s3_obj["Body"] as stream:
        file_data = await stream.read(chunk_size)
        while file_data:
            yield file_data
            file_data = await stream.read(chunk_size)


async def yield_bytes(s3_ob):
    while True:
        chunk = await s3_ob["Body"].readchunk()
        yield chunk[0]
        if chunk[1]:
            break


async def proxy_fragment_request(request):

    boto3_session = aioboto3.Session()
    async with boto3_session.client(
            "s3",
            endpoint_url='http://minios3server.local',
            aws_access_key_id='SOMEKEY',
            aws_secret_access_key='SOMEPASS',
    ) as s3:
        bucket = 'bucket1'
        blob_s3_key = 'bigfile'  # bigfile is only around 30KB
        s3_ob = await s3.get_object(Bucket=bucket, Key=blob_s3_key)

        # return StreamingResponse(yield_bytes(s3_ob))
        # return StreamingResponse(read_bytes(s3_ob))
        return StreamingResponse(s3_ob["Body"])

routes = [
    Route("/tests3", endpoint=proxy_fragment_request),
]

app = Starlette(routes=routes)


def main():
    import uvicorn

    logger = logging.getLogger('')
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    formatter = logging.Formatter(
        '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    ch.setFormatter(formatter)
    logger.addHandler(ch)
    uvicorn.run(app, http='h11', loop='uvloop', log_level=0)


if __name__ == "__main__":
    main()

```

### Expected behavior

Full file streamed to the client

### Actual behavior

Streaming stops after first 4KB read

### Debugging material

I have tried the following functions to abstract away the StreamReader, but with similar results:

```python
async def read_bytes(s3_obj):
    chunk_size = 1024
    async with s3_obj["Body"] as stream:
        file_data = await stream.read(chunk_size)
        while file_data:
            yield file_data
            file_data = await stream.read(chunk_size)
return StreamingResponse(read_bytes(s3_ob))

async def yield_bytes(s3_ob):
    while True:
        chunk = await s3_ob["Body"].readchunk()
        yield chunk[0]
        if chunk[1]:
            break
return StreamingResponse(yield_bytes(s3_ob))

```

### Environment

- OS: Linux
- Python version: 3.9.0
- Starlette version: 0.16.0 (tested back to the version that starts checking for for AsyncIterator)

### Additional context

I tracked the execution chain through to aiohttp waiting for the reader to request more data (or at least that's what I think it's doing) in aiohttp/streams.py line 306. i.e.:

```python
        waiter = self._waiter = self._loop.create_future()
        try:
            if self._timer:
                with self._timer:
                    await waiter  ## <---------- last call I see
            else:
                await waiter
        finally:
            self._waiter = None
```

Weirdly I get the following log entry from starlette before all the data is transferred:
INFO:     127.0.0.1:35494 - "GET /tests3 HTTP/1.1" 200 OK
Which I thought should only get printed at the end of the transaction.

When I ctrl-c the app it still believes there are open connections:
2021-10-15 13:14:23,702 - uvicorn.error - INFO - Shutting down
2021-10-15 13:14:23,803 - uvicorn.error - INFO - Waiting for connections to close. (CTRL+C to force quit)

**Comment by Kludex** [comment]
> Weirdly I get the following log entry from starlette before all the data is transferred:
INFO: 127.0.0.1:35494 - "GET /tests3 HTTP/1.1" 200 OK
Which I thought should only get printed at the end of the transaction.

You see that logs when the headers are sent, so it's before.

**Comment by Kludex** [comment]
Are you perhaps using any middleware that inherits from `BaseHTTPMiddleware`?

**Comment by scattym** [comment]
With the help of the aiobotocore team, this was tracked to a programmatic error around the lifecycle of the s3 instance. Your message triggered me to go and look through my email trail.

Basically we were dropping the s3 object when it still had data to send due to the "async with" call.

Thanks!

**Comment by Kludex** [comment]
Glad it was solved, and thanks for closing the issue! :smile:

**Comment by hozn** [comment]
@scattym , I'm hitting a similar issue and wondering if you could share more about the correct implementation here (vs. `async with ...`).

Edit: nevermind, I found https://github.com/aio-libs/aiobotocore/issues/891 and see the proposal there.  I'm using FastAPI, so I created an injected dependency to instantiate the s3 client.

**Comment by Kludex** [comment]
I'm locking this issue, as people may get confused about further comments.

The issue here was solved. If you have a similar issue, please create a GitHub discussion, or talk to us over Gitter.
