### ISSUE TITLE
🐛 Different `Host` behavior for setting `host` argument and getting `Host` header

### ISSUE THREAD

**Issue by WhiteApfel** [Kludex/starlette#1317]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug
When adding a host-based routes, `host` value can accept the port and does not process it in any way. But `Host.matches()` cuts off the port number ([`routing.py:432`](https://github.com/encode/starlette/blob/master/starlette/routing.py#L432))

### Expected behavior
When adding, cut off the port, or сonsider it when matching.

### Actual behavior
```python
import uvicorn as uvicorn
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.routing import Host, Router, Route

app = Starlette(routes=[
    Host('127.0.0.1:8889', app=Router(routes=[Route('/', lambda *a, **k: PlainTextResponse('Hello World'))])),
])

uvicorn.run(app, port=8889)
```

Breakpoint at [`routing.py:433`](https://github.com/encode/starlette/blob/master/starlette/routing.py#L433)
![breakpoint variables](https://user-images.githubusercontent.com/29860366/137943818-4a9ba822-d0ae-4c56-9ca2-03cce844ecba.png)

- Starlette version: 0.16.0

**Comment by WhiteApfel** [comment]
@aminalaee, maybe we should also cut off the port when matching host-based routes? As I understand it, the `Host.host` value is used to generate links via `url_for`, the port number may be useful there

**Comment by aminalaee** [comment]
@WhiteApfel I agree. I think that can be useful in host-based routing,

**Comment by WhiteApfel** [comment]
It might be cool to make the port handling principle similar to the subdomain principle
