### ISSUE TITLE
No elastic-apm transaction in synchronous `StreamingResponse` handler

### ISSUE THREAD

**Issue by stephan-hesselmann-by** [Kludex/starlette#1333]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When trying to access the Elastic transaction from within a synchronous `StreamingResponse` handler, no such transaction is found. This problem only occurs with synchronous responses, for asynchronous responses the transaction is injected as expected.

### To reproduce

```python
from elasticapm.contrib.starlette import ElasticAPM, make_apm_client
from elasticapm.traces import execution_context
from starlette.applications import Starlette
from starlette.responses import StreamingResponse
from starlette.testclient import TestClient


async def async_response():
    transaction = execution_context.get_transaction()
    if not transaction:
        raise RuntimeError("No transaction found")
    yield "ok"


def sync_response():
    transaction = execution_context.get_transaction()
    if not transaction:
        raise RuntimeError("No transaction found")
    yield "ok"


def create_app():
    _app = Starlette()

    @_app.route("/async/")
    def async_route(request):
        return StreamingResponse(async_response())

    @_app.route("/sync/")
    def sync_route(request):
        return StreamingResponse(sync_response())

    client = make_apm_client()
    _app.add_middleware(ElasticAPM, client=client)

    return _app


app = create_app()


# This test passes
def test_async_response():
    client = TestClient(app)
    client.get("/async")


# This test fails
def test_sync_response():
    client = TestClient(app)
    client.get("/sync")
```

### Expected behavior

The Elastic execution context should return a valid transaction in the response code.

### Actual behavior

`execution_context.get_transaction()` returns `None`.

### Debugging material

I performed a `git bisect` with the tests above and found the first bad commit to be the `anyio` integration https://github.com/encode/starlette/commit/42592d68e5d7fd044b79d7846eabe7f33961527c. Consequently, the issue starts to occur with `starlette>=0.15`.

### Environment

- OS: macOS
- Python version: 3.9.7

```
Package            Version   Editable project location
------------------ --------- -------------------------
anyio              3.3.4
attrs              21.2.0
certifi            2021.10.8
charset-normalizer 2.0.7
elastic-apm        6.6.1
idna               3.3
iniconfig          1.1.1
packaging          21.2
pip                21.3.1
pluggy             1.0.0
psutil             5.8.0
py                 1.11.0
pyparsing          2.4.7
pytest             6.2.5
requests           2.26.0
setuptools         58.5.3
sniffio            1.2.0
starlette          0.17.0    /Users/lgtf/git/starlette
toml               0.10.2
urllib3            1.26.7
wheel              0.37.0
```

**Comment by Kludex** [comment]
This doesn't look a Starlette issue, the main actors here are `execution_context` from `elasticapm` and [`run_sync`](https://github.com/agronholm/anyio/blob/5376d62a423aedab5ede02086b33805588f0e94a/src/anyio/to_thread.py#L10) from `anyio`.

Although I'd like to help more, it would be more helpful if the needed stack to reproduce your example was available.

I'm closing this, but I'd be more than happy to reopen if what I mentioned above is provided.

**Comment by stephan-hesselmann-by** [comment]
> Although I'd like to help more, it would be more helpful if the needed stack to reproduce your example was available.

What do you mean by this? What is missing to reproduce the issue with the information I provided?

**Comment by stephan-hesselmann-by** [comment]
This issue seems to have been resolved in the meantime in `anyio` with this commit https://github.com/agronholm/anyio/commit/a170da3e543d94d7491611280821612fc871cb42.
