### ISSUE TITLE
Handling of `scope["root_path"]` and `scope["path"]` differs from ASGI spec

### ISSUE THREAD

**Issue by silane** [Kludex/starlette#1336]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Accoring to https://github.com/django/asgiref/issues/229#issuecomment-765583185, `scope["path"]` includes the `scope["root_path"]`.
So if root_path is `/foo` and request for `/foo/bar` has come, the upstream application servers (such as uvicorn) are passing `scope["path"] == "/foo/bar" and scope["root_path"] == "/foo"`, which is correct behavior. 

But starlette does not conform this. It assumes `scope["path"]` is a remainder of stripping `scope["root_path"]` from original request path. In this case, `scope["path"] == "/bar" and scope["root_path"] == "/foo"`. This ASGI incompatible assumption can be seen [here](https://github.com/encode/starlette/blob/6af5c515e0a896cbf3f86ee043b88f6c24200bcf/starlette/routing.py#L368) or [here](https://github.com/encode/starlette/blob/6af5c515e0a896cbf3f86ee043b88f6c24200bcf/starlette/datastructures.py#L23) and many other places.

The following "To reproduce" section shows just one aspect of this wrong assumption.

### To reproduce

1. Save `main.py` as follows.
```python
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.routing import Route, Mount


class Bar:
    async def __call__(self, scope, receive, send):
        await PlainTextResponse(f"bar {scope['root_path']=} {scope['path']=}")(scope, receive, send)

class FooBar:
    async def __call__(self, scope, receive, send):
        await PlainTextResponse(f"foobar {scope['root_path']=} {scope['path']=}")(scope, receive, send)

routes =[
    Route('/bar', endpoint=Bar()),
    Mount('/foo', routes=[
        Route('/bar', endpoint=FooBar())
    ])
]
app = Starlette(routes=routes)
```

2. Run `uvicorn main:app --port 8000 --root-path /foo`
3. Access by `curl http://localhost:8000/foo/bar`

### Expected behavior

Receives
```
bar scope['root_path']='/foo' scope['path']='/foo/bar'
```

### Actual behavior

Receives
```
foobar scope['root_path']='/foo/foo' scope['path']='/bar'
```

Some points here are,
1. `scope['path']` does not include `scope['root_path']` , which is ASGI incompatible.
2. `FooBar` ASGI handler is called. It does not take `scope['root_path']` into account when routing.

### Environment

- OS: Linux
- Python version: 3.8.2
- Starlette version: 0.17.0

### Additional context

This may be a root cause of [this issue in fastapi](https://github.com/tiangolo/fastapi/issues/2872)

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/1336">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/1336/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/1336/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
Hello @Kludex :wave: I would be interested to help tackling this issue; if you need a hand, let me know :)

**Comment by Kludex** [comment]
Take in consideration that I'll need a lot of references to follow on this, and to understand the implications for our users.

But yeah, help is appreciated. 🙏
