### ISSUE TITLE
Wrong unauthorized WebSocket status code

### ISSUE THREAD

**Issue by andreadelfante** [Kludex/starlette#1362]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I have a protected websocket endpoint, with the decorator `@requires('authenticated', status_code=401)`.
If the authentication check fails, the response code from the websocket is `403 Forbidden`, but it should be `401 Unauthorized`.

### To reproduce

Here an example to reproduce the use case.

```python
import uvicorn
from starlette.applications import Starlette
from starlette.authentication import AuthenticationBackend, AuthenticationError, AuthCredentials, SimpleUser, requires
from starlette.middleware import Middleware
from starlette.middleware.authentication import AuthenticationMiddleware
from starlette.websockets import WebSocket


class BasicAuthBackend(AuthenticationBackend):
    async def authenticate(self, request):
        auth = request.headers.get("Authorization", None)
        if auth != 'sample_key':
            raise AuthenticationError('Invalid auth credentials')

        return AuthCredentials(["authenticated"]), SimpleUser("username")


app = Starlette(
    middleware=[
        Middleware(AuthenticationMiddleware, backend=BasicAuthBackend()),
    ],
)


@app.websocket_route("/websocket")
@requires("authenticated", status_code=401)
async def websocket(websocket: WebSocket):
    await websocket.accept()
    await websocket.send_json({'message': 'Connected and authenticated!'})
    await websocket.close()


if __name__ == '__main__':
    uvicorn.run("websocket:app", host="0.0.0.0", port=10123)
```

<img width="1154" alt="Schermata 2021-12-14 alle 13 22 55" src="https://user-images.githubusercontent.com/7781176/145997556-155f4e47-e8e4-4e25-bce6-232d2b5025c5.png">

### Expected behavior

The websocket endpoint should return 401, according to the status_code specified in the `@requires` decorator.

### Actual behavior

The websocket endpoint should return 403, even if I specify the desired status_code in the `@requires` decorator.

### Environment

- OS: Linux
- Python version: 3.8
- Starlette version: 0.17.1

**Comment by aminalaee** [comment]
I'm not 100% sure but after checking the code I think this might be happening In Uvicorn.

What do you think @Kludex ?

https://github.com/encode/uvicorn/blob/65ec8d132c37a8338a2f495fa1be9f14bd4368d9/uvicorn/protocols/websockets/websockets_impl.py#L236-L244

**Comment by Kludex** [comment]
Is it related to this? https://github.com/encode/uvicorn/issues/1181

**Comment by aminalaee** [comment]
I guess they are related, they point to the same code but not exactly the same issue.
I think this issue is [here](https://github.com/encode/uvicorn/blob/1d9511f0b9dc73867bbbb38f72dbbdcac5478651/uvicorn/protocols/websockets/websockets_impl.py#L246) where we hard-coded http response to 403, and the `@requires` in Starlette has no effect on http response.

**Comment by aminalaee** [comment]
I think this should probably be discussed in Uvicorn, but out of curiosity I've checked `daphne` websocket, and they're doing the same thing [here](https://github.com/django/daphne/blob/6a5093982ca1eaffbc41f0114ac5bea7cb3902be/daphne/ws_protocol.py#L225):

```python
def serverReject(self):
        """
        Called when we get a message saying to reject the connection.
        """
        self.handshake_deferred.errback(
            ConnectionDeny(code=403, reason="Access denied")
        )
        del self.handshake_deferred
```

The HTTP status of WebSocket rejection is hard-coded, I don't have much info about Uvicorn but maybe @Kludex or @euri10 can check the possibility to see if we can override that from Starlette.

**Comment by paulo-raca** [comment]
[AuthenticationMiddleware](https://github.com/encode/starlette/blob/master/starlette/middleware/authentication.py#L40) sends `websocket.close` message, which maps to HTTP 403.

This is  the only possible behavior with regular ASGI server, but there is an [ASGI extension](https://asgi.readthedocs.io/en/latest/extensions.html#websocket-denial-response) that allows sending custom HTTP responses.

I have implemented this for [ExceptionMiddleware](https://github.com/encode/starlette/pull/1478), should be straightforward to do the same for AuthenticationMiddleware

**Comment by paulo-raca** [comment]
Update: I implemented this in my PR: #1478

**Comment by Kludex** [comment]
I see. Thanks for clarifying @paulo-raca. 👍

We'd still need to implement the extension on uvicorn's side.

**Comment by Kludex** [comment]
We are going to document this behavior first on https://github.com/encode/starlette/pull/1636. 

At some point, I'll take a look at the implementation of the [WebSocket Denial Response](https://asgi.readthedocs.io/en/latest/extensions.html#websocket-denial-response) by @paulo-raca. There are a couple of things in the list before that, but we are going to get there - I'm not confirming we are going to have the extension, it needs to be discussed, and we need to see if it's worth it.

Note: An implementation on the uvicorn needs to take place as well.
