### ISSUE TITLE
ImmutableMultiDict should be comparable (__eq__) to other mappings

### ISSUE THREAD

**Issue by cauebs** [Kludex/starlette#1367]
The current implementation (see below) does not allow comparing instances of `ImmutableMultiDict` to instances of other `Mapping` types, such as dicts.

This makes testing less convenient. For example, I was trying to check what was received via `Request.query_params` (`QueryParams`), but then have to cast it to a `dict` (which makes testing `MagicMock.method_calls` cumbersome).

https://github.com/encode/starlette/blob/c8b9581e371968b4da42d0f2de01e4028d71ac3c/starlette/datastructures.py#L301-L304

**Comment by Kludex** [comment]
What's the problem of using `items()`?

**Comment by cauebs** [comment]
I'm using `unittest.mock.call`, and instead of comparing
```python
assert my_mock.method_calls == [
    call.my_method("something", {"query_parameter": "foo"})
]
```
I have to use one of the following:
```python
assert my_mock.method_calls == [
    call.my_method("something", QueryParameter("query_parameter=foo"))
    # even though this method takes a mapping and the test might fail in the future
]
```
```python
assert len(my_mock.method_calls) == 1
assert len(my_mock.method_calls[0].args) == 2
assert my_mock.method_calls[0].args[0] == "something"
assert dict(my_mock.method_calls[0].args[1]) == {"query_parameter": "foo"}
```

Would the solution I proposed create any issues? I'm willing to open a PR.

**Comment by Kludex** [comment]
> I'm willing to open a PR.

On my side, I'm not positive towards this change. I think the method `__eq__` is right.

If you're checking the `request.query_params`, can't you do something like the below snippet?

```python
from starlette.requests import Request
from starlette.applications import Starlette
from starlette.routing import Route
from starlette.responses import Response

async def endpoint(request: Request):
    assert request.query_params.items() == {"pot": "ato"}.items()
    return Response(status_code=204)

app = Starlette(routes=[Route("/", endpoint=endpoint)])
```

**Comment by Kludex** [comment]
Closing this issue as author seems not interested anymore. We can reopen/discuss in a new issue if needed.
