### ISSUE TITLE
Use new GitHub issue template

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#1370]
Use same template as `uvicorn` on issues:

- https://github.com/encode/uvicorn/issues/new?assignees=&labels=&template=feature-request.yml
- https://github.com/encode/uvicorn/blob/master/.github/ISSUE_TEMPLATE/feature-request.yml

It avoids people creating issues like this i.e. ignoring completely the template.

**Comment by aminalaee** [comment]
Interesting..I can do that if you don't plan to do it.

**Comment by Kludex** [comment]
If you want, feel free to do it. :)
