### ISSUE TITLE
Consolidating HTTP status codes

### ISSUE THREAD

**Issue by berislavlopac** [Kludex/starlette#138]
I have noticed that there is `starlette.status`, which groups all status codes in one place. However, there are several places in the code where it's using a number directly instead of the `starlette.status`, e.g. when [returning errors](https://github.com/encode/starlette/blob/49f76ab5e9ef0ce5d966485553ad6019a9d37da5/starlette/endpoints.py#L40).

That said, I'm a big fan of the standard library's nice little `http.HTTPStatus` enum, which neatly groups all the status codes and their standard messages and descriptions, while at the same time keeps the integer functionality (truth be told, HTTP status codes are not _really_ integers; we just treat them as such as it's easy and clean).

So I'd like to propose doing a few minor refactorings in the Starlette code; I can easily make a PR myself, but I'd like to hear any comments on the idea first, in particular if there is any concrete reason for not using `http.HTTPStatus`. My ideas are:

1. Replace all integer values in `starlette.status` with the equivalent `HTTPStatus` value; or even, possibly, completely replace them in the manner that `starlette.status.HTTP is http.HTTPStatus` (this needs applying the change everywhere, but it shouldn't be a problem if its just internal).
2. Replace all the integers used for status code with the corresponding `startlette.status` values.
3. Create a `HTTPStatus`-like enum for all the codes it does not cover -- this especially goes for the WebSocket Close Codes -- and apply them in the same manner as above.

Optionally, I would like to suggest a new `PlainTextResponse` subclass specifically for errors, so in the case [linked above](https://github.com/encode/starlette/blob/49f76ab5e9ef0ce5d966485553ad6019a9d37da5/starlette/endpoints.py#L40) it would be something like:

    return HTTPErrorResponse(status.HTTP_405_METHOD_NOT_ALLOWED)

or, if the second approach in no. 1 above is used:

    return HTTPErrorResponse(status.HTTP.METHOD_NOT_ALLOWED)

My main problem here is that it can be used for any type of response and not just errors; the solutions I can think of are:

1. Trust the user and let them use it as they see fit (I would prefer this).
2. Not trust the user and explicitly check if the status is >= 400; I'm not sure what is the general policy for Starlette in such cases.

OK, that's it from me for now, looking forward to any thoughts and comments.

**Comment by alexbotello** [comment]
As far as I am aware the decision not to use `http.HTTPStatus` was a conscious one. See #43 for the discussion on that.

However, I too have noticed many places in the code where the proper `starlette.status` should replace the integer value. Go for it and make an easy PR.

**Comment by berislavlopac** [comment]
Thanks Alex! As far as I can tell, the main concern expressed in #43 is that `HTTPStatus` does not include both the phrase and numeric value in item names, which is fine -- this is covered with the option 1a above, which suggests replacing the numeric values with the `HTTPStatus` values, e.g.:

    HTTP_206_PARTIAL_CONTENT = HTTPStatus.PARTIAL_CONTENT

In practical terms there is no difference to using integers, one could still do, e.g.:

    if 400 <= status_code < 500:
        logging.error('client error')

But it would add `status_code.phrase` and `status_code.description` in a standard-library-compatible way.

Also, any thoughts on the `HTTPErrorResponse`? Thank you!

**Comment by alexbotello** [comment]
> Also, any thoughts on the `HTTPErrorResponse`? 

I guess I'm just not sure if there is really a clear need for that. Is there any reason why just using `PlainTextResponse` would not suffice?

**Comment by berislavlopac** [comment]
Well there is no _need_ as such, I just find it more clear to have

    return HTTPErrorResponse(HTTP_406_NOT_ACCEPTABLE)

which would then extract the phrase and description, than something like

    return PlainTextResponse(HTTP_406_NOT_ACCEPTABLE.description, status_code=HTTP_406_NOT_ACCEPTABLE.value)

Of course, if we use plain integers instead of the enum this second example is less verbose, but requires either passing an explicit message each time or keeping a separate repository of error messages. Of course, it would be possible to optionally customise the message for the `HTTPErrorResponse`:

    return HTTPErrorResponse(HTTP_429_TOO_MANY_REQUESTS, message='Chill, man!')

**Comment by berislavlopac** [comment]
Very well, this seems like a solid compromise, I can do this PR.

**Comment by berislavlopac** [comment]
I've created a pull request, but implementing this actually made me think about the use case that prompted this question in the first place.

Specifically, we're returning a `PlainTextResponse` in various places -- but shouldn't we instead be raising `HTTPException` and let the `ExceptionMiddleware` take care of the responses? Just trying to understand what are the goals. Thanks!

**Comment by lovelydinosaur** [comment]
Happy with the state of this for now.

**Comment by kkirsche** [comment]
For what it's worth, we use HTTPStatus pretty broadly in our starlette and fastapi applications. It usually works, but having explicit support in the MyPy typings would simplify the need to have to `int()` them earlier in the lifecycle
