### ISSUE TITLE
MultiDict __iter__ returns tuples instead of just keys

### ISSUE THREAD

**Issue by ryankask** [Kludex/starlette#139]
The `QueryParams` and `Headers` multidict classes' `__iter__` method returns key/value pairs instead of just keys which is what I would expect from a Python mapping.

I haven't seen an implementation like this and checked a few from Django, Werkzeug, urllib3, and aio-lib's multidict.

Was this intentional or should it be changed?

Thanks!

**Comment by lovelydinosaur** [comment]
Should probably be changed if it doesn’t match standard dict behaviour.
It’d be interesting to know what eg. werkzueg does here, since keys() and values() aren’t super meaningful in a multidict context. set(d.keys()) is pretty much the only context I can see it as being meaningful.

**Comment by ryankask** [comment]
I've posted a few examples below. The behaviour of these libraries differs but in both cases, `list(instance) == list(instance.keys())`.

[Werkzeug's `MultiDict`](http://werkzeug.pocoo.org/docs/0.14/datastructures/#werkzeug.datastructures.MultiDict) returns the first value seen:

```python
In [68]: d = MultiDict([('a', 1), ('b', 2), ('a', 3)])

In [69]: list(d.keys())
Out[69]: ['a', 'b']

In [70]: list(d.values())
Out[70]: [1, 2]

In [71]: list(d)
Out[71]: ['a', 'b']
```

[aio-lib's `MultiDict`](https://multidict.readthedocs.io/en/stable/multidict.html#multidict.MultiDict.keys) returns all possible values:

```python
In [2]: d = MultiDict([('a', 1), ('b', 2), ('a', 3)])

In [3]: list(d.keys())
Out[3]: ['a', 'b', 'a']

In [4]: list(d.values())
Out[4]: [1, 2, 3]

In [5]: list(d)
Out[5]: ['a', 'b', 'a']
```

Starlette:

```python
In [10]: params = QueryParams(items=[('a', 1), ('b', 2), ('a', 3)])

In [11]: params
Out[11]: QueryParams(query_string='a=1&b=2&a=3')

In [12]: list(params)
Out[12]: [('a', 1), ('b', 2), ('a', 3)]

In [13]: list(params.keys())
Out[13]: ['a', 'b', 'a']

In [14]: list(params) == list(params.keys())
Out[14]: False
```

I'm happy to help if this is something you'd like to change.

**Comment by ryankask** [comment]
I've submitted #142 to address the first point above but I've noticed that Werkzeug's `Headers` class doesn't inherit from its `MultiDict` class (see below). 

It might be best to close the PR and this issue and leave Starlette as is. Each package has different behaviour for these data structures so unless Starlette behaves identically to an existing package, it's hard to know where to go.

This originally came up for me because I wanted to validate `request.query_params` using Marshmallow and it didn't work:

```python
In [16]: Schema().load(QueryParams(query_string='a=1&b=2&a=3'))
...
KeyError: ('a', '1')
```

This is easy enough to fix though...

---

Werkzeug's `Headers` actually behaves like Starlette's `QueryParams` and `Headers` classes:

```python
In [49]: h = Headers([('a', 1), ('b', 2), ('a', 3)])

In [50]: list(h.items())
Out[50]: [('a', 1), ('b', 2), ('a', 3)]

In [51]: list(h.keys())
Out[51]: ['a', 'b', 'a']

In [52]: list(h.values())
Out[52]: [1, 2, 3]
```

For point two above, Werkzeug's behaviour is different for  `MultiDict.items()` too because it returns only one pair for each duplicate key. It has a modified signature `MultiDict.items(multi=True)` to return all items.

```python
In [24]: from werkzeug.datastructures import MultiDict

In [25]: d = MultiDict([('a', 1), ('b', 2), ('a', 3)])

In [32]: list(d.items())
Out[32]: [('b', 2), ('a', 1)]

In [33]: list(d.items(multi=True))
Out[33]: [('b', 2), ('a', 1), ('a', 3)]
```
