### ISSUE TITLE
Is multipart/form-data fully supported?

### ISSUE THREAD

**Issue by pingenglj** [Kludex/starlette#140]
I'd like to use starlette/responder, but when uploading an HTML form containing inputs of `type="file"` and `type="text"`; and parsing using `request.form()` it only parses a subset. Might be an issue with `parse_options_header()`?

request data in parser:
```
[(<MultiPartMessage.PART_BEGIN: 1>, b''), (<MultiPartMessage.HEADER_FIELD: 4>, b'Content-Disposition'), (<MultiPartMessage.HEADER_VALUE: 5>, b'form-data name="inputFile" filename="default.xml"'), (<MultiPartMessage.HEADER_END: 6>, b''), (<MultiPartMessage.HEADER_FIELD: 4>, b'Content-Type'), (<MultiPartMessage.HEADER_END: 6>, b''), (<MultiPartMessage.HEADERS_FINISHED: 7>, b''), (<MultiPartMessage.PART_DATA: 2>, b'<?xml>....somexmlstring'), (<MultiPartMessage.PART_DATA: 2>, b'\r\n'), (<MultiPartMessage.PART_END: 3>, b''), (<MultiPartMessage.PART_BEGIN: 1>, b''), (<MultiPartMessage.HEADER_FIELD: 4>, b'Content-Disposition'), (<MultiPartMessage.HEADER_VALUE: 5>, b'form-data name="outputName"'), (<MultiPartMessage.HEADER_END: 6>, b''), (<MultiPartMessage.HEADERS_FINISHED: 7>, b''), (<MultiPartMessage.PART_DATA: 2>, b'test'), (<MultiPartMessage.PART_END: 3>, b''), (<MultiPartMessage.END: 8>, b'')]
```

**Comment by pingenglj** [comment]
Seems that `parse_options_header()` check for a `;` to see if there are any options, and does not process headers like `Content-Disposition: form-data name=...` correctly.

**Comment by lovelydinosaur** [comment]
Is it replicable with `requests`?
Is it replicable in a test case?

**Comment by pingenglj** [comment]
Tom, I think this was an issue with my request headers, not an issue with starlette.

**Comment by lovelydinosaur** [comment]
Thanks! If you're able to follow up with what you were doing that made you think there was an error, then that might end up being useful context for someone else along the way.

**Comment by pingenglj** [comment]
Of course, I was manually adding header data to my request like so: `Content-Disposition: form-data name=`, forgetting the **;** that should be placed after `form-data`.
