### ISSUE TITLE
Add built-in CSRF support

### ISSUE THREAD

**Issue by Niccolum** [Kludex/starlette#1407]
### Checklist

- [X] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

Add full description here
https://github.com/tiangolo/fastapi/issues/4419
TL;DR according https://github.com/encode/starlette/issues/1 I want something built-in like https://github.com/frankie567/starlette-csrf

**Comment by Kludex** [comment]
Right now, we have at least three implementations:
- https://github.com/muicss/starlette-wtf#csrf-protection
- https://github.com/simonw/asgi-csrf
- https://github.com/frankie567/starlette-csrf

@frankie567 @simonw @tomchristie opinions on this?

At least a note in the documentation is worth it.
