### ISSUE TITLE
Add security headers as middlewares

### ISSUE THREAD

**Issue by Niccolum** [Kludex/starlette#1424]
### Checklist

- [X] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

Add couple of security middleware, which, I think, must be built-in app

### Describe the solution you would like.

Implement middlewares from https://github.com/tmotagam/Secweb :
Required (my opinion):

- Content Security Policy (CSP)
- Referrer Policy
- HTTP Strict Transport Security(HSTS)
- X-XSS-Protection

Other - as you want (my opinion)

- ExpectCT
- Origin Agent Cluster
- X-Content-Type-Options
- X-DNS-Prefetch-Control
- X-Download-Options
- X-Frame
- X-Permitted-Cross-Domain-Policies
- Cross-Origin-Embedder-Policy
- Cross-Origin-Opener-Policy
- Cross-Origin-Resource-Policy

### Describe alternatives you considered

SecWeb

### Additional context

Duplicate of https://github.com/tiangolo/fastapi/issues/4420

**Comment by lovelydinosaur** [comment]
If a feature request *can* start off as a third party package, then I'd almost always like to see that as a first pass.
