### ISSUE TITLE
Support for case-sensitive headers

### ISSUE THREAD

**Issue by angel-langdon** [Kludex/starlette#1454]
### Checklist

- [X] There are no similar issues or pull requests for this yet.
- [X] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

I am currently serving PDFs using `StreamingReponse` and `Range Requests`  (https://tools.ietf.org/html/rfc7233) specific headers to load them in batches using Mozilla `pdf.js` javascript library. The problem is that they have a case-sensitive implementation of headers, this is causing to fail because `Starlette` by default lower cases all headers.

I have tried disabling `.lower()` in `Response` class manually and everything works as expected: 
https://github.com/encode/starlette/blob/master/starlette/responses.py
![image](https://user-images.githubusercontent.com/53478143/151700445-2772090f-f2ac-4af0-a159-2a0f1cb95c94.png)

### Describe the solution you would like.

A parameter in `Response` that could be inherited through all responses that did enable case-sensitive headers

### Describe alternatives you considered

I have considered copying `Reponse` and `StreamingResponse` classes and customize them to don't lower case headers, however I don't think this is a long term solution.

### Additional context

There are many libraries that consider headers to be case sensitive

**Comment by Kludex** [comment]
We are following the ASGI specifications.

There's already an open issue about this on the asgiref repository: https://github.com/django/asgiref/issues/246

Once the specifications change there, we can comply here.
