### ISSUE TITLE
Minimum typing-extensions version is not specified

### ISSUE THREAD

**Issue by drasmuss** [Kludex/starlette#1474]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Starlette has a bare `typing-extensions` requirement, with no minimum version. But using older versions of `typing-extensions` will cause an error.

### Steps to reproduce the bug

```
pip install typing-extensions~=3.7.0
pip install starlette
python -c "from starlette.applications import Starlette"
```

### Expected behavior

Starlette should specify the minimum version of `typing-extensions` it requires, which would cause the `pip install starlette` command to upgrade `typing-extensions` to the required version (3.10).

### Actual behavior

Starlette doesn't install the required `typing-extensions` version, then the import fails.

### Debugging material

```
$ python -c "from starlette.applications import Starlette"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../lib/python3.8/site-packages/starlette/applications.py", line 3, in <module>
    from starlette.datastructures import State, URLPath
  File ".../lib/python3.8/site-packages/starlette/datastructures.py", line 8, in <module>
    from starlette.concurrency import run_in_threadpool
  File ".../lib/python3.8/site-packages/starlette/concurrency.py", line 10, in <module>
    from typing_extensions import ParamSpec
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (.../lib/python3.8/site-packages/typing_extensions.py)
```

### Environment

- Ubuntu 20.04, Python 3.8, Starlette 0.18

**Comment by lovelydinosaur** [comment]
Yup that's valid. Anyone want to issue a pull request for it?

Incidentally, in the trade-off between precise types vs. keep-it-simple I'd probably rather we just look at dropping `ParamSpec` from our typing entirely, and having more relaxed typing in the few cases we're currently using it.

(But the simpler approach for now is just to specify the min version in the `setup.py` file)

**Comment by drasmuss** [comment]
I can do a PR adding the minimum version (removing the `ParamSpec` requirement also seems fine, but is more than I'd want to get into).

**Comment by aminalaee** [comment]
I wonder how we should decide the minimum version.
The `typing_extensions` project doesn't have changelog prior to version 0.4.0.

**Comment by lovelydinosaur** [comment]
@drasmuss mentions correctly that it needs >= 3.10

See https://github.com/python/typing/pull/774/files and...

<img width="608" alt="Screenshot 2022-02-04 at 17 09 08" src="https://user-images.githubusercontent.com/647359/152572284-c8757dc8-9826-45e9-a209-fc339d872889.png">
