### ISSUE TITLE
Drop usage of routing decorators in test cases.

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#1481]
For quite a while now we've no longer documented the decorator-style for routing.

*We document this style of routing configuration...*

```python
def homepage(request):
    ...

routes = [
    Route('/', homepage),
]

app = Starlette(routes=routes)
```

*We no longer document this...*

```python
app = Starlette()

@app.route("/")
def homepage(request):
    ...
```

However several of our test cases still continue to use the old style, which is a bit inconsistent.

The same also applies to `app.add_middleware` vs. `app = Starlette(..., middleware=...)`.

We could do with a bit of clean-up here.

* Drop routing decorators in test cases.
* Drop `.add_middleware` in test cases.
* Add docstrings to the now undocumented API - "We no longer document this decorator style API, and its usage is discouraged"

For splitting this into individual chunks I'd probably suggest...

* A pull request for the docstrings change.
* Several pull requests for the test case change. Each pull request should only affect one file.

**Comment by adriangb** [comment]
Wow @aminalaee amazing work 🥳 ! I think #1505 is the last one (I found it by deleting the deprecated decorators and running tests)

**Comment by aminalaee** [comment]
@adriangb Thank you :)
Yes I think that's probably the last one. It will need a final check.

**Comment by adriangb** [comment]
@tomchristie I think we're done here :)
