### ISSUE TITLE
Form field names do not escape perfect encoding

### ISSUE THREAD

**Issue by HarrySky** [Kludex/starlette#149]
I switched one microservice from Flask to Starlette and got unexpected form parsing problem.
This code will return %20 in places where spaces were supposed to be:
```
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.requests import Request as StarletteRequest

SERVER = Starlette()

@SERVER.route("/send", methods=["POST"])
async def send_endpoint(request: StarletteRequest) -> PlainTextResponse:
    form = await request.form()
    if "number" in form and "name" in form:
        number = form["number"]
        name = form["name"]
        return PlainTextResponse("Number: " + number + " ; Name: " + name)
```

Maybe there are other issues with form parsing (x-www-form-urlencoded).

**Comment by mikespub** [comment]
Nice work - problem is it doesn't unquote the field names, e.g. field[0] remains field%5B0%5D

I'm pretty sure the multipart library can already handle all of this correctly if you pass it the Content-Type header...

**Comment by lovelydinosaur** [comment]
> I'm pretty sure the multipart library can already handle all of this correctly if you pass it the Content-Type header...

Perhaps - I don't know. QuerystringParser doesn't appear to care about the content-type header (and it's not obvious to me why the header would make a difference in this case).

https://andrew-d.github.io/python-multipart/api.html#multipart.multipart.QuerystringParser

**Comment by mikespub** [comment]
Sorry, I was referring to the main FormParser rather than the QuerystringParser in multipart.
After all, forms can be POSTed as application/x-www-form-urlencoded or multipart/form-data.

**Comment by lovelydinosaur** [comment]
Okay, does this need reopening then?
Anyone fancy submitting either a failing test case, or a test case and fix?

**Comment by lovelydinosaur** [comment]
Retitled to reflect the one remaining issue here.
