### ISSUE TITLE
responses.py does not handle MIME Types for fonts (.woff, ...) properly 

### ISSUE THREAD

**Issue by vucenovic** [Kludex/starlette#1524]
Hello, I am trying to deploy my app via FastAPI/Starlette, but font requests are being responded with "text/plain" in utf8 encoding causing errors. 

Can you add these lines to responses.py:

// add mimetype for fonts
mimetypes.add_type('application/vnd.ms-fontobject', '.eot')
mimetypes.add_type('application/x-font-opentype', '.otf')
mimetypes.add_type('application/x-font-ttf', '.ttf')
mimetypes.add_type('application/font-woff', '.woff')

so the guess_type function does behave properly?

**Comment by Kludex** [comment]
It looks fine here:
```python
from starlette.responses import FileResponse

print(FileResponse("potato.woff").media_type)  # font/woff
print(FileResponse("potato.woff2").media_type)  # font/woff2
print(FileResponse("potato.eot").media_type)  # application/vnd.ms-fontobject
print(FileResponse("potato.ttf").media_type)  # font/ttf
print(FileResponse("potato.otf").media_type)  # font/ttf
```

**Comment by lazka** [comment]
In case anyone else ends up here: The official `python:slim` Docker images (and variants like `python:3.11-slim-bullseye` etc) don't have a mime type list installed, which means fastapi and starlette will just default to `plain/text` for many things:

```python
Python 3.11.9 (main, May 14 2024, 08:32:26) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from starlette.responses import FileResponse
>>> print(FileResponse("potato.woff2").media_type)
text/plain
```

The fix is to `apt install media-types` so that `/etc/mime.types` exists.
