### ISSUE TITLE
[Potential Issue] Request headers not persisting to consequtive middlewares

### ISSUE THREAD

**Issue by ilyayudkovich** [Kludex/starlette#1541]
I have two middlewares that I'd like to execute in sequence. The first middleware modifies the headers of the request and the second does some logging utilizing the headers of the request.

This is a FastAPI app - not sure if that makes a difference. Below is the simple configuration I have 

```
class Middleware1(BaseHTTPMiddleware):

    async def dispatch(
        self, request: Request, call_next: RequestResponseEndpoint
    ) -> Response:
        request_id = 'my-test-request'

        new_headers = request.headers.mutablecopy()
        new_headers.append('X-Request-ID', request_id)
        request._headers = new_headers

        response = await call_next(request)

        response.headers['X-Request-ID'] = request_id

        return response


class Middleware2(BaseHTTPMiddleware):
    async def dispatch(
            self, request: Request, call_next: RequestResponseEndpoint
        ) -> Response:
            
            print('Request.headers ', request.headers) # Doesn't show new header
    
            response = await call_next(request)
    
            response.headers['X-Request-ID'] = request.headers.get('X-Request-ID')
    
            return response


app = FastAPI()

app.add_middleware(Middleware2)
app.add_middleware(Middleware1)

@app.get("/")
async def sum_numbers():
    return {"success": True}
```

**Expected behavior** : Middleware2 would get the request with the updated headers - thus being able to get `X-Request-ID` out of the request.headers

**Current behavior**: Middleware2 gets the request without the updated headers

**Comment by Kludex** [comment]
Yeah, we actually use the `scope` to create the `Request` object that is going to be used on each `dispatch` function call. When modifying the `Request.headers` it will not modify the `scope`, so that's why you can't see it on the other middleware.

I think this behavior is as intended. You can use https://github.com/tomwojcik/starlette-context for this specific use-case.
