### ISSUE TITLE
Raise custom Starlette Exception on missing "boundary"

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#1542]
We should probably catch that and raise something else from Starlette itself :thinking:

_Originally posted by @Kludex in https://github.com/encode/starlette/issues/1349#issuecomment-1028902007_

Check comment for context.

**Comment by opeco17** [comment]
Hi, @Kludex 
May I work on this task?

**Comment by Kludex** [comment]
Sure. 👍

**Comment by opeco17** [comment]
Hi, @Kludex 
Could you please help review my PR (https://github.com/encode/starlette/pull/1544) when you have some time?

**Comment by Kludex** [comment]
@opeco17 Thanks for the PR, but after the research (check https://github.com/encode/starlette/pull/1544#issuecomment-1080197920), I think we should not follow what this issue proposes. I'll create another issue to replace this one.
