### ISSUE TITLE
Denying WebSocket connection in WebSocketEndpoint.on_connect leads to Exception

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#1560]
### Discussed in https://github.com/encode/starlette/discussions/1555

<div type='discussions-op-text'>

<sup>Originally posted by **dingensundso** March 27, 2022</sup>
I created a WebSocketEndpoint class in which I want to deny the connection in certain conditions.
When the WebSocket is closed in on_connect I receive the following exception:

```
  File "starlette/endpoints.py", line 83, in dispatch
    close_code = int(message.get("code", status.WS_1000_NORMAL_CLOSURE))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
So code is None when the server denies the connection instead of non-existant.

https://github.com/encode/starlette/blob/e086fc2da361767b532cf690e5203619bbae98aa/starlette/endpoints.py#L72-L87

Changing line 83 to the following should fix the issue:
```python
close_code = int(message.get("code") or status.WS_1000_NORMAL_CLOSURE)               
````
</div>

**Comment by Kludex** [comment]
Can someone confirm this?

**Comment by aminalaee** [comment]
I can't reproduce this, a minimal example would be very helpful.

**Comment by dingensundso** [comment]
While creating a minimal example I noticed that the problem only exists when using **wsproto** instead of websockets.

Minimal example:
```python
from starlette.applications import Starlette
from starlette.endpoints import WebSocketEndpoint, HTTPEndpoint
from starlette.responses import HTMLResponse
from starlette.routing import Route, WebSocketRoute

html = """
<!DOCTYPE html>
<script>
    var ws = new WebSocket("ws://localhost:8000/ws");
</script>
"""

class Homepage(HTTPEndpoint):
    async def get(self, request):
        return HTMLResponse(html)

class Echo(WebSocketEndpoint):
    async def on_connect(self, websocket):
        await websocket.close()

routes = [
    Route("/", Homepage),
    WebSocketRoute("/ws", Echo)
]

app = Starlette(routes=routes)
```

Running it with `uvicorn ws:app --ws=wsproto` and opening the URL produces the Exception.

**Comment by Kludex** [comment]
As per https://asgi.readthedocs.io/en/latest/specs/www.html#disconnect-receive-event-ws (image below), the application should receive the "code" from the server. There's no default on the specs, meaning that the server MUST send it.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/7353520/161829298-13c9e326-97f9-4a84-b30b-81cfb21e22ad.png">

The interpretation of "if the server" should default to a value, or if the application should be the one to default to, is confusing... That being said, I'll create a fix for Starlette as well.
