### ISSUE TITLE
[question] how to mount router into Starlette app? `app.mount('/', router)` does't work

### ISSUE THREAD

**Issue by vanyakosmos** [Kludex/starlette#160]
Example:

```python
from starlette.applications import Starlette
from starlette.middleware.cors import CORSMiddleware
from starlette.requests import Request
from starlette.routing import Router, Route
import uvicorn

from views import FooView


app = Starlette(debug=True)
# need middleware, so I use Starlette app
app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_headers=["*"], allow_methods=["*"]
)
router = Router([
    Route('/foo', endpoint=FooView),
])
app.mount('/', router)  # << doesn't work for some reason

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=4000)
```

**Comment by lovelydinosaur** [comment]
Actually I think we need to do some work here. Mount points should probably forcibly always end with “/“ and raise an error otherwise. That way we can enforce consistent style.

**Comment by lovelydinosaur** [comment]
Actually not obvious to me what style we should enforce here, but I think we need to make it harder to get wrong.

**Comment by jessebraham** [comment]
I was running into some similar issues with the Router today while playing around with it. Mounting the `Router` instance to the `Starlette` instance using an empty string as @vanyakosmos described did initially fix the problem. As stated by @tomchristie however, this should be more difficult to get wrong; `/` and empty string should be equivalent in this scenario.

To add on to this, I also noticed (unless I'm missing something fundamental here) that endpoints of mounted sub-applications **must** have the trailing `/` present or a 404 is returned.  

Example:

```python
admin = Starlette()

@admin.route("/")
class Dashboard(HTTPEndpoint):
    async def get(self, request):
        return UJSONResponse({"success": True})
```

```python
router = Router([Mount("/admin", app=admin)])

app = Starlette(debug=True)
app.mount("", router)
```

`GET http://localhost:8000/admin/` -> 200  
`GET http://localhost:8000/admin` -> 404

Just feels a bit unnatural to me, but again please let me know if I'm missing something here ;)
