### ISSUE TITLE
Request to provide an easy canonical way to specify a function to call after last byte is sent.

### ISSUE THREAD

**Issue by zya-performance** [Kludex/starlette#166]
This will help with cleaning up any temp resources used to stream a response out.

Similar in functionality to : http://flask.pocoo.org/docs/1.0/patterns/deferredcallbacks/  
@after_this_request  etc.

**Comment by lovelydinosaur** [comment]
https://www.starlette.io/background/

**Comment by zya-performance** [comment]
class StreamingResponse(Response):  does not have background  in its init or call 
leading to ..  
    return StreamingResponse( generate , media_type="audio/wav", background = cleanup_task )
TypeError: __init__() got an unexpected keyword argument 'background'
