### ISSUE TITLE
Provide `whence` feature in file handling

### ISSUE THREAD

**Issue by meysam81** [Kludex/starlette#1737]
https://github.com/encode/starlette/blob/0673aebb14f33ac9c19f2aa71ea28f7a65b43017/starlette/datastructures.py#L467:L471

In some applications, there might be a need to use the `whence` feature. This might be a special use case but in some of our data applications, the `pandas` is leveraging the `whence` API and it would be really good if we don't have to manually handle that with `self._file.seek(offset, whence)` ourselves.

**Comment by euri10** [comment]
this has been dismissed, see https://github.com/encode/starlette/pull/1084
