### ISSUE TITLE
Route paths do not preserve spaces

### ISSUE THREAD

**Issue by alexbotello** [Kludex/starlette#175]
Bit of a niche problem, but one that could cause frustrating bugs if encountered. If spacing exists in a `path` the router will fail to match the route.

A request made to `http://0.0.0.0:8000/stream/song name here.mp3` 
Will try to match as `http://0.0.0.0:8000/stream/song%20name%20here.mp3`

Somewhere, maybe in `Router.__call__`, we can intercept the scope and modify it's `path`
```python
path = scope["path"]
scope["path"] = unquote(path)
```
Unless modifying the scope directly is not advised?

**Comment by lovelydinosaur** [comment]
Step 1.  Double check the ASGI spec re. if the path should be unquoted already. (In which case address this in uvicorn etc.)
