### ISSUE TITLE
Log errors and abort in case exceptions are thrown in the startup handler

### ISSUE THREAD

**Issue by supriyo-biswas** [Kludex/starlette#177]
At present, any uncaught exceptions that are thrown in the startup handler are apparently consumed without logging it to the standard input/error.

Can we have a change in this behaviour, so that any uncaught exceptions in the startup handler cause Starlette to log the error and abort execution?

**Comment by lovelydinosaur** [comment]
Starlette should just raise the error. Uvicorn should log the errors and abort startup (If it doesn’t already).

**Comment by lovelydinosaur** [comment]
Looks like uvicorn logs the lifespan exceptions at “debug” level instead of “error” level...

https://github.com/encode/uvicorn/blob/master/uvicorn/lifespan.py

I’ve not checked on if it’d abort on exceptions or not.

**Comment by lovelydinosaur** [comment]
Resolved in Uvicorn 0.3.23
