### ISSUE TITLE
Session middleware is highly insecure

### ISSUE THREAD

**Issue by supriyo-biswas** [Kludex/starlette#178]
The session middleware does not have any timestamp component to it, which means that if a session happens to be somehow leaked, it can be reused any time in the future.

Can we have a timestamp component added to the session, so that the session middleware can reject such sessions after a reasonable period of time (e.g. 24 hours)?

**Comment by jessebraham** [comment]
This is actually a relatively simple fix, as `itsdangerous` also provides a `TimestampSigner` class. This works the exact same way as `Signer`, while additionally recording the time of signing. When unsigning you can provide a `max_age` argument (in seconds), which will raise `itsdangerous.exc.SignatureExpired` if the signature has expired.

With this in mind, my questions would be:
1. Is 24 hours the value we want to use for `max_age` (seems reasonable enough to me), or if not what value would be appropriate?
2. In the case that the signature has expired, what do we want to do? Do we want to simply clear the scope's session (ie. `scope["session"] = {}`) like we are if the session cookie is not present in the request and continue execution, or raise an exception?

I can make a pull request once I have answers for the above questions.

**Comment by lovelydinosaur** [comment]
Django uses 2 weeks by default. If we make it configurable then that sounds okay. We should treat the session as empty if it’s expiried - it’s not an exception case.
