### ISSUE TITLE
Negative values and int&float convertors

### ISSUE THREAD

**Issue by jvail** [Kludex/starlette#1790]
### Discussed in https://github.com/encode/starlette/discussions/1778

<div type='discussions-op-text'>

<sup>Originally posted by **jvail** July 27, 2022</sup>
Hi,

I may have missed the discussion/issue but I wonder what the reason might be to not support negative values in the default float & int convertors?

I have now implemented them myself (by copying starlette's default converters and changing the regex). But of course I'd prefer not to do that.

Thank you
Jan</div>

Would you accept a PR for this? I am using the regex from here https://docs.python.org/3/library/re.html#simulating-scanf. So fairly reliable, I guess.

**Comment by Kludex** [comment]
The behavior we have matches Django and Flask.

We already allow the [creation of custom convertors](https://www.starlette.io/routing/#path-parameters), as you did.

Based on the above, I don't see a strong case to implement this on Starlette.
