### ISSUE TITLE
Support route convertors

### ISSUE THREAD

**Issue by manatlan** [Kludex/starlette#182]
Hi, I've just discovered starlette (seems to be the perfect asgi fw ! great)
Looking into docs/unitests ... but it seems that regex routing is not implemented yet (will look into the code)

Is it possible to declare something like that ?
```python 
@app.route("/api/{name:.*}")
def ...
```

It's the only thing it seems to miss (to quit aiohttp)

**Comment by lovelydinosaur** [comment]
We don't *currently* have any support for that, no.
And yes, it would be (very) good to do so.

I'm not sure exactly what we'd want to adopt here - if we should use something like [flask's URL convertors](http://exploreflask.com/en/latest/views.html), or if we should just use regexs. What existing different options do other frameworks currently use? Which options support type coercion, and which always return strings for the path parameters?

**Comment by manatlan** [comment]
I don't known flask at all (I just know that it was a joke against bottle, at the begining ..)

I'm coming from bottle(wsgi) ( https://bottlepy.org/docs/dev/routing.html ). Bottle does type coercions.

And in asgi world: I use aiohttp ( https://aiohttp.readthedocs.io/en/stable/web_quickstart.html#resources-and-routes ), which just return strings.

But in all cases : you'll need to add a sort of "path/catchall" ... to let the developper parse the path as he wants.
Because, currently ; It's impossible to make an endpoint with an abritratry number of subpaths

Currently i do : (it's not pretty, and it works only for 6 ;-)  
```python
@app.route('/{p1}/{p2}/{p3}/{p4}/{p5}/{p6}')
@app.route('/{p1}/{p2}/{p3}/{p4}/{p5}')
@app.route('/{p1}/{p2}/{p3}/{p4}')
@app.route('/{p1}/{p2}/{p3}')
@app.route('/{p1}/{p2}')
@app.route('/{p1}')
@app.route('/')
async def gotopath(request):
    fullpath="/".join( request.path_params.values() )
```

**Comment by Dith3r** [comment]
> Because, currently ; It's impossible to make an endpoint with an abritratry number of subpaths

It's possible to declare your own regex. 

```
@app.route("/(?P<path>.*)")
```

**Comment by lovelydinosaur** [comment]
@Dith3r That's true actually, yeah. (Tho it won't work with `request.url_for(...)`)

**Comment by lovelydinosaur** [comment]
I've retitled the issue with the feature that we'd actually like to have here. Converters for routes.

So, initially just making sure that we can support this kind of thing...

`/{something:path}`  # Allow slashes in the path
`/{user_id:int}`  # Coerced to an integer

**Comment by anentropic** [comment]
How do I get a regex route to work?

```
@app.route("/base/{someid}/(?P<myvar>.*)")
```

this gives an error
```
apilibrary_1  |   File "/home/webapp/.local/share/virtualenvs/src-NCIGkioc/lib/python3.7/site-packages/starlette/routing.py", line 182, in matches
apilibrary_1  |     matched_params[key] = self.param_convertors[key].convert(value)
apilibrary_1  | KeyError: 'myvar'
```

**Comment by Dith3r** [comment]
Look at URL converters pull request. Only option is to extend converters array with ours specific one regex.

**Comment by lovelydinosaur** [comment]
Don’t. Just use :path for open ended stuff, and verify or 404 in the endpoint.

**Comment by anentropic** [comment]
👍
