### ISSUE TITLE
Move setup.cfg into pyproject.toml

### ISSUE THREAD

**Issue by ischaojie** [Kludex/starlette#1849]
I notice `starlette` starting to use `pyproject.toml`, but some tools config are still in `setup.cfg`, it's better to move that config into `pyproject.toml`。

**Comment by Kludex** [comment]
Yes. But before that, I'd like to know if https://pypi.org/project/Flake8-pyproject/ is reliable, so we can remove the `setup.cfg`.

**Comment by Kludex** [comment]
We start those kind of PRs in `httpx`, then we follow the other encode projects.
