### ISSUE TITLE
 Starlette is not parsing the manipulated or newly added headers from gateway

### ISSUE THREAD

**Issue by vijaycenation14** [Kludex/starlette#1859]
We have a gateway which routes and add certain headers to the request. All our node services are able to parse the manipulated headers but the fast api service which internally uses starlette is not getting the headers.

**Comment by csrgxtu** [comment]
![image](https://user-images.githubusercontent.com/5053620/190574004-cdf9ca5e-7800-4cc2-8130-58fc65d1e9d9.png)

starlette wont drop your customized header, it will pass it into your application, you should check or make sure that gateway do send the customized header.

according to `asgi` protocol, the framework should load data from scope, here is starlette's code to load headers:
```python
    @property
    def headers(self) -> Headers:
        if not hasattr(self, "_headers"):
            self._headers = Headers(scope=self.scope)
        return self._headers
```

**Comment by vijaycenation14** [comment]
Hi @csrgxtu, Sorry this was due to fast-api being redirecting the request with trailing `/` and the headers are dropped during the redirection. We fixed it. Thanks for the reply.
