### ISSUE TITLE
Support an `APISpec` SchemaGenerator

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#189]
So @kennethreitz's Responder uses APISpec for generating the API schemas.
That's actually really nice, as it includes various plugins including marshmallow support etc.

We should have a [SchemaGenerator](https://www.starlette.io/schemas/) implementation that uses APISpec. I'm guess ideally it should be a third party implementation, rather than included in the main package.

This would make a great little project for a contributor to jump onto.

See also #172

**Comment by lovelydinosaur** [comment]
Note that we'll kept the schema generation strictly separate from any API docs generation.

**Comment by woile** [comment]
Some questions

1) What would be the idea for now? Do you have any rough example using APISpec?

 Would something like this be okay?

```python
from starlette.applications import Starlette
from apispec import APISpec

app = Starlette()
app.schema_generator = APISpec(
    title='Gisty',
    version='1.0.0',
    openapi_version='3.0.0',
    info=dict(
        description='A minimal gist API'
    )
)

@app.route("/users", methods=["POST"])
def create_user(request):
    """
    responses:
      200:
        description: A user.
        examples:
          {"username": "tom"}
    """
    raise NotImplementedError()

@app.route("/schema", methods=["GET"], include_in_schema=False)
def schema(request):
    return OpenAPIResponse(app.schema)
```

Of course this would mean that you could use marshmallow plugin for example

And make starlette understand when an `APISpec` instance is received?

And regarding this:

> Note that we'll kept the schema generation strictly separate from any API docs generation.

2) It means apistar could be used to generate the docs based on starlette's schema, right?

Cheers!

**Comment by lovelydinosaur** [comment]
@Woile That's about right yes.

You wouldn't be able to *quite* do this: `app.schema_generator = APISpec` since the schema generator needs to fulfil the `BaseSchemaGenerator` interface.

https://github.com/encode/starlette/blob/master/starlette/schemas.py#L24

Ie. implement `get_schema` so that it passes each route to `spec.add_path`

**Comment by woile** [comment]
Yeah, true. So we should have a wrapper over APISpec, maybe called `APISpecSchemaGenerator`, right?

Should this schema generator live inside Starlette or should it be a third party package?

**Comment by lovelydinosaur** [comment]
> Should this schema generator live inside Starlette or should it be a third party package?

Probably a separate package, but could go either way. I guess start out by demonstrating it in code, then we can figure out where it lives afterwards.

**Comment by woile** [comment]
I think we can close this now, right?

In conclusion, a package was released for apispec: [starlette-apispec](https://github.com/Woile/starlette-apispec)

**Comment by lovelydinosaur** [comment]
Let’s wait til we’ve got docs linking to it.
Initially let’s include a brief paragraph and link from the schemas docs section. We can expand things out to a plugins doc later.

**Comment by woile** [comment]
Oki, I can create a PR, if you don't mind, something along the lines:

in `docs/schemas.md`
```
# Third party packages

## starlette-apispec
Easy APISpec integration for Starlette
```

And on a side note, is there a preference for any of these names: `plugins`, `extensions` or `third party packages`?

**Comment by lovelydinosaur** [comment]
Third party packages would be fine.
