### ISSUE TITLE
Add GitHub repository on our documentation

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#1896]
The idea is to allow people to fix or recommend suggestions on our documentation with this `mkdocs-material` feature: https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/.

**Comment by ayushthe1** [comment]
Hey ,i would like to work on this issue . Could you please explain what i need to do here .

**Comment by Kludex** [comment]
I think you only need to include "repo_url", and "edit_uri" on the "mkdocs.yml" file.

The task is to be able to see a button on the top of each documentation page, that allows people to propose fixes on those pages more easily.

**Comment by ayushthe1** [comment]
hey @Kludex ,i made a pr for this issue . Could you please review it.
