### ISSUE TITLE
Default `jinja2` setup.

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#196]
I think we *probably* ought to include a default Jinja2 setup out-of-the box, so...

```python
from starlette.applications import Starlette
from starlette.responses import Response

app = Starlette(template_dir="templates")

@app.route("/")
async def homepage(request):
    template = app.get_template("index.html")
    content = template.render(request=request)
    return HTMLResponse(content=content)
```

We'd ensure that the support is strictly optional, and document what a more explicit setup would look like.

This would require:

* Adding `template_dir=` to `Starlette.__init__` and use it to setup a `.template_env` attribute.
* Add `Starlette.get_template()`

See our [example repo](https://github.com/encode/starlette-example) or our [template docs](https://www.starlette.io/templates/) for how the template setup should work.

Any feedback on this?
Anyone interested in tacking a crack at it?

**Comment by marcosschroh** [comment]
Good one. Also I think the templates that we are using for DEBUG mode (500) and in the future 404 should be loaded by Jinja as well.

**Comment by jessebraham** [comment]
I can take a swing at this one over the weekend

**Comment by Witekkq** [comment]
So currently the jinja2 package is needed to be installed even if I do not use tempate in my project at all?

**Comment by jessebraham** [comment]
Jinja2 is an optional package and is only required for using the default template configuration

**Comment by lovelydinosaur** [comment]
@Witekkq - It's completely optional. If you set `template_directory` it'll set up a default environment for you, but otherwise you can either just omit that, or use a different templating engine or whatever.
