### ISSUE TITLE
Testing template reponses

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#199]
This is going to require a bit of thinking about.

```python
app = Starlette(template_directory='templates')

@app.route('/')
async def homepage(request):
    template = app.get_template('index.html')
    content = template.render(request=request)
    return HTMLResponse(content)

client = TestClient(app)
response = client.get('/')
assert response.template = 'index.html'
assert 'request' in response.context
```

Two issues here. Firstly we haven't associated the template name or context with the response in any way, so we can't reference them from the template. We could do so, with something like...

```python
return app.render_reponse('index.html', context={'request': request})
```

Or...

```python
return TemplateResponse(template, context={'request': request}))  # I *guess* `template` has the "index.html" name string associated with it somewhere?
```

Secondly, we don't have access to the response instance itself, we've just been sent ASGI messages. We'd need to ensure that `TemplateResponse` included some extra info ("template", "context") in the messages that it sent back, and that `TestClient` was able to additionally annotate the response with that information.

**Comment by jordaneremieff** [comment]
@tomchristie I updated the PR to include one potential pathway for the first part (assuming I understood the issue correctly) - though making the response details available on the `TestClient` appears to be a more difficult challenge.

Is that something that perhaps extensions could be used for? Or just custom message types? I found that if I send the template/context data through the response messages into the adapter that I was still faced with the problem of allowing the mock response to digest that information through the raw request.
