### ISSUE TITLE
Starlette doesn't work well on AppEngine/python37 standard environment

### ISSUE THREAD

**Issue by manatlan** [Kludex/starlette#200]
It's not the place to post that ...
But perhaps, somebody has already tested that ...

I've setuped a starlette app, on GoogleAppEngine standard env (2nd generation/python37)
with an app.yaml with an entrypoint like thoses (tested with the 2 variants): 
- gunicorn -w 2 -k uvicorn.workers.UvicornWorker -b :$PORT main:app
- uvicorn --host 0.0.0.0 --port $PORT main:app

On local (dev_appserver) or in the cloud (appspot's instance)
Things seems to work (except: streamed responses are sended in one block, websockets doesn't seems to be available)

But on the appspot's instance : some simple requests ends in 500, with this simple message in the logs : 

    The process handling this request unexpectedly died. This is likely to cause a new process to be used for the next request to your application. (Error code 203) 

hitting F5, and requests works .... til the next error.

Seems unstable ...

someone has got better results on gae/py37 ?
should it work ?

**Comment by lovelydinosaur** [comment]
Might be worth searching for similar issues reported to Sanic or aiohttp?

**Comment by manatlan** [comment]
In fact, GAE breaks when I try to send back a 304 with empty content (#201 )
(I reproduce it always)

Else, everything works (except websocket ... but it seems that GAE block that from the ground ... but perhaps available in the future !!! )
StreamingResponse seems to be capturated by GAE and send back in one shot.

Else : everything seems to work (background task , ...)

BTW you can close that issue, as non-related ...

I will make more tests, but it seems ok ...

**Comment by manatlan** [comment]
In fact, it's me ;-(

I sent back the 304 with headers [content-type, etag] : and it breaks GAE ...
Now, everything is OK (except details ^^)
