### ISSUE TITLE
GZipMiddleware appears to not honor minimize_size

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#2003]
### Discussed in https://github.com/encode/starlette/discussions/1253

<div type='discussions-op-text'>

<sup>Originally posted by **flashgorman-chorus** July 26, 2021</sup>
I have installed `GZipMiddleware` with a `minimize_size` set to 1024.  When I make a request that returns a response smaller than 1024, I expect the response will not be compressed and the `Content-Encoding` header will not be set to `gzip`.

My testing, however, shows that the responses are always compressed and `Content-Encoding` is always set to `gzip`.

Debugging the code, I see `send_with_gzip` is called but `message["more_body"]` is set to `True` the first time through, no matter what, from `testclient.py`:

```python
    async def stream_response(self, send: Send) -> None:
        await send(
            {
                "type": "http.response.start",
                "status": self.status_code,
                "headers": self.raw_headers,
            }
        )
        async for chunk in self.body_iterator:
            if not isinstance(chunk, bytes):
                chunk = chunk.encode(self.charset)
            await send({"type": "http.response.body", "body": chunk, "more_body": True})

        await send({"type": "http.response.body", "body": b"", "more_body": False})
```

As a result, the key block of code in `gzip.py` that I expected to enter is skipped:

```python
if len(body) < self.minimum_size and not more_body:
    # Don't apply GZip to small outgoing responses.
    await self.send(self.initial_message)
    await self.send(message)
```

Since `more_body` is `True`, it never enters this block.  Perhaps this is just an aberration of the test client?  Or I am doing something wrong?</div>

**Comment by Kludex** [comment]
This test shows that everything is fine:

https://github.com/encode/starlette/blob/048643adc21e75b668567fc6bcdd3650b89044ea/tests/middleware/test_gzip.py#L42-L56

**Comment by luizgois-luizalabs** [comment]
@Kludex I'm having the same problem.
Looking at the test I don't see that it guarantees that a small payload doesn't see GZIP, it's just guaranteeing that it returns a 200.
Would it be possible to reopen the issue?

**Comment by Kludex** [comment]
How's that test not guaranteeing that? If you create a test that fails, and should pass proving your point, we can reopen it.

**Comment by luizgois-luizalabs** [comment]
Sorry, the github interface didn't show the rest of the test.

But I discovered the problem that was happening in my application, it was the order that the middlewares were being added, putting GzipMiddleware in the first one solved the problem.

Again, I'm sorry

**Comment by Kludex** [comment]
No problem. Glad the problem was solved. :)
