### ISSUE TITLE
the raw "Response" should'nt mandatory a content ... no ?

### ISSUE THREAD

**Issue by manatlan** [Kludex/starlette#201]
I need to manage myself the etag/304 response ...

to send a 304 if-none-match, I use : 

    Response(status_code=304,content="",headers=rheaders)

But the body content should not be written ... here the content is mandatory : None cause troubble, and empty string is an empty string ...

**Comment by lovelydinosaur** [comment]
Sure. Let’s change the default value to b””.

**Comment by laixintao** [comment]
I can make this change, should we change https://github.com/encode/starlette/blob/3a16d660490b54daad5711749fa00fd7a0970b4e/starlette/responses.py#L166 as well?

**Comment by manatlan** [comment]
In fact, the response shouldn't write anything when no content ... (and not a b"" too) (from RFC:  The 304 response MUST NOT contain a message-body, and thus is always ...)

I'm pretty sure it's that problem which make my issue #200 .
in fact ; it seems that GAE breaks when I try to send back a 304 with empty content ""

I have no time today, but tomorrow I will hack the Response to try something, which will perhaps resolve my #200 trouble ... (I'd like to remove this line https://github.com/encode/starlette/blob/3a16d660490b54daad5711749fa00fd7a0970b4e/starlette/responses.py#L124)

**Comment by manatlan** [comment]
In fact, it was me ;-(

I sent back the 304 with headers [content-type, etag] : and it breaks GAE ...
no trouble with empty content (b"")
