### ISSUE TITLE
Docs workflow

### ISSUE THREAD

**Issue by tarsil** [Kludex/starlette#2010]
I was wondering if it would be worth it to split the workflows and trigger possible documentation workflows without the need of a new release?

If is possible, I wasn't fully aware so I apologize in advance.

**Comment by Kludex** [comment]
I don't think that's worth it. 🧐

When code changes are followed by documentation changes, that will not be possible anyway.

**Comment by tarsil** [comment]
I understand, but this also for the sense of, what if we deploy some typos that everyone missed? Small examples of course

**Comment by Kludex** [comment]
If they are small examples, they can wait to be fixed... Can't they? I mean, it never happened...

**Comment by tarsil** [comment]
Fair enough, this was just a thought

**Comment by Kludex** [comment]
Suggestions are always welcome. I understand that you want your package to land on the docs, but don't worry, let's see if we can make a release by the end of the month. 👀

**Comment by tarsil** [comment]
Oh no no, Its not that. It's because coincidentally I was working with Django an reading some docs and I found a typo and not only I thought adding that to Esmerald as well but I thought about suggesting the same in Starlette. Nothing else :)

**Comment by Kludex** [comment]
Oh well, I'm sorry. I guess I put myself in your shoes, and I'm a bit more impatient hahaha

**Comment by tarsil** [comment]
Oh, no worries, I would probably think the same if I were in your shoes ahahah. Thank you :)
