### ISSUE TITLE
Question/New Feature: Support for periodic timers

### ISSUE THREAD

**Issue by emacsuser123** [Kludex/starlette#202]
Hello.
Any plans to support periodic timers?
I have seen support only for startup/shutdown events.

I'm trying to develop an ASGI web server and, on top of it, also being able to do some periodic tasks apart from responding to the exposed endpoints.

I have tried (programatically) to use the regular asyncio framework along with startlette/uvicorn but they do not share the same event loop. If I start the uvicorn server configured with asyncio event loop, I get also an error because it cannot run the event loop while another is running, which is expected.

Any way to share the same event loop for both the web server and the periodic async timers?

Thanks. 
-Bob V

**Comment by lovelydinosaur** [comment]
> Any plans to support periodic timers?

Yup.

> Any way to share the same event loop for both the web server and the periodic async timers?

The short version of this is: Start a new task in startup then cancel it in shutdown. Do whatever background stuff you want off of that task.

**Comment by emacsuser123** [comment]
Thanks!  I'll try that out.
One more question... If that background stuff means sending HTTP requests, I have been taking a look and the only thing that seems to be available is the aiohttp client, which is based on asyncio framework.
That means that I cannot use uvicorn with uvicorn event loop, and my only valid choice is asyncio as the loop. Right?

Thanks.

**Comment by lovelydinosaur** [comment]
You shouldn't have any issues using the `aiohttp` client.

**Comment by emacsuser123** [comment]
Even if I use the uvicorn event loop?  OK, that is great.   Thanks!

**Comment by emacsuser123** [comment]
I'm getting an error when I start my periodic timer upon startup event.
It seems to work right, but after some time, the following error is fired:

......
>    self.loop.run_until_complete(self.lifespan.wait_startup())
>   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
>     return future.result()
>   File "/home/user/.local/share/virtualenvs/repo-rmveCKyM/lib/python3.7/site-packages/uvicorn/lifespan.py", line 56, in wait_startup
>     await asyncio.wait_for(self.startup_event.wait(), timeout=self.startup_timeout)
>   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
>     raise futures.TimeoutError()
> concurrent.futures._base.TimeoutError

Taking a look at the Starlette home page, the following is stated:

_Starlette will not start serving any incoming requests until all of the registered startup handlers have completed._

Does it mean that periodic tasks cannot be periodic if I want to also serve web content?
None of my periodic tasks will ever complete.

Thanks.

**Comment by lovelydinosaur** [comment]
It means you’ll need to start a sub-task, with `loop.create_task` and let *that* run your background stuff.

**Comment by emacsuser123** [comment]
Ah ok. I have done it and it is working now, thanks.
If I await for the task, then it fails with the error that I mentioned above.
But if I do not await for the task (its sub-tasks are awaited inside it), then it works ok.

**Comment by realsby** [comment]
@emacsuser123 can you share a sample please
