### ISSUE TITLE
bug: TestClient no longer accepts json as a delete argument

### ISSUE THREAD

**Issue by LorhanSohaky** [Kludex/starlette#2087]
When they migrated from requests to httpx they forgot to add the json parameter.

> TypeError: delete() got an unexpected keyword argument 'json'

![image](https://user-images.githubusercontent.com/16273730/226229345-9e515d40-0a04-4419-b7de-fc629d1392ba.png)

https://github.com/encode/starlette/pull/1376/files

**Comment by euri10** [comment]
hello, a quick search : https://github.com/encode/httpx/discussions/1587

**Comment by Kludex** [comment]
You can also use https://github.com/Kludex/bump-testclient for the migration, if you want. :eyes:

**Comment by LorhanSohaky** [comment]
> hello, a quick search : [encode/httpx#1587](https://github.com/encode/httpx/discussions/1587)

Sorry, I was looking for open discussions. But then shouldn't this migration be classified as breaking change and not just change?

**Comment by Kludex** [comment]
Since we are on zero version (0.x), any breaking or important change alters the minor (`0.y.z` -> `0.(y + 1).0`). Which is what we did.

**Comment by LorhanSohaky** [comment]
I refer to the changelog
https://github.com/encode/starlette/releases/tag/0.21.0

**Comment by Kludex** [comment]
> [...] your test suite will likely break. [...]

What were you expecting there?

**Comment by LorhanSohaky** [comment]
I'm just commenting because when I updated the fastapi version the tests broke, so I saw that they had updated the starlette version. So I searched the changelogs for breaking change or something similar, but I couldn't find it.

So I kept looking using "git diff" to find out what version it happened on

> ## BREAKING CHANGE
> 
> - Replace requests with httpx in TestClient #1376.

**Comment by LorhanSohaky** [comment]
I could be wrong, but they usually put breaking changes like this

**Comment by Kludex** [comment]
Who are "they"?

**Comment by LorhanSohaky** [comment]
> Who are "they"?

"they" = other libraries

**Comment by mehmetcanfarsak** [comment]
Hi,
I wrote an article about possible solutions and how to implement it
https://medium.com/@mehmetcanfarsak/solution-for-testclient-delete-payload-support-8ae12e153a3a
