### ISSUE TITLE
StaticFiles with follow_symlink not working correctly in venvs on Windows.

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#2112]
### Discussed in https://github.com/encode/starlette/discussions/2111

<div type='discussions-op-text'>

<sup>Originally posted by **falkoschindler** April  4, 2023</sup>
It looks like there is something wrong in `StaticFiles.loopup_path`. On venvs on Windows we noticed a problem with the common prefix check.

Consider the following test script (here I'm refering to our library called NiceGUI, but any other side package should give a similar result):

```py
from nicegui import ui

directory = Path(ui.__file__).parent / 'static'
print(f'{directory = }')
print(f'{os.path.abspath(directory)  = }')
print(f'{os.path.realpath(directory) = }')
```

This yields the following output:

```
directory = WindowsPath('C:/Users/username/Envs/venv_name/lib/site-packages/nicegui/static')
os.path.abspath(directory)  = 'C:\\Users\\username\\Envs\\venv_name\\lib\\site-packages\\nicegui\\static'
os.path.realpath(directory) = 'C:\\Users\\username\\Envs\\venv_name\\Lib\\site-packages\\nicegui\\static'
```

Note that `realpath` returns an uppercase "Lib" while `abspath` doesn't.

This causes the common prefix to be only "C:\Users\username\Envs\venv_name\", which is outside of the `directory`. Therefore the following check is true and the directory is not served:

https://github.com/encode/starlette/blob/f7bf74194358cceb5708f758989df89240c0c1aa/starlette/staticfiles.py#L172

I'm not perfectly sure how to fix it. Maybe using `commonpath` instead of `commonprefix`? Maybe converting strings to lowercase first? Maybe using pathlib instead of os.path?

Anyway, it's an issue which confused us quite a bit over here: https://github.com/zauberzeug/nicegui/issues/714</div>

**Comment by kiwifoxtrot** [comment]
I think it might be a simple fix using `os.path.normcase()` to process `full_path` and `directory` before checking with `os.path.commonprefix()`:

`os.path.normcase(path)`
_Normalize the case of a pathname. On Windows, convert all characters in the pathname to lowercase, and also convert forward slashes to backward slashes. On other operating systems, return the path unchanged._

**Comment by aminalaee** [comment]
@falkoschindler @kiwifoxtrot 
Can you check this with Starlette 0.27.0 release, I think this should be fixed now.

**Comment by falkoschindler** [comment]
@aminalaee Sorry, I don't have a Windows machine at hand.

**Comment by Kludex** [comment]
> @falkoschindler @kiwifoxtrot Can you check this with Starlette 0.27.0 release, I think this should be fixed now.

Given this comment, I'll be closing the issue.

If it still persists, let me know so I can reopen. 👍
