### ISSUE TITLE
When using a custom Jinja loader, directory parameter is unnecessary but still required.

### ISSUE THREAD

**Issue by NickColley** [Kludex/starlette#2134]
In our project we're using Jinja templates like so:

```python
from jinja2 import ChoiceLoader, PackageLoader, PrefixLoader, FileSystemLoader
from fastapi.templating import Jinja2Templates

template_loader = ChoiceLoader(
    [
        FileSystemLoader("name/web/templates"),
        PrefixLoader({"govuk_frontend_jinja": PackageLoader("govuk_frontend_jinja")}),
    ]
)

# Use a custom template loader and avoid the default directory option.
templates = Jinja2Templates(directory="null", loader=template_loader)
```

At the moment we use a generic "null" which is not used since in the code if you provide your own loader the default file system loader is bypassed.
https://github.com/encode/starlette/blob/882ab6998e9b9ea73b9237552ef295faae3d2c62/starlette/templating.py#L85-L86

With this in mind, if a loader is passed should the directory parameter be entirely optional?

Should the API allow this?

```python
templates = Jinja2Templates(loader=template_loader)
```

**Comment by euri10** [comment]
see this https://github.com/encode/starlette/issues/1214  for the background as to why the API is what is

I agree with @alex-oleshkevich that currently the special case for loader is unsatisfactory if you want fine-grained control.

**Comment by NickColley** [comment]
I think this could also be confusing if people expect the directory to be merged with the loader or something like this. It's not clear what's happening at the moment. But seems like that thread has covered that confusion somewhat.

**Comment by Kludex** [comment]
@alex-oleshkevich wdyt?

**Comment by alex-oleshkevich** [comment]
My opinion: we need only two mutually exclusive parameters for this purpose: `env: jinja2.Environment` and `directory: str|list[str]`. The latter one is a shortcut. This covers all cases I ever faced.

I disagree with having `loader` and `kwargs` as, IMO, it is not a nice API because:
* not obvious
* mixes env-specific and class-specific parameters
* it is not clear what are kwargs about. Do they include env and class arguments or only env?

cc @Kludex

**Comment by NickColley** [comment]
I agree that the environment should be exposed since you can then do whatever you'd like and starlette doesnt have to concern itself with duplicating interfaces.

I've also ran into issues where a third party Jinja project assumed I had access to the environment, which we dont with starlette.

**Comment by alex-oleshkevich** [comment]
I made a PR to demonstrate the changes we discussed - https://github.com/encode/starlette/pull/2159

**Comment by Kludex** [comment]
I've suggested to first deprecate it: https://github.com/encode/starlette/pull/2159#issuecomment-1570493474

Then on v1 we can remove it.

**Comment by alex-oleshkevich** [comment]
The solution is merged. We can close this issue.

**Comment by NickColley** [comment]
Thank you for your work on this much appreciated
