### ISSUE TITLE
Testclient doesn't accept cookies with domain "testserver" in Python < 3.11

### ISSUE THREAD

**Issue by nidico** [Kludex/starlette#2152]
As the starlette testclient uses `http://testserver` as its default `base_url`, it is obvious to set the cookie domain to `testserver` in a test setup.

This works as expected in Python 3.11, but fails in Python 3.10 and below due to a change in `http.cookiejar.DefaultCookiePolicy.set_ok_domain` (compare [3.10](https://github.com/python/cpython/blob/3.10/Lib/http/cookiejar.py#L1047) with [3.11](https://github.com/python/cpython/blob/3.11/Lib/http/cookiejar.py#L1046)).

For example, the following test case works fine in Python 3.11, but not in 3.10:

```py
from starlette.responses import Response
from starlette.testclient import TestClient


async def app(scope, receive, send):
    response = Response("foo")
    response.set_cookie("bar", "baz", domain="testserver")
    await response(scope, receive, send)


def test_app():
    client = TestClient(app)
    response = client.get("/")
    assert len(response.cookies) == 1
```

**Workaround:** Use `testserver.local` as cookie domain for testclient. This works fine in both Python 3.10 and Python 3.11.

---

**Is this a starlette issue?** I think so, somewhat, as Starlette uses `testserver` as default `base_url` - which doesn't work "as expected" if a cookie domain is set.

**What could be done about it?** Either use a different `base_url` (e.g. `testserver.local`) (this would certainly break backward compatibility in lots of tests), or just document the issue, e.g. in the [Testclient chapter](https://www.starlette.io/testclient/).

**Comment by rehaut** [comment]
Thanks, I also stumbled upon the problem and this helped me a lot. Would be really good if this was in the documentation! (still on Python 3.9 here)

**Comment by Kludex** [comment]
Can you create a test with this behavior, please?

**Comment by nidico** [comment]
> Can you create a test with this behavior, please?

Ok, done in #2154.

Note that this just adds a testcase (which fails in Python < 3.11), but doesn't solve the actual problem!
