### ISSUE TITLE
`set_cookie` encodes value as Latin1 for header instead of UTF-8

### ISSUE THREAD

**Issue by inhwangYang** [Kludex/starlette#2217]
I'm a developer from south korea.
There was an error in that line, so I changed it to utf-8, so it worked properly. I'd like to suggest a correction

https://github.com/encode/starlette/blob/844220819f1cfcf2726d1628dd4ea597182d6f3e/starlette/responses.py#L123C60-L123C60

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2217">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2217/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2217/pledge.svg">
</picture>
</a>

**Comment by adriangb** [comment]
Headers are supposed to be latin1, not utf8. It’s unfortunate for non-English languages but that’s how it works, nothing Starlette can do about it.

**Comment by Kludex** [comment]
Related resources:
- https://github.com/encode/starlette/pull/1236
- https://github.com/encode/starlette/discussions/1238

**Comment by Kludex** [comment]
- Let's continue this on https://github.com/encode/starlette/discussions/1238 for the time being.
