### ISSUE TITLE
Starlette breaks GAE (python37) with this simple trick (except 0.8.1)

### ISSUE THREAD

**Issue by manatlan** [Kludex/starlette#222]
Hi,

This simple app breaks GAE when trying to return the 304 (GAE instance breaks with a server error "The server encountered an error and could not complete your request.") (the first request works, and return the 200, but the second always breaks)

With all versions of Starlette, except the **"0.8.1"** ... (so I stay in 0.8.1, and can't upgrade)

```python
import uvicorn
from starlette.applications import Starlette
from starlette.responses import Response

app = Starlette()
###############################################################################
@app.route('/',methods=["GET"])
def test(request):
    if "myetag"!=request.headers.get("if-none-match",None):
        return Response(status_code=200,content="hello",headers={"Content-Type":"text/plain","etag":"myetag"})
    else:
        return Response(status_code=304)

if __name__=="__main__":
    uvicorn.run(app, host="0.0.0.0", port=8080)
```

What's happening since 0.8.1 ?
I really like to upgrade to newer version, but I stick with a working one ;-(

**Comment by manatlan** [comment]
BTW I suspect starlette's trying to return some headers with my 304, and it could break GAE ... can I force to return "no headers" at all ?

**Comment by manatlan** [comment]
In fact : 0.8.1 return a "content-length: 0" ... others returns no "content-length"

so I ended with this patch : 
```python
return Response(status_code=304,headers={"Content-Length":"0"})
```

and it works with 0.8.5 !

**Comment by lovelydinosaur** [comment]
Should be resolved by latest Uvicorn. https://github.com/encode/uvicorn/pull/248

(Also I assume the issue would not replicate with either `daphne` or `hypercorn`.)
