### ISSUE TITLE
App config

### ISSUE THREAD

**Issue by jordaneremieff** [Kludex/starlette#223]
How should an app configuration be included in Starlette? 

An example use-case:

```python
app = Starlette(config=config)

@app.on_event("startup")
async def open_database_connection_pool():
    await app.config["db"].create_connection()


@app.on_event("shutdown")
async def close_database_connection_pool():
    await app.config["db"].close_connection()
```

I've subclassed the application class locally for including a simple dict parameter to achieve this, but I think we probably want something else here.

**Comment by lovelydinosaur** [comment]
Hiya! 😃

For now I'd suggest that the config doesn't need to be attached to the app.

Eg. use whatever you want for configuration and environment, and have a `config` and/or `env` global alongside the `app` global.

We'll almost certainly want to do some work in this area, but for now it's a decoupled issue.

**Comment by lovelydinosaur** [comment]
```python
config = ...
app = Starlette()

@app.on_event("startup")
async def open_database_connection_pool():
    await config["db"].create_connection()


@app.on_event("shutdown")
async def close_database_connection_pool():
    await config["db"].close_connection()
```
