### ISSUE TITLE
Bug: Host() routes are not registering correctly with the same subdomain

### ISSUE THREAD

**Issue by nicolaipre** [Kludex/starlette#2248]
- [x] Initially raised as discussion #2243 

- Python version: `3.10`
- Starlette version: `starlette==0.31.0`

---

Since there has not been any response in the discussion for over two weeks and I have been debugging this for quite some time I am opening an issue on this.

When registering `Host()` routes with the same subdomain, only the first object is registered in the application. 

For the example below, only the Foo Routes will respond 200 OK, but the Bar Routes will return a 404:
```python
Host("api.example.com", name="Foo Routes", app=Router(routes=[ # 200 OK
    Mount("/foo", name="Foo Mount", routes=[
        Route("/foo", foo, name="Foo")
    ]),
])),

Host("api.example.com", name="Bar Routes", app=Router(routes=[ # 404 Not Found
    Mount("/bar", name="Bar Mount", routes=[
        Route("/bar", bar, name="Bar")
    ]),
])),
```

If you comment out the `Host()` objects and only use `Mount()` objects like this, you can see that having multiple `Mount()` objects with the same path works fine, and both Foo and Bar routes return 200 OK:
```python
Mount("/foo", name="Foo Mount", routes=[ # 200 OK
    Route("/foo", foo, name="Foo")
]),

Mount("/bar", name="Bar Mount", routes=[ # 200 OK
    Route("/bar", bar, name="Bar")
]),
```

I have recently moved to Starlette from Sanic (a different framework where you are able to do this (see code example/comparison in https://github.com/encode/starlette/discussions/2243#discussioncomment-6768255) which is the reason I discovered the issue.

Here is a full snippet that demonstrates the problem:
```python
# example.py
from starlette.applications import Starlette
from starlette.routing import Host, Mount, Route, Router
from starlette.responses import PlainTextResponse
import uvicorn

async def home(request):
    return PlainTextResponse("home\n")

async def foo(request):
    return PlainTextResponse("foo\n")

async def bar(request):
    return PlainTextResponse("bar\n")

ROUTES = [
    Route("/", endpoint=home),
    
    Host("api.example.com", name="Foo Routes", app=Router(routes=[ # 200 OK
        Mount("/foo", name="Foo Mount", routes=[
            Route("/foo", foo, name="Foo")
        ]),
    ])),
    
    Host("api.example.com", name="Bar Routes", app=Router(routes=[ # 404 Not Found
        Mount("/bar", name="Bar Mount", routes=[
            Route("/bar", bar, name="Bar")
        ]),
    ])),
]

for r in ROUTES:
    print(r)
    # Notice the print, it seems like both Host() objects are registered to the 
    # speicified subdomain, but accessing the routes only works for the Foo Routes...
print("----")

app = Starlette(routes=ROUTES)

if __name__ == '__main__':
    uvicorn.run("example:app", host='0.0.0.0', port=8000, reload=True)
    
# Run tests:
# curl -i api.example.com:8000/foo/foo # 200 OK
# curl -i api.example.com:8000/bar/bar # 404 Not found
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2248">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2248/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2248/pledge.svg">
</picture>
</a>

**Comment by aminalaee** [comment]
It's kind of similar to the Route Priority: https://www.starlette.io/routing/#route-priority

The first Host that is matched is used, so for any `curl -H "Host: api.example.com"` you do the Foo `Mount` is used and then it fails because /bar doesn't exist in Foo.

As for the fix I think we can check that both Host header is matched (what we do now) and also the path matches, the same way we do for others like Route and WebsocketRoute. I've created a PR to address this if we can agree on the approach: https://github.com/encode/starlette/pull/2263

**Comment by nicolaipre** [comment]
@aminalaee Thank you for helping out! I wasn't sure where to start debugging this issue, so great to get some help.

I have tested your PR and it seems to work as intended. Just need to confirm with some tests. I modified one of the tests to test for multiple Host() matches:
```python
# test_routing.py (Line 405 -> 482)
mixed_hosts_app = Router(
    routes=[
        Host(
            "www.example.org",
            app=Router(
                [
                    Route("/", homepage, name="homepage"),
                    Route("/users", users, name="users"),
                ]
            ),
        ),
        Host(
            "api.example.org",
            name="api",
            app=Router([Route("/users", users_api, name="users")]),
        ),
        # Test that was failing because two Host() objects cannot use the same subdomain, 
        # it just ignores it but does not throw any error. FIXED in PR: #2263
        Host(
            "api.example.org",
            name="api_more",
            app=Router([Route("/test", homepage, name="homepage")]),
        ),
        Host(
            "port.example.org:3600",
            name="port",
            app=Router([Route("/", homepage, name="homepage")]),
        ),
    ]
)


def test_host_routing(test_client_factory):
    client = test_client_factory(mixed_hosts_app, base_url="https://api.example.org/")

    response = client.get("/users")
    assert response.status_code == 200
    assert response.json() == {"users": [{"username": "tom"}]}
    
    # Test that is failing because two Host() objects cannot use the same subdomain, it just ignores it but does not throw any error
    response = client.get("/test")
    assert response.status_code == 200

    response = client.get("/")
    assert response.status_code == 404

    client = test_client_factory(mixed_hosts_app, base_url="https://www.example.org/")

    response = client.get("/users")
    assert response.status_code == 200
    assert response.text == "All users"

    response = client.get("/")
    assert response.status_code == 200

    client = test_client_factory(
        mixed_hosts_app, base_url="https://port.example.org:3600/"
    )

    response = client.get("/users")
    assert response.status_code == 404

    response = client.get("/")
    assert response.status_code == 200

    # Port in requested Host is irrelevant.

    client = test_client_factory(mixed_hosts_app, base_url="https://port.example.org/")

    response = client.get("/")
    assert response.status_code == 200

    client = test_client_factory(
        mixed_hosts_app, base_url="https://port.example.org:5600/"
    )

    response = client.get("/")
    assert response.status_code == 200
```

This seems to pass, but later down the line `test_subdomain_routing` broke with the current PR.

It could of course be that `test_subdomain_routing` simply needs to be updated according to the changes in #2263

**Comment by aminalaee** [comment]
@nicolaipre Yes, you are right. It is failing one of the existing tests and I will add the relevant tests for this change.
I was waiting to get some feedback from the @encode/maintainers before continuing.

**Comment by nicolaipre** [comment]
Closing this with #2263
