### ISSUE TITLE
Yesterday's update to `anyio` breaks startlette

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#2262]
### Discussed in https://github.com/encode/starlette/discussions/2261

<div type='discussions-op-text'>

<sup>Originally posted by **fernandosilveira** August 31, 2023</sup>
Yesterday [`anyio` updated to version `4.0.0`](https://github.com/agronholm/anyio/releases/tag/4.0.0)  and starlette [accepts anything `>=3.4.0`](https://github.com/encode/starlette/blob/master/pyproject.toml#L31).

Apparently, the latest `anyio` no longer has `start_blocking_portal`, thus breaking the test client (e.g., [here](https://github.com/encode/starlette/blob/cb6d284877cd359a21a0f31ebf8103a7b285a848/starlette/testclient.py#L416)).

I haven't looked deep enough into it but I suppose it's reasonable that `anyio` did not feel obliged to maintain backwards compatibility on a major version upgrade.</div>

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2262">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2262/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2262/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
Case closed: https://github.com/encode/starlette/discussions/2261

Thanks @agronholm

**Comment by estraph** [comment]
Just for anyone who finds this: we also had the reported error in our (somewhat old) fast API project. As per the [linked discussion](https://github.com/encode/starlette/discussions/2261#discussioncomment-6932928) we pinned `anyio` to `3.7.1` which has allowed the tests to pass again. Pin your dependencies, friends.

**Comment by agronholm** [comment]
FastAPI itself pinned AnyIO to < 4 in the [0.103.1 release](https://github.com/tiangolo/fastapi/releases/tag/0.103.1).
