### ISSUE TITLE
httpx 0.25.0 changes decoding behaviour of `.query_params` when using `TestClient`

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#2282]
### Discussed in https://github.com/encode/starlette/discussions/2281

<div type='discussions-op-text'>

<sup>Originally posted by **chris48s** September 13, 2023</sup>
Hello. I'm not really sure if this is an issue with starlette or httpx. It kind of sits at the intersection between the two. Here''s a minimal example application:

`app.py`:

```py
from starlette.applications import Starlette
from starlette.responses import Response
from starlette.routing import Route

async def index(request):
    foo = request.query_params.get("foo")
    return Response(foo, status_code=200, media_type="text/html")

routes = [Route("/", endpoint=index)]

app = Starlette(debug=True, routes=routes)
```

..and here's a unit test (pytest):

`test.py`:

```py
from starlette.testclient import TestClient

from app import app

def test_foo():
    client = TestClient(app)
    response = client.get("/?foo=%3A/")
    assert ":/" == response.text
```

---

If I run that test with

```
starlette==0.31.1
httpx==0.24.1
```

installed, the test passes.

---

Install

```
starlette==0.31.1
httpx==0.25.0
```

and run it again. The test now fails. The output is `%3A/` not `:/`

---

Note that the actual application behaviour is unchanged. i.e: when invoked independently of `TestClient` (I'm serving with `uvicorn app:app`), the response is still `:/` in either case.

This seems like it could be related to https://github.com/encode/httpx/discussions/2844 but I decided to open a discussion specifically about the impact on starlette `TestClient`</div>

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2282">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2282/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2282/pledge.svg">
</picture>
</a>

**Comment by chris48s** [comment]
possibly related: https://github.com/encode/httpx/discussions/2856

**Comment by Kludex** [comment]
I'll close this since it's a httpx issue to be solved on https://github.com/encode/httpx/pull/2990.
