### ISSUE TITLE
Chat button not working on website

### ISSUE THREAD

**Issue by nicolas-chaulet** [Kludex/starlette#2303]
When clicking on the "Chat" button on the website it open a sidebar which seems broken (Chrome, MacOS).

<img width="1602" alt="Screenshot 2023-10-16 at 15 53 21" src="https://github.com/encode/starlette/assets/3178237/c51b0ef3-b1e2-458f-a13c-4c1f5e2aaa8f">

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2303">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2303/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2303/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
@tomchristie What do you want to do with it? It fails on uvicorn, starlette and httpx.

**Comment by lovelydinosaur** [comment]
It looks like gitter removed support for their embed widget in their UI overhaul.

I think we need to delete `docs/js/chat.js` and `docs/js/sidecar-1.5.0.js` from our projects?

**Comment by MhmoudGit** [comment]
Hi I'm new to contribution can I take on this issue? if all what you need is deleting the js files in docs/js?

**Comment by MhmoudGit** [comment]
I made a PR to comment out the js files from mkdocs.yml without deleting docs/js folder.
sorry if this sounds like a spam @Kludex

**Comment by Kludex** [comment]
It's not a spam. Thanks for the PR.

I've reviewed it.

**Comment by Kludex** [comment]
This was fixed. 🙏
