### ISSUE TITLE
how about return BackgroundTask result 

### ISSUE THREAD

**Issue by fishjam** [Kludex/starlette#2337]
We have the following scenario ( fastapi + starlette with async functions)
- user upload file  => our app will load and analyze the file => send to other rest servers for analyze the text => return response to user.
- it will take long time for `load and analyze the file`,  if we run the logical in caller thread, it will block all other new connections to our server. so have to create thread or just use [starlette.starlette.background.BackgroundTask](https://github.com/encode/starlette/blob/master/starlette/background.py#L15). 
- BUT I found [starlette.BackgroundTask](https://github.com/encode/starlette/blob/master/starlette/background.py#L15) can NOT return any data to caller. so I have to write a similar class `BackgroundWithResultTask` just for add "return" 

# sample caller code
```python
  task = BackgroundWithResultTask(self.loader_mgr.load_file, file_path)   # return task result without block other request, 
  parsed_docs = await task()
  return await other_rest_request(parsed_docs)
```

# change code(just modify return type and add 2 return)
```python
class BackgroundTask:
    def __init__(
        self, func: typing.Callable[P, typing.Any], *args: P.args, **kwargs: P.kwargs
    ) -> None:
        self.func = func
        self.args = args
        self.kwargs = kwargs
        self.is_async = is_async_callable(func)

    async def __call__(self) -> typing.Any:     # return Any
        if self.is_async:
            return await self.func(*self.args, **self.kwargs)   # add return
        else:
            return await run_in_threadpool(self.func, *self.args, **self.kwargs)  # add return
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2337">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2337/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2337/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
Conceptually, I don't think it makes sense for the `BackgroundTask` to return the results.
