### ISSUE TITLE
Change media_type of JSONResponse to "application/json; charset=utf-8"

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#2342]
### Discussed in https://github.com/encode/starlette/discussions/2340

<div type='discussions-op-text'>

<sup>Originally posted by **muxacarin** November 22, 2023</sup>
I am using fastapi (which using starlette), and when I return data with Korean character (and possibly none-alphabet character), encoding is wrong.

It is double-encoded: it was encoded in UTF-8, then the resulting bytes were interpreted as ISO-8859-1 (or a similar encoding) and encoded in UTF-8 again. (answer from GitHub copilot)

example: "피노키오랩" expected to be encoded to %ED%94%BC%EB%85%B8%ED%82%A4%EC%98%A4%EB%9E%A9 (in url encoded form), but resulted in %C3%AD%C2%94%C2%BC%C3%AB%C2%85%C2%B8%C3%AD%C2%82%C2%A4%C3%AC%C2%98%C2%A4%C3%AB%C2%9E%C2%A9

And when I change media_type of JSONResponse to "application/json; charset=utf-8", this issue solved</div>

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2342">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2342/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2342/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
MRE: https://github.com/encode/starlette/discussions/2340#discussioncomment-7639762

**Comment by Kludex** [comment]
> And when I change media_type of JSONResponse to "application/json; charset=utf-8", this issue solved

This is not true. The `charset` set doesn't solve anything.

**Comment by neolooong** [comment]
From muxacarin provided sample code, the two endpoints have different response just because of calling `json.dumps` without pass `ensure_ascii=False`.

> And when I change media_type of JSONResponse to "application/json; charset=utf-8", this issue solved.

Adding `charset=utf-8` is not intended to make both endpoints respond the same.

The problem is if starlette do not provide `charset=utf-8` explicitly, some client cannot parse response correctly. [dart http library](https://github.com/dart-lang/http/blob/9fb4cfa088f1bacdcd5a5154faa8e450ab06373d/pkgs/http/lib/src/response.dart#L22-L25) is the one. It would use latin1, if charset is unknown.

**Comment by Kludex** [comment]
> From muxacarin provided sample code, the two endpoints have different response just because of calling `json.dumps` without pass `ensure_ascii=False`.
> 
> > And when I change media_type of JSONResponse to "application/json; charset=utf-8", this issue solved.
> 
> Adding `charset=utf-8` is not intended to make both endpoints respond the same.
> 
> The problem is if starlette do not provide `charset=utf-8` explicitly, some client cannot parse response correctly. [dart http library](https://github.com/dart-lang/http/blob/9fb4cfa088f1bacdcd5a5154faa8e450ab06373d/pkgs/http/lib/src/response.dart#L22-L25) is the one. It would use latin1, if charset is unknown.

Ah. Got it!

I've been reading around, and I understand why we don't send the `chatset=utf-8` on `application/json`. The reason is that JSON already assumes UTF-8: https://datatracker.ietf.org/doc/html/rfc4627#section-3.

Since that's the case, I think HTTP clients that don't make this consideration should be in the wrong.

Thanks for the help here.
