### ISSUE TITLE
SystemError when using gradio==4.12.0 with starlette>=0.30.0 on Python3.8

### ISSUE THREAD

**Issue by narugo1992** [Kludex/starlette#2388]
See https://github.com/gradio-app/gradio/issues/6904 for details

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2388">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2388/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2388/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
Continue on Gradio's side, please.
