### ISSUE TITLE
[Feature request] starlette.requests.Request should work for websocket scopes

### ISSUE THREAD

**Issue by doncatnip** [Kludex/starlette#240]
Following use-case:
I am writing some authentication middleware for websockets. I'm using session tokens that are stored as cookie. For that, the relevant data in scope object needs to be rehashed. This functionality already exist within Starlette in the form of starlette.requests.Request, but it only works for http requests. Perhaps there is some rationale behind this, but it eludes me for now.

**Comment by lovelydinosaur** [comment]
Cookie support ought to be on WebSocket too - it’s just an oversight. Really we ought to include a common base class, HTTPConnection.
