### ISSUE TITLE
Typing error for app.add_exception_handler (Argument "handler" to "add_exception_handler" of "Starlette" has incompatible type)

### ISSUE THREAD

**Issue by aryaniyaps** [Kludex/starlette#2417]
### Discussed in https://github.com/encode/starlette/discussions/2416

<div type='discussions-op-text'>

<sup>Originally posted by **aryaniyaps** January 13, 2024</sup>
I have my custom errors which are subclasses of the `Exception` class itself

Here's an example:

```py
# app/core/errors.py
class BaseError(Exception):
    """Base error class."""

    def __init__(self, message: str) -> None:
        self.message = message
        super().__init__(self.message)


class InvalidInputError(BaseError):
    """Indicate that the client has issued an invalid request."""
 ```

and this is my corresponding error handler:

```py
# app/core/error_handlers.py
from fastapi import Request
from .errors import InvalidInputError

async def handle_invalid_input_error(
    _request: Request,
    exception: InvalidInputError,
) -> Response:
    """Handle InvalidInputError expections."""
    return ORJSONResponse(
        content={
            "message": exception.message,
        },
        status_code=status.HTTP_400_BAD_REQUEST,
    )
```

I am using FastAPI but I believe that the error arises from the `add_exception_handler` method defined in starlette.

While initializing my app like this:

```py
# app/__init__.py
from fastapi import FastAPI

from app.core.error_handlers import handle_invalid_input_error
from app.core.errors import InvalidInputError


def create_app() -> FastAPI:
    """Initialize an app instance."""
    app = FastAPI(version="0.0.1")
    app.add_exception_handler(
        InvalidInputError,
        handler=handle_invalid_input_error,
    )
    return app

```

this mypy error arises:

```
error: Argument "handler" to "add_exception_handler" of "Starlette" has incompatible type "Callable[[Request, InvalidInputError], Coroutine[Any, Any, Response]]"; expected
"Callable[[Request, Exception], Response | Awaitable[Response]] | Callable[[WebSocket, Exception], Awaitable[None]]"  [arg-type]
            handler=handle_invalid_input_error,
```
</div>

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2417">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2417/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2417/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
Please use the search engine, and check previous discussions about the subject. 🙏
