### ISSUE TITLE
typing map _RequestData in testclient.py might be missing type bytes

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#2421]
### Discussed in https://github.com/encode/starlette/discussions/2296

<div type='discussions-op-text'>

<sup>Originally posted by **VietThan** October  4, 2023</sup>
## Context
I'm coming from using FastAPI but I have an endpoint where I use it in the following manner:

```py
from fastapi.testclient import TestClient

def test_upload(test_client: TestClient):
  # URL of your FastAPI endpoint
  url = "http://localhost:8000/upload/?param1=temp&param2=temp"
  
  # Path to the file you want to upload
  file_path = "your_file.bin"
  
  # Open the file and send it as binary data in the request
  with open(file_path, "rb") as file:
      response = test_client.post(url, data=file.read())
  
  # Print the response from the server
  print(response.status_code)
  print(response.text)
```

The endpoint itself is defined something like:

```py
@app.post(
    '/upload/',
    status_code=status.HTTP_201_CREATED,
)
async def upload(request: Request) -> str:
  data: bytes = await request.body()
  s3_client = get_s3_client()
  key = generate_random_key()
  s3_client.put_object(Key=key, Body=data, Bucket=BUCKET_NAME)
  return key
```

## Issue 
The test above works, but mypy giving me an error:
```
error: Argument "data" to "post" of "TestClient" has incompatible type "bytes"; expected "Mapping[str, str | Iterable[str]] | None"  [arg-type]
```

At the moment, in `starlette/testclient.py` is the following:
```py
_RequestData = typing.Mapping[str, typing.Union[str, typing.Iterable[str]]]
```

I would like to submit a PR to add `bytes` if we think how I'm using the TestClient is appropriate.</div>

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2421">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2421/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2421/pledge.svg">
</picture>
</a>

**Comment by Massakera** [comment]
Hii @Kludex I've opened #2510 to fix this

**Comment by Kludex** [comment]
- Fixed by https://github.com/encode/starlette/pull/2510.

**Comment by clovisNyu** [comment]
Hi, I still seem to be getting this issue on the latest version of starlette. I saw the merge request #2510 , but it seems to indicate that `data` still has to be a `mapping`, but can be a `Dict[str, bytes]` now? Is it possible to allow `data` to be `bytes` directly?

**Comment by seebi** [comment]
I have the same issue and need to `# type: ignore[arg-type]` these lines.

Are there better workarounds for that?
