### ISSUE TITLE
Enable `branch = true` for `coverage.run`

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#2452]
The goal here is to enable `branch = true` on `tool.coverage.run`. We want to be able to cover all logic paths.

**Comment by ShreySinha02** [comment]
#2512

**Comment by ShreySinha02** [comment]
opened #2513

**Comment by ShreySinha02** [comment]
can not pass on --fail-under=100 but on 99 it can pass the the coverage

**Comment by Kludex** [comment]
Well, the goal is exactly to add tests...

**Comment by ShreySinha02** [comment]
which means i have to write test for every file which have not full coverage

**Comment by TechNiick** [comment]
There was already a PR open for this issue [here](https://github.com/encode/starlette/pull/2503).
I have started to work on test coverage. The first PR was opened [here](https://github.com/encode/starlette/pull/2505).
After merging this first one I will continue with the rest of them.

**Comment by hoenie-ams** [comment]
> [ ![Fund with Polar](https://camo.githubusercontent.com/9597ae75678dcf7fd4201b195661a74f581e81b8216a8bfb06ba7cff306507bd/68747470733a2f2f706f6c61722e73682f6170692f6769746875622f656e636f64652f737461726c657474652f6973737565732f323435322f706c656467652e737667) ](https://polar.sh/encode/starlette/issues/2452)

FYI @Kludex : The link doesn't work (404)

**Comment by Kludex** [comment]
> > [ ![Fund with Polar](https://camo.githubusercontent.com/9597ae75678dcf7fd4201b195661a74f581e81b8216a8bfb06ba7cff306507bd/68747470733a2f2f706f6c61722e73682f6170692f6769746875622f656e636f64652f737461726c657474652f6973737565732f323435322f706c656467652e737667) ](https://polar.sh/encode/starlette/issues/2452)
> 
> FYI @Kludex : The link doesn't work (404)

We are not using polar. They don't remove the links after you remove the integration.

**Comment by lealre** [comment]
Putting the table to make it easier to identify:

| Name                               | Branch   | BrPart   | Cover   | Missing                         |
| ---------------------------------- | -------- | -------- | ------- | ------------------------------- |
| starlette/\_utils.py               | 14       | 1        | 98%     | 78->82                          |
| starlette/middleware/gzip.py       | 22       | 2        | 98%     | 16->22, 91->exit                |
| starlette/requests.py              | 96       | 3        | 99%     | 114->116, 233->225, 253->278    |
| starlette/routing.py               | 164      | 3        | 99%     | 199->202, 401->430, 484->496    |
| TOTAL                              | 2016     | 9        | 99%     |                                 |

Let me know if there is any inconsistency in it.

**Comment by Kludex** [comment]
Very few missing now:

```bash
+ venv/bin/coverage report --show-missing --skip-covered --fail-under=100
Name                           Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------
starlette/_utils.py               50      0     14      1    98%   78->82
starlette/middleware/gzip.py      82      0     22      2    98%   16->22, 91->exit
starlette/requests.py            201      0     96      3    99%   114->116, 233->225, 253->278
starlette/routing.py             471      0    164      3    99%   199->202, 401->430, 484->496
--------------------------------------------------------------------------
TOTAL                           9240      0   2016      9    99%
```

Nice! Thanks @lealre for the help here. :)

**Comment by Kludex** [comment]
Thanks for the help here @lealre 🙏

**Comment by Kludex** [comment]
Ups... I think it's not finished yet 👀

**Comment by lealre** [comment]
Glad I could help here 👍

> Ups... I think it's not finished yet 👀

Was it not possible to set branch=True because coverage fails in Python versions earlier than 3.9, or is it something else?

**Comment by Kludex** [comment]
Yes. 😔

**Comment by Kludex** [comment]
This issue is only on 3.9 now. Do you know why?

**Comment by Kludex** [comment]
- It's related to this https://github.com/nedbat/coveragepy/issues/1175

**Comment by Kludex** [comment]
Let's change the `scripts/test` to only run `--branch` on higher than Python 3.10, and remove this custom logic when we drop 3.9.
