### ISSUE TITLE
links on the release-notes  not found. 

### ISSUE THREAD

**Issue by me-v2** [Kludex/starlette#2482]
source: https://www.starlette.io/release-notes/

Create anyio.Event on async context [#2459](https://github.com/encode/starlette/2459).
 this page all links 404. 

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2482">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2482/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2482/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
Thanks.

- I'll fix it on https://github.com/encode/starlette/pull/2457/
