### ISSUE TITLE
Add `Partitioned` cookie attribute

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#2507]
### Discussed in https://github.com/encode/starlette/discussions/2500

<div type='discussions-op-text'>

<sup>Originally posted by **Flecart** February 10, 2024</sup>
Currently there is experimentation for a `Partitioned` attribute for the cookies. [See docs here](https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies).

This attribute is important for third party cookies to work when in the future `SameSite=None; Secure` cookies will stop working
For example Chrome is starting to block them for some users https://developers.google.com/privacy-sandbox/3pcd#report-issues.
Example: this is a common warning for third party cookies on Chrome:
```txt
Cookies with the SameSite=None; Secure and not Partitioned attributes that operate in cross-site contexts are third-party cookies. In future Chrome versions, reading third-party cookies will be blocked. This behavior protects user data from cross-site tracking.
Please refer to the article linked to learn more about preparing your site to avoid potential breakage.
```

So I would like to suggest to add this attribute for the cookie to prepare for the future blocks on standard third party cookies.

Useful links:
https://datatracker.ietf.org/doc/html/draft-cutler-httpbis-partitioned-cookies#section-2.1
https://github.com/privacycg/CHIPS
https://github.com/python/cpython/issues/112713</div>

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2507">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2507/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2507/pledge.svg">
</picture>
</a>

**Comment by Flecart** [comment]
FYI, #2501 draft open, just waiting for the PR on python `http` to be merged.

**Comment by Kludex** [comment]
Closing here.

- Reason: https://github.com/encode/starlette/pull/2501#issuecomment-1946194391
