### ISSUE TITLE
Bug: `_TemplateResponse` is still relying on `request` key from `context` which maybe different from  `request` argument to `TemplateResponse`.

### ISSUE THREAD

**Issue by apiwat-chantawibul** [Kludex/starlette#2531]
## Situation

- Since #2191 and the resulting release 0.29.0, `request` required argument has been added to `TemplateResponse` constructor to become a replacement for passing `request` as key-value pair into `context` argument.
- In theory, this should open up previously reserved `request` keyword as a variable name that coder can use in Jinja template.

## Reproduction

For example, one should be able to run FastAPI server:

```python
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates

app = FastAPI()
templates = Jinja2Templates(directory="templates")

@app.get("/items/{id}", response_class=HTMLResponse)
async def read_item(request: Request, id: str):
    return templates.TemplateResponse(
        request = request,
        name = "item.html",
        context = {
            "id": id,
            "request": "value the user wants to template into request variable",
        }
    )
```

with `templates/item.html`

```html
<html>
<body>
id is {{ id }} and request is {{ request }}
</body>
</html>
```

However, this will raise:

```
  File "/usr/local/lib/python3.12/site-packages/starlette/templating.py", line 45, in __call__
    extensions = request.get("extensions", {})
                 ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

when `/items/whateverid` is accessed.

## Cause

When all arguments to `TemplateResponse` are keyword arguments, `request: Request` is obtained from one of the keyword arguments:

https://github.com/encode/starlette/blob/39dccd911251dfa886775493ed6cefcb15549bc2/starlette/templating.py#L218

However, this `request: Request` is never passed to `_TemplateResponse` which will still try to find `request: Request` from `context`.

https://github.com/encode/starlette/blob/39dccd911251dfa886775493ed6cefcb15549bc2/starlette/templating.py#L44

- In this case, it will find `request: str` instead leading to the previously mentioned error.
- Or in the case that user didn't supply any `request` key in `context`, it will set `request` to `{}` which should also be undesirable.

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2531">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2531/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2531/pledge.svg">
</picture>
</a>

**Comment by alex-oleshkevich** [comment]
@apiwat-chantawibul  while  I agree that having it in the context is not required anymore, removing `request` from  the context is a breaking change as projects expect this variable to be automatically available in templates.

We can have request  as constructor argument of `_TemplateResponse` and it is an option. However I am not sure if it is a good idea. Many developers are used to have `request` variable in the template context (so does Django, so do we) and I would prefer to keep this convention further.

What do you think @Kludex ?

**Comment by Kludex** [comment]
The changes that we propose ourselves on 1.0 solve this issue, right?

**Comment by alex-oleshkevich** [comment]
Yes, it would be possible to override `request` context variable in v1.0.
See https://github.com/encode/starlette/pull/2384/files#diff-e36747b146f2f9c644d1ae076c13ee41df4a81132f25f14ebe9c6ad4facb1352L225

cc @apiwat-chantawibul

**Comment by alex-oleshkevich** [comment]
Feel free to reopen this ticket in case if you still have questions.
