### ISSUE TITLE
Template endpoint

### ISSUE THREAD

**Issue by jordaneremieff** [Kludex/starlette#254]
Is there any interest in including a `TemplateEndpoint` class in Starlette? 

I initially made an attempt [here](https://github.com/encode/starlette/pull/211). The previous PR only supported a sync version, though I have implemented an async version [here](https://github.com/erm/guitarlette/blob/master/guitarlette/endpoints.py).

 I could submit a new PR and include any feedback changes if something like this is desired here.

**Comment by lovelydinosaur** [comment]
I'm going to go with a probably-not-needed on this

(Tho we will want some kind of `TemplateResponse` or `app.render_response(template, context)` at some point, that is like a standard HTML response, but is additionally able to populate the test client response with more `.template` and `.context`.)

**Comment by jordaneremieff** [comment]
@tomchristie 

Which style is preferred for a template response? 

I'd be happy to take a more incremental approach and put forward either a `TemplateResponse` or `app.render_response` (assuming the test client attributes aren't necessary in a first pass) instead of an endpoint sub-class.

**Comment by lovelydinosaur** [comment]
I guess ‘TemplateResponse(template, context)’ for consistency.
