### ISSUE TITLE
Running under PyPy: 'yield' inside async function

### ISSUE THREAD

**Issue by franchb** [Kludex/starlette#258]
Documentation says:

> Several of the ASGI servers also have pure Python implementations available, so you can also run under `PyPy` if your application code has parts that are CPU constrained.

[Source](https://www.starlette.io/#performance)

But when I run under `PyPy 3-6.0` after trying to import Starlette a `SyntaxError` is raised:

```
Python 3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)
[PyPy 6.0.0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import uvicorn
>>>> from starlette.applications import Starlette
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/apps/pypy3-v6.0.0-linux64/site-packages/starlette/applications.py", line 4, in <module>
    from starlette.exceptions import ExceptionMiddleware
  File "/mnt/d/apps/pypy3-v6.0.0-linux64/site-packages/starlette/exceptions.py", line 6, in <module>
    from starlette.requests import Request
  File "/mnt/d/apps/pypy3-v6.0.0-linux64/site-packages/starlette/requests.py", line 118
    yield self._body
    ^
SyntaxError: 'yield' inside async function
```

Is supporting running `Starlette` under `PyPy` planned in any way? Or this paragraph in documentation is outdated?

**Comment by franchb** [comment]
This issue is clarified in `uvicorn` documentation:

> To run under PyPy you'll want to use pure-python implementation instead. You can do this by using the UvicornH11Worker class.
>
> `gunicorn -w 4 -k uvicorn.workers.UvicornH11Worker`

**Comment by lovelydinosaur** [comment]
That trace back is not a Pypy issue. That’s an issue with trying to run with Python 3.5 (3.6+ is required)
