### ISSUE TITLE
[FeatureRequest] Cant configure request.stream() chunk size -- always 128kb per chunk read

### ISSUE THREAD

**Issue by YunchuWang** [Kludex/starlette#2590]
The starting point for issues should usually be a discussion...
Hi I am from Azure Function team, we are integrating starlette req/response to support http streaming. When streaming upload a large file and using starlette request stream function to iterate chunks on server side. each chunk size is 128kb. It hinders the uploading speed for large files. Wonder is there a way to configure the upload chunk size or this is by design? 

![image](https://github.com/encode/starlette/assets/12449837/5849a6a2-55b8-47a6-9a94-5ca743f91c93)
![image](https://github.com/encode/starlette/assets/12449837/d106ee0e-0185-4195-a0a7-f858548177a2)

https://github.com/encode/starlette/discussions

Possible bugs may be raised as a "Potential Issue" discussion, feature requests may be raised as an "Ideas" discussion. We can then determine if the discussion needs to be escalated into an "Issue" or not.

This will help us ensure that the "Issues" list properly reflects ongoing or needed work on the project.

---

- [ ] Initially raised as discussion #...

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2590">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2590/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2590/pledge.svg">
</picture>
</a>

**Comment by nggit** [comment]
The chunk size of the [receive event](https://asgi.readthedocs.io/en/latest/specs/www.html#request-receive-event) on ASGI is determined by the ASGI server. Not the Starlette/app. You may need to confirm with the ASGI server you are using.

**Comment by Kludex** [comment]
Yeah, it's on the server side, not on Starlette.

So... It needs to be on the Azure ASGI function adapter sdk.
