### ISSUE TITLE
static: is a file not a directory

### ISSUE THREAD

**Issue by benjiqq** [Kludex/starlette#2637]
in the case that the path is a file, not a dir, this error can be confusing https://github.com/encode/starlette/blob/master/starlette/staticfiles.py#L59C8-L59C81

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2637">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2637/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2637/pledge.svg">
</picture>
</a>

**Comment by Kludex** [comment]
What?

**Comment by benjiqq** [comment]
if the path is a file it will say "Directory '{directory}' does not exist", which doesn't make sense. the path does exist its a file, not directory, so an error message like "Path is a file not a directory" would be clearer.
