### ISSUE TITLE
Python 3.13.0b3: AttributeError: 'functools.partial' object has no attribute '__name__'

### ISSUE THREAD

**Issue by musicinmybrain** [Kludex/starlette#2638]
```
$ gh repo clone encode/starlette
$ cd starlette
$ python3.13 --version
Python 3.13.0b3
$ python3.13 -m venv _e
$ . _e/bin/activate
(_e) $ pip install -r requirements.txt
(_e) $ pip install -e .
(_e) $ python -m pytest
_e/lib64/python3.13/site-packages/trio/_path.py:164: in generate_forwards
    raise TypeError(attr_name, type(attr))
E   TypeError: ('parser', <class 'module'>)
(_e) $ pip install --upgrade trio
(_e) $ python -m pytest
==================================================================================================== ERRORS ====================================================================================================
____________________________________________________________________________________ ERROR collecting tests/test_routing.py ____________________________________________________________________________________
tests/test_routing.py:135: in <module>
    Route("/", endpoint=functools.partial(partial_endpoint, "foo")),
starlette/routing.py:227: in __init__
    self.name = get_name(endpoint) if name is None else name
starlette/routing.py:103: in get_name
    return endpoint.__name__
E   AttributeError: 'functools.partial' object has no attribute '__name__'. Did you mean: '__ne__'?
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================================== 1 error in 0.64s ===============================================================================================
```

This appears to be a new regression in Python 3.13.0b3 (vs. 3.13.0b2).

---

- [x] Initially raised as discussion #2610 – “Please file an issue in this repo for any incompatibility you encounter with 3.13.”

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/2638">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/2638/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/2638/pledge.svg">
</picture>
</a>

**Comment by mgorny** [comment]
This is according to the documentation:

> [partial](https://docs.python.org/3/library/functools.html#functools.partial) objects are like function objects in that they are callable, weak referenceable, and can have attributes. There are some important differences. For instance, the [__name__](https://docs.python.org/3/library/stdtypes.html#definition.__name__) and __doc__ attributes are not created automatically.

https://docs.python.org/3/library/functools.html#partial-objects
