### ISSUE TITLE
Update pipeline to use PyPI trusted publishing

### ISSUE THREAD

**Issue by Kludex** [Kludex/starlette#2721]
@tomchristie can you give me PyPI ownership to do this to starlette and uvicorn?

**Comment by lovelydinosaur** [comment]
Invites sent. 👍

**Comment by Kludex** [comment]
I'll update the projects today.

Thanks. 🙏

**Comment by lovelydinosaur** [comment]
Is this integrated using `PYPI_TOKEN`?

**Comment by Kludex** [comment]
> Is this integrated using `PYPI_TOKEN`?

I'm not sure I understand the question? I'll show you when I have the PR, but the plan is to follow this: https://docs.pypi.org/trusted-publishers/

The idea is to have a build step to create the artifacts, and then a publishing job. See here how it should look like: https://github.com/Kludex/python-multipart/blob/master/.github/workflows/publish.yml
