### ISSUE TITLE
Cannot add a custom handler for HTTPExceptions with status_code=500

### ISSUE THREAD

**Issue by clickonben** [Kludex/starlette#2723]
### Discussed in https://github.com/encode/starlette/discussions/2499

<div type='discussions-op-text'>

<sup>Originally posted by **clickonben** February  9, 2024</sup>
I found this through FastAPI but the code causing the problem appears to be in Starlette.
```
from fastapi import FastAPI, HTTPException

app = FastAPI()

@app.exception_handler(500)
def custom_exception_handler(request, exc):
    print(f"Oops! An HTTP error occurred: {exc}")
    return JSONResponse({"detail":"Internal Server Error"}, status_code=500)


@app.get("/")
def read_root():
    raise HTTPException(status_code=500, detail="Internal Server Error")
```

This exception handler never gets called. When I dug into it I found the problem was this:

```
def build_middleware_stack(self) -> ASGIApp:
        debug = self.debug
        error_handler = None
        exception_handlers: dict[
            typing.Any, typing.Callable[[Request, Exception], Response]
        ] = {}

        for key, value in self.exception_handlers.items():
            if key in (500, Exception):
                error_handler = value
            else:
                exception_handlers[key] = value

        middleware = (
            [Middleware(ServerErrorMiddleware, handler=error_handler, debug=debug)]
            + self.user_middleware
            + [
                Middleware(
                    ExceptionMiddleware, handlers=exception_handlers, debug=debug
                )
            ]
        )

        app = self.router
        for cls, args, kwargs in reversed(middleware):
            app = cls(app=app, *args, **kwargs)
        return app
```
in this file [https://github.com/encode/starlette/blob/master/starlette/applications.py](https://github.com/encode/starlette/blob/master/starlette/applications.py)

I don't understand why it is doing this:

```
for key, value in self.exception_handlers.items():
    if key in (500, Exception):
        error_handler = value
    else:
        exception_handlers[key] = value
```
because if I change it to this:

```
for key, value in self.exception_handlers.items():
    exception_handlers[key] = value
```
Everything works as expected and my error handler handles 500 errors the same as any other status code.</div>

**Comment by Kludex** [comment]
This is not an issue.

If you set `@app.exception_handler(500)` or `@app.exception_handler(Exception)`, it's used for the `ServerErrorMiddleware` instead of the `ExceptionMiddleware`. You can read more about it here: https://www.starlette.io/middleware/#using-middleware.

**Comment by clickonben** [comment]
OK, thanks.  Can I just point out that I created this as a discussion marked as "potential issue" in February because I suspected that there was a reason for this that I was unaware of and nobody responded. Can I politely suggest that Ii might be good if someone could have a look at those every now and then.

**Comment by Kludex** [comment]
I try my best here.

**Comment by clickonben** [comment]
Thanks for your hard work, don't take what I said as a criticism more a friendly suggestion.

**Comment by ccrims0n** [comment]
@Kludex I understand this is by design. Is there any place where I can find the reason for this design choice?
What's the reason for having exception handlers in 2 places, `ExceptionMiddleware` and `ServerErrorMiddleware`?

**Comment by clickonben** [comment]
Upon reflection, I think it might be worth clarifying that the issue is not that I care which middleware handles 500 errors, it's that setting @app.exception_handler(500) or @app.exception_handler(Exception) doesn't do anything at all that I can see, the handler never runs so I cannot do any custom handling of 500 errors.  The block of Starlette source code I posted was just what I thought was causing the problem.
