### ISSUE TITLE
`Location` returned by `redirect_slashes` should be relative instead of absolute

### ISSUE THREAD

**Issue by rijenkii** [Kludex/starlette#2748]
### Discussed in https://github.com/encode/starlette/discussions/2651

<div type='discussions-op-text'>

<sup>Originally posted by **rijenkii** July 23, 2024</sup>
I have a following setup:
```
Browser --(https)--> Nginx --(http)--> FastAPI/Starlette
```

When a browser accidentally calls an endpoint without an ending slash, Starlette responds with a 307 with `Location: http://example.org/api/endpoint/`, which browser rightfully rejects because of mixed content blocking.

If Starlette responded with `Location: /api/endpoint/` instead, browser would then just slap that relative location to the current host.

Django does it like that, but they respond with 301s:
```
> GET /api/endpoint HTTP/1.1

< HTTP/1.1 301 Moved Permanently
< location: /api/endpoint/
```

</div>

---

Related code: https://github.com/encode/starlette/blob/c2e3a39b09a613553ee03586589ed9cd0fbf07f3/starlette/routing.py#L750-L763

**Comment by Kludex** [comment]
Can you provide an MRE on how to reproduce this? Also, it would speed up to have similar code with other web frameworks, so I can see the difference in behavior.

**Comment by rijenkii** [comment]
Sure. Written as `uv` scripts, run with `uv run <script_name>.py`, it will download all the dependencies automatically.

<details><summary><code>apidaora_repro.py</code></summary>

```python
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "apidaora",
#     "uvicorn",
# ]
# ///

import uvicorn
from apidaora import appdaora
from apidaora import route


@route.get("/test/")
def homepage():
    return {"hello": "world"}


app = appdaora(homepage)


if __name__ == "__main__":
    uvicorn.run(app, port=3000, log_level="info")
```

</details>
<details><summary><code>blacksheep_repro.py</code></summary>

```python
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "blacksheep",
#     "uvicorn",
# ]
# ///

import uvicorn
from blacksheep import Application
from blacksheep import get

app = Application()


@get("/test/")
def homepage():
    return {"hello": "world"}


if __name__ == "__main__":
    uvicorn.run(app, port=3000, log_level="info")
```

</details>
<details><summary><code>django_repro.py</code></summary>

```python
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "django",
#     "uvicorn",
# ]
# ///

import uvicorn
from django.conf import settings
from django.core.asgi import get_asgi_application
from django.http import HttpRequest
from django.http import JsonResponse
from django.urls import path

settings.configure(
    DEBUG=True,
    SECRET_KEY="secret-key",
    ROOT_URLCONF=__name__,
    MIDDLEWARE=["django.middleware.common.CommonMiddleware"],
)


app = get_asgi_application()


async def homepage(request: HttpRequest):
    return JsonResponse({"hello": "world"})


urlpatterns = [path("test/", homepage)]

if __name__ == "__main__":
    uvicorn.run(app, port=3000, log_level="info")
```

</details>
<details><summary><code>flask_repro.py</code></summary>

```python
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "asgiref",
#     "flask",
#     "uvicorn",
# ]
# ///

import uvicorn
from asgiref.wsgi import WsgiToAsgi
from flask import Flask

app = Flask(__name__)
asgi_app = WsgiToAsgi(app)


@app.route("/test/")
def hello_world():
    return {"hello": "world"}


if __name__ == "__main__":
    uvicorn.run(asgi_app, port=3000, log_level="info")
```

</details>
<details><summary><code>sanic_repro.py</code></summary>

```python
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "sanic",
# ]
# ///

from sanic import Request
from sanic import Sanic
from sanic.response import json

app = Sanic("MyHelloWorldApp")


@app.get("/test/")
async def homepage(request: Request):
    return json({"hello": "world"})


if __name__ == "__main__":
    app.run(dev=True, port=3000)
```

</details>
<details><summary><code>starlette_repro.py</code></summary>

```python
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "starlette",
#     "uvicorn",
# ]
# ///

import uvicorn
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route


async def homepage(request):
    return JSONResponse({"hello": "world"})


routes = [Route("/test/", endpoint=homepage)]

app = Starlette(debug=True, routes=routes)

if __name__ == "__main__":
    uvicorn.run(app, port=3000, log_level="info")
```

</details>

Results (ran without nginx in front of the servers):
|Framework|Request to `/test`|Request to `/test/`|
|-|-|-|
|apidaora|200|200|
|blacksheep|200|200|
|django|301 to `/test/`|200|
|flask|308 to `http://localhost:3000/test/`|200|
|sanic|200|200|
|starlette|307 to `http://localhost:3000/test/`|200|

So it seems that it's not as black and white as I hoped it would be.

**Comment by rijenkii** [comment]
Or, do you need examples specifically with a reverse proxy in front of the actual server?

**Comment by Kludex** [comment]
Can the reverse proxy somehow alter the scheme from 301? It seems this is the problem? 🤔

**Comment by rijenkii** [comment]
I have set up an nginx with a self-signed certificate that is pointing at the port 3000:

<details><summary>Generate certificates</summary>

```bash
mkcert starlette.test.home.arpa
```

</details>
<details><summary>Set up hosts</summary>

```bash
echo "127.0.0.1 starlette.test.home.arpa" | sudo tee --append /etc/hosts
```

</details>
<details><summary><code>nginx.conf</code></summary>

```nginx
server {
    listen       80;
    listen       443 ssl;
    
    ssl_certificate starlette.test.home.arpa.pem;
    ssl_certificate_key starlette.test.home.arpa-key.pem;

    server_name starlette.test.home.arpa;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
    }
}
```

</details>
<details><summary>Start the nginx</summary>

```bash
docker run --rm -it --network host \
    -v ./starlette.test.home.arpa-key.pem:/etc/nginx/starlette.test.home.arpa-key.pem \
    -v ./starlette.test.home.arpa.pem:/etc/nginx/starlette.test.home.arpa.pem \
    -v ./nginx.conf:/etc/nginx/conf.d/default.conf \
    nginx
```

</details>

Django also requires a change:
```diff
 settings.configure(
     DEBUG=True,
     SECRET_KEY="secret-key",
     ROOT_URLCONF=__name__,
     MIDDLEWARE=["django.middleware.common.CommonMiddleware"],
+    ALLOWED_HOSTS=["*"],
 )
```

Results:
|Framework|Request to `https://starlette.test.home.arpa/test`|Request to `https://starlette.test.home.arpa/test/`|
|-|-|-|
|apidaora|200|200|
|blacksheep|200|200|
|django|301 to `/test/`|200|
|flask|308 to `http://starlette.test.home.arpa/test/`|200|
|sanic|200|200|
|starlette|307 to `http://starlette.test.home.arpa/test/`|200|

Both flask and starlette start sending people to wrong protocols. When `proxy_set_header Host $host;` is removed from nginx config the behaviour is fixed and they both start redirecting to `https`.

So it seems that nginx is a little bit at fault here, but it would be nice to have the option to configure the redirect logic to allow for behaviour of other frameworks to be implemented. Or document a way of doing this kind of thing.

---

Will explore further later today, I've already set up a logging asgi wrapper around starlette, but I'm a bit busy right now.

**Comment by Kludex** [comment]
Which Uvicorn version are you using?

**Comment by rijenkii** [comment]
`uv run` installs the latest when ran, so 0.34.0.

**Comment by Kludex** [comment]
Is nginx setting up the forward headers properly? Uvicorns should be able to pass the https scheme properly to Starlette, and send the redirect to https instead of http.

**Comment by rijenkii** [comment]
Indeed:

- When nginx is ran without the `proxy_set_header Host $host;`, it seems to just rewrite the `Location` returned by starlette, as starlette returns this header:
  ```python
  (b'location', b'http://127.0.0.1:3000/test/')
  ```
- When nginx is ran with that directive, starlette returns `Location` with `http` and nginx does not try to rewrite it:
  ```python
  (b'location', b'http://starlette.test.home.arpa/test/')
  ```
- When nginx is ran with an additional `proxy_set_header X-Forwarded-Proto $scheme;` directive, starlette returns `Location` with `https`:
  ```python
  (b'location', b'https://starlette.test.home.arpa/test/')
  ```

So the issue then can be closed, as the redirect scheme can be fixed by correctly configuring the reverse proxy. Thanks for the help, and sorry for taking your time.

**Comment by Kludex** [comment]
I wish every OP had the same proactive behavior on the investigation as you showed here.

I didn't lose any time. 😄 

Thanks!
