### ISSUE TITLE
Feature request: session cookie flags

### ISSUE THREAD

**Issue by HarrySky** [Kludex/starlette#275]
Can session cookie flags like HttpOnly be set through session somehow? I haven't found it in documentation.

**Comment by lovelydinosaur** [comment]
Not through the session interface, no. We could allow configration at the middleware level.
What configuration options would we need?

**Comment by HarrySky** [comment]
@tomchristie I think for secure session cookie we need: Secure, HttpOnly and SameSite flags. SameSite flag right now cannot be set.

**Comment by lovelydinosaur** [comment]
I assume we ought to just always set these, rather than making it configurable.
Would you be up for issuing a pull request that added these to the session cookie?

**Comment by HarrySky** [comment]
@tomchristie issued a pull request #276 :)

**Comment by HarrySky** [comment]
It looks like Firefox and Chrome treat cookie related headers as case-sensitive, will fix it later.

**Comment by HarrySky** [comment]
Everything is fine, my mistake :smile:
