### ISSUE TITLE
`add_middleware` hint `Expected type '_MiddlewareFactory[ParamSpec("P")]', got 'Type[XXX]' instead`

### ISSUE THREAD

**Issue by eastack** [Kludex/starlette#2760]
![image](https://github.com/user-attachments/assets/4581d63d-a773-418b-9a15-0a8ea63c475d)

```
from fastapi import FastAPI, APIRouter, Request
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()
origins = []

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)
```

starlette v0.41.3

**Comment by Kludex** [comment]
Is this PyCharm?

We need to change the issue template.

**Comment by chbndrhnns** [comment]
Might be an issue with Pycharm: https://youtrack.jetbrains.com/issue/PY-70855/ParamSpec-problem-with-Protocol

**Comment by eastack** [comment]
@Kludex Indeed, it is PyCharm. I sincerely apologize for raising this issue in an unprofessional manner. I think I should close this issue for now because it does seem likely to be related to PyCharm. However, my VSCode has stopped working, so I am unable to perform further testing.

**Comment by Kludex** [comment]
PyCharm is always a step behind in the Python typing world.

**Comment by eastack** [comment]
![image](https://github.com/user-attachments/assets/d34e453a-5920-4900-ab60-14aaac4aa855)

It’s confirmed that it was a PyCharm issue. After getting VSCode working again, everything seems fine. I guess I won’t be using PyCharm for writing Python code anymore, haha. Thank you!

**Comment by antoni-szych-rtbhouse** [comment]
Actually, newest mypy 1.14.1 also raises the same error with starlette 0.41.3 and newest 0.45.1 (python 3.11.4):

```
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware # sentry-python 2.19.0
web_app.add_middleware(SentryAsgiMiddleware)
```

```
myproject/api/server.py:80: error: Argument 1 to "add_middleware" of "Starlette" has incompatible type "type[SentryAsgiMiddleware]"; expected "_MiddlewareFactory[[VarArg(Any), KwArg(Any)]]"  [arg-type]
myproject/api/server.py:80: note: Following member(s) of "SentryAsgiMiddleware" have conflicts:
myproject/api/server.py:80: note:     Expected:
myproject/api/server.py:80: note:         def __call__(Callable[[MutableMapping[str, Any], Callable[[], Awaitable[MutableMapping[str, Any]]], Callable[[MutableMapping[str, Any]], Awaitable[None]]], Awaitable[None]], /, *Any, **Any) -> Callable[[MutableMapping[str, Any], Callable[[], Awaitable[MutableMapping[str, Any]]], Callable[[MutableMapping[str, Any]], Awaitable[None]]], Awaitable[None]]
myproject/api/server.py:80: note:     Got:
myproject/api/server.py:80: note:         def __init__(app: Any, unsafe_context_data: bool = ..., transaction_style: str = ..., mechanism_type: str = ..., span_origin: str = ..., http_methods_to_capture: tuple[str, ...] = ...) -> SentryAsgiMiddleware
myproject/api/server.py:80: note: "_MiddlewareFactory[[VarArg(Any), KwArg(Any)]].__call__" has type "Callable[[Callable[[MutableMapping[str, Any], Callable[[], Awaitable[MutableMapping[str, Any]]], Callable[[MutableMapping[str, Any]], Awaitable[None]]], Awaitable[None]], VarArg(Any), KwArg(Any)], Callable[[MutableMapping[str, Any], Callable[[], Awaitable[MutableMapping[str, Any]]], Callable[[MutableMapping[str, Any]], Awaitable[None]]], Awaitable[None]]]"
```

Do you know if this is some known limitation of mypy as well?

**Comment by mel-mason** [comment]
I'm also getting the same error as @antoni-szych-rtbhouse . For me it's present with Starlette 0.44.0, but not with 0.41.3

**Comment by nameer** [comment]
<img width="790" height="264" alt="Image" src="https://github.com/user-attachments/assets/36dcb618-32e2-45bf-a7f6-c6069da7da03" />

We get this error with ty as well.

**Comment by Kludex** [comment]
https://github.com/astral-sh/ty/issues/1635
