### ISSUE TITLE
Breaking change in httpx=0.28.0 for starlette.testclient.TestClient

### ISSUE THREAD

**Issue by vladislavkoz** [Kludex/starlette#2771]
TypeError: Client.__init__() got an unexpected keyword argument 'app' 

connexion==3.0.5 
starlette-0.32.0
httpx-0.28.0

**Comment by mr-grj** [comment]
We had a hard time yesterday and today trying to figure out why all of our tests were failing all of a sudden. Specifically adding `httpx` to the requirements file and downgrading it to `27.2.0` worked for us (at least as a temporary solution).

**Comment by vladislavkoz** [comment]
Yes, I've also found that we can install connexion==3.0.3 and all other dependencies will be installed correctly(older starlette/httpx). So it's possible to use 3.0.3 if it works for specific service.

**Comment by Kludex** [comment]
A good practice is to test on the last release of involved packages.

**Comment by vladislavkoz** [comment]
yes, but httpx-0.28.0(released yeterday). And it was installed automatically)

**Comment by Kludex** [comment]
Not that it matters for this, but: https://github.com/encode/starlette/pull/2773
