### ISSUE TITLE
Elif branch with error raise in TestClient _choose_redirect_arg never triggers

### ISSUE THREAD

**Issue by t-ded** [Kludex/starlette#2783]
In here, the elif branch should likely be the first condition to trigger only then followed by check of the individual parameters - I can do a PR for this if accepted

https://github.com/encode/starlette/blob/d40bc9e5e12d686542a180368bc78402e9501efd/starlette/testclient.py#L458C1-L462C24

**Comment by Kludex** [comment]
Makes sense. PR welcome.

**Comment by Kludex** [comment]
We dropped the `allow_redirects` from the `TestClient`.

Ref.: https://github.com/encode/starlette/pull/2808
