### ISSUE TITLE
MultiPartException:  Part exceeded maximum size 1M

### ISSUE THREAD

**Issue by lsaint** [Kludex/starlette#2785]
It came from [here](https://github.com/encode/starlette/commit/fd038f3070c302bff17ef7d173dbb0b007617733#diff-59eaf7e36ef8b186735f99bca714455f02f04cee26e014dc89120417996d35b2R121).  @ version [0.41.3](https://github.com/encode/starlette/releases/tag/0.41.3)

Need to make this variable customizable.

**Comment by Kludex** [comment]
PR welcome to customize it, or use the default value.

**Comment by Kludex** [comment]
Why did you close this?

**Comment by lsaint** [comment]
> Why did you close this?

I found a solution [here](https://github.com/fastapi/fastapi/discussions/12961#discussioncomment-11336476), so this is not an issue for me now.

**Comment by Kludex** [comment]
I'll leave this open. It's a valid issue.
