### ISSUE TITLE
Installing with uv in symlink mode can break StaticFiles default settings

### ISSUE THREAD

**Issue by sfermigier** [Kludex/starlette#2788]
When installing with `uv` with `UV_LINK_MODE=symlink` (cf. <https://docs.astral.sh/uv/configuration/environment/#uv_link_mode>), `StaticFiles` instances that point to a package won't work unless one explicitly sets `follow_symlink=True` when instantiating the class.

I assume most people aren't aware of the issue, unless they use `UV_LINK_MODE=symlink` (which is a pretty cool way so save space on your disk).

**Comment by Kludex** [comment]
And what's the question?

**Comment by zanieb** [comment]
The default link mode in uv is a hard link and we generally discourage use of symlinks — is there a reason you prefer this mode?

**Comment by sfermigier** [comment]
@Kludex It's not a question, it's a bug report.

**Comment by sfermigier** [comment]
@zanieb I tend to prefer symlinks because of they can cross partitions. I wasn't aware that hard links were the preferred option for the uv team. Maybe this should be made explicit in the documentation ?
