### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by graingert** [Kludex/starlette#2821]
### Discussed in https://github.com/encode/starlette/discussions/2820

<div type='discussions-op-text'>

<sup>Originally posted by **graingert** December 28, 2024</sup>
I recently ran into https://github.com/python/cpython/issues/69968 in https://github.com/encode/starlette/pull/2814

and would like to avoid a work-around.</div>

**Comment by Kludex** [comment]
- Closed by https://github.com/encode/starlette/pull/2823
