### ISSUE TITLE
Add an SQLite database driver

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#283]
Integrate `aiomysql` and `aiosqlite` as database backends.

**Comment by rajeev** [comment]
@tomchristie I just saw this ticket. I've added an initial integration for MySQL under #364. Please do review and let me know. I still need to add test cases though probably by refactoring the existing test cases for Postgres

**Comment by lovelydinosaur** [comment]
*Update* - We have MySQL support now. Re-titling this issue accordingly.

**Comment by lovelydinosaur** [comment]
See http://github.com/encode/databases instead.
Will close this once we push out `DatabaseMiddleware` in favor of `databases`.

**Comment by lovelydinosaur** [comment]
Resolved 👍
