### ISSUE TITLE
Support for AWS Lambda

### ISSUE THREAD

**Issue by rajeev** [Kludex/starlette#286]
I would like to add some sort of "driver" for AWS Lambda.

We want to use starlette to develop our API backend on AWS Lambda. At some later date, we might want to move off Lambda (depending on cost, etc). For that reason, we want to build the API in such a way that we can readily move to a full uvicorn+starlette stack with minimal changes.

I've been investigating the starlette for this purpose. I'm not a starlette expert. If one were to build a "driver" for AWS Lambda, how would that work? An outline for a good performant solution would be helpful so that we can implement the corresponding code in the best way possible

**Comment by rajeev** [comment]
Closing this issue as it is irrelevant.

**Comment by erichaus** [comment]
@rajeev I'm using [Mangum](https://github.com/jordaneremieff/mangum) and it's working out well...
