### ISSUE TITLE
Running without blocking the eventloop?

### ISSUE THREAD

**Issue by narigama** [Kludex/starlette#288]
Hi there,

I'm looking to use Starlette within a larger application but the documentation only suggests either running my application within an ASGI framework in it's own process, or invoking something like `uvicorn.run` which is a blocking call.

Is there any simple method to schedule uvicorn/applications on the eventloop in a non exclusive manner?

**Comment by lovelydinosaur** [comment]
I think this issue really belongs on uvicorn.

Similar: https://github.com/encode/uvicorn/issues/265
