### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by florimondmanca** [Kludex/starlette#290]
Hi!

While figuring out a potential solution for #289, I had to setup the repo and install Starlette locally.

Although the process is rather straight-forward, I think it would be good practice to have contribution guidelines to make things clear and facilitate contributor onboarding.

I already went ahead and committed a [draft](https://github.com/encode/starlette/commit/df8805aa1ba26e46d90673a53e7029bc113380b7) to my fork based on the guidelines I wrote for Bocadillo. If it looks fine, I'd be happy to open a PR. :+1:

**Comment by lovelydinosaur** [comment]
> If it looks fine, I'd be happy to open a PR.

I’d recommend opening the PR whatever and discussing it there - better visibility into inline comments etc that way.
