### ISSUE TITLE
Security and password utils

### ISSUE THREAD

**Issue by jordaneremieff** [Kludex/starlette#293]
Given that Starlette implements a basic authentication interface at this point, are there any plans to also provide some common password hashing functionality/security utils?

For example, both [Werkzeug](http://werkzeug.pocoo.org/docs/0.14/utils/#module-werkzeug.security) and [Django](https://docs.djangoproject.com/en/2.1/topics/auth/passwords/) offer some tools in this regard. I think security is something easy to get wrong and password authentication is a common enough problem to warrant shipping some utils with Starlette as well.

Alternatively, we may want to document recommended approaches/best practices to provide some guidance to those implementing the authentication interface or a third-party extension.

**Comment by lovelydinosaur** [comment]
We’ll want to provide login/logout endpoints, yes.

**Comment by jordaneremieff** [comment]
@tomchristie would this also include our own password salting/hashing/validation methods (and potentially support for multiple hashing algorithms), or more simply to provide the building blocks for implementations to use their own security methods with the interface?

I've been digging into this a bit and may be able to put forward a PR at some point to get the ball rolling depending on how much should be included here.

**Comment by lovelydinosaur** [comment]
We’d do something similar to Django’s hashing strategy. Allow it to be configurable, but use PBKDF2 by default since the stdlib includes support for that.

**Comment by Chaostheorie** [comment]
Has there been any recent developments regarding this feature set? I'm at the moment implementing [secure](https://pypi.org/project/secure/0.1.8/) for one of my applications. It may be a viable option for secure cookie based authentication that may support login/ logout enpoints.

**Comment by lovelydinosaur** [comment]
Let's close this off for now.

Right now we need to get the maintenance load into balance before we consider if we'd want any more feature work to be in-scope for Starlette or not.
