### ISSUE TITLE
HTTPException with headers - pull request proposal

### ISSUE THREAD

**Issue by tiangolo** [Kludex/starlette#295]
I would like to be able to raise `HTTPException` with custom headers.

I'm willing to implement it and send a PR if this is something acceptable for Starlette.

Currently, that's not possible. As the headers would have to be set in an exception handler, and it wouldn't have a way to know the associated realms of a specific exception raised.

---

Use case:

I would like to be able to raise an authentication error 401 Unauthorized, including `WWW-Authenticate`, with a specific type (like `Basic`) and possibly, with a specific set of realms.

---

What do you think? Would that be acceptable/desirable in Starlette?

**Comment by lovelydinosaur** [comment]
I'd *probably* prefer not to actually.

The use case for exceptions-rather-than-responses is when you need to strictly decouple the exception from the kind of response it generates.

For example, generic 404 exceptions that the developer *might* want to render as an HTML page, or as a JSON response depending on if they're developing a website or API.

Having built-in execeptions that mandate the specific of the response such as headers starts to defeat the point, and just makes it less clear if the developer should use an exception or a response.

**Comment by tiangolo** [comment]
Get it. Thanks for the explanation.

I guess it also doesn't make as much sense here in Starlette, as all the responses are handled in the route endpoint, or in middleware directly, but not in between.

...I just prefer to keep as much as possible of the features/changes "upstream" (in Starlette) when it makes sense for the project, before adding custom stuff to FastAPI. So I prefer to propose it here first :slightly_smiling_face: 

---

I'll handle it outside of Starlette, but just as future reference, here's my case in FastAPI:

As I'm having injected dependencies (in this specific scenario for security/auth), they can return a value from the request that gets injected in the endpoint function, or they can raise an exception, that aborts all the rest of the process.

But I can't return a response directly from the dependency that would somehow override the response handled by the endpoint function (and it doesn't seem very natural in that case). So I want to be able to raise an exception from the security dependency that results in an HTTP 401 error response with a standard `WWW-Authenticate` header, etc.
