### ISSUE TITLE
Starlette's scope

### ISSUE THREAD

**Issue by jordaneremieff** [Kludex/starlette#3]
I am very interested in contributing to some common middleware for ASGI, and this seems like it is the perfect place to do that, however I have a few questions about how much Starlette is aiming to achieve:

How much functionality will this project implement?

How much functionality does it intend to leave up to particular frameworks?

Will it potentially become a more traditional framework itself, or is the intention to remain a small library?

**Comment by lovelydinosaur** [comment]
The set of stuff that it makes sense to provide for here is ~anything that is composable.

Would be in scope:

* A routing middleware, where each target is itself an ASGI app.

Would not be in scope:

* An application instance that configures templates, parsers, renders etc...

Think along similar lines to werkzeug for scope.

**Comment by lovelydinosaur** [comment]
Okay, so there's a bit of an case-in-point in https://github.com/encode/starlette/pull/5

It adds a router, but doesn't include anything like Django's "reverse()".

Instead, I think it should stick with simple, composible units, that make it easy to glue things together, and that also serve as a reference point for how to build more fully featured equivalents.

**Comment by jordaneremieff** [comment]
Ah yes, that clears things up nicely. Thanks.
