### ISSUE TITLE
Include more information in `DebugMiddleware`.

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#30]
Right now we just display a raw `format_trackback()`.

It'd make sense to have a proper page with lines of context around each file in the stack, and local variables at each point. (As with Django or Werkzeug's debugger pages)

**Comment by supriyo-biswas** [comment]
What about integrating the werkzeug debugger itself? This feature was there previously in APIStar.

**Comment by marcosschroh** [comment]
Ok, perfect!

**Comment by marcosschroh** [comment]
Related to #179

**Comment by Kludex** [comment]
I guess the local variables are still missing, correct?

**Comment by lovelydinosaur** [comment]
Closing as per #1386

**Comment by mireq** [comment]
@supriyo-biswas i tried to integrate werkzeug.  It's simple hack and should work without problems. Package is published on pypi - [starlette-werkzeug-debugger](https://pypi.org/project/starlette-werkzeug-debugger/) and it's implemented as [middleware](https://github.com/mireq/starlette-werkzeug-debugger/blob/78487667362b6fa97f8b30638e401f90db973eaa/starlette_werkzeug_debugger/__init__.py).
