### ISSUE TITLE
Secret objects leak value in print, logging, and format statements

### ISSUE THREAD

**Issue by sloria** [Kludex/starlette#301]
According to the docs, `Secret` is meant to hide a value from tracebacks, logging, and format statements.

However, since the value is revealed by the `__str__` method, it will still appear in `print`, `logging`, and `format` statements.

```python
In [1]: from starlette.datastructures import Secret

In [2]: s = Secret('foo')

In [3]: print(s)
foo

In [4]: import logging

In [5]: logging.critical(s)
CRITICAL:root:foo

In [6]: format(s)
Out[6]: 'foo'
```

This happening on the latest `master` commit (b94f02e as of this writing).

One possible solution would be to hide the value in `__str__` and expose the value by accessing the `value` attribute.

```python
class Secret:
    """
    Holds a string value that should not be revealed in tracebacks etc.
    You should access the ``value`` attribute at the point it is required.
    """

    def __init__(self, value: str):
        self.value = value

    def __repr__(self) -> str:
        return "%s('**********')" % self.__class__.__name__

    __str__ = __repr__
```

**Comment by sloria** [comment]
This is also an issue with `DatabaseURL`:

```python

In [1]: from starlette.datastructures import DatabaseURL

In [2]: db = DatabaseURL('postgres://username:password@localhost/database_name')

In [3]: db
Out[3]: DatabaseURL('postgres://username:********@localhost/database_name')

In [4]: print(db)
postgres://username:password@localhost/database_name

In [5]: import logging

In [6]: logging.critical(db)
CRITICAL:root:postgres://username:password@localhost/database_name

```

**Comment by lovelydinosaur** [comment]
Not sure. Might be that we instead want to rephrase the docs. (Hide the value from accidentally leaking in tracebacks or other code introspection.)

Yes, if you explicitly include the variable in a print or logging you get the str value.

Perhaps we want to use the more forcible `.value`, but I think we should defer that decision to a major-point change, since we'll need to break API if we want to do that.

**Comment by sloria** [comment]
That's fine. At the very least, the docs should be updated. I'll send a separate PR for that.

**Comment by remarkov** [comment]
I just faced the same issue, even after the fix in docs I still got confused at first and expected that if I put something like:
`logger.info(f"Database initialized with {settings.DATABASE_URL}")`
that would appear with masked password in the logs which is unfortunately not the case.

Reading through this issue I've got the point of backward compatibility but then I've come up with another idea, actually an opposite approach. We can add a `masked` property to both URL and Secret classes (the latter is mostly for consistency but still I see some use cases).
So I made a short PR, please see https://github.com/encode/starlette/pull/711

PS: Also I made an update to the docs to reflect the change from DatabaseURL to URL.
