### ISSUE TITLE
Decorator for validating required scopes per-method in class-based endpoints

### ISSUE THREAD

**Issue by DrPyser** [Kludex/starlette#321]
The `authentication.requires` doesn't work with handler methods defined in a class-based endpoint. 

I don't know if there's another way, currently, to declaratively annotate required scopes per-method for a class-based endpoint. If not, there should be another decorator(e.g. `method_requires`) that can be used with methods. 

Thanks!

**Comment by lovelydinosaur** [comment]
Resolved in master. See 
https://github.com/encode/starlette/pull/314 and #311 

Release incoming. (Tho welcome to reopen this if I’ve missed anything)
