### ISSUE TITLE
Support for Multiple Files for One Form Field

### ISSUE THREAD

**Issue by vchendrix** [Kludex/starlette#327]
I am trying to submit a list of data files under the same parameter name but only the first file is parsed from `request.form()`.

```bash
curl -X POST "http://0.0.0.0:3031/myapi" -H "accept: multipart/form-data" -H "Authorization: Bearer atoken"  -F "data=@/path/tp/favicon-16x16.png" -F"data=@/path/to/file.txt"
```
According to IETF RFC 7578 this should be supported.  Is this something you would consider supporting?
https://tools.ietf.org/html/rfc7578#section-4.3
```
4.3.  Multiple Files for One Form Field

   The form data for a form field might include multiple files.

   [RFC2388] suggested that multiple files for a single form field be
   transmitted using a nested "multipart/mixed" part.  This usage is
   deprecated.

   To match widely deployed implementations, multiple files MUST be sent
   by supplying each file in a separate part but all with the same
   "name" parameter.

   Receiving applications intended for wide applicability (e.g.,
   multipart/form-data parsing libraries) SHOULD also support the older
   method of supplying multiple files.
```

**Comment by lovelydinosaur** [comment]
Absolutely yes. Have this on the backlog here  
https://github.com/encode/starlette/issues/114 but I’ll try to bump up the priority, unless someone gets to it before me.

**Comment by lovelydinosaur** [comment]
I think the QueryParams data structure has all the functionality we need, tho we’ll want to do some renaming.

**Comment by vchendrix** [comment]
I saw that issue but wasn't sure if it was the same thing.  Thanks!  Loving
starlette!
