### ISSUE TITLE
Example code for raw SQL query

### ISSUE THREAD

**Issue by tobiasmuehl** [Kludex/starlette#329]
Looking through PostgresBackend, every method calls `compile()`. The docs state that raw SQL queries are supported too - can you give an example?

Example query: `SELECT now();`

**Comment by lovelydinosaur** [comment]
Actually yes, you're right. It's not quite supported at the moment. Needs a bit of tweaking to deal with the "raw SQL string" case.

**Comment by rajeev** [comment]
@tobiasmuehl If you want something quick and dirty (before @tomchristie comes up with a more elegant solution, then you can use the following:

from sqlalchemy import String
from sqlalchemy.sql import text, column
query = text("SELECT business_name FROM owner_info WHERE owner = :owner_id")
query = query.columns(column('business_name', type_=String))
query = query.bindparams(owner_id=id)
await request.database.fetchall(query)

**Comment by lovelydinosaur** [comment]
Closing this issue in favor of https://github.com/encode/databases/issues/9 - since we'll be moving to recommending `databases` in any case.
