### ISSUE TITLE
RuntimeError: Got invalid message type on lifespan protocol "http.response.start"

### ISSUE THREAD

**Issue by matthewhegarty** [Kludex/starlette#330]
First steps with starlette...

Trying to run the [example](https://github.com/encode/starlette#framework-or-toolkit):

```python
from starlette.responses import PlainTextResponse


class App:
    def __init__(self, scope):
        self.scope = scope

    async def __call__(self, receive, send):
        response = PlainTextResponse('Hello, world!')
        await response(receive, send)
```

Running with: `uvicorn app:App`

Error is:

```
INFO: Started server process [18742]
INFO: Waiting for application startup.
ERROR: Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/home/matthew/.virtualenvs/dummy/lib/python3.7/site-packages/uvicorn/lifespan.py", line 29, in run
    await self.asgi(self.receive, self.send)
  File "./app.py", line 10, in __call__
    await response(receive, send)
  File "/home/matthew/.virtualenvs/dummy/lib/python3.7/site-packages/starlette/responses.py", line 124, in __call__
    "headers": self.raw_headers,
  File "/home/matthew/.virtualenvs/dummy/lib/python3.7/site-packages/uvicorn/lifespan.py", line 50, in send
    raise RuntimeError(error % message['type'])
RuntimeError: Got invalid message type on lifespan protocol "http.response.start"
ERROR: Application startup failed. Exiting.
```

- python 3.7
- uvicorn 0.3.25
- starlette (latest version)

Looks like the ['type' string sent by starlette](https://github.com/encode/starlette/blob/master/starlette/responses.py#L122) doesn't match the [uvicorn expected type](https://github.com/encode/uvicorn/blob/master/uvicorn/lifespan.py#L39).

If I am doing something wrong - please advise.

**Comment by lovelydinosaur** [comment]
We should probably change the example to...

```python
    def __init__(self, scope):
        assert scope['type'] == 'http'
        self.scope = scope
```

Same as https://github.com/encode/uvicorn

The issue here is that ASGI has now also introduced "lifespan" messages.
You can either turn those off by using a switch in `uvicorn` to disable the lifespan messages, or else make the change above, which will raise an error on receiving lifespan messages, and will automatically disable it for you in uvicorn.

We ought to update any of the examples we use along these lines.

**Comment by lovelydinosaur** [comment]
Labelling this up as a bug, although it's a documentation bug rather than an implementation issue.
