### ISSUE TITLE
QueryParams unexpected bahavior

### ISSUE THREAD

**Issue by taoufik07** [Kludex/starlette#333]
Hey, in QueryParams when calling the `.keys()` it returns the keys from the `self._list` which can return duplicate keys if a key have multiple values. Same for `.values()` and `.items()`, it returns all the values, while the expected behavior is to return for each key the last value.

```python
>>> q = QueryParams(query_string="a=1&a=2")
>>> q.keys() # ['a', 'a'] the expected ['a']
>>> q.values() # [1, 2] the expected [2]
>>> q.items() # (a, 1) (a, 2) the expected (a, 2)
```
I can easily fix those, but I suggest to create a MultiValueDict that can be subclassed by other classes. 

So what do you think, should I keep it that way and fix the behavior or add a MultiDict ?

** In the QueryParams implementation, the items are stored in both a dict and a list, is it more efficient than django's `Mapping[str, List]` or just because back then there were more important things to do.

**Comment by lovelydinosaur** [comment]
Let's treat this as two different issues.

1. Yup, perfectly happy to have the single-value variants instead.
2. Perhaps we'll have a base class too, but let's discuss that separately, later.

**Comment by taoufik07** [comment]
okie dokie :D

**Comment by taoufik07** [comment]
@tomchristie you want `.keys()` to return a `generator`, a `dict_keys`  or a `list` ?

**Comment by lovelydinosaur** [comment]
I'd suggest just starting with a list, as it currently is.
QueryParams have a limited size, so that'll be just fine.
I'd be okay with considering later pull requests that use dictkeys, but it'd depend on the additional complexity it adds.
