### ISSUE TITLE
Params dropped in test client

### ISSUE THREAD

**Issue by rjwittams** [Kludex/starlette#340]
https://github.com/encode/starlette/blob/10b61f6cc28ec233ad3265b2822ae713dc26a68d/starlette/testclient.py#L70

params needs to be added back to path here, or urls like http://server/path;params will have the ;params chopped off.

**Comment by lovelydinosaur** [comment]
Thanks for noticing this!
We'll use `urlsplit` instead throughout. Also this matches up with the portion of the URL that gets used for our URL routing.

**Comment by rjwittams** [comment]
That was quick! Thanks
