### ISSUE TITLE
Support virtual hosts

### ISSUE THREAD

**Issue by studer** [Kludex/starlette#360]
It would be really nice to have a virtual hosts support (like with tornado) : 

> We support virtual hosts with the `add_handlers` method, which takes in a host regular expression as the first argument:
> 
> ```
> application.add_handlers(r"www\.myhost\.com", [
>     (r"/article/([0-9]+)", ArticleHandler),
> ])
> ```
> If there’s no match for the current request’s host, then default_host parameter value is matched against host regular expressions.

I've seen some references to a `base_url` variable in the code, but it doesn't seem possible to actively set it.

The point is to have only one instance of `uvicorn` with one instance of `Starlette` but being able to handle multiple domains or subdomains.

**Comment by lovelydinosaur** [comment]
Well, you can already sling multiple hosts at it, so strictly speaking the issue is about *routing* different hostnames with separate configurations.

You can do something like this using a plain ASGI application, along these lines...

```python
site = Starlette()
api = Starlette()

class App:
    def __init__(self, scope):
        headers = Headers(scope)
        host = headers.get('host')
        if host == 'www.example.org':
            return site(scope)
        else:
            return api(scope)
```

However, there's far more comprehensive support in the #363 pull request.

**Comment by lovelydinosaur** [comment]
Any thoughts on best ways around for testing multiple domain routed applications? (Ie. if you're running locally, requests will all be coming in to "127.0.0.1" or whatever.)

**Comment by studer** [comment]
Thanks for your incredibly fast pull request and idea ! 👍 🥇 
One solution for local testing would be to use the whole 127.0.0.0/8 range (without editing the `hosts` file). Let's say : 

> - 127.0.0.1 -> example.org
> - 127.0.0.2 -> api.example.org
> - 127.0.0.3 -> test.com

To answer another question : I'm also not a big fan of decorator style routing, I prefer `HTTPEndpoint` (especially for medium to big projects).
