### ISSUE TITLE
Custom Exception Handlers aren't called

### ISSUE THREAD

**Issue by xenosdio** [Kludex/starlette#367]
Hello.

I noticed that if I create any exception handlers for my custom exceptions, they are only called if they reside in the same file as the Starlette app initialization.
If i create a separate, let's say `exception_handlers.py`, file and import the Starlette app there, the handling methods are never called.

Is this intented? Am I doing something wrong?

**Comment by lovelydinosaur** [comment]
I *guess* you've probably strucuted the files in such a way that it's not actually being imported. (Ie. the `@app.exception_handler(...)` lines of code aren't actually being run at all when you import the app instance.) If you've got them in a seperate file then you'll want to make sure that file gets imported from `app.py` or whatever you've called your main module. (Tho you may need to import them after the app instantiation to avoid a circular dependency.)
