### ISSUE TITLE
MultipartParser: option to write files to temporary directory on file upload

### ISSUE THREAD

**Issue by vchendrix** [Kludex/starlette#388]
Would you consider enhancing `formparsers.MultipartParser` to allow the option to write to a temporary file  instead using `SpooledTemporaryFile`?  Maybe allow the user to specify the temporary file type?

**Comment by lovelydinosaur** [comment]
Perhaps yeah. What’s the motivation? It’s possible that we’ll look at having a generic interface for parsing the request body with `request.parse()`, rather than individual .json and .form methods.

**Comment by vchendrix** [comment]
Thanks for the response!  We are a data archive for earth and environmental science data.   We allow our users to upload up to 1GB of data via HTTP.  The large data transfers ( upto TB or more of data) will be handled in other non-http methods.  We want the files to be written to a temporary directory so that we may perform a number of securiry and quality checks.  Also under load we will not be able to handle all that data in memory but we do have lots of storage space to work with.  

A `request.parse()` actually sounds great because one of the things we need to do is a `checksum` on each file.  It would be really great to do this during parse as the data is coming in. 

Thanks for your consideration.

**Comment by lovelydinosaur** [comment]
So, I guess this won't be resolved until we have a generic answer to "configurable parsers".
In the meantime I guess you may want to deal with this explicitly - subclass `MultipartParser`, and use `files = MyParser().parse(request.stream)` or something.

**Comment by simonw** [comment]
Subclassing `MultipartParser` is a bit messy right now if you want to do this, because you end up needing to copy-and-paste the entire `parse()` method just to change the one line that references `UploadFile`:
https://github.com/encode/starlette/blob/eeb6e549b6bed325e69dc09d88040aed0050f2ea/starlette/formparsers.py#L160-L242

**Comment by simonw** [comment]
Here's a suggestion for a way to make it much easier to subclass this behaviour: https://github.com/simonw/starlette/commit/d53f89d39b4d6451d82e679fffbe0bea342296fc

Does that feel like a good solution? I'm not sure if that's a clean pattern or not.

**Comment by lovelydinosaur** [comment]
Probably sensible, yup.

**Comment by lovelydinosaur** [comment]
Going to close this off for now with the same justification as https://github.com/encode/starlette/issues/849

Out of scope. If ya need more complex parsing than we currently provide, you need to do so within your own project.

**Comment by CarliJoy** [comment]
I think the only background of the question was to be able to change "SpooledTemporaryFile" to "NamedTemporaryFile" while Uploading files. 
This way people that want to handle simple file uploads with a little extra would be able to to access the temporary file and move it reducing the drive IO and used file system memory by 100%.

For quite a number of people this is quite a normal use case and forcing them to write their own parser for such a common would be tricky for the most of them.

So the [argument](https://github.com/encode/starlette/issues/849#issuecomment-1041887047) @adriangb brought up in #849 seems to be even more valid here.

Even if one would use move `tempfile = SpooledTemporaryFile(max_size=self.max_file_size)`  to a extra function call `create_temporary_file(max_size: int ) -> TemporaryFile` in order for people to monkey patch it, would be helpful.
