### ISSUE TITLE
Project configuration for multiple environments

### ISSUE THREAD

**Issue by kdebowski** [Kludex/starlette#391]
What is your solution to have few `.env` (`.default`, `.production`?) files that share some settings and change another. I presume that ie. `integration` environment could still have `DEBUG=True` but different `DATABASE_URL` settings. The most common way to do it is to inherite/import one file from another and then override values when needed. Solution described in documentation shows how to load settings file, but not how to do it for real life application when we need to work with multiple environments. Do you have some habits in this case? How would you develop bigger application with many settings - would you assign the same values in multiple configs?

**Comment by euri10** [comment]
I played a little with it but can't comment first hand on the "best" way to do it, but when I tried to achieve that kind of setup I used [starlette config](https://www.starlette.io/config/)

I had only test and dev settings though and load env variables through a docker-compose file but essentially it boils down to have a settings.py file like that

```
from starlette.config import Config
from starlette.datastructures import DatabaseURL, Secret

config = Config(".env")

DEBUG = config('DEBUG', cast=bool, default=False)
TESTING = config('TESTING', cast=bool, default=False)
SECRET_KEY = config('SECRET_KEY', cast=Secret)

DATABASE_URL = config('DATABASE_URL', cast=DatabaseURL)
DATABASE_TEST_URL = config('DATABASE_TEST_URL', cast=DatabaseURL)
if TESTING:
    DATABASE_URL = DATABASE_TEST_URL
    DEBUG = True
```

on same level than settings I got a app.py file that contains a function that returns a FastAPI instance, this way:
```
def create_app():
    app = FastAPI()
    app.debug = settings.DEBUG
    app.add_middleware(
        DatabaseMiddleware,
        database_url=settings.DATABASE_URL,
        rollback_on_shutdown=settings.TESTING
    )
    from project.apis.auth import auth_router
    app.include_router(auth_router, prefix="/auth")
    from project.apis.users import users_router
    app.include_router(users_router, prefix="/users")
    return app
```
I run it in dev settings with a manage.py file one level above, that my `entrypoint.sh` calls in my docker-compose file,

```
@cli.command()
def run():
    from project.app import create_app
    app = create_app()
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info", debug=True)
```
that run function could take debug / prod, whatever params you want, hope it helps

```
├── Dockerfile-dev
├── entrypoint.sh
├── __init__.py
├── manage.py
├── project
│   ├── app.py
│   ├── db
│   │   ├── create.sql
│   │   └── Dockerfile
│   ├── __init__.py
│   ├── settings.py
```

**Comment by lovelydinosaur** [comment]
Typically the environment should be minimal enough that you specify it explicitly in each case, or use a default value if appropriate.

python-decouple has some good examples https://github.com/henriquebastos/python-decouple/
