### ISSUE TITLE
WebSocket max message size

### ISSUE THREAD

**Issue by divad** [Kludex/starlette#407]
Does Starlette support a max message size config option or parameter?

I've looked through the docs and code and cannot find one.

If it does not exist then one should be added. Without such an option a client can perform a memory exhaustion attack on the server simply by sending a huge message.

Other frameworks have added max message size support for this reason:

* aiohttp added one: https://github.com/aio-libs/aiohttp/issues/1952
* Sanic has four options: https://sanic.readthedocs.io/en/latest/sanic/websocket.html
* Tornado also has a max_message_size.

Cheers!

**Comment by lovelydinosaur** [comment]
Yes, good call, but probably(?) ought to be at the server level instead. Have a check to see if we have an open issue for this on Uvicorn. Also maybe checkout Hypercorn’s behaviour here.

**Comment by divad** [comment]
I asked about this same issue on Quart and the author confirmed that this is handled in Hypercorn (he said it should be part of the ASGI server), I had a check to see if support is in Uvicorn but I couldn't see it, so I'll open an issue.

**Comment by divad** [comment]
https://github.com/encode/uvicorn/issues/306
