### ISSUE TITLE
Config/Settings dump?

### ISSUE THREAD

**Issue by wshayes** [Kludex/starlette#408]
What's the best way to dump all of the settings using starlette.config? I want to create an endpoint to make it easy to review the settings being used but I don't want the Secrets to be viewable, e.g. things like:

    JWT_SECRET = config("JWT_SECRET", cast=starlette.datastructures.Secret)

We are currently using:

```
@router.get("/settings", tags=["Info"])
def get_settings() -> dict:
    dctconfig = dict(settings.config)
    return dctconfig
```
But it shows the the secrets (instead of Secret('**********')) along with everything else.

**Comment by lovelydinosaur** [comment]
Something like this would get you most the way there I guess...

`{var: repr(getattr(settings, var)) for var in dir(settings)}`

Tho you’d want to filter out everything except UPPERCASED var names.

**Comment by lovelydinosaur** [comment]
You can’t use `settings.config` directly, since it’s just a view onto the environment- it doesn’t “know” about how you’ve cast each element in it. We might want to think about debug level logging for any config accesses.

**Comment by lovelydinosaur** [comment]
Also we *could* switch things around a bit so that the dict representation of the config only includes things that have been accessed, and returns their actual cast values.

**Comment by wshayes** [comment]
Thanks for the quick response (and Starlette!) - the following works great! I would be nice to have a convenience function for this, but I'll put a PR for the docs to show this and update the DatabaseURL (which was removed) in place of the URL cast.

        results = {var: repr(getattr(settings, var)) for var in dir(settings) if var.isupper()}
