### ISSUE TITLE
Problem with formdata in utf-8, with non latinic symbol

### ISSUE THREAD

**Issue by Ekuzkamaza** [Kludex/starlette#425]
version starlette is __version__ = "0.11.3"

in formparsers.py in line 218 following code  =>  items.append((field_name, data.decode("latin-1")))
need change to => items.append((field_name, data.decode("utf-8")))

Because, for example, the data in the Russian language is displayed as a scribble.
I'm sure there's a more elegant solution.

**Comment by lovelydinosaur** [comment]
Looks like a valid issue, yup. We should probably be using whatever charset is present in the `Content-Type` header.

**Comment by shizidushu** [comment]
I also have this problem when try uploading file in html form with fastapi. I hope it can be fixed soon.

**Comment by lovelydinosaur** [comment]
Released as 0.12.5
