### ISSUE TITLE
Middleware for a specific route

### ISSUE THREAD

**Issue by Ekuzkamaza** [Kludex/starlette#426]
How to add a Middleware for a specific route or routing group?
like a => Route('/Messanger', endpoint = Messanger, methods=['GET','POST'], middleware=['CSRF', 'Auth'])
Or mechanism a call a Middleware from endpoints.

**Comment by lovelydinosaur** [comment]
We don't currently support that, but it'd be worthwhile to do so.
I'll plan to take a look at it sometime this month.

**Comment by lovelydinosaur** [comment]
Going to pass on this for now. You can submount an app, and apply middleware to that.
