### ISSUE TITLE
templateing: jinja2: pass kwargs for environment

### ISSUE THREAD

**Issue by blueyed** [Kludex/starlette#427]
I think it would be good to pass something like `env_kwargs` via https://github.com/blueyed/starlette/blob/24c135de71ac56a73f7f797258115941579155bf/starlette/templating.py#L51-L53.

While you can change the env afterwards, it would allow Jinja2 to validate e.g. `enable_async`, and call `load_extensions` etc.

**Comment by lovelydinosaur** [comment]
Yup I'm up for this. We'll want to `autoescape` and `loader` be overridable there too.

Related to this is configuring `env.globals`.

We *could* just use `**options`, and support both `globals` and any valid Environment keyword arguments?

**Comment by blueyed** [comment]
I think it should just allow more easily to set the env altogether.

`url_for` could be still set to the globals then by default.

But it is also the only reason for requiring `request` to be in the context (`ValueError('context must include a "request" key')`), and if `url_for` is not used in a template, it is not used (by default).  I.e. it might be better to raise the error then from `url_for` only.

Not sure about backward compatibility with regard to removing `directory` from the constructor, but #473 might indicate that it is not used much (at least with tested code).. ;)

I am using a quite customized version already myself, and that is fine, but wanted to provide this feedback anyway.

**Comment by liquiddandruff** [comment]
+1 as well, since as currently stands it's not possible to change common fields such as `auto_reload`, `enable_async` when loading the environment, especially when deploying through a docker environment.
