### ISSUE TITLE
Path prefix for PATH_INFO with WSGIMiddleware

### ISSUE THREAD

**Issue by blueyed** [Kludex/starlette#430]
When mounting an app (e.g. Django) through `WSGIMiddleware` it seems to be required to also adjust `PATH_INFO` accordingly.

With the following, Django would e.g. redirect to "/admin/" (without the outer "/dj" prefix).

```python
djapp = django.core.wsgi.get_wsgi_application()
app.mount("/dj", app=WSGIMiddleware(djapp))
```

I've got this working through an additional "path_prefix" argument for WSGIMiddleware, but I think it makes sense to either prepend the mount path in `build_environ` always (using `"PATH_INFO": scope["root_path"] + scope["path"]`, and making it visible to the mounted app though), or handle e.g. "Location" response headers by prepending it there.
The latter could likely result in redirect-loops, and does not help with Django POSTing to "/admin/login" then.

I've not investigated too much into this yet, what do you think?

**Comment by blueyed** [comment]
(it works better when using ASGI via Django Channels - related code: https://github.com/django/channels/blob/a660d81899e1cfd030f20a499cdeae1cea3e0646/channels/http.py#L39-L65)

**Comment by lovelydinosaur** [comment]
Prob just a case of needing to pass the ASGI root_path through to the WSGI PATH_INFO

**Comment by blueyed** [comment]
Yes, just prepending it might do the trick - initially I've thought that the mounted app should not know about it, but there is not really a way around it.

What Channels does for Django itself is more complicated though..

**Comment by lovelydinosaur** [comment]
“SCRIPT_NAME”: scope.get(“root_path”, “”) would resolve this
