### ISSUE TITLE
url_for for one endpoint with combinations of routes 

### ISSUE THREAD

**Issue by em92** [Kludex/starlette#433]
```python
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse


app = Starlette()


@app.route("/")
@app.route("/{page:int}")
@app.route("/cat/{cat}")
@app.route("/cat/{cat}/{page:int}")
def http_method(request):
    cat = request.path_params.get("cat", "")
    page = request.path_params.get("page", 0)
    return PlainTextResponse("cat: {}, page: {}".format(cat, page))


print(app.url_path_for("http_method", cat=None, page=1))  # expected /1
print(app.url_path_for("http_method", cat="name", page=1))  # expected /cat/name/1
print(app.url_path_for("http_method", cat="name", page=None))  # expected /cat/name
```

First print does not match with expected, second print matches, third one throws exception

**Comment by em92** [comment]
Can be fixed with:
```diff
diff --git a/starlette/routing.py b/starlette/routing.py
index 15786b1..8118032 100644
--- a/starlette/routing.py
+++ b/starlette/routing.py
@@ -190,6 +190,7 @@ class Route(BaseRoute):
         return Match.NONE, {}
 
     def url_path_for(self, name: str, **path_params: str) -> URLPath:
+        path_params = {k: v for k, v in path_params.items() if v is not None}
         seen_params = set(path_params.keys())
         expected_params = set(self.param_convertors.keys())
 ```

If it is acceptable, I suggest to add PR with test cases yourself @tomchristie. I am quite busy at work.

**Comment by em92** [comment]
Temporary solution, before PR is merged:

```python
from starlette.routing import Route

def fixed_url_path_for(self, name: str, **path_params: str):
    path_params = {k: v for k, v in path_params.items() if v is not None}
    return self.bugged_url_path_for(name, **path_params)


Route.bugged_url_path_for = Route.url_path_for
Route.url_path_for = fixed_url_path_for
```

**Comment by lovelydinosaur** [comment]
I'm not convinced that we should change the behavior...

The following do not work:

```python
print(app.url_path_for("http_method", cat=None, page=1))  # expected /1
print(app.url_path_for("http_method", cat="name", page=1))  # expected /cat/name/1
print(app.url_path_for("http_method", cat="name", page=None))  # expected /cat/name
```

But these do...


```python
print(app.url_path_for("http_method", page=1))  # expected /1
print(app.url_path_for("http_method", cat="name", page=1))  # expected /cat/name/1
print(app.url_path_for("http_method", cat="name"))  # expected /cat/name
```

The second set look more obviously valid to me.

Eg. in PR #444 - the test case that's been added passes regardless of if the `if v is not None` change is included.

**Comment by em92** [comment]
> in PR #444 - the test case that's been added passes regardless of if the if v is not None change is included.

Fixed

> I'm not convinced that we should change the behavior...

Here is a real example:
https://github.com/em92/quakelive-local-ratings/blob/cb4b8cb515cc2a784efa0d10c00feff6eb147982/qllr/blueprints/player/__init__.py#L31-L44

For example we have: 
```python
path_params = {'page': 0, 'steam_id': 123}
```
It will redirect to `/matches/player/76561198155322638/None/0/`. See`None` in new url, it is not supposed to be there. Pretty sure, that current behaviour of `url_path_for` is invalid, but then how `url_path_for` is supposed to deal with NoneType?

Of course we can do something like this:
```python
@bp.route("/{steam_id:int}/matches/")
@bp.route("/{steam_id:int}/matches/{page:int}/")
@bp.route("/{steam_id:int}/matches/{gametype}/")
@bp.route("/{steam_id:int}/matches/{gametype}/{page:int}/")
class PlayerMatchesDeprecatedRoute(HTTPEndpoint):
    async def get(self, request: Request):
        return RedirectResponse(
            request.url_for(
                "MatchesHtml",
                **request.path_params,
            )
)
```
But it works if "MatchesHtml" endpoint has route with equivalent path_params.

**Comment by lovelydinosaur** [comment]
This sort of thing makes much more sense...

```python
request.url_for("MatchesHtml", **request.path_params)
```

Or else build up the keyword arguments explicitly.

I'd rather we don't discard `None` values in this way. If anything I think we should make sure we're raising errors if a value is used that doesn't match the correct type given in the URL route.
