### ISSUE TITLE
Better support for HEAD method

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#45]
* Routing should automatically include `'HEAD'` in the supported methods if `'GET'` is there.
* Static files should respond appropriately to `'HEAD'` requests without sending the entire file.

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/45">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/45/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/45/pledge.svg">
</picture>
</a>

**Comment by laixintao** [comment]
Defining a `head` dispatch won't be necessary?

```
@app.route("/{username}")
class User(HTTPEndpoint):
    async def head(self, request, username):
        pass
```

**Comment by lovelydinosaur** [comment]
> Defining a head dispatch won't be necessary?

Correct
