### ISSUE TITLE
How to reduce not needed dependencies?

### ISSUE THREAD

**Issue by koddr** [Kludex/starlette#450]
Hello and many thanks for Starlette 👍 

I search right way to reduce not needed dependencies of Starlette core (when installation). 

For example:

* I use classic REST (no need GraphQL);
* I use Starlette as REST API server, only returned JSON data from database (no need jinja2);
* No need YAML, docs generation and etc..

May I get true way to have `lite` or `slim` version of Starlette? 

In (_my_) ideal World, I use Starlette `core` and add some libs if needed (not built-in on Starlette bundle). Only core features for REST API JSON.

Respectfully.

**Comment by lovelydinosaur** [comment]
> May I get true way to have lite or slim version of Starlette?

Starlette has no dependencies.

There's various things you can *optionally* install if you need them. https://www.starlette.io/#dependencies
