### ISSUE TITLE
py.typed missing in published artifacts

### ISSUE THREAD

**Issue by uranusjr** [Kludex/starlette#452]
I didn’t check for earlier versions, but at least 0.11.4 on PyPI does not include `py.typed`. I assume this is an oversight, given it is mentioned in `setup.py`?

https://github.com/encode/starlette/blob/77b84a08c1e4de0db64a197b58ac363a26c51d4f/setup.py#L49

**Comment by lovelydinosaur** [comment]
No idea. Happy to take pull requests against the `setup.py`.
It was introduced here: https://github.com/encode/starlette/pull/253 but I've not looked in any detail into exactly what it ought to do.

**Comment by uranusjr** [comment]
It signifies that the package is typed, and mypy looks for this file in determine whether it should follow type hints in the package (and show type errors when calling it). I guess I’ll make a PR adding that file.
