### ISSUE TITLE
Multiple template backends

### ISSUE THREAD

**Issue by alex-oleshkevich** [Kludex/starlette#453]
Multiple template engines support

As Starlette is an unopionated framework it should support various template engines.
The engine to use it determined by template file extension.

In order to support it the framework needs an unified API to transparently select engines.

In this RFC I propose the following API:
`Renderer` - an object which abstracts developer from underlying template engine.
`TemplateEngine` - this is an adapter between template engine and renderer
`EngineMapper` - this binds template extension to a concrete template engine

The API for the classes above:
```python
class Renderer:
    def __init__(self, engines: EngineMapper)
    async def render(template: str, context: dict = None) -> str: ...
```

```python
class TemplateEngine:
    async def render(template: str, context: dict = None) -> str: ...
```

```python
class EngineMapper:
    def bind(extension: str, engine: TemplateEngine) -> None: ...
    def find_for_extension(extension: str) -> TemplateEngine: ...
```

The usage of there classes may be like this:
```python
class JinjaTemplateEngine:
    def __init__(self, environment: jinja2.Environment):
        self._env = environment
        
    async def render(template: str, context: dict = None) -> str:
        return self._env.render_async(template, context or {})


jinja = jinja2.Environment(enable_async=True)
engines_map = EngineMapper()
engines_map.bind('.html', JinjaTemplateEngine(jinja))
renderer = Renderer(engines)

rendered_contents = await renderer.render('template_name.html', {'hello': 'world'})
print(rendered_contents) # rendered template
```

Note, `TemplateEngine.render` is async as template may come from file, database or other IO source.

If this proposal works for you I can form a PR.

**Comment by lovelydinosaur** [comment]
Right now you can already introduce an alternate templating engine by implementing a class that defines a `TemplateResponse(...)`, mirroring the existing jinja2 implementation. https://github.com/encode/starlette/blob/master/starlette/templating.py#L48

I'd rather we start by seeing an alternate implementation that matches the *current* API.
