### ISSUE TITLE
Official Starlette logo

### ISSUE THREAD

**Issue by koddr** [Kludex/starlette#456]
Hello and thanks (again) for Starlette 👍 

I think, we're ready for official Starlette logo.

> Btw, I made [official logo of Quart](https://github.com/koddr/quart-logo) ASGI Python Framework. I do this, because I want to make Starlette better and make it recognizable. So, use with [Creative Commons license](https://creativecommons.org/share-your-work/public-domain/cc0) (CC0 1.0 Universal) and it's for free.

This is my vision of `a young actress with aspirations to become a star` (macOS EN Dictionary).

> Yes, I know, `starlette` is a French word and literally means `rising star`, english equivalent of a `starlet`, but with a different meaning :)

<img width="735" alt="Screen Shot 2019-03-29 at 10 36 13" src="https://user-images.githubusercontent.com/11155743/55216800-c9ca2a00-520e-11e9-8cf1-4999bbe89e9d.png">

<img width="823" alt="Screen Shot 2019-03-29 at 10 37 50" src="https://user-images.githubusercontent.com/11155743/55216806-c9ca2a00-520e-11e9-8e4c-e0aa85688851.png">

The meaning of the logo is quite simple: ascending (read, _like new_) bright star, which shines brightly. Good typography for merchandising and speeches at Python conferences, catchy graphics for everything else.

And short logo is:

<img width="695" alt="Screen Shot 2019-03-29 at 10 36 45" src="https://user-images.githubusercontent.com/11155743/55216801-c9ca2a00-520e-11e9-9164-17dadf0d85bb.png">

The small star is directed slightly up and to the right to show the dynamics of movement, but not to be super intrusive.

I experimented with other fonts and elements, for example:

<img width="876" alt="Screen Shot 2019-03-29 at 10 37 03" src="https://user-images.githubusercontent.com/11155743/55216802-c9ca2a00-520e-11e9-8c98-62099ec4669e.png">

...or: 

<img width="944" alt="Screen Shot 2019-03-29 at 10 37 23" src="https://user-images.githubusercontent.com/11155743/55216804-c9ca2a00-520e-11e9-8ac2-c1d33148c3c8.png">

But first logo is most better for me. 

What do you think? Come to comments :)

**Comment by koddr** [comment]
Main image slider with new Starlette logo (just for example):

![starlette-1280](https://user-images.githubusercontent.com/11155743/55277958-02552b00-5317-11e9-8780-ef9874d137b2.jpg)

To be honest, this logo may good to any place :D 

![Free-Acid-Wash-Tee-Mockup-_-Michael-Hoss-Design](https://user-images.githubusercontent.com/11155743/55278156-be175a00-5319-11e9-8752-9794fb54d8ac.jpg)

**Comment by lovelydinosaur** [comment]
![image](https://user-images.githubusercontent.com/647359/55393965-280c4b00-5536-11e9-89bb-c32bf8818b55.png)

This is pretty nice yeah - great work! Wanna try out a PR replacing the README image and docs homepage, and see how it looks? You might want to try some different text size to border crops.

**Comment by koddr** [comment]
> This is pretty nice yeah - great work! Wanna try out a PR replacing the README image and docs homepage, and see how it looks? You might want to try some different text size to border crops.

Sorry for 22 days disappearing.. hard work on my project :(

Okay, I prepare this at weekend:

- README + PR;
- Repo with style guide;
- - Add more versions with other font weight;
- All image sources (PNG, SVG, AI/EPS);

P.S. btw, I work out to translate Starlette docs to Russian (my birth language) :)

**Comment by koddr** [comment]
Okay, it's finally done: https://github.com/koddr/starlette-logo 👍 
And PRs: #496 #521

**Comment by lovelydinosaur** [comment]
It's looking great. Thanks again!
