### ISSUE TITLE
URL Reversing

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#46]
The App and Router classes should support a `.url_for(name, **kwargs)` method.

We'll probably need to finesse our routing a bit here, eg. remove the ability to drop into plain regex, and instead add something like `{username:str}` / `{page_number:int}`.

Eventually we'll probably also want to support namespacing eg. `app.url_for('users:create_user', username=foo)`

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/46">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/46/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/46/pledge.svg">
</picture>
</a>

**Comment by berislavlopac** [comment]
Tornado uses regex with URL reversing, so I suppose it could be included.
