### ISSUE TITLE
Include timing-asgi in 3rd party packages

### ISSUE THREAD

**Issue by steinnes** [Kludex/starlette#463]
Instrumenting HTTP endpoints to emit metrics is a fairly common practice, and while automatically doing so via a middleware is not without caveat, it's so convenient that I started doing so ~3-4 years ago (https://steinn.org/post/flask-statsd/) and haven't stopped since.

As I was implementing another hacky middleware like the one described in the post linked above I thought to myself: why not do a proper job of this and package it up for other Starlette (or ASGI) users to enjoy, and skip the hard-coupling with statsd?

The result was this package: https://github.com/steinnes/timing-asgi

I was wondering if this package fits the bill to be included in the starlette list of 3rd party packages, and more than that I'd love to get feedback from other Starlette users on the usefulness, and/or ideas for improvement?

 used these technologies with great success a few years ago (monitoring an API with a couple of thousand req/s) and if the lessons I've learned so far can benefit others, I'd love to discuss and share :-)

**Comment by lovelydinosaur** [comment]
Absolutely, yup!!!

We've already got a decent place for this to go... https://www.starlette.io/middleware/#third-party-middleware - want to submit a pull request adding it to the docs there?

One big thing to be aware of is the move to ASGI 3 - Eg. see the example on http://www.uvicorn.org/

Starlette has a 0.12.0beta prerelease which moves to this style. Uvicorn is already updated (supports ASGI 2 and 3), and Hypercorn and Daphne will both get this too shortly. You'll probably want to update the middleware to ASGI3 at that point, and I'll do the same for the 3rd party Sentry middleware.

(You shouldn't expect to see a big breaking change like that any other time, but the 2->3 jump was needed, and we felt it was just about still viable)

**Comment by jordic** [comment]
Sorry, I started a new project with starlette, need to write some middelwares for it, any example of the middelware asgi v3?

**Comment by lovelydinosaur** [comment]
@jordic So, `pip install starlette --pre` will give you the 0.12 beta release, which uses ASGI 3 throughout. You can take a look at any of the ASGI middleware implementations there. Also have a look at https://www.aeracode.org/2019/03/20/asgi-30/

**Comment by lovelydinosaur** [comment]
If you're using [BaseHTTPMiddleware](https://www.starlette.io/middleware/#basehttpmiddleware) it won't matter anyways because that's giving you a request/response interface to build against, rather than building against the raw ASGI interface.

**Comment by lovelydinosaur** [comment]
Basic pattern now looks like:

```python
class SomeMiddleware:
    def __init__(self, app, **config):
        ...  # Setup the middleware. 'app' is the next app in the chain.

    async def __call__(self, scope, receive, send):
        ...  # This is the ASGI entry point. Do some stuff, and call into `await self.app(scope, receive, send)`
```

(Which is much nicer than before when we had to use weird `functools.partial` indirection.

**Comment by jordic** [comment]
So many thanks!

**Comment by lovelydinosaur** [comment]
I'll leave this issue open, til we've got a PR against https://github.com/encode/starlette/blob/master/docs/middleware.md#third-party-middleware

**Comment by steinnes** [comment]
I'm so happy this is well received!

I'll make a PR to add this to the middleware docs today, but first I want to look into supporting both ASGI2 and ASGI3 :-)

**Comment by lovelydinosaur** [comment]
It's probably a bit awakward to support both.

You may want to add it to the docs as it stands, and then just update it once we release Starlette 0.12 (including a note in your docs saying "install this older version" for ASGI 2 frameworks).

**Comment by steinnes** [comment]
Ah, thanks for that, one less rabbit hole for me today :-)

**Comment by lovelydinosaur** [comment]
Alrighty - 0.12.0 is released. @steinnes Wanna bump the package into the docs now?

**Comment by steinnes** [comment]
Thanks @tomchristie I just released an ASGI3 compatible version of timing-asgi now, and the package is listed in the Starlette docs (https://www.starlette.io/middleware/#timingmiddleware).

Thanks again for the new release :-)

**Comment by lovelydinosaur** [comment]
Great work - thanks!
