### ISSUE TITLE
JSON-RPC for Starlette

### ISSUE THREAD

**Issue by kdebowski** [Kludex/starlette#469]
Hey, I've been working on json-rpc implementation for Starlette for some time. 

Here is my repository: https://github.com/kdebowski/starlette-jsonrpc

I would be really grateful for your feedback, ideas, contribution. Please be gentle as it is my first public, open source project :)

**Comment by lovelydinosaur** [comment]
That looks great! Nice work.
Want to submit a pull request adding it here?... https://www.starlette.io/third-party-packages/
