### ISSUE TITLE
Docs: DATABASE_URL should be cast to databases.DatabaseURL to subsequent statements make sense

### ISSUE THREAD

**Issue by mths0x5f** [Kludex/starlette#470]
https://github.com/encode/starlette/blob/master/docs/config.md

```s/config('DATABASE_URL', cast=URL)/config('DATABASE_URL', cast=databases.DatabaseURL)/g```

**Comment by lovelydinosaur** [comment]
Resolved. https://github.com/encode/starlette/commit/2d88c4cd295967bffb9828a7cd39eaade4a84bbc#diff-d39a8a737bc5c13f36e41aa92a0c7602
