### ISSUE TITLE
Rendering templates without explicitly passing request

### ISSUE THREAD

**Issue by supriyo-biswas** [Kludex/starlette#482]
As present, Starlette's templating requires that the response variable be passed explicitly. This requires `TemplateResponse('index.html', {'request': request})` to be written everywhere, thus I have been playing around with the idea of performing the render in the middleware where the request would be available, thus avoiding the need of passing it explicitly.

To do this, I tried adding a subclass of `Response` like so:

```
class TemplateResponse(Response):
    def __init__(self, template, context={}, status_code=200, headers={}, media_type='text/html', background=None):
        self.template = jinja2_env.get_template(template)
        self.context = context
        headers['X-Templated-Response'] = '1'
        super().__init__('', status_code, headers, media_type, background)
```

... and then render in the middleware and return the "real" response like so:

```
class TemplatingMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        if response.headers.get('X-Templated-Response'):
            del response.headers['X-Templated-Response']
            content = response.template.render({
                **response.context,
                'config': self.app.config,
                'request': request
            })
            response = Response(content, response.status_code, response.headers, response.media_type)
        return response
```

However, it appears that all responses get converted to a `StreamingResponse` object preventing me from achieving this goal.

Is there a way to preserve the original "TemplateResponse" object; or is there another way of achieving this?

**Comment by lovelydinosaur** [comment]
You'd want to take a different approach.

In `TemplateResponse` (See https://github.com/encode/starlette/blob/master/starlette/templating.py) you'd want to:

1. Perform the template rendering *not* in `__init__`, but in `__call__` instead.
2. Instantiate a request instance from the `scope` if there isn't already one in the context.

**Comment by tomchristie** [comment]
You'd want to take a different approach.

In `TemplateResponse` (See https://github.com/encode/starlette/blob/master/starlette/templating.py) you'd want to:

1. Perform the template rendering *not* in `__init__`, but in `__call__` instead.
2. Instantiate a request instance from the `scope` if there isn't already one in the context.

**Comment by aminalaee** [comment]
As per discussion in #1400:

> * I think this change will end up setting Content-Length: 0 on template responses. (Which would be broken.)
> * Switching TemplateResponse so that it renders at the point it is called, rather than on __init__ is a bit of a behaviour changing thing for use to do. If response.body is inspected directly in the endpoint, it'll be b"".

We won't be doing this, unless there's a proper way to achieve this.
