### ISSUE TITLE
Flake8 codebased in CI

### ISSUE THREAD

**Issue by alimcmaster1** [Kludex/starlette#485]
There seems to be a few unused var in the codebase eg in:

https://github.com/encode/starlette/blob/master/starlette/middleware/cors.py

requested_cookie = "cookie" in request_headers

Seems to be unused. Could we run flake8 in CI to catch this? Happy to look at setting this up

**Comment by lovelydinosaur** [comment]
Would be very happy to consider any pull requests along these lines, sure!
