### ISSUE TITLE
Should WebSocketTestSession use current event loop?

### ISSUE THREAD

**Issue by unmade** [Kludex/starlette#487]
Hi there! 

First of all, thanks for the beautiful framework!

I'm in the middle of migrating one of my apps from Sanic to FastAPI and I'm a little bit stuck with testing web socket endpoints. 

In the web socket handler I use redis connection pool (aioredis), which is created on the app startup (thanks to according event). However, in test whenever I try to access redis I keep getting this error:
```
RuntimeError: Task ...  attached to a different loop
```

I think the problem can be in this line:
https://github.com/encode/starlette/blob/master/starlette/testclient.py#L266

Here is what happening: to run events in test we use TestClient as context manager. Event handlers runs in current event loop, but WebSocketTestSession runs app in new event loop

So, my question is there specific reason to create new event loop in the WebSocketTestSession? It seems that we can just use current loop.

To illustrate the problem I created **pull request**:
https://github.com/unmade/starlette/pull/1/files

P.S: There seems to be incorrect return value in type annotation. I can fix it also:
https://github.com/encode/starlette/blob/master/starlette/testclient.py#L444
https://github.com/encode/starlette/blob/master/starlette/testclient.py#L426

**Comment by unmade** [comment]
Any thoughts on this problem?

**Comment by tiangolo** [comment]
@unmade I'm glad you're liking Starlette and family (FastAPI :smile: )!

Where are you using `aioredis`? In your WebSocket endpoint or in the TestClient? Or both? Are you sharing the same object?

**Comment by lovelydinosaur** [comment]
> So, my question is there specific reason to create new event loop in the WebSocketTestSession? It seems that we can just use current loop.

Probably be good for us to adopt a "get_event_loop" with "new_event_loop" as a fallback if that fails, right? Would be happy to consider a pull request towards that. Anywhere else that we're doing this that could benefit from the same approach?

**Comment by unmade** [comment]
@tiangolo 
Yes, I'm sharing the same object. I create redis client on "startup" event and assign it to `app`, then I use this client both in WebSocket endpoint (via `request.app.redis_cli`) and in tests (via `TestClient.app.redis_cli`)

Here is steps from my project:
- [Creation of redis client](https://github.com/excars/excars-back/blob/master/excars/main.py#L16-L18)
- [Usage in WebSocket endpoint](https://github.com/excars/excars-back/blob/master/excars/api/v1/ws.py#L15)
- [Simple test for WS endpoint](https://github.com/excars/excars-back/blob/master/excars/tests/api/v1/test_ws.py#L38-L41)
- [TestClient monkey patch to avoid described problem](https://github.com/excars/excars-back/blob/master/excars/tests/conftest.py#L50-L57)

@tomchristie 
Great! Will do in the next couple days

**Comment by tiangolo** [comment]
I see. Makes sense.

> Will do in the next couple days

Awesome! Thanks!

**Comment by unmade** [comment]
I opened Pull Request. Please take a look when you will have time. 
It seems that `get_event_loop` works fine in all cases, except ones that uses `websocket_connect` in endpoint

**Comment by grubberr** [comment]
Hello,
I am stuck with a similar problem on my project
Below I put some code snippet to demonstrate problem again

```python3
#!/usr/bin/env python3

import aioredis
from starlette.applications import Starlette
from starlette.testclient import TestClient

app = Starlette(debug=True)
redis_pool = None


async def on_startup():
    global redis_pool
    redis_pool = await aioredis.create_redis_pool('redis://localhost')
    await redis_pool.set('key', 'Hello')

app.add_event_handler('startup', on_startup)


@app.websocket_route('/ws')
async def websocket_endpoint(websocket):

    await websocket.accept()
    msg = await redis_pool.get('key', encoding='utf-8')
    await websocket.send_text(msg)


with TestClient(app) as client:
    websocket = client.websocket_connect('/ws')
    print(websocket.receive_text())
```

I also want to highlight that this problem only happens with TestClient
if you run this code under uvicorn all works ok

**Comment by dmontagu** [comment]
https://github.com/vinissimus/async-asgi-testclient might help, it worked for me in some cases where I struggled with event loop issues.

**Comment by grubberr** [comment]
@dmontagu 
yes it seems it's helped for me
thank you

```python3
#!/usr/bin/env python3

import asyncio
import aioredis
from starlette.applications import Starlette
from async_asgi_testclient import TestClient

app = Starlette(debug=True)
redis_pool = None


async def on_startup():
    global redis_pool
    redis_pool = await aioredis.create_redis_pool('redis://localhost')
    await redis_pool.set('key', 'Hello')

app.add_event_handler('startup', on_startup)


@app.websocket_route('/ws')
async def websocket_endpoint(websocket):

    await websocket.accept()
    msg = await redis_pool.get('key', encoding='utf-8')
    await websocket.send_text(msg)


async def main():
    async with TestClient(app) as client:
        websocket = client.websocket_connect('/ws')
        await websocket.connect()
        print(await websocket.receive_text())

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by grubberr** [comment]
@unmade because WebSocket connection run in separate thread it looks reasonable to create new event loop for it. For example one my test runs 2 WebSocket connections and failed even with your fix. As for me it's bad design problem of TestClient.

**Comment by unmade** [comment]
@grubberr 
Apologies for not replying so long, I'm somehow overlooked your reply. I agree that all troubles are because of the way how TestClient works and my PR was a kinda workaround. 

Since there is a better solution by using [async-asgi-testclient](https://github.com/vinissimus/async-asgi-testclient), I'm closing this issue

**Comment by grutts** [comment]
This was the cause of our issues and using async-asgi-testclient worked. We had a global async kafka producer created on startup and were trying to use the TestClient with websocket_connect to test. We only had the issue in tests, prod was fine. 

I assume removing (starlette's) TestClient in favour of async-asgi-testclient has already been considered and decided against. So, would you be open to adding a recommendation to use async-asgi-testclient for testing when using a global async object and websockets to the Starlette / FastAPI documentation? The use case which triggers this issue strikes me as quite common, and documenting it would help future users get it right the first time. I'll happily open a PR on the docs if you agree.
