### ISSUE TITLE
Drop `requests` and `aiofiles` as hard requirements.

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#49]
* Ensure that `requests` is only required at the point of instantiating `TestClient`.
* Ensure that `aiofiles` is only required at the point of instantiating `FileResponse` or `StaticFiles`.

**Comment by lovelydinosaur** [comment]
Completed in 0.3

**Comment by pawamoy** [comment]
Not sure about later versions, but we're using Starlette 0.14.2, and getting a `ModuleNotFoundError: No module named aiofiles` error when trying to use static files. I don't see `aiofiles` mentioned anywhere in the docs. Are users expected to add it to their dependencies themselves? If yes, should it also be added in the `full` extra, and documented in the Static files doc page?
