### ISSUE TITLE
Exceptions context loosing

### ISSUE THREAD

**Issue by KACAH** [Kludex/starlette#514]
Hi! Why do you use `raise ... from None` construct here?

https://github.com/encode/starlette/blob/556a8a0a189a6fa3ec76bcff7fb740ffc6c4e60e/starlette/middleware/errors.py#L122
https://github.com/encode/starlette/blob/556a8a0a189a6fa3ec76bcff7fb740ffc6c4e60e/starlette/exceptions.py#L73

This is the reason, why exceptions raised like `raise NewExc from OldExc` loosing OldExc information (original message and traceback). Pure Python example:

Function:
```
def func():
    try:
        raise ValueError("Orig error")
    except Exception as exc:
        raise SyntaxError("New error") from exc
```

1) Call:
```
try:
    func()
except Exception as exc:
    raise exc
```

Output:
> Traceback (most recent call last):
>   File "<stdin>", line 3, in func
> ValueError: Orig error
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 4, in <module>
>   File "<stdin>", line 2, in <module>
>   File "<stdin>", line 5, in func
> SyntaxError: New error

2) Call:
```
try:
    func()
except Exception as exc:
    raise exc from None
```

Output:
> Traceback (most recent call last):
>   File "<stdin>", line 4, in <module>
>   File "<stdin>", line 2, in <module>
>   File "<stdin>", line 5, in func
> SyntaxError: New error

It's hard to get information about exception reasons because of this...

**Comment by blueyed** [comment]
Yeah, asked this also already somewhere here.

**Comment by blueyed** [comment]
With regard to exceptions in tests you might be interested in (or can help with) https://github.com/encode/starlette/pull/505.

**Comment by lovelydinosaur** [comment]
We do this because the end user needs to know about the actual original exception, rather than the context of "we caught this in the error middleware and then re-raised it".

**Comment by blueyed** [comment]
The end user still gets to know about the original exception.
I think the "during handling another exception happened" can be useful to see where it was caught/handled/re-raised.

**Comment by lovelydinosaur** [comment]
Personally I'd *probably* refer not too - I think it's a misdirection to the user.
But not absolute on this, and could be convinced to change tack at a later date.
