### ISSUE TITLE
The futures bright, the futures Starlette.

### ISSUE THREAD

**Issue by stuartaccent** [Kludex/starlette#515]
I just wanna say I’ve been developing in django for a while now and as a company we wanted to try something different. So we came here.

We have been building a set of packages that will handle the usual features all our sites need. I have to say I doubt I will look at django again. This is awesome and has mentally fast response times. The first site we are building has the feel of a static site where it’s quite the opposite. 

Well done and thanks for the awesome work. 

Stu

**Comment by lovelydinosaur** [comment]
That’s ace! Glad you’re enjoying it. 👍👍🥳
