### ISSUE TITLE
'starlette' is not a package

### ISSUE THREAD

**Issue by ajmcateer** [Kludex/starlette#516]
I am running Kubuntu 18.04, I have installed python 3.7.1 and created a virtual enviroment and installed starlette 0.12.0b3. But when I try to run the starlette introduction example I get the following error.

`ModuleNotFoundError: No module named 'starlette.applications'; 'starlette' is not a package`

I am using pycharm and can see that starlette and uvicorn are installed. but whether I run it from outside pycharm or inside with the virtual env active I keep getting this error.

**Comment by vineetrshenoy** [comment]
I am getting the same error. Running Python 3.5.2 and my version of starlette is `starlette==0.11.4`. Have you found a solution to this?

**Comment by em92** [comment]
Cannot reproduce `starlette=0.12.0b3` on Python 3.7.2 and `starlette==0.11.4` on Python 3.5.3.
Debian 9.9. Python 3.7.2 compiled from source.

> I am using pycharm and can see that starlette and uvicorn are installed

Find out, which interpreter with which environment it is using. Settings -> Project: <project-name> -> Project interpreter.

**Comment by lovelydinosaur** [comment]
@vineetrshenoy Starlette requires Python 3.6+

@ajmcateer Can't reproduce this with `pip install --pre starlette` - you're likely not inside the same virtual environment where you think you've installed it or *something* like that, but doesn't appear to be anything to do with Starlette's pacakaging either way.

**Comment by ajmcateer** [comment]
@em92 @tomchristie 

Got this error on Linux and Windows, Weird thing is if I start from scratch it works fine, but if I try to use it in an existing project it it seems to fail. My plan was to get a basic starlette server working and convert the project over. but seems like the easiest path is just make a new project and copy/paste.

![image](https://user-images.githubusercontent.com/7401629/57902603-1954cb80-7838-11e9-8b42-687e65b5a1c1.png)

**Comment by em92** [comment]
@ajmcateer how about renaming your `starlette.py` file to something else not to have name conflicts?

**Comment by lovelydinosaur** [comment]
Oh right, if you’ve named the module `starlette.py`, and it’s importable then it`ll clash with the  startlette package. Use `app.py` or something else instead.

**Comment by iyushaw** [comment]
Am having similar issue, my main file is called app and I have starlette-graphql==0.2.1 and starlette==0.17.1
