### ISSUE TITLE
Authenticate only a specific route

### ISSUE THREAD

**Issue by brendanator** [Kludex/starlette#517]
I would expect the AuthBackend to be used in the account route but it never gets used. However the CORS headers are added for all routes as expected.
```python
app = Starlette()
app.add_middleware(CORSMiddleware, allow_headers=['*'], allow_methods=['*'], allow_origins=['*'])
account = Starlette()
account.add_middleware(AuthenticationMiddleware, backend=AuthBackend())
app.mount('/account', account)
```
I don't know if this is a bug or if there's another way to do this

**Comment by lovelydinosaur** [comment]
Can you demonstate the issue more clearly here. Eg. *X* works if the auth backend is not submounted, but behaves differently like *Y* if it is?

Ideally something I can copy-paste and then see the behavior you mean.

Ta! 😄
