### ISSUE TITLE
ci: should only fail if total coverage is < 100%

### ISSUE THREAD

**Issue by blueyed** [Kludex/starlette#519]
https://travis-ci.org/encode/starlette/jobs/534507756 failed for py38 because of coverage being less than 100%.

But coverage should be only 100% across supported envs, i.e. codecov or similar services should report on it, based on all CI environments.

**Comment by lovelydinosaur** [comment]
We shouldn't have code that's version specific any main part of the codebase.
If we *do* need something that's only for a particular python version it should live in a compat.py module, and should be coverage-excluded.

**Comment by blueyed** [comment]
Isn't this just another sacrifice to having "100% coverage"?  It means that you do not see if compat code is used at all (anymore)?

Also it makes https://github.com/encode/starlette/pull/505#pullrequestreview-239255776 fail - although that is more an issue with coverage.py probably, it would still require to add py38 to allowed-failures because of this (if it would be taken as-is that is).

**Comment by lovelydinosaur** [comment]
> means that you do not see if compat code is used at all (anymore)?

Doesn't really crop up no - you'll always have the branch commented as "X for this version Y", and dropping python versions is rare. Been using this policy with django-rest-framework since forever, and it's a nice, neat approach.
