### ISSUE TITLE
[question] Possible to have a path parameter containing '/'?

### ISSUE THREAD

**Issue by seandavi** [Kludex/starlette#525]
I am trying to pass an entire path to a route as a path parameter:

```
app.route('/data/{full_path}')
....
```

If I access `.../data/abc/123/this/that.txt`, I'd like to have `full_path` return `abc/123/this/that.txt`. I didn't start reading source yet (yes, lazy), but I did not see an obvious example or approach in the docs. Is that possible with starlette?

**Comment by euri10** [comment]
You could use url convertor path
https://github.com/encode/starlette/pull/221

**Comment by seandavi** [comment]
Ths, @euri10. I had missed that.
