### ISSUE TITLE
multiple static folders

### ISSUE THREAD

**Issue by ghost** [Kludex/starlette#537]
will it be possible to get multiple folder to deliver static content ? 

eg 

```
app = Router(routes=[
    Mount('/static', app=StaticFiles(directory=['static', '/home/foxmask/static'], packages=['bootstrap4']), name="static"),
])
```
this will allow to avoid 

```
app.mount('/static', StaticFiles(directory="/home/foxmask/static/"))  # use to delivery files
app.mount('/static-css', StaticFiles(directory="static/css"))
app.mount('/static-js', StaticFiles(directory="static/js"))
```

**Comment by lovelydinosaur** [comment]
I *probably* don't want us to add complexity to the existing implementation if we can avoid it.
At the moment you'd need to implement a custom StaticFiles app if you wanted that.

**Comment by lovelydinosaur** [comment]
Would certainly be happy to *consider* a pull request adding support for multiple directories to `StaticFiles`, but I'd rather not consider it a pressing issue unless someone wants to take it on. (And would still need to take a call on the complexity vs. functionality trade-off)

**Comment by ghost** [comment]
OT : i noticed i typo in `get_directories` : 
``` 
Given `directory` and `packages` arugments,
```
should be
```
 Given `directory` and `packages` arguments,
```
I wont open  a PR just for that ;)

**Comment by paulmsmith** [comment]
I could have done with this today too. I thinking a little like the way 'include paths' works in Node Sass, etc
