### ISSUE TITLE
Jinja2Templates tweak

### ISSUE THREAD

**Issue by stuartaccent** [Kludex/starlette#540]
Just thought this would be worth a mention.

Thanks for all your work. 

we have a version of [starlette.templating.Jinja2Templates](https://github.com/encode/starlette/blob/master/starlette/templating.py#L13) with a small tweak. Instead of taking a directory as an argument we are passing an instance of [jinja2.BaseLoader](http://jinja.pocoo.org/docs/2.10/api/#loaders) then we can have one globally defined template var that can utilize many folders/packages/egg's etc and pass it around.

Just incase you like the idea for future.

Cheers, Stu

**Comment by lovelydinosaur** [comment]
Yeah, that's pretty reasonable. At some point we might switch it to accept *either* a `directory` argument, *or* a loader argument. Happy to consider pull requests towards that.
