### ISSUE TITLE
mypy errors when accessing Request.state

### ISSUE THREAD

**Issue by dmontagu** [Kludex/starlette#545]
From https://www.starlette.io/requests/:
> Other state
>
> If you want to store additional information on the request you can do so using request.state.
>
> For example:
>
> request.state.time_started = time.time()

This causes mypy errors since any accessed/set attributes aren't present in the `State` class. As far as I can tell, there isn't a good way to tell mypy to expect certain attributes to potentially be set.

I could imagine solutions that somehow make `Request.state` generic, and those would probably be the most type-safe, but that seems like it would take a lot of work for little gain, and could make the API a little uglier.

As a workaround, I propose adding a `def __getattr__` in an `if typing.TYPE_CHECKING:` block within the class definition. This will silence the mypy errors without changing anything about how the class behaves during runtime.

One counter-argument to this approach would be that this would prevent state attribute accesses from being called out by mypy even if you want the warnings. But then you'd have to add `# type: ignore` to disable it, and would lose any ability to check the continued validity going forward. Given the suggested usage pattern, I just don't see much value to keeping these errors (though I could be convinced otherwise).

Alternatively, the state could be replaced by a `Dict[str, Any]` (or something that behaves more like one anyway), or given one as an attribute.

**Comment by lovelydinosaur** [comment]
I guess we could explicitly add `__getattr__`, `__setattr__`, and `__delattr__` methods, just to signal that it really is just an untyped container object. Any other ways we could achieve that?

> "One counter-argument to this approach would be that this would prevent state attribute accesses from being called out by mypy even if you want the warnings" 

I don't think we'd care about that - it neccessarily needs to be an untyped interface.
