### ISSUE TITLE
BackgroundTasks are not executed concurrently

### ISSUE THREAD

**Issue by patrys** [Kludex/starlette#549]
The mechanism for background tasks works like this:

```python
    async def __call__(self) -> None:
        for task in self.tasks:
            await task()
```

Is this by design? Should this be `asyncio.gather(*[task() for task in self.tasks])`?

**Comment by lovelydinosaur** [comment]
Possibly, yeah. Less sure now that we should have it at all (instead just support a single task, and allow users to deal with whatever subset of stuff they want, within that)

**Comment by patrys** [comment]
I kind of like the control flow it enables where unrelated pieces of code can add their own tasks and then the parent is ultimately responsible for either discarding the entire queue or executing it. An example would be an atomic transaction doing a number of tasks where everything should either fail or succeed atomically.

**Comment by lovelydinosaur** [comment]
Going to close this off - I think it's okay for our default to be the simple (and more reproducible case).
I'd be perfectly happy for us to add a note in the documentation making it clear that the behavior is sequential. (And that users should deal with the concurrency themselves if that's not what they want.)

**Comment by infnetdanpro** [comment]
Only for asyncio I created a custom class `GatherBackgroundTasks`:
```python3
import asyncio

import httpx
from starlette.applications import Starlette
from starlette.background import BackgroundTasks
from starlette.responses import JSONResponse
from starlette.routing import Route

client = httpx.AsyncClient()


async def some_request():
    r = await client.get("https://www.python-httpx.org/")
    return r


class GatherBackgroundTasks:
    def __init__(self, tasks: list | None = None):
        self.tasks = list(tasks) if tasks else []

    def add_task(self, func, *args, **kwargs) -> None:
        self.tasks.append(func(*args, **kwargs))

    async def __call__(self) -> None:
        await asyncio.gather(*self.tasks)


async def test_simple(*_, **__):
    tasks = BackgroundTasks()
    tasks.add_task(some_request)
    tasks.add_task(some_request)
    return JSONResponse({"hello": "world1"}, background=tasks)


async def test_gather(*_, **__):
    tasks = GatherBackgroundTasks()
    tasks.add_task(some_request)
    tasks.add_task(some_request)
    return JSONResponse({"hello": "world2"}, background=tasks)


routes = [
    Route("/simple/", endpoint=test_simple),
    Route("/gather/", endpoint=test_gather),
]

app = Starlette(debug=True, routes=routes)

```

**Comment by vsvn-CuongLD** [comment]
> Only for asyncio I created a custom class `GatherBackgroundTasks`:
> 
> ```python
> import asyncio
> 
> import httpx
> from starlette.applications import Starlette
> from starlette.background import BackgroundTasks
> from starlette.responses import JSONResponse
> from starlette.routing import Route
> 
> client = httpx.AsyncClient()
> 
> 
> async def some_request():
>     r = await client.get("https://www.python-httpx.org/")
>     return r
> 
> 
> class GatherBackgroundTasks:
>     def __init__(self, tasks: list | None = None):
>         self.tasks = list(tasks) if tasks else []
> 
>     def add_task(self, func, *args, **kwargs) -> None:
>         self.tasks.append(func(*args, **kwargs))
> 
>     async def __call__(self) -> None:
>         await asyncio.gather(*self.tasks)
> 
> 
> async def test_simple(*_, **__):
>     tasks = BackgroundTasks()
>     tasks.add_task(some_request)
>     tasks.add_task(some_request)
>     return JSONResponse({"hello": "world1"}, background=tasks)
> 
> 
> async def test_gather(*_, **__):
>     tasks = GatherBackgroundTasks()
>     tasks.add_task(some_request)
>     tasks.add_task(some_request)
>     return JSONResponse({"hello": "world2"}, background=tasks)
> 
> 
> routes = [
>     Route("/simple/", endpoint=test_simple),
>     Route("/gather/", endpoint=test_gather),
> ]
> 
> app = Starlette(debug=True, routes=routes)
> ```

Can you provide an example that describes the improvement in the performance of this method? @infnetdanpro
