### ISSUE TITLE
Allow passing an awaitable as a background task

### ISSUE THREAD

**Issue by patrys** [Kludex/starlette#550]
It would be nice to be able to pass an awaitable instead of a function to `BackgroundTask`. If your code is already async, it would make the API less awkward:

```python

async def some_background_job(foo, bar):
    ...

# current - no autocomplete in IDE
BackgroundTask(some_background_job, 1, 5)

#proposed - autocomplete working as expected
BackgroundTask(some_background_job(1, 5))
```

**Comment by lovelydinosaur** [comment]
I kinda prefer the style you have here, but on the other hand, I *really* want to only use either one or the other, and this wouldn’t support plain callables. Unsure.

**Comment by patrys** [comment]
Hmm... You could allow both coroutines and unparametrized lambdas. The latter still benefit from IDE knowing what function you're calling.

```python
BackgroundTask(lambda: something(1, 2))
```

**Comment by dmontagu** [comment]
For what it's worth, I saw this issue and tried to use this pattern in an unrelated place in my code, and ended up with (in my opinion) a surprising and confusing bug in my code:

```python
[lambda: f(x) for x in args]
```
is actually equivalent to
```python
[lambda: f(args[-1]) for x in args]
```
(when `len(args)` > 0)

Maybe I should have realized this is how lambdas and list comprehensions would work together, but I think this is a pretty subtle point that could easily lead to confusion.

Not sure exactly what the usage pattern would be; if there's no world where someone tries to declare a list of `BackgroundTask` then maybe this is fine. But I think _requiring_ `lambda` for functions taking arguments could be the source of some painful debugging issues. `functools.partial` would prevent this issue, but then you are back to not having IDE assistance.

**Comment by lovelydinosaur** [comment]
Going to leave things as they are for now.
It's functionaly complete, and other approaches would just mean more differing types of style onto the same thing.
