### ISSUE TITLE
Any examples on how to integrate with aiohttp client?

### ISSUE THREAD

**Issue by didip** [Kludex/starlette#553]
I am trying to replace an old Tornado proxy server with combo of Starlette and aiohttp SessionClient.

However I keep getting `raise RuntimeError('Timeout context manager should be used '`

Most examples I see is to use the event loop directly to wait until completion, but I don't think I should do that from inside Starlette's http request handler.

**Comment by lovelydinosaur** [comment]
Early days, but you may want to take a look at https://github.com/encode/http3
You'll need to use [the AsyncClient](https://www.encode.io/http3/async/) (It provides both sync and async interfaces) 

We'll probably end up to moving to that as the test client once it's got support for plugging into WSGI and ASGI apps - https://github.com/encode/http3/issues/49

**Comment by chenglinning** [comment]
i use httpx:
import logging
import uvicorn
import httpx

from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.responses import JSONResponse

async def getbaidu():
    client = httpx.AsyncClient(proxies=None, trust_env=False)
    response = await client.get('https://www.baidu.com/')
    print("OOOKK: {}".format(response))

app = Starlette()
@app.route("/", methods=["GET", "POST"])
async def homepage(request):
    data = await request.json()
    logging.info("method: {} url: {} clientip: {}".format(request.method, request.url, request.client.host))
    logging.info("data type: {}".format(type(data)))
    logging.info("request: {}".format(data))
    await getbaidu()
    return JSONResponse({'hello': 'world'})    

if __name__ == "__main__":
    logging.info("Starting Starlette server!")
    logging.info("Hello world")
    uvicorn.run("myapp:app", host="0.0.0.0", port=8000, reload=True)

**Comment by chenglinning** [comment]
`import logging
import uvicorn
import httpx

from starlette.applications import Starlette
from starlette.responses import PlainTextResponse
from starlette.responses import JSONResponse

async def getbaidu():
    client = httpx.AsyncClient(proxies=None, trust_env=False)
    response = await client.get('https://www.baidu.com/')
    print("OOOKK: {}".format(response))

app = Starlette()
@app.route("/", methods=["GET", "POST"])
async def homepage(request):
    data = await request.json()
    logging.info("method: {} url: {} clientip: {}".format(request.method, request.url, request.client.host))
    logging.info("data type: {}".format(type(data)))
    logging.info("request: {}".format(data))
    await getbaidu()
    return JSONResponse({'hello': 'world'})    

if __name__ == "__main__":
    logging.info("Starting Starlette server!")
    logging.info("Hello world")
    uvicorn.run("myapp:app", host="0.0.0.0", port=8000, reload=True)`
