### ISSUE TITLE
Why request headers is an immutable Mapping but response headers are mutable?

### ISSUE THREAD

**Issue by didip** [Kludex/starlette#554]
The reason why I ask is because request.headers is another convenient place to pass along string data between layers of middleware. E.g.:

* debug strings.

* auth tokens.

You may say, then why not stick them on response.headers? 

I could, But these strings can be considered semi-sensitive and I may not want them to leak back to client (which means I have to delete them in my final request handlers).

**Comment by lovelydinosaur** [comment]
Because request.headers should actually represent the request headers. (Rather than “the request headers, and possibly also arbitrary other stuff”)

The response headers is different, because it makes sense to be able to modify what’s about to be sent.
