### ISSUE TITLE
AuthenticationBackend - requires Failing with "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by mthipparthi** [Kludex/starlette#567]
Issue: requires giving IndexError: tuple index out of range error.
reason : args will not present when we use synchronous decorators
Fix: args, idx wont be avilable in synchronous decorators, it should be removed from that check.

Test Code:
`
@router.post(
    "/v1/ns/user-subscriptions", status_code=HTTP_201_CREATED, response_model=SubscriptionsResponse
)
@requires("authenticated")
def create_subscription(request: Request, l_request: SubscriptionsRequest):
    # validate_auth_token(g_request)

    service = SubscriptionService()
    # service.user_id = get_user_id(g_request)
    service.user_id = "12345"
    service.create(l_request.dict())
    return l_request.dict()
`

**Comment by cesarferradas** [comment]
@mthipparthi getting this error too, did you work around it or do you know if the Starlette maintainers will work on this? If you understand the issue enough to explain it to me, I can make a PR.

**Comment by ethan-fox-capsule** [comment]
@mthipparthi @cesarferradas Make it 3 ... im a little disheartened that I am coming across this issue months down the road and there doesn't seem to be a resolution. Short of copy-pasting the decorator and removing the `.get` default myself, is there a workaround for this?

**Comment by Kludex** [comment]
Is this issue still valid? Can someone confirm?

**Comment by cda2** [comment]
@Kludex Solved after using 0.17.1 version, which #1335 merged.
But when using old versions, still valid. (FastAPI in my case, using 0.16.0)

**Comment by Kludex** [comment]
Thanks :)
