### ISSUE TITLE
Different versions in pypi and here

### ISSUE THREAD

**Issue by em92** [Kludex/starlette#570]
Latest commit: https://github.com/encode/starlette/commit/387a2b87fa4bd78d1c8a041f62cde875ac4d92c0 shows 0.12.1
Latest version in [pypi](https://pypi.org/project/starlette/) 0.12.2

**Comment by lovelydinosaur** [comment]
Thanks. Needed to push my local to master.

**Comment by em92** [comment]
Bump.
Pypi: 0.12.5, https://pypi.org/project/starlette/#history
here - 0.12.4: https://github.com/encode/starlette/blob/master/starlette/__init__.py
