### ISSUE TITLE
Disable BackgroundTasks in tests

### ISSUE THREAD

**Issue by hidalgopl** [Kludex/starlette#578]
Hey!
First of all, thank you for our effort in creating Starlette, so far I'm in love with it.
The issue that I bumped into recently is: I've got an API endpoint which process incoming data, returns response to user and schedules a `BackgroundTask`. Background task calls another web  service in my production cluster. However, I would like to write integration tests for this endpoint (just validate if for request X I'll get Y response), without mocking this another service (or service response).
So I thought it would be great to have flag in config that will prevent executing background tasks during tests.
I'm happy to help & implement this feature. Let me know what you think about it ;)

**Comment by lovelydinosaur** [comment]
See also #533.

I'll close this, and reopen the other instead.
