### ISSUE TITLE
TestClient: store original response?

### ISSUE THREAD

**Issue by blueyed** [Kludex/starlette#584]
I think it is useful to store the response itself in messages during tests, so that the TestClient can put it into the response.

This could be achieved by adding something like `initial_internal_response` with a reference to `self` there for `http.response.start` messages, but should only be done for tests then likely.

It is useful for assertions in tests then, and something that is nice with DRF.

What do you think about this in general?

**Comment by blueyed** [comment]
My use case was asserting properties from the original response, rather than having to assert against (dynamic) logging messages etc.
I think the template rendering could be covered with the same mechanism then - i.e. instead of template/context properties there it could be used via the original response.
Basically making this code unnecessary then: https://github.com/blueyed/starlette/blob/cf9f35d063ef50ee89a338e721e9f37695375c91/starlette/templating.py#L30-L41

But to use this only for debugging the same idea with a extension could be used (e.g. `http.response.debug` or something similar).

**Comment by lovelydinosaur** [comment]
I guess it depends on exactly *what* sort of thing you'd expect to assert against. (Eg. specifically what properties?)

Tests written against the response *as the client sees it* give quite a nice separation as you're more properly testing against the actual interface layer, rather than digging into the implementation itself.

**Comment by blueyed** [comment]
One example would be just the `__class__` / instance itself - which is useful if using different subclasses for different code paths.

I see that it is better to test things end-to-end in general, but this is only meant to be something useful to have on top of that (for more specific / different tests).

**Comment by lovelydinosaur** [comment]
Gotcha. Yeah I don't know really.

Obvs Starlette's sticking to a style that doesn't particularly provide for that. (Prioritize interoperability -> ASGI all the way through -> test client that plugs into ASGI.)

Possibly (?) there's something here that could be worth discussion on the ASGI repo (eg. I've not raised a discussion about the template messaging as an extension yet)
