### ISSUE TITLE
starlette should ignore "inline" comment in env file

### ISSUE THREAD

**Issue by ghost** [Kludex/starlette#585]
Hi,
when using https://www.starlette.io/config/ , if we put 
```
VAR = 'value'   # this var is use for ....
```
we get error related to the expected role of the var.

For example in my case 
```
  File "app.py", line 292, in <module>
    Mount('/files', StaticFiles(directory=settings('JOPLIN_RESOURCES'))),
  File "[...]/lib/python3.7/site-packages/starlette/staticfiles.py", line 55, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/home/foxmask/.config/joplin-desktop/resources/'   # path to get the joplin `resources` to be able to display them' does not exist
```
or if that was for a HTTP port :
```
Traceback (most recent call last):
  File "app.py", line 303, in <module>
    uvicorn.run(main_app, host='0.0.0.0', port=settings('HTTP_PORT', cast=int, default=8001))
  File "[...]lib/python3.7/site-packages/starlette/config.py", line 59, in __call__
    return self.get(key, cast, default)
  File "[...]lib/python3.7/site-packages/starlette/config.py", line 69, in get
    return self._perform_cast(key, value, cast)
  File "[...]lib/python3.7/site-packages/starlette/config.py", line 103, in _perform_cast
    f"Config '{key}' has value '{value}'. Not a valid {cast.__name__}."
ValueError: Config 'HTTP_PORT' has value '8001   # listen port number'. Not a valid int.
```

**Comment by alaminopu** [comment]
@foxmask I was able to re-generate the issue and would like to work on it. 

<img width="996" alt="Screen Shot 2019-08-04 at 3 29 06 PM" src="https://user-images.githubusercontent.com/1296554/62421978-a50a2580-b6cc-11e9-87f3-20eb9c36e41e.png">

**Comment by blueyed** [comment]
So if this is about `.env` files only (not clear from the original issue), I'd say that we should stick to e.g. what Docker uses: https://docs.docker.com/compose/env-file/

As seen in #593 it is not trivial / cannot be split by just "#" (since that can be in the value itself).

Just put the comment(s) above.

**Comment by ghost** [comment]
So let's put comment before the Def of a var.
