### ISSUE TITLE
[question] Example of code registering middleware for a specific routes

### ISSUE THREAD

**Issue by theruziev** [Kludex/starlette#587]
Can anybody show example of registering middleware for a specific routes or mounts?

Thanks

**Comment by theruziev** [comment]
I found the answer myself. You can register middleware for a route by wrapping route's app with middleware like this:


```python
from starlette.applications import Starlette
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import JSONResponse
import uvicorn
from starlette.routing import Router, Route

app = Starlette(debug=True)


class CustomMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        response.headers['Custom-Header'] = 'Example'
        return response


async def homepage(request):
    return JSONResponse({'hello': 'world'})


async def me(request):
    return JSONResponse({'user': 'its me'})


home_route = Route("/", homepage)
home_route.app = CustomMiddleware(home_route.app)

app.mount("/", Router([
    home_route,
    Route("/me", me)
]))

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)

```

@tomchristie  what are you thinking about adding method for registering middleware for Router, Route, Mount?
My use case is registering rate limiter or RequestID for specific groups of endpoints. 
If it's a good idea, I can add a PR for registering middleware for specific routers.

**Comment by mreschke** [comment]
Route specific middleware has always been a requirement for my projects, both web and api based.  Before moving to Python I worked with PHP Laravel for years and their idea of Global, API, Web and Route specific middleware was extremely beneficial.  I will be attempting this in Starlette myself, but it would be ideal if starlette could provide this out of the box.

```
routes = [
    Route("/", endpoint=homepage, middleware=[abc, xyz]),
]
```

Or in you class based endpoints

```
class Homepage(HTTPEndpoint):
   middleware = [abc, xyz]

    async def get(self, request):
        return PlainTextResponse(f"Hello, world!")
```
