### ISSUE TITLE
Bug for set_cookie

### ISSUE THREAD

**Issue by 631068264** [Kludex/starlette#590]
I use 
```python
resp = UJSONResponse(...)
resp.set_cookie('user_token' , 'xx' )
return resp
```

But when I use `TestClient` to test and get cookie 
```python
resp = client.post(url, json={
        ...
    })

assset resp.cookies['user_token'] == 'xx'
```

I get error it's strange   `print(resp.cookies['user_token'])`  I get `'"xx"'`  

How to get a normal result

**Comment by lovelydinosaur** [comment]
Any contributors want to see if they can reproduce this?

**Comment by 631068264** [comment]
`dXNlcuelRe7PI33nGbptHWqwwO3F9JSaM-hGtF0_pLc=`

use `base64.urlsafe_b64encode` create

![image](https://user-images.githubusercontent.com/8144089/62094941-5bc36b80-b2b1-11e9-92d9-ad6f7700896e.png)
![image](https://user-images.githubusercontent.com/8144089/62094968-6847c400-b2b1-11e9-88e9-dfd7079bd7ec.png)

**Comment by 631068264** [comment]
I know why get error  cookie not support base64 `=`

**Comment by pawamoy** [comment]
I have this issue as well.

I have no control over the cookie value, and it contains equal (`=`) signs, which results in it getting enclosed by double-quotes.

Based on https://stackoverflow.com/questions/23392882/must-cookies-have-an-equals-sign, it seems that equal signs are allowed in the cookie value.

The response headers look like `{'set-cookie': 'cookiename="VER=1&CTX=576..."'}`

Then `requests` gives me the following:

```
>>> session.cookies["cookiename"]
'"VER=1&CTX=576..."'
```

and I have to `.strip('"')` it to fix it.

Of course I can remove those quotes on the client-side, but I would prefer not having to.

If I understand [this comment](https://github.com/psf/requests/issues/440#issuecomment-4098685) correctly, "old-style" cookies, using the `Set-Cookie` header, must not be quoted, and "new-style" cookies, using the `Set-Cookie2` headers, must be quoted if they are not valid tokens. Further information says that the Cookie2 spec never caught on, and is now deprecated.

EDIT: anyway the cookie value encoding is done in `http.cookies`: https://github.com/python/cpython/blob/3.8/Lib/http/cookies.py#L161-L183, so Starlette can't do anything here.
