### ISSUE TITLE
Jinja2Templates directory parameter is relative to working directory

### ISSUE THREAD

**Issue by skewty** [Kludex/starlette#595]
From [https://www.starlette.io/templates/](https://www.starlette.io/templates/):
```python
templates = Jinja2Templates(directory='templates')
```
This folder is relative to the working directory.  This could perhaps be more clearly stated in the documentation.  (This caught us off guard when it wasn't working in a dockerized environment)

We fixed it by doing:
```python
templates = Jinja2Templates(directory=__file__[:__file__.rindex('/') + 1] + 'templates')
```
The relative to working directory is unexpected.  Perhaps something like what I have should also be provided in the documentation.

**Comment by ghost** [comment]
thanks buddy!

**Comment by dmontagu** [comment]
@skewty A slightly more platform-independent version (I believe yours would break on windows, for example):
```python
from pathlib import Path

templates = Jinja2Templates(directory=Path(__file__).parent / "templates")
```
(I believe this is equivalent.)

**Comment by lovelydinosaur** [comment]
Happy to accept pull requests improving the docs here - I quite like @dmontagu's approach here.
