### ISSUE TITLE
Debugger content should be escaped

### ISSUE THREAD

**Issue by abersheeran** [Kludex/starlette#599]
![TIM截图20190817000318](https://user-images.githubusercontent.com/25364828/63181405-7f90fa80-c082-11e9-84a2-8e98d05930a3.png)
![TIM截图20190817000415](https://user-images.githubusercontent.com/25364828/63181441-91729d80-c082-11e9-837a-db66b91035f5.png)

**Comment by lovelydinosaur** [comment]
Closed via #601
