### ISSUE TITLE
MyPy conformance

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#6]
There are a few remaining mypy errors that it'd be nice to tidy up...

```shell
$ mypy starlette 
starlette/datastructures.py:148: error: Signature of "get" incompatible with supertype "Mapping"
starlette/datastructures.py:158: error: Argument 1 of "__contains__" incompatible with supertype "Mapping"
starlette/datastructures.py:158: error: Argument 1 of "__contains__" incompatible with supertype "Container"
starlette/testclient.py:114: error: Signature of "request" incompatible with supertype "Session"
```

The datastructures ones really aren't obvious. It may be that they're resolvable but I've not figured out how.

The testclient one we might want to just put an exclude against - otherwise we need to include all of the keyword arguments to request explicitly, rather than capturing them with `**kwargs` and passing them on.

**Comment by marcosschroh** [comment]
I think we have solved some of those, especially the `__contains__` on GH-60.
