### ISSUE TITLE
[question] Recommended way of adding an endpoint in Middleware

### ISSUE THREAD

**Issue by invokermain** [Kludex/starlette#605]
Hi I am trying to make my own middleware class to handle open id connect flow. I was wondering if there is a recommended way of adding a GET endpoint in the middleware class so that when you add the middleware to the app it registers the end point to the router?

Currently it seems possible by accessing the app with self.app.app where self.app is the exceptionmiddleware, but this feels hacky.

Any thoughts?

**Comment by lovelydinosaur** [comment]
If you want to do this in middleware, then I'd just inspect the URL path and method of the request (rather than adding it to the URL routes).

Alternately, provide both a middleware implementation, and an endpoint, and document how to add both in order to install open id connect support.

**Comment by invokermain** [comment]
Thanks Tom, inspecting the request URL makes sense.
