### ISSUE TITLE
Response Handler

### ISSUE THREAD

**Issue by dgrahn** [Kludex/starlette#606]
I have a case where I'd like to do the following.

```py
@app.on_event('response')
def response_handler(response):
    return JSONResponse(response[1], status_code=response[0])

@app.route('/')
def root(request):
    return 200, { 'hello': 'world' }
```

Is this sort of response handler possible?

**Comment by lovelydinosaur** [comment]
No, there's nothing like that available.
You'll need to return response instances from endpoints.

**Comment by lovelydinosaur** [comment]
Not currently, no. I think it's a reasonable design constraint for us to impose, in order to provide consistency.
