### ISSUE TITLE
Mounted App does not Pass Exceptions to Parent

### ISSUE THREAD

**Issue by dgrahn** [Kludex/starlette#607]
I have the following code.

```py
app = Starlette()
service = Starlette()

@app.exception_handler(500)
def handle(request, exc):
  # Do something

app.mount('/service', service)
```

The exceptions should be handled by the parent app... but they are not.

**Comment by lovelydinosaur** [comment]
You're mouting a full starlette application there, which means that the exceptions will be handled by the child, and the parent will just "see" a valid 500 response.

You probably want to just be submounting a router instance instead. (And leave all the exception handling to the top level)
