### ISSUE TITLE
Response that returns a Zip file?

### ISSUE THREAD

**Issue by hrtejada** [Kludex/starlette#609]
Is it possible to send a zip file as an attachment in a response? Looked through the starlette's response library but could not figure out a way to do this. My initial feeble attempt at making this work was using the Response object, specifying the media_type as 'application/zip' and passing the zipped I/O buffer in the content...normally in Flask I would do something like:

```
response_obj = Response(zipped, mimetype='application/zip', headers={
            'Content-Disposition': 'attachment;filename=api.zip'
            })
return response_obj
```

Where zipped was of type io.BytesIO(). Is something like this possible using Starlette's responses?

**Comment by euri10** [comment]
I would look at https://www.starlette.io/responses/#fileresponse but never tried with zip files

**Comment by lovelydinosaur** [comment]
FileResponse, yup
