### ISSUE TITLE
Application State

### ISSUE THREAD

**Issue by elyobo** [Kludex/starlette#612]
It's now possible to store [arbitrary state](https://www.starlette.io/requests/#other-state) on requests (via https://github.com/encode/starlette/pull/404); it would be great to be able to store arbitrary application state on the application and have it available in requests as well.

It seems common to use globals to configure things (e.g. [have a `settings.py` somewhere that's imported all over a project](https://www.starlette.io/config/#a-full-example)), but this seems far less sane (especially for tests, where you might want to verify various different settings) than providing configuration to your application and accessing it from there.

https://github.com/encode/starlette/issues/64 provides a useful point at which state could be attached, potentially, if only there was somewhere to put it like the request state.

What I have done for the moment is to use middleware to wrap up the things that I want to share with all requests and inject that in to the request state instead; it's an acceptable workaround for me, but if I was adding state in the lifecycle hooks I'd have to add the middleware there as well and it starts to get pretty messy.

example

```python
from myproject import settings
@app.middleware('http')                                                      
async def provide_request_settings(request: Request, call_next):
  """Injects settings in to all requests"""                                  
  request.state.settings = settings
  return await call_next(request)                                         
```

**Comment by octopoulpe** [comment]
Hi. Very personal opinion coming here.

I think your middleware is exactly what needs to be done. I do not think it is a workaround as global variables/states should be made local as soon as you go down in your application scope and business modules.

That way you can manage your own state lifecycle in your main application file (with big responsibilities), and treat these variables as stateless local variables in your business methods/modules.

I also think that lifecycle hooks should be centralized in your main file, by calling methods of your submodules explicitly (with control over arguments and order), rather than using @on_event everywhere in your submodules. That way the workflow is explicit and anybody that reads your application main file is able to understand it.

Also, as you say, an external file imported everywhere with a shared state IS a workaround.

**Comment by elyobo** [comment]
I think we largely agree.

> I think your middleware is exactly what needs to be done.

Yes, it's totally fine for this trivial example.

> Also, as you say, an external file imported everywhere with a shared state IS a workaround.

It is, but it's not a good one, and one with major problems for testing - I prefer to keep things as contained as possible and pass in all dependencies instead of reaching out and grabbing globals all over the place.

> I also think that lifecycle hooks should be centralized in your main file, by calling methods of your submodules explicitly (with control over arguments and order), rather than using @on_event everywhere in your submodules.

Absolutely agreed also; but the lack of application state makes this worse.

For example, I use `asyngpg` with a connection pool.  The pool is created in an @on_event, but then I have to provide that pool to handlers somehow, so I have to add middleware in the `@on_event` once the pool is available.  To me, it would be clearer if I just added my middleware, which would pull the pool from the application state (if available), and the @on_event created the pool and added it to the application state.

**Comment by octopoulpe** [comment]
> For example, I use `asyngpg` with a connection pool. The pool is created in an @on_event, but then I have to provide that pool to handlers somehow, so I have to add middleware in the `@on_event` once the pool is available. To me, it would be clearer if I just added my middleware, which would pull the pool from the application state (if available), and the @on_event created the pool and added it to the application state.

I would have made something in the main application file, using the global :

```
myapp_state = {}  # application store

@app.on_event("startup")
def startup():
    myapp_state["pg_pool"] = my_pg_module.get_pool(settings)
    myapp_state["http_cli_ua"] = other_submodule.get_ua(settings)
    # you can even use your pg pool and http cli during state mutations
    myapp_state["useful_data"] = another_module.get_specifics(app_state)

# here you could manage other @app.on_event or even other event types

@app.middleware('http')                                                      
async def state_injector(request, call_next):                          
  request.state.app_state = myapp_state
  return await call_next(request)
```

If your state is a much more complicated thing (that would not fit in a main.py), then it would be a good idea to manage it in a dedicated module, maybe using some state machine tools or redux-like stores. That way your business modules would provide tooling for the state management but would not manage state on their own, ensuring decoupling.

**Comment by elyobo** [comment]
Thanks @tomchristie, that's aweseome - although I have to admit that @octopoulpe was half bringing me around to their point of view :sweat_smile: 

Having application state available is handy, but it's still hard to get at - middleware and endpoints get the requests, but they don't get the application.  We can use a closure to provide access to it as per octo's example, e.g. as follows, but it would also be handy if the app (or app state) was accessible directly already (e.g. [expressjs](https://expressjs.com/en/api.html#req.app) provides the app on each request, with [app.locals](https://expressjs.com/en/api.html#app.locals) being the equivalent to the new `app.state`, so anything that can access a request can access the application and therefore the application state).

```
app = Starlette()
app.state.ADMIN_EMAIL = 'admin@example.org'

@app.middleware('http')                                                      
async def state_injector(request, call_next):                          
  request.state.app_state = app.state
  return await call_next(request)

# OR just provide the whole app
@app.middleware('http')                                                      
async def app_injector(request, call_next):                          
  request.state.app = app
  return await call_next(request)
```

**Comment by em92** [comment]
> it's still hard to get at - middleware

Have you tried `request.app.state`?

**Comment by elyobo** [comment]
No I have not 😂 If it's that simple then perfect.

**Comment by elyobo** [comment]
@em92 I had tried looking at the [request docs](https://www.starlette.io/requests/) though and the ability to access the application via the request is not mentioned there.  I can see that `HTTPConnection`, which `Request` is a subclass of, does provide access to it though.

I'll open a PR for the a doc change :)
