### ISSUE TITLE
Question regarding sync code in Starlette App

### ISSUE THREAD

**Issue by rwboyer** [Kludex/starlette#616]
I've started experimenting with moving services from Flask over to ASGI specifically using starlette. I've got a few services up and running in production but I'm looking for what the consensus is on running sync code/packages inside a starlette app. Things like replacing the requests package with httpx are simple and make sense. Other things not so much.

I've looked a lot of places but not really found a definitive best practice. It boils down to this...

Assuming in real world apps for at least the time being it's useful to use stable well tested sync packages for some things is the best way to do this:

A) make all routes async and then use Starlette.concurrency and await run_in_threadpool(compute, *args, **kwargs) to run a set of sync code or...

B) make the route sync but then what is the best way to use Starlette request/response routines?

C) Something completely different?

Thanks.

**Comment by dmontagu** [comment]
I'm also curious about this. My current "flowchart" is:

1. Prefer async routes wherever possible, unless I need to make use of a sync package (e.g., sqlalchemy ORM, though I'm using encode/databases as much as possible these days).
2. If I need to have blocking io anywhere in the call, try to just make it a sync route
3. If I need to have blocking io AND make use of an async call/functionality in the same route, manually handle it using `run_in_threadpool`.

I'd be interested if anyone else has a different convention.

**Comment by lovelydinosaur** [comment]
@dmontagu's approach here is about what I'd go for, yup.

> make the route sync but then what is the best way to use Starlette request/response routines?

Yeah right now we don't have a great answer to that. A future version *could* tweak the request body handling so that by default it'll get streamed prior to being passed to the endpoint. That way we could just introduce plain sync properties for accessing it. (I think that's the only bit of i/o on the request that you might need to access)
