### ISSUE TITLE
CORSMiddleware and HTTPExceptions from other middleware

### ISSUE THREAD

**Issue by hongymagic** [Kludex/starlette#617]
`CORSMiddleware` decorates given response with CORS headers - and this works fine if you're raising exceptions from the route handlers. However, if you use it with things like `AuthenticationMiddleware` (or any other middleware installed globally to perform, ...well global tasks) do not include these CORS headers.

Here's an example:

```python
from starlette.applications import Starlette
from starlette.authentication import AuthenticationBackend, AuthenticationError
from starlette.exceptions import HTTPException
from starlette.middleware.authentication import AuthenticationMiddleware
from starlette.middleware.cors import CORSMiddleware
from starlette.responses import JSONResponse

import uvicorn


class DumbAuthBackend(AuthenticationBackend):
    async def authenticate(self, request):
        raise AuthenticationError("You will never be authenticated!")


app = Starlette(debug=True)

# Expect all responses to contain CORS headers
app.add_middleware(CORSMiddleware, allow_origins=["*"])

# Global authentication
app.add_middleware(AuthenticationMiddleware, backend=DumbAuthBackend())

@app.route('/')
async def index(request):
    return JSONResponse({"hello": "world"})

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)
```

In this case, `GET /` won't include CORS headers and the response from the `AuthenticationMiddleware` cannot be read. This is true of any other middleware that comes after `CORSMiddleware` that raise `HTTPException`. So what is installed to be _applied across your entire application_ (quoted from Starlette website) is not.

Should CORS header be applied here without extra code?

**Comment by lovelydinosaur** [comment]
Requests with authentication errors probably shouldn't have CORS headers applied.

> This is true of any other middleware that comes after CORSMiddleware that raise HTTPException

Middleware should return responses rather than raise exceptions. This helps ensure thant middleware implementations can be used across any ASGI application, and keeps the exception handling behavior more clear. (HTTPException is only caught by endpoints, not from other middleware.)

**Comment by thomasleveil** [comment]
Just put the CORSMiddleware around the starlette app and you will be fine

```python
from starlette.applications import Starlette
from starlette.authentication import AuthenticationBackend, AuthenticationError
from starlette.exceptions import HTTPException
from starlette.middleware.authentication import AuthenticationMiddleware
from starlette.middleware.cors import CORSMiddleware
from starlette.responses import JSONResponse

import uvicorn


class DumbAuthBackend(AuthenticationBackend):
    async def authenticate(self, request):
        raise AuthenticationError("You will never be authenticated!")


app = Starlette(debug=True)

# Global authentication
app.add_middleware(AuthenticationMiddleware, backend=DumbAuthBackend())

@app.route('/')
async def index(request):
    return JSONResponse({"hello": "world"})

if __name__ == '__main__':
    uvicorn.run(
        CORSMiddleware(app=app, allow_origins=["*"]),
        host='0.0.0.0',
        port=8000
    )
```
