### ISSUE TITLE
How to add routes from modules?

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [Kludex/starlette#631]
I have a package called `views` inside which I have separated modules for each resource, for example, I have a module called `users.py` which imports the `app` instance from top-level package and using `@app.route("/{some_variable}")` decorator I have a `class User(HTTPEndpoint)`

I am also importing the module into my `app.py` but the route doesn't seem to be registered. Am I missing something?

```
.
├── app.py
└── views
    ├── __init__.py
    └── users.py
```

**Comment by narzeja** [comment]
Sounds like your users.py never get imported, which would also cause circular imports.
You can use this approach instead, where you mount the endpoints from app.py:

```python
# inside users.py

async def add_user():
    ...

async def delete_user():
    ...
```

```python
# inside app.py
from starlette.applications import Starlette
from views import users

app = Starlette()

app.add_route('/users/add', endpoint=users.add_user, methods=['POST'])
app.add_route('/users/delete', endpoint=users.delete_user, methods=['DELETE'])
```

Or you can use a submounted application, where in your `users.py` you instantiate a Router object where you mount your user methods, then mount that inside your `app.py`, as described here: https://www.starlette.io/routing/

**Comment by lovelydinosaur** [comment]
Closing this off, since our docs from 0.13 are now much better at walking through mounted routes etc... (And I think the new routing style is much clearer for these cases too)

https://www.starlette.io/routing/
