### ISSUE TITLE
RedirectResponse http method leakage?

### ISSUE THREAD

**Issue by wshayes** [Kludex/starlette#632]
I had a case where I was redirecting from a POST /token endpoint to the GET /docs endpoint. The redirectresponse `response = RedirectResponse(url=redirect_url)` was using the same http method POST for the redirect url /docs as was used for the /token endpoint.  After adding another decorator for @router.post("/docs") to the endpoint (in addition to @router.get("/docs"), it started working again.  Without it, I was getting the '405 Method not allowed' error. I didn't see any way of setting the method in the RedirectResponse. 

Starlette == 0.12.7  (FastAPI 0.36.0)

**Comment by dmontagu** [comment]
It looks like the behavior is actually determined by the client based on the response code:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections#Temporary_redirections

Note this line:
> The specification had no intent to allow method changes, but practically there are user agents out there doing this. 307 has been created to remove the ambiguity of the behavior when using non-GET methods.

So it sounds like 307 (the default response code) is supposed to explicitly indicate "don't change the method", whereas 303 (and maybe 302) can indicate that the method should be converted to a `GET` (and the body dropped).

I'm not sure what kind of client you are using (a browser?) but try setting the `status_code` in the `RedirectResponse` to `303` (or `starlette.status.HTTP_303_SEE_OTHER`) and see if it gives you the behavior you want. If that doesn't work, it's probably best to use `@router.api_route("/docs", methods=['GET', 'POST'])` over `@router.get` or `@router.post` individually (given that you are using fastapi).

At any rate, it seems like this is probably not something starlette is really capable of controlling under the HTTP protocol, but is instead determined by the user agent.

**Comment by wshayes** [comment]
@dmontagu  Thanks for the suggestion - it's happening in the browser. I secure my API documentation and in going from the /login (GET), to the /token endpoint (POST), to the redirected /docs (should be a GET but is a POST) it gets a little weird.

I tried setting it to a 303 status_code, but that didn't change anything. It's working for me with the additional @router.post() decorator so I'll close this out since it's not something Starlette handles.

**Comment by steflsd** [comment]
I had this same issue, but using <code>return RedirectResponse(url="/keys", status_code=303)</code> it redirected with a GET
