### ISSUE TITLE
TestClient: allow to change raise_server_exceptions on instance

### ISSUE THREAD

**Issue by blueyed** [Kludex/starlette#637]
Currently you have to use `client.adapter.raise_server_exceptions = False`.

I think it would be better to allow for `client.raise_server_exceptions = False`.

This could be achieved by passing the client into adapter, instead of the app.

(Since this is likely to cause conflicts with https://github.com/encode/starlette/pull/505 I'd like to get some feedback first)

**Comment by lovelydinosaur** [comment]
Closing as stale.
