### ISSUE TITLE
[question] production configuration of gunicorn

### ISSUE THREAD

**Issue by sandys** [Kludex/starlette#642]
hi guys,
so i am looking to go to production using starlette or a derivative of starlette (fastapi,etc).

I'm looking at this as my starting script for a production configuration of gunicorn - https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/python3.7/gunicorn_conf.py

is this good enough ? I'm not sure if i should be using threads (because of the async nature of starlette) or other gunicorn configs

On reading documentation of gunicorn with uvicorn, there are lines like this

> "Gunicorn provides a different set of configuration options to Uvicorn, so some options such as --limit-concurrency are not yet supported when running with Gunicorn"

This is for a medium-high traffic site. any help would be much appreciated.

**Comment by lovelydinosaur** [comment]
Seems perfectly reasonable yup.

I reckon we'll probably start to just recommend running uvicorn on it's own at some point, but provide the Gunciron worker classes as a third party option. https://github.com/encode/uvicorn/issues/517#issuecomment-564090865
