### ISSUE TITLE
Improved RBAC support for authentication.requires

### ISSUE THREAD

**Issue by WillNye** [Kludex/starlette#643]
The requires scope uses an all check which can be problematic for certain endpoints using RBAC. This is because for endpoints where, say, Data-Science and Sales both have access it can start to get complicated. I wrote this and am currently using it as a solution. It's backward compatible. I would've forked and made a PR but I'm not in it for the glory hah

```
import asyncio
import functools
import inspect
import typing

from starlette.exceptions import HTTPException
from starlette.requests import HTTPConnection, Request
from starlette.responses import RedirectResponse, Response
from starlette.websockets import WebSocket


def has_required_scope(conn: HTTPConnection, scopes: typing.Sequence[str], match_all: bool = True) -> bool:
    if match_all:
        return all(scope in conn.auth.scopes for scope in scopes)
    else:
        return any(scope in conn.auth.scopes for scope in scopes)


def requires(
    scopes: typing.Union[str, typing.Sequence[str]],
    status_code: int = 403,
    redirect: str = None,
    requires_all: bool = True
) -> typing.Callable:
    scopes_list = [scopes] if isinstance(scopes, str) else list(scopes)

    def decorator(func: typing.Callable) -> typing.Callable:
        type = None
        sig = inspect.signature(func)
        for idx, parameter in enumerate(sig.parameters.values()):
            if parameter.name == "request" or parameter.name == "websocket":
                type = parameter.name
                break
        else:
            raise Exception(
                f'No "request" or "websocket" argument on function "{func}"'
            )

        if type == "websocket":
            # Handle websocket functions. (Always async)
            @functools.wraps(func)
            async def websocket_wrapper(
                *args: typing.Any, **kwargs: typing.Any
            ) -> None:
                websocket = kwargs.get("websocket", args[idx])
                assert isinstance(websocket, WebSocket)

                if not has_required_scope(websocket, scopes_list, requires_all):
                    await websocket.close()
                else:
                    await func(*args, **kwargs)

            return websocket_wrapper

        elif asyncio.iscoroutinefunction(func):
            # Handle async request/response functions.
            @functools.wraps(func)
            async def async_wrapper(
                *args: typing.Any, **kwargs: typing.Any
            ) -> Response:
                request = kwargs.get("request", args[idx])
                assert isinstance(request, Request)

                if not has_required_scope(request, scopes_list, requires_all):
                    if redirect is not None:
                        return RedirectResponse(url=request.url_for(redirect))
                    raise HTTPException(status_code=status_code)
                return await func(*args, **kwargs)

            return async_wrapper

        else:
            # Handle sync request/response functions.
            @functools.wraps(func)
            def sync_wrapper(*args: typing.Any, **kwargs: typing.Any) -> Response:
                request = kwargs.get("request", args[idx])
                assert isinstance(request, Request)

                if not has_required_scope(request, scopes_list, requires_all):
                    if redirect is not None:
                        return RedirectResponse(url=request.url_for(redirect))
                    raise HTTPException(status_code=status_code)
                return func(*args, **kwargs)

            return sync_wrapper

    return decorator
```

Example:
```
@app.route('/v1/customer/{customer_id}/reports/unique-files')
@requires(['DataScience', 'Manager', 'Sales'], requires_all=False)
async def unique_file_report(request):
```

**Comment by josh-stableprice** [comment]
This seems like a short sighted change, something like the following would be leaps and bounds better, supporting arbitrarly complex permissions setups.

```
@app.route('/v1/customer/{customer_id}/reports/unique-files')
@requires(And('Manager', Or('DataScience', 'Sales')))
async def unique_file_report(request):
```

**Comment by lovelydinosaur** [comment]
The general approach I'd like us to switch to is:

* one or more required scopes associated with endpoints.
* programmatic controls (or third party permissioning APIs) for anything else.

The benefits of keeping the built-in system really simple is that it'll map well onto OpenAPI schemas, and also onto standard UIs for granting particular scopes with API tokens.

I think we *probably* want to acutally build that into the routing API itself, so that we can expose an API for the routing table, complete with associated permission scopes.

You *can* still have as much fine grained permissioning control as needed, either by:

1. Ensuring that the authentication layer deals with granting scopes `And('Manager', Or('DataScience', 'Sales'))` ---grants--->  'file-reports'
2. Third party options that provide more complex interfaces such as `@requires(And('Manager', Or('DataScience', 'Sales')))` but that are not exposed in the routing table.
3. Custom logic in the endpoints (required eg. to deal with object-based permissions.)

**Comment by WillNye** [comment]
@tomchristie and @josh-stableprice The variable name could/should probably be different but adding this allows you to create those complex scopes with minimal updates to code. Maybe I misinterpreted the documentation but isn't something like this example a realistic scenario? It's an alternative to the `And('Manager', Or('DataScience', 'Sales'))` by grouping the And/Or into their own decorator.

```

app = Starlette(debug=True)
app.add_middleware(AuthenticationMiddleware, backend=CustomAuthBackend())


@app.route('/example')
@requires('Manager')
@requires(['DataScience', 'Sales'], requires_all=False)
async def example_route(request):
    pass 

```

**Comment by yackx** [comment]
Reviving this thread. The approach proposed by @josh-stableprice is more flexible, and the added suggestions by @tomchristie would make it close to a comprehensive solution.

However, there is simplicity in @WillNye proposition. IMHO there is a low hanging fruit waiting to be grabbed with `requires_all=False` - tiny modification and backward compatibility.

Food for thoughts: the "any scope" approach, as opposed to "all scopes", is how Spring Security `@Secured` [annotation](https://www.baeldung.com/spring-security-method-security) work. Quoting anything from the Java world here may not be the best strategic move to retain credibility, but I believe they got that one right. 🙂

I would certainly assist @WillNye in a PR. It would not preclude a more advanced solution in the future. But the more comprehensive solution seems like a daunting task.

**Comment by adriangb** [comment]
I have implemented in the past an interface that looks something like

```python
class AuthPredicate(Protocol):
    def __call__(self, user: User, creds: AuthCredentials) -> bool:  ...

class AuthCheck(AuthPredicate):
    def __init__(self, predicate: AuthPredicate):
        self.predicate = predicate

    def __call__(self, user: User, creds: AuthCredentials) -> bool:
        return self.predicate(user, creds)
    
    def __or__(self, other: AuthPredicate) -> AuthCheck:
        return AuthCheck(lambda user, creds: self(user, creds) or other(user, creds))

   # implement xor, etc.

def requires(predicate: AuthPredicate):
     # decorator, FastAPI dependency or other to actually enforce the predicate
```

And then some helpers like:

```python
def AllScopes(*scopes: str) -> AuthCheck:
    scopes = set(scopes)
    return AuthCheck(lambda user, creds: scopes.issubset(creds.scopes))
```

The big advantage here is that you can easily chain and compose these like:

```python
@requires(AllScopes("read", "write") | (AnyScope("admin", "manager") & lambda *ignore: is_tuesday()))
```

Also this supports arbitrary predicates, e.g. my org sometimes checks email domains for authentication. `is_tuesday()` is just an absurd example of this.

Maybe it's too complicated. But maybe it's nice. I think it's more flexible and composable than adding an extra `all` parameter. Just throwing it out there.

**Comment by adriangb** [comment]
> The general approach I'd like us to switch to is:
> 
> * one or more required scopes associated with endpoints.
> * programmatic controls (or third party permissioning APIs) for anything else.

This seems very sensible. Auth can be arbitrarily complex, but that can't be expressed declaratively in something like OpenAPI. So it makes sense that there's a "declarative" level that interacts w/ the routing table and such, and another "programmatic" layer that holds any more advanced auth logic.

Let me know if this is in line with what you were thinking @tomchristie 

One thing I am not sure of is: should the declarative layer serve only for documentation / routing purposes, or should those scope requirements also be enforced (perhaps they are enforced as part of routing)?

**Comment by taybin** [comment]
I think if we were just able to pass in our own `has_required_scope()` to requires, that would open up a lot of flexibility.

**Comment by lovelydinosaur** [comment]
> This seems very sensible. Auth can be arbitrarily complex, but that can't be expressed declaratively in something like OpenAPI. So it makes sense that there's a "declarative" level that interacts w/ the routing table and such, and another "programmatic" layer that holds any more advanced auth logic.

Exactly yes.

> should the declarative layer serve only for documentation / routing purposes, or should those scope requirements also be enforced

If we *did* do something here, then we'd also want to enforce it yes.

However I wouldn't want us to consider anything here until we feel like the issue backlog is *very much in hand*. Let's keep the focus right now on stability, bug-fixes, and getting everything to a really nicely sustainable workflow.

**Comment by erichaus** [comment]
Any update on this? I need to implement `@requires(Or('vendor', 'manufacturer'))` and not sure how to do it?
