### ISSUE TITLE
FileResponse: RuntimeError: File at path {self.path} does not exist when Dockerized?

### ISSUE THREAD

**Issue by scheung38** [Kludex/starlette#646]
from flask import send_from_directory
 send_from_directory(".", "my-api.yaml")

How to replace this in Starlette thanks

**Comment by theruziev** [comment]
Two way of doing this:
1. Define [StaticFiles](https://www.starlette.io/staticfiles/) in route.
2. Return [FileResponse](https://www.starlette.io/responses/#fileresponse) in handler

**Comment by scheung38** [comment]
@theruziev thanks FileResponse works in local machine but not when Dockerized?

this is my main.py

```
@app.get("/definition"):
async def get_yaml():
    return FileResponse("my-api.yaml")

if __name__ == "__main__":
    uvicorn.run(app, host='0.0.0.0', port=9000)
```

where my-api.yaml is also in same directory as main.py


this endpoint runs when running locally on port 9000 via Right Click PyCharm

http://localhost:9000/definition

Dockerfile:
```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

WORKDIR /app/

ENV HOME /root

COPY requirements.pip ./

ENV PYTHONPATH=/app

COPY pip.conf /root/.pip/pip.conf

RUN pip install -r requirements.pip

EXPOSE 8000

COPY . /app

EXPOSE 80
```


But after 

docker build -t my-api .

docker run --rm -d -it -p 8000:80 my-api:latest

my other endpoints (i.e returning simple {"hello": "world"}, not shown) work as expected but this endpoint returning FILEResponse:

http://localhost:8000/definition

RuntimeError: File at path {self.path} does not exist

I know that the fastapi auto-generates endpoint whether dockerized or not, the endpoint http://localhost:8000/openapi.json and maybe better approach but in order not the change existing /definition endpoint, like to know why the dockerized app returns File not found error as above.

**Comment by theruziev** [comment]
Hi @scheung38 
When you write only filename without path, python use relative path and append filename regarding where you run script. 
You said my-api.yaml in the same folder as main.py, we can find folder of main.py and append filename.
Please check this example below:
```python

import os
import uvicorn
from starlette.applications import Starlette
from starlette.responses import FileResponse


app = Starlette()
app.debug = True

app = Starlette(debug=True)


@app.route("/definition")
async def get_yaml(request):
    dirname = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__))))
    return FileResponse(f"{dirname}/my-api.yaml")


if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8000)
```

**Comment by KaranTrivedi** [comment]
Hello, I got this working as a function in a fastapi app, but when I go to DL files, they show up as "download" for the name of the file. How can I pass the filename to the download? Here is what my sample function looks like .. 

```
@app.get("/shows/")
async def get_items(q: List[str] = Query(None)):
    '''
    Pass path to function.
    Returns folders and files.
    '''

    results = {}

    query_items = {"q": q}
    if query_items["q"]:
        entry = PATH + "/".join(query_items["q"])
    else:
        entry = PATH

    if os.path.isfile(entry):
        logger.info(entry)
        return FileResponse(entry)

    dirs = os.listdir(entry + "/")
    results["folders"] = [
        val for val in dirs if os.path.isdir(entry + "/"+val)]
    results["files"] = [val for val in dirs if os.path.isfile(entry + "/"+val)]
    results["path_vars"] = query_items["q"]

    return results
```

**Comment by aminalaee** [comment]
@florimondmanca @Kludex I think this isn't really related to Starlette. Do you think it can be closed?

**Comment by Kludex** [comment]
This is already replied by @theruziev (thanks) :)

We can close it.
