### ISSUE TITLE
Organizing the view models in different modules/directories

### ISSUE THREAD

**Issue by sudhakar-datta** [Kludex/starlette#648]
How to have the equivalent blueprint concept in flask? I have 5 different feature set which needs to reside in its own modules (which in turn have the views, models and helpers). How to mimic this in starlette.

It would be also nice to have an example of how to tie this up with hypercorn.

**Comment by prostomarkeloff** [comment]
Hello! Maybe [routers](https://www.starlette.io/routing/) can help you?

**Comment by lovelydinosaur** [comment]
As @prostomarkeloff notes, submounting routers is one good way to split out functionality, into something similar to Django Apps / Flask Blueprints.
