### ISSUE TITLE
Multiple headers of the same name

### ISSUE THREAD

**Issue by nhumrich** [Kludex/starlette#650]
HTTP spec allows multiple headers of the same key to be present. This is why libraries such as h11 accept a list of headers instead of dictionaries. 

[HTTP 1.1, section 4.2](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

Currently starlette dosen't support this because it is just running `value.encode()` on the value in the header. 

I propose that the header dictionary be able to contain lists as values as well, in which case starlette will add a header for each value. 
This is most common when using the `set-cookie` header, when a backend wants to add multiple cookies, but not have the one header exceed too big of an individual header length. 

for example:
```
headers = {'mykey': ['value1', 'value2']}
```

would produce the following headers:

```
mykey: value1
mykey: value2
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/650">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/650/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/650/pledge.svg">
</picture>
</a>

**Comment by nhumrich** [comment]
This is especially important for the `set-cookie` header. There are two ways to set headers of the same key in `HTTP`. First, is listing the header twice, as shown above, the second way is to comma seperate the values, i.e.

```
mykey: value1,value2
```

Google Chrome however does not respect this way of setting headers, at least not for the `set-cookie` directive. So without a fix to this api, you cant set more than one cookie with google chrome. 
Its worth noting that firefox handles comma separated cookies just fine.

**Comment by lovelydinosaur** [comment]
`.append()` can be used to append headers, even when there's a duplicate present.

But yes, interesting idea wrt. list-of-values. Not sure how I feel about that, or if we instead ought to support *either* a mapping *or* a list of items, and use the list-of-items case for when we want duplicate entries.

Are you running into this issue in practice, or is it something you spotted?

**Comment by nhumrich** [comment]
I am running into this in practice. I am currently monkey patching starlette to apply this patch to workaround it. 
> we instead ought to support either a mapping or a list of items
If you look at my PR, that is how I implemented it.

**Comment by lovelydinosaur** [comment]
With `Set-Cookie` or some other header? Are you able to use `.headers.append()`?
What does you patch look like?

**Comment by nhumrich** [comment]
I believe `.headers.append()` will solve the issue. Didn't realize it existed. Thanks.

**Comment by cp-weng-tkspring** [comment]
Not working in 2023

**Comment by dmvieira** [comment]
not working here too... Should reopen?

**Comment by zanieb** [comment]
@dmvieira can you please provide a reproducible example and include the version you are using?
