### ISSUE TITLE
`url_for` for static files from a sub-application gives NoMatchFound error

### ISSUE THREAD

**Issue by loek17** [Kludex/starlette#654]
Example
```
import uvicorn

from starlette.applications import Starlette
from starlette.staticfiles import StaticFiles
from starlette.responses import PlainTextResponse

app1 = Starlette()
sub_app = Starlette()

sub_app.mount('/static', StaticFiles(directory='/static/subapp', check_dir=False), name='static')
app1.mount('/subapp', sub_app, name='index')

@sub_app.route('/test', name='index')
def test(request):
    return PlainTextResponse(request.url_for('index:static', path='/js/file.js'))

def main(args):
    uvicorn.run(app1, host="0.0.0.0", port=5000, debug=True, access_log=True)

if __name__ == '__main__':
    main(sys.argv[1:])

```

Expected result
`/subapp/static/js/file.js`

Result
`starlette.routing.NoMatchFound`

The `path` kwarg seens to be the problem, this is set to "" in the `Mount.url_path_for` but not set back on the `remaining_params`

**Comment by lovelydinosaur** [comment]
I'd suggest using a `Router()` instance for subapps, rather than a `Starlette()` instance.

You only want the exception middleware that a `Starlette` app includes to run at the very top-layer of everything else. We could do with some better documentation about subapps tho.
