### ISSUE TITLE
websockets.exceptions.ConnectionClosedError: code = 1006 

### ISSUE THREAD

**Issue by rlewkowicz** [Kludex/starlette#655]
My uvicorn process keeps dying with:
```
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```
I'm using "fastapi" (https://github.com/tiangolo/fastapi) which is built on starlette and uses the starlette websocket.

To send my data, I'm using the python websockets library (as I don't think starlette can establish the initial connection). I'm sending data in a while loop at about 10ms intervals. I even tried setting up a socket ping.

Is there a way to just tell the socket to stay open indefinitely with no timeout?

**Comment by rlewkowicz** [comment]
I switched to hypercorn and my problems went away

**Comment by rlewkowicz** [comment]
The issue it turns out, did not go away. Nothing is hanging up. I'm blasting msgpacked numpy arrays though the sockets and its working very well until it abruptly hangs up. I'm not sure what to do.

**Comment by rlewkowicz** [comment]
So im wrong again. Problem was there's a library called websocket. You dont want that. You want websockets

**Comment by vlori2k** [comment]
Did you solve this? Did it work with hypercorn?

If so, how do you run the fastapi websocket server with hypercorn in docker?
