### ISSUE TITLE
json encoding in WebSocketEndpoint raises AttributeError (instead of more meaningful Runtime error) when message is {'bytes': None, 'text': 'a', 'type': 'websocket.receive'}

### ISSUE THREAD

**Issue by rmorison** [Kludex/starlette#657]
Starting from the example at https://www.starlette.io/endpoints/#websocketendpoint and changing the encoding to json, i.e.,
```
class Echo(WebSocketEndpoint):

    encoding = "json"
```
excepts at
```
  File "/home/rod/.local/share/virtualenvs/websockets_starlette_example-BcV4RAgj/lib/python3.7/site-packages/starlette/endpoints.py", line 92, in decode
    return json.loads(message["bytes"].decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'

```
instead of raising the `RuntimeError` 3 lines above because message = `{'bytes': None, 'text': 'a', 'type': 'websocket.receive'}` (which seems to be how the asgi recv method constructs `message`)

----

Other notes/questions:
- To send `bytes` data through the asgi receive--and hence `encoding = "json"` given Starlette's current design--need something like
```
ws.send(new TextEncoder().encode(JSON.stringify({"message": input.value})))
```
...would be helpful to note this in the example or somewhere

- Why won't Starlette let me send text json? I certainly see the _advantage_ of encoded json, but for simple use cases, it would be nice if text "just worked."

**Comment by jordaneremieff** [comment]
@rmorison I believe this was addressed in https://github.com/encode/starlette/issues/332. You should be able to receive a JSON string with `encoding = "json"` set.  I attempted to re-create the issue with the example from the docs but didn't see an exception.

Could you post your full code?

**Comment by JayH5** [comment]
Closing as stale, reopen if needed.
