### ISSUE TITLE
Components?

### ISSUE THREAD

**Issue by prostomarkeloff** [Kludex/starlette#659]
Hello anyone,

I very like starlette and his ecosystem (like orm, typesystem, etc), but in starlette i was'nt found an any ways for implement [this](https://docs.vibora.io/initial), if not use globals variables, of course :)

It is most efficient and elegant way for access to configs, database connections, etc. 
We can add this to starlette?

**Comment by lovelydinosaur** [comment]
For per-request information you can use `request.state` to store any additional information.
For app-global information you can use `app.state` to store any additional information.

For most stuff you don't actually need to do either of those tho, there's really nothing wrong with defining components in one place, and then importing and using them.

Some state really *is* global state, and that's totally okay.
