### ISSUE TITLE
Unit testing with starlette

### ISSUE THREAD

**Issue by PeriGK** [Kludex/starlette#661]
I am very excited with Starlette and I am building stuff with hellish speed. It is a good chance to thank you for the high-quality you provide, guys.

As part of this, I am trying to write some automation tests for my API and if I understand correctly, I see that you recommend using the TestClient for it? Could you point me to a more detailed example, as the one in the documentation is a bit basic, if any?
What is your view on unit testing Starlette routes? I am a bit confused that you have minimal references to unit testing in starlette.io. After that, I suppose pytest-asyncio is the suggested way to unit test?

Thanks,
Periklis

**Comment by dmontagu** [comment]
Yes, I think using the TestClient is the easiest way to write unit tests for API endpoints.

It would be helpful if *you* could create an example of an endpoint that you don't know how to unit test; then we can show you what it would look to test it using the TestClient.

----

Regarding asyncio, in most circumstances, pytest-asyncio shouldn't be necessary -- the starlette `TestClient` exposes a synchronous interface, and currently doesn't play very nice with running event loops; if you need that functionality, you may want to use another test client library (such as httpx or async-asgi-testclient). (This should get better eventually.)

pytest-asyncio is typically only necessary when you want to mix direct interaction with other async apis into your tests. In most of my projects I need to use pytest-asyncio for some unit tests, but usually not for testing api endpoints.

**Comment by PeriGK** [comment]
Hi @dmontagu 

Thanks for the detailed answer.

Here is an example endpoint I use (a bit abstract to avoid introducing complexity for no reason)

```
async def total_cost_details(request):
    body = await request.json()

    schema = Schema({'user_id': int})

    try:
        validated = schema.validate(body)
    except Exception as e:
        raise HTTPException(status_code=404, detail=f'An error occurred while validating the schema {str(e)}')

    user_id = body['user_id']
    costs = await get_individual_costs(user_id)

    try:
        details = await get_user_details(user_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f'An error occurred while fetching costs per partner: {str(e)}')

    return JSONResponse({'costs': costs, 'details': details})
```

Thanks,
Periklis

**Comment by dmontagu** [comment]
It could look something like this:

```python
@app.route("/endpoint", ["POST"])
async def total_cost_details(request):
    body = await request.json()

    schema = Schema({'user_id': int})

    try:
        validated = schema.validate(body)
    except Exception as e:
        raise HTTPException(status_code=404, detail=f'An error occurred while validating the schema {str(e)}')

    user_id = body['user_id']
    costs = await get_individual_costs(user_id)

    try:
        details = await get_user_details(user_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f'An error occurred while fetching costs per partner: {str(e)}')

    return JSONResponse({'costs': costs, 'details': details})

client = TestClient(app)

def test_endpoint():
    response = client.post(total_cost_details.__name__, json={"body": "good data"})
    assert response.status_code == 200
    assert response.json() == {"expected": "response"}

def test_endpoint_errors():
    response = client.post(total_cost_details.__name__, json={"body": "bad data"})
    assert response.status_code == 404
    assert response.json() == {"detail": "An error occurred while validating the schema"}
```

Obviously the tests won't pass as written above, but hopefully this gives you the idea.

**Comment by PeriGK** [comment]
Thanks, that's a very good point to begin.

About the app instance, do I import it from the main file like
```from src.app import starlette_app as app```

where starlette_app is something like
```starlette_app = Starlette(debug=True)```

or is there any equivalent to ```flask.current_app``` here?

**Comment by euri10** [comment]
> About the app instance, do I import it from the main file like

yes, there's no such thing that resemble `flask.current_app`

**Comment by PeriGK** [comment]
Thanks guys :)

**Comment by PeriGK** [comment]
One last one, am I supposed to call explicitly the test functions in order to run or there is some kind of auto-discovery?

```
@app.route("/endpoint", ["POST"])
async def total_cost_details(request):
    body = await request.json()

    schema = Schema({'user_id': int})

    try:
        validated = schema.validate(body)
    except Exception as e:
        raise HTTPException(status_code=404, detail=f'An error occurred while validating the schema {str(e)}')

    user_id = body['user_id']
    costs = await get_individual_costs(user_id)

    try:
        details = await get_user_details(user_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f'An error occurred while fetching costs per partner: {str(e)}')

    return JSONResponse({'costs': costs, 'details': details})

client = TestClient(app)

def test_endpoint():
    response = client.post(total_cost_details.__name__, json={"body": "good data"})
    assert response.status_code == 200
    assert response.json() == {"expected": "response"}

def test_endpoint_errors():
    response = client.post(total_cost_details.__name__, json={"body": "bad data"})
    assert response.status_code == 404
    assert response.json() == {"detail": "An error occurred while validating the schema"}

test_endpoint()
test_endpoint_errors()
# ETC
```

**Comment by euri10** [comment]
that's pytest job to discover your tests http://doc.pytest.org/en/latest/goodpractices.html#conventions-for-python-test-discovery

on a side you can do 
`response = client.post(app.url_path_for("total_cost_details"), json={"body": "good data"})`
or
`response = client.post("/endpoint", json={"body": "good data"})`

**Comment by PeriGK** [comment]
I see, for some reason I thought it is detached from pytest. :)

**Comment by lovelydinosaur** [comment]
I'll close this one off. Good to see you're making progress! 👍
