### ISSUE TITLE
ASGI 3.0 Application (including Middleware) Signature

### ISSUE THREAD

**Issue by TomChapple** [Kludex/starlette#682]
According to the [ASGI 3.0 specification](https://asgi.readthedocs.io/en/latest/specs/main.html#applications), Applications can be defined as a single callable accepting `scope`, `receive` and `send`. In contrast, there is a reference to a Legacy Application which is a callable class instantiated with `scope` and called with `receive` and `send`.

According to the release notes documented on the [starlette.io website](https://www.starlette.io/release-notes/), 0.12.0 made Starlette compatible with ASGI 3.0.

However, I am unable to use a sole callable as an Application when adding middleware to Starlette. An example is as follows:
```python
async def hello_world(scope, receive, send):
    logging.info("Hello World!")

app = Starlette()
app.add_middleware(hello_world)
```
This results in the following exception:
```
TypeError: hello_world() missing 2 required positional arguments: 'receive' and 'send'
```
This indicates that it is still using the Legacy Application style for ASGI middleware.

Was this ASGI Application Signature expected to be changed with ASGI 3.0? Is there a technical reason for this style of middleware to continue being used?

**Comment by lovelydinosaur** [comment]
Middleware is a callable, that takes the next application in the chain as an application, and *then* returns an ASGI callable as a response. 

As a class it might typically look like this...

```python
class MyMiddleware:
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        # Do stuff
        await self.app(scope, receive, send)  # Optionally, call into the next item in the middleware stack
        # Do stuff
```

As a function it might look like this...

```python
def hello_world_middleware(app):
    async def run_hello_world(scope, receive, send):
        logging.info("Hello World!")
    return run_hello_world
```

So yeah, it *is* using ASGI 3, but you're missing the initial call that sets up the middleware, providing it with the context of the next item in the stack.

It's not obvs in the docs how much we should be documenting it at this kind of low level, vs. eg. "Here's how to subclass BaseHTTPMiddleware".

**Comment by TomChapple** [comment]
Thanks for the response, Tom! It helps to clear up how Middleware is implemented and makes much more sense on the relationship between each layer.

I must say that the ASGI spec itself is a little too ambiguous there as I misconstrued the line "...and then calling an inner application" as expecting the ASGI server to handle this instead of the applications. Would you happen to know if there are any good examples/documentation I can use as a reference to avoid future confusion?

**Comment by lovelydinosaur** [comment]
I think the ASGI docs could probably do with an implementation example in the https://asgi.readthedocs.io/en/latest/specs/main.html#middleware section, yeah. Might be worth opening an issue for, or drafting something up.
