### ISSUE TITLE
More specific type annotation for app instance

### ISSUE THREAD

**Issue by chbndrhnns** [Kludex/starlette#688]
When accessing the `app` property in a `TestClient` or `Request` instance, there could be better support for autocompletion by annotating the fields.

- `class TestClient(requests.Session)` currently has `self.app = asgi_app`
- `class HTTPConnection(Mapping)` currently has `def app(self) -> typing.Any:`

While I am not sure how better annotations would look like, I would appreciate them.

(First raised in https://github.com/tiangolo/fastapi/issues/632)

**Comment by lovelydinosaur** [comment]
Looks like we're already explictly including a complete ASGI type signature... https://github.com/encode/starlette/blob/c0bf5e3976542de2a0d0441bee0b5d7b2f83050e/starlette/testclient.py#L363

And then here...

https://github.com/encode/starlette/blob/c0bf5e3976542de2a0d0441bee0b5d7b2f83050e/starlette/testclient.py#L34

(Tho I doubt there's much useful stuff auto-complete will be able to do for you with complex type annotations like that.)
