### ISSUE TITLE
Add samesite option for Response.set_cookie

### ISSUE THREAD

**Issue by weeshiang** [Kludex/starlette#691]
Would be great if you are able to add the samesite options for Response.set_cookie and not just for the session middleware. Thanks.
------------
`set_cookie(key, value='', max_age=None, expires=None, path='/', domain=None, secure=False, httponly=False, samesite=None)`

_Originally posted by @shawnwall in https://github.com/encode/starlette/issues/275#issuecomment-540026711_

**Comment by lovelydinosaur** [comment]
Had to review this with https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie and https://web.dev/samesite-cookies-explained/

Yes - we'd certainly accept a pull request for that.

It's not *super* obvious *exactly* what we should use for the default unset case. [Setting "SameSite=None" does not have quite the same behaviour as not setting SameSite](https://web.dev/samesite-cookies-explained/#changes-to-the-default-behavior-without-samesite).

We might want `samesite=''` as the default?

**Comment by lovelydinosaur** [comment]
This would be a great one for a contributor to jump on.
Related - we might want to review our defaults at some point - it'd be sensible to be using secure defaults wherever possible.

**Comment by HarrySky** [comment]
@tomchristie in SessionMiddleware I set `same_site='lax'` by default. It is secure default from my POV. Can I create pull request that implement this feature with this default? :)

**Comment by HarrySky** [comment]
Another default I used for security in Sessions is `HttpOnly` by default, but for normal cookie it might be unnecessary.

**Comment by HarrySky** [comment]
Only problem now I have is inconsistency between argument names in `Response.set_cookie` and `SessionMiddleware`. 

In SessionMiddleware I have `same_site` when almost all arguments in `Response.set_cookie` are without underscore and I used `https_only` name as you suggested, but in `Response.set_cookie` used actual flag name - `secure`.

So what should I add `samesite` to be consistent with other arguments or `same_site` to be consistent with `SessionMiddleware`? And should I change `https_only` to `secure` in `SessionMiddleware` (this may break things for some users)?

**Comment by ghost** [comment]
I have a patch for this issue, but before I submit the PR we should get consensus on whether to follow the default behavior specified in [1] and [2] with the caveat that older versions of Safari on iOS and macOS may be impacted [3].

According to [4], Chrome will be shipping with this behavior enabled by default, and Firefox development is in progress [5].

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
[2] https://web.dev/samesite-cookies-explained/#changes-to-the-default-behavior-without-samesite
[3] https://bugs.webkit.org/show_bug.cgi?id=198181
[4] https://www.chromestatus.com/feature/5088147346030592
[5] https://bugzilla.mozilla.org/show_bug.cgi?id=1551798

**Comment by ackinc** [comment]
Looks like this has already been implemented https://www.starlette.io/responses/#set-cookie

Perhaps this issue can be closed
