### ISSUE TITLE
Consider using X-Forwarded-Proto with HTTPSRedirectMiddleware

### ISSUE THREAD

**Issue by shangxiao** [Kludex/starlette#692]
It would be handy if `HTTPSRedirectMiddleware` had an option to use the `X-Forwarded-Proto` header for redirecting on platforms like Heroku.

**Comment by lovelydinosaur** [comment]
Use Uvicorn's `--proxy-headers` to get the same functionality. That adds middleware to set the http/https scheme based on the `X-Forwarded-Proto` header, and the client address based on the `X-Forwarded-For` header.

(Note that the upcoming version 0.10 will automatically determine if it can apply proxy headers, based on the `ALLOW_FORWARDED_IPS` environment variable, which means you won't need to do anything to get the right behavior on heroku with uvicorn 0.10.)
