### ISSUE TITLE
Connecting templates with endpoints

### ISSUE THREAD

**Issue by jodusan** [Kludex/starlette#694]
What is the correct way to display template from an endpoint? For example jinja2?

For jinja2 something like this should be performed:

```
templates = Jinja2Templates(directory='templates')

Class Test(HTTPEndpoint):
    async def get(self, request):
         ....
         return templates.TemplateResponse(template, context)
```

But if I have multiple endpoints in different files I would need to create many Jinja2Templates objects. 

What is the more elegant way of displaying templateResponse from endpoints?

Thanks

**Comment by lovelydinosaur** [comment]
Just create a single `templates` instance in your codebase, then import and use that throughout. Check out the Starlette example or hostedapi repos for examples.
