### ISSUE TITLE
How to get date and URI from response object's headers?

### ISSUE THREAD

**Issue by abhisheksms** [Kludex/starlette#716]
Newbie question here, I am only able to get `content-type` and `content-length` in response HTTP headers. I also want date and URI. How do I do that? Please help me out. Thank You

**Comment by lovelydinosaur** [comment]
The `Date:` HTTP header will be added by the webserver, rather than at the application level.
It's not available in application code. (What are you attempting to use it for?)

I'm not sure which URI you mean? The URL for the incoming request? The URL in the `Location:` header of a redirect response? Something else?

**Comment by abhisheksms** [comment]
Thank you for the response

I am trying to perform HMAC authentication where I require `Date:` HTTP header and URI(i.e. URL for the incoming request). Please help me how to perform this authentication.

**Comment by lovelydinosaur** [comment]
I can’t provide the time to help you out on this, but I think it’s the request you want to verify here, not the response. You can access the *request* date header from `request.headers[“Date”]` and the URL with `request.url`.

**Comment by abhisheksms** [comment]
I am able to access the URL, but I am getting `KeyError` for `Date`.
I get the following output on printing `request.headers`

`Headers({'host': 'localhost:8000', 'user-agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0', 'accept': 'image/webp,*/*', 'accept-language': 'en-US,en;q=0.5', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'cache-control': 'max-age=0'})
`

**Comment by lovelydinosaur** [comment]
Then your request presumably has not included a date header.
