### ISSUE TITLE
on_thread_startup event

### ISSUE THREAD

**Issue by azmeuk** [Kludex/starlette#720]
I realized that when a endpoint is not async, it is executed in another python thread:

```python
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route
import threading

def startup_task():
    print("startup ", threading.get_ident())

def homepage(request):
    print("homepage", threading.get_ident())
    return JSONResponse({'hello': 'world'})

app = Starlette(
    routes=[Route('/', homepage)],
    on_startup=[startup_task],
)
```
```bash
$ uvicorn example:app
INFO:     Started server process [211944]
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Waiting for application startup.
startup  140630902069056
INFO:     Application startup complete.
homepage 140630840559360
INFO:     127.0.0.1:57170 - "GET / HTTP/1.1" 200 OK
```
I see no mention of this in the documentation. Maybe it worth having a word on this?

For some reasons I have to work with some legacy endpoints. They are not async, and I cannot change this easily. They use [threading local data](https://docs.python.org/3/library/threading.html#threading.local) that are initialized the same time the application is launched.

```python
def startup_task():
    initialize_my_thread_data()

def homepage(request):
    read_my_thread_data()
    return JSONResponse({'hello': 'world'})

app = Starlette(
    routes=[Route('/', homepage)],
    on_startup=[startup_task],
)
```

In this situation, the endpoint cannot access the data initialized earlier. I would love a `on_thread_startup` event that could handle my thread data initializations.

What do you think?

**Comment by lovelydinosaur** [comment]
I think(?) you probably want to use `contextvars` instead of thread locals in order to deal with this correctly.

Either ways around, I don't see us adding a `on_thread_startup` - if you need to be more explicit about something there, then use an `async` startup task instead, and explcitly call Starlette's `run_in_threadpool` to switch out to sync - that way you're in complete control of where and when to perform any startup operations. (In the main thread, or in a thread within the threadpool)

**Comment by cjw296** [comment]
Bumped into this while checking for existing issues for #885; does seem reasonable to want to be able to pass in the executor is used for running threads. That way, if you wanted any special stuff doing on thread startup, you'd be able to set up your own threadpool however you wanted.
