### ISSUE TITLE
http://starlette.io doesn't work without the www

### ISSUE THREAD

**Issue by jtrakk** [Kludex/starlette#721]
It would be nice for http://starlette.io to work without the www subdomain.

**Comment by lovelydinosaur** [comment]
Appears to be working fine atm

**Comment by lovelydinosaur** [comment]
Oh sorry, I read that the wrong way around. Sure the *bare* "https://starlette.io" doesn't work no.

**Comment by brettcannon** [comment]
Just ran into this issue myself.
