### ISSUE TITLE
Strange behavior ... is there a "glitch" in computing the "request.url.path" ?

### ISSUE THREAD

**Issue by manatlan** [Kludex/starlette#725]
The latest starlette, on glicth.com ...(versions = https://a-starlette.glitch.me/version )

see : https://a-starlette.glitch.me/
the (editable) code here : https://glitch.com/edit/#!/a-starlette

simple app's code :
```
app = Starlette(debug=True)

@app.route('/')
async def homepage(request):
    return HTMLResponse("request.url.path = '%s'" % request.url.path)
```

I've got :  `request.url.path = 'https,http,http://a-starlette.glitch.me/'`

I understand that, it's a "glitch.com" trouble (which forward the http) ... but perhaps there is a trouble in starlette (in this case), when trying to resolve the url ... no ?
(It happens in glitch.com, but ... perhaps elsewhere too)

**Comment by lovelydinosaur** [comment]
Glitch appears to be sending a malformed 'x-forwarded-proto' header, with an invalid value of 'https,http,http'.

No idea what we should sensibly do about that.

**Comment by lovelydinosaur** [comment]
I guess the malformed scheme is then causing the URL to be parsed oddly.
Unicorn should probably catch cases where x-forwarded-proto has a duff value, ignore it, and log an error.

**Comment by lovelydinosaur** [comment]
Closing this off as there's no Starlette issue here. If anyone wanted to raise a PR against Uvicorn wrt. logging errors on broken x-forwarded-proto case that'd be welcome.
