### ISSUE TITLE
[Feature request] Route "sinks"

### ISSUE THREAD

**Issue by onecrayon** [Kludex/starlette#726]
One of the features I really like over in Falcon is "sinks" (note: framework isn't strictly equivalent, as it's WSGI): https://falcon.readthedocs.io/en/stable/api/api.html#falcon.API.add_sink

The idea is that you have a URL prefix that is explicitly passed off to a callable so that you can forward requests through to other systems alongside your primary application.

My particular use case for this would be to forward v1 API requests through to a legacy Django app, while building out the replacement ASGI server in Starlette over time.

Is this something that would make sense in the core library? I assume I could probably override Router or similar and roll my own solution, but it would be pretty neat if there were a first party router class that was built to pass requests through.

**Comment by gvbgduh** [comment]
I'm not sure if it can replace the "sink", but did you know that you can either mount a WSGI app to the `Router` class and the Router itself is also app, so it might look like.

```
api_v2 = Router(
    [
        Route("/entities", endpoint= Entities, methods=["GET", "POST"]),
        Route("/entities/{entity_id}", endpoint=Entity, methods=["GET", "PACTH", "DELETE"]),
    ]
)

app = Starlette()

app.mount(
    "/v1", app=WSGIMiddleware(old_app.wsgi_app),
    "/v2", app=api_v2,
)
```

**Comment by lovelydinosaur** [comment]
> it would be pretty neat if there were a first party router class that was built to pass requests through.

That's exactly what `Mount` does, yup...

I've updated @gvbgduh's answer here, with the newer style 0.13 routing API...

```python
routes = [
    Mount('/v1', app=WSGIMiddleware(old_app.wsgi_app)),
    Mount('/v2', routes=[
        Route("/entities", endpoint=Entities, methods=["GET", "POST"]),
        Route("/entities/{entity_id}", endpoint=Entity, methods=["GET", "PATCH", "DELETE"]),
    ]),
]

app = Starlette(routes=routes)
```

**Comment by dmontagu** [comment]
@onecrayon I think the responses above address most common use cases, but if you *did* want to roll your own version of a "`SinkRoute`", I think all you'd need to override in a subclass is the `matches` method. (Along with however you wanted to actually implement the handoff, obviously.)

(Maybe you already realized this, but figured I'd share in case you were interested but hadn't looked into the details.)

**Comment by onecrayon** [comment]
Awesome, thanks @tomchristie! I missed that paragraph of the docs!
