### ISSUE TITLE
starlette handles request before startup event complete

### ISSUE THREAD

**Issue by zhammer** [Kludex/starlette#733]
### summary

in the [starlette Events docs](https://www.starlette.io/events/):
> Starlette will not start serving any incoming requests until all of the registered startup handlers have completed.

this seems to not be true on `starlette==0.13.0` / `uvicorn==0.10.8`. noticed this as it caused a bug on http requests sent to a heroku app of mine when heroku container needs to wake up to handle request (https://github.com/zhammer/scribly/issues/16).

### reproduce

this is a simple starlette server that includes a 10 second `asyncio.sleep` in its startup handler, after which it sets `app.state.startup_complete` to true. (not to be confused with the actual startup.complete event, which i believe is part of the new asgi lifecycle.)

in those 10 seconds, requests to the `/` ping route _will_ be handled and the server will log that the `app.state.startup_complete` bool is still false.

server.py
```py
# server.py

import asyncio
import sys

from starlette.applications import Starlette
from starlette.responses import PlainTextResponse


app = Starlette()
app.state.startup_complete = False


@app.on_event("startup")
async def startup():
    print("starting up, will sleep for 10 seconds")
    await asyncio.sleep(10)
    app.state.startup_complete = True
    print("startup_complete set to true")



@app.route("/")
async def ping(request):
    if not app.state.startup_complete:
        print("Received http request, but app.state.startup_complete is not set to True!")
    return PlainTextResponse("pong")
```

requirements.txt
```
Click==7.0
h11==0.8.1
httptools==0.0.13
starlette==0.13.0
uvicorn==0.10.8
uvloop==0.14.0
websockets==8.1
```

**Comment by zhammer** [comment]
here’s my workaround, middleware waits for an asyncio.Event set in the startup event handler to start serving http requests: https://github.com/zhammer/scribly/pull/17

**Comment by zhammer** [comment]
this could also be an issue with uvicorn, not sure whose responsibility it is to order lifecycle events

**Comment by zhammer** [comment]
looked into this a bit further, seems like there is definitely no guarantee on the `uvicorn` side that the server won't start handling requests until startup is complete

https://github.com/encode/uvicorn/blob/4da64be4335ba50e43d7ac8c3b5535460a9c1594/uvicorn/main.py#L416-L443

```py
            try:
                server = await loop.create_server(
                    create_protocol, host=config.host, port=config.port, ssl=config.ssl
                ) # < --- AT THIS POINT THE SERVER IS RUNNING AND WILL ACCEPT HTTP
            except OSError as exc:
                logger.error(exc)
                sys.exit(1)
            protocol_name = "https" if config.ssl else "http"
            message = "Uvicorn running on %s://%s:%d (Press CTRL+C to quit)"
            color_message = (
                "Uvicorn running on "
                + click.style("%s://%s:%d", bold=True)
                + " (Press CTRL+C to quit)"
            )
            logger.info(
                message,
                protocol_name,
                config.host,
                config.port,
                extra={"color_message": color_message},
            )
            self.servers = [server]


        await self.lifespan.startup()  # <-- STARTUP HAPPENS AFTER UVICORN SERVER IS RUNNING
        if self.lifespan.should_exit:
            self.should_exit = True
        else:
            self.started = True
```

**Comment by lovelydinosaur** [comment]
Closing this in favour of the uvicorn ticket.
