### ISSUE TITLE
Question: Application object in startup events with configuration in Starlette.__init__()?

### ISSUE THREAD

**Issue by vikanezrimaya** [Kludex/starlette#736]
If startup events could receive the Starlette app object, modifying state could become a lot easier. My use case is injecting database and aiohttp connections into app state to not incur penalty of bootstrapping a database connection on the first request.

I tried to look into it and make a PR, but got confused in Router object :sad:

If I used Starlette.add_event_handler or Starlette.on_event decorator, I could be able to do this. Problem is -- these are now discouraged. For which reason? Can the app be somehow launched before configuration takes place? If I construct an app object in the function and return it, this should not be a problem. Flask apps sometimes use this pattern.

**Comment by lovelydinosaur** [comment]
For now I'd suggest lazily importing the app inside the startup function.
