### ISSUE TITLE
[QUESTION] how-to consume multiple values in a form field

### ISSUE THREAD

**Issue by playgroundctl** [Kludex/starlette#738]
Hi,

when submitting a form that gets processed like (using `fastapi` and `starlette`'s `Request` object):
```
@app.post("/apps/bgp")
async def do_lookup_bgp_network_prefix(
    request: starlette.requests.Request,
):
    form_data = await request.form()
    print(form_data)
    print(form_data["netelement_location"])
    print(form_data["routing_prefix"])
```

I can see the following in the logs:
```
FormData([('netelement_location', 'ch__zrh03a'), ('netelement_location', 'us__nyc01b'), ('routing_prefix', '1.1.1.1')])
us__nyc01b
1.1.1.1
```

The issue is that I don't know how-to access the **list** of values transmitted using the form field `netelement_location `.
Using `form_data["netelement_location"]` gets only the last value..

Could you please advise ?

**Comment by lite31** [comment]
found it, `getlist` it is :)
