### ISSUE TITLE
Rising Responses

### ISSUE THREAD

**Issue by imbolc** [Kludex/starlette#74]
Is there any cons for inherit `Response` from `Exception` to be able to raise it?

**Comment by lovelydinosaur** [comment]
I think it’s probably better for the library to have handled exceptions be more constrained then simply general purpose responses. That makes it easier to modify the error handling.

**Comment by imbolc** [comment]
I don't mean using it for exceptions on the library level. It just convenient when you can just "raise" response from some nested coroutine or a middleware rather than passing it all the way back.

**Comment by lovelydinosaur** [comment]
Sure, and we have `HTTPException` for that kind of use-case. It’s just more constrained than having Response itself be an exception class.

**Comment by imbolc** [comment]
Looking at the code and don't see how can I use a particular response (let's say `RedirectResponse`) with `HTTPException`? Let me clarity what I mean by example, with this rising feature we can write:

```python
@app.route('/')
def homepage(request):
    validate_request(request):
    return JSONResponse({'hello': 'world'})

def validate(request):
    raise JSONResponse({...}, status_code=400)
```

**Comment by blueyed** [comment]
I guess you could make this work by using a mixin / custom JSONResponse class, and handling it via `@app.exception_handler(RaisingJSONResponse)`, or a middleware.
