### ISSUE TITLE
[Question] Will you support default renderers?

### ISSUE THREAD

**Issue by erichaus** [Kludex/starlette#743]
Hello! New to Starlette and excited by it. Are there any plans to add a hook for setting a default renderer such that I don't need to explicitly return a JSONResponse? e.g. following code would work:
```
async def posts(req):
    return [{'id': 1}, {'id': 2}]
```
Or, where in the code might you implement a hook to create this?

**Comment by lovelydinosaur** [comment]
Plans, yes. Not here yet tho.
