### ISSUE TITLE
How can I add a url prefix to all routes?

### ISSUE THREAD

**Issue by erichaus** [Kludex/starlette#744]
I tried to implement a middleware that would append a namespace to all routes, but received error that "Attribute can't be set".
```
PREFIX = 'v1/'


class URLPrefixMiddleware(base_mw.BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        print(request.base_url)
        request.url = f'{request.url}{PREFIX}'
        response = await call_next(request)
        return response


middleware = [
    Middleware(URLPrefixMiddleware),
]
```
Tried with request.base_url as well.

How could I implement this?

![image](https://user-images.githubusercontent.com/230757/70198387-9ad05600-16c3-11ea-9a0d-3f047dc06f8e.png)

**Comment by erichaus** [comment]
NVM found https://www.starlette.io/routing/#submounting-routes and I suppose that's the preferred way to do it(?)

**Comment by lovelydinosaur** [comment]
Exactly, yup.
