### ISSUE TITLE
Endpoint path parameters type specification compatibility with OAS

### ISSUE THREAD

**Issue by inverseTrig** [Kludex/starlette#746]
When specifying a convertor type for a path parameter like so:
```
...
Route('/users/{user_id:int}', user, methods=["GET", "POST"])
...
```

The OAS schema generated using `SchemaGenerator` interprets the whole portion within `{}`  eg. `'user_id:int'` as the required path parameter variable name, which then requires the parameter name in OAS to be `user_id:int` instead of just `user_id`.

![user_idint](https://user-images.githubusercontent.com/26809407/70369654-50312280-18eb-11ea-9089-53743115394c.png)

I think the convertor is great in that a GET request to `/users/foo` will result in `404: NOT FOUND`. Of course, another option is to have a `try-except` clause to handle non-integer values within the method... but I was wondering what the community thinks about this and if this even should be supported by the `SchemaGenerator`.

**Comment by lovelydinosaur** [comment]
Thanks for raising this.

As a first pass at resolving this we should just do the simple thing and strip any `:<specifier>` portion from the string. Would gratefully accept a pull request for that.

A second pass could be to *also* make sure that we're generating the correct type description in OpenAPI.
