### ISSUE TITLE
request.query_params & request.url missing query params

### ISSUE THREAD

**Issue by erichaus** [Kludex/starlette#747]
Hey,

I have a simple test app (`starlette==0.13.0`) running and I noticed that requests only contain the first query parameter. All subsequent query params are trimmed out of the request url & query params:
```
curl http://localhost:8000/v1/posts?foo=bar&show=yes&test=1
```
The resulting `request` object in my view shows this:
```
URL('http://localhost:8000/v1/posts?foo=bar')
QueryParams('foo=bar')
```
![image](https://user-images.githubusercontent.com/230757/70400988-6bcb2480-19e2-11ea-8887-c797eb34730a.png)
![image](https://user-images.githubusercontent.com/230757/70401104-117e9380-19e3-11ea-824e-0dad5140a5ce.png)

**Comment by alex-oleshkevich** [comment]
Hi @erichonkanen,
please, share a route definition you've used.

**Comment by lovelydinosaur** [comment]
There isn't enough in this issue description to replicate an issue.

```python
>>> from starlette.datastructures import URL, QueryParams
>>> u = URL('http://localhost:8000/v1/posts?foo=bar&show=yes&test=1')
>>> q = QueryParams(u.query)
>>> print(q)
QueryParams('foo=bar&show=yes&test=1')
```

I'm happy to reopen this, but only if its reduced to an absolutely minimal reproducible example case.

**Comment by erichaus** [comment]
@tomchristie @alex-oleshkevich definitely, I was able to replicate it with this simple app and curl command:
```
# app.py

from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Mount, Route


async def posts(request):
    qp = request.query_params

    print(str(qp))
    # > foo=bar

    return JSONResponse({k: v for (k, v) in qp.items()})


routes = [Mount('/v1', routes=[
    Route('/posts', posts),
])]


app = Starlette(
    routes=routes,
)
```
```
uvicorn --host 0.0.0.0 app:app

curl http://localhost:8000/v1/posts?foo=bar&test=1&yes=true
```
output:
```
{"foo":"bar"}
```

**Comment by lovelydinosaur** [comment]
That doesn't replicate for me at all?...

![Screen Shot 2019-12-09 at 17 07 46](https://user-images.githubusercontent.com/647359/70456655-751dc500-1aa6-11ea-808c-dac67dec1972.png)

![Screen Shot 2019-12-09 at 17 07 52](https://user-images.githubusercontent.com/647359/70456673-7d760000-1aa6-11ea-90d9-b9dadcb0f952.png)

**Comment by erichaus** [comment]
that's weird! it's happening for me on two fresh installs... is there any underlying lib that could impact it?

**Comment by erichaus** [comment]
@tomchristie ok I just created new app again with above # app.py and discovered that making the request in the browser indeed works, whereas making the request with curl does not work.

Is there a header that when not present is affecting this?

![image](https://user-images.githubusercontent.com/230757/70466904-0d04ba00-1a79-11ea-9067-9f5f9c4c6e2a.png)

![image](https://user-images.githubusercontent.com/230757/70467052-5bb25400-1a79-11ea-9d94-149810ada66a.png)

**Comment by lovelydinosaur** [comment]
Found it 🤣 It's a scripting issue...

```shell
$ curl http://localhost:8000/v1/posts?foo=bar&test=1&yes=true
                                             ^ Ampersand is a special character.
```

This is *actually* being interperated as:

* `curl http://localhost:8000/v1/posts?foo=bar`
* `test=1`
* `yes=true`

Try `echo $test; echo $yes` and you'll see what I mean.

**Comment by erichaus** [comment]
ohhh wow, son of a gun! that's it 😊 sigh, my bad! thanks for helping get to the bottom of it!
