### ISSUE TITLE
feat/sse

### ISSUE THREAD

**Issue by sysid** [Kludex/starlette#749]
Build of my pull request feat/sse is failing with:
`tarlette/middleware/wsgi.py:91: error: Argument 1 to "wait_for" has incompatible type "Task[None]"; expected "Union[Future[<nothing>], Generator[Any, None, <nothing>], Awaitable[<nothing>]]"`

This file is not part of my new feature branch but rather from master. 
Looks to me that also other pull requests are failing due to this.

How to proceed?

**Comment by lovelydinosaur** [comment]
Thanks... https://github.com/encode/starlette/pull/756
