### ISSUE TITLE
Returning RedirectResponse fails for full URL's if trailing slash is missing

### ISSUE THREAD

**Issue by chbndrhnns** [Kludex/starlette#750]
I played with [this](https://github.com/encode/starlette/blob/master/tests/test_responses.py#L60) test case by redirecting to an external URL and it seems to fail when a trailing slash is missing and `allow_redirects` is set to `True` (which is the default).

The same is true if you append any path parameter or query parameter to the URL.

It fails for starlette 0.12.13 and 0.13.

The error I receive is:

```
            if len(resp.history) >= self.max_redirects:
>               raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
E               requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

This is my test:

```python
def test_redirect_response():
    url: str = 'https://github.com'

    async def app(scope, receive, send):
        if scope["path"] == "/":
            response = Response("hello, world", media_type="text/plain")
        else:
            response = RedirectResponse(url=url)
        await response(scope, receive, send)

    client = TestClient(app)

    response = client.get("/redirect", allow_redirects=False)
    assert response.status_code == status.HTTP_307_TEMPORARY_REDIRECT

    response = client.get("/redirect")
    assert response.status_code == status.HTTP_200_OK

```

To me, it seems to be an issue with the TestClient as it actually works when running a server and return a RedirectResponse.

**Comment by lovelydinosaur** [comment]
I'm not really sure what behaviour we'd want from the test client for external URLs.
Or even how the test client could determine if it is an external URL?

Eg. If the service returns a redirect response to "https://api.myservice.com/users" how would we determine if that's an external URL, or the service itself?

We also don't really want the test client to make live network queries.

I can kind of see some approachs onto tightening up the behavior here, but it's a complex area.

In the meantime I guess I'd suggest that you use allow_redirects=False for any test client calls that'll result in an external host redirect.
