### ISSUE TITLE
feat: Update the GraphQL page

### ISSUE THREAD

**Issue by athul** [Kludex/starlette#753]
Update the GraphQL page from GraphiQL to GraphQL Playground by [Prisma Labs](https://github.com/prisma-labs/graphql-playground). 
It provides a better and Interactive UI for testing and checking Endpoints. [Demo](https://www.graphqlbin.com/v2/6RQ6TM)

I could make a PR for the same by Changing the contents of the `GRAPHIQL` variable  here https://github.com/encode/starlette/blob/c5239ba89bc273645c82bd76bce185a5bd4964c7/starlette/graphql.py#L147-L279
I'll start working on this if this gets a green flag 😅 😅

**Comment by lovelydinosaur** [comment]
That looks pretty decent yup.

I'm not sure I really want us to take pull requests in this area or not, since what I'd really like to see at this point is having the GraphQL app move out into a third party package as per https://github.com/encode/starlette/issues/619

**Comment by athul** [comment]
I haven't had any expereience with making python packages... But I'd totally love to work on the above mentioned. Do you have any suggestions or workarounds for the same? 
Should I reuse the code in `graphql.py` file for developing the package. 

Plus  updating the package might cause some disinterest who use FastAPI framework for GraphQL in production.

**Comment by lovelydinosaur** [comment]
I *think* I probably just need to leave this one in other folk's hands.

I'd be totally happy with someone starting up a project based on the existing `graphql.py` and associated tests & docs. If someone happens to take a propactive lead on that, then we can consider deprecating the built-in option, and instead start linking out to third parties instead.

**Comment by athul** [comment]
Obviously Understandable.

**Comment by athul** [comment]
Hey @tomchristie I actually Tried it by playing a bit with Source code and it actually worked and really well too....
![Screen Shot 2019-12-18 at 6 05 19 PM](https://user-images.githubusercontent.com/40897573/71086958-13094200-21c1-11ea-8f3d-b1fbe2cd2362.png)
```python
import graphene
from fastapi import FastAPI
from starlette.graphql import GraphQLApp


class Query(graphene.ObjectType):
    hello = graphene.String(name=graphene.String(default_value="stranger"))

    def resolve_hello(self, info, name):
        return "Hello " + name

#
app = FastAPI()
app.add_route("/", GraphQLApp(schema=graphene.Schema(query=Query)))
```
This is the source code for it

**Comment by JayH5** [comment]
Thank you for filing this issue. We have decided to deprecate GraphQL support within Starlette itself so I am going to close this issue. See #619.

**Comment by jrdnbrj** [comment]
@athul How you enabled playground?
