### ISSUE TITLE
Proposal: Pass a single callable for exception_handlers

### ISSUE THREAD

**Issue by berislavlopac** [Kludex/starlette#754]
Currently, the `exception_handlers` argument of `Starlette` app class accepts a mapping of exception types to handler functions. I'd like to propose that, in addition to that, it could accept a single callable which would manage the error types internally.

The reason for this is that it would then be possible to manage the different handlers for different error types using the [`functools.singledispatch`](https://docs.python.org/3.7/library/functools.html#functools.singledispatch) decorator. The only problem is that the signature of that callable would have to be `func(exc, request)`, which is the opposite of the individual handlers accepted in the mapping. (Alternatively, would it be too difficult to change their signatures too? :thinking: )

Thoughts?

**Comment by lovelydinosaur** [comment]
> Thoughts?

That's a really interesting style.

I'd *probably* be more keen on having something like that in the domain of higher-level frameworks, or a third party package. If we keep Starlette really slimline, we ought to be able to make sure that it's easy enough to override which bits of built-in middleware the application automatically includes. (So eg. folks can swap out to a different exception handler middleware.)

**Comment by berislavlopac** [comment]
Is there currently a way to use middleware for error handling?
