### ISSUE TITLE
Handling Deepobject Query params

### ISSUE THREAD

**Issue by Origin1227** [Kludex/starlette#760]
Hi,  am working on a project in which i be having urls with query params of the form 
http://server.com/sample?field["email"]="title" 
that is query parameters of style deepObject ( OpenAPI)
Does starlette support these type of parameters or is there a way for me to write my own custom deserializer for these

**Comment by lovelydinosaur** [comment]
Nope, we don't have any built-in support for that. You'll have to look into third party packages or writing your own. You can access the raw query string with `request.url.query`.
