### ISSUE TITLE
Global scope accessor

### ISSUE THREAD

**Issue by blaggacao** [Kludex/starlette#762]
I'm pretending to use the Session middleware as backend for a session store implemetation.
The session store is however lazily loaded deep inside the "legacy" framework.

Patching the session store loader, I need to feed it the scope (or at least the session dict)  out of "nowhere".

So I thought, maybe the following solution is generic enough to make it a middleware:
```python

from starlette.types import ASGIApp, Receive, Scope, Send

import contextvars

scope = contextvars.ContextVar('scope')


class GlobalScopeAccessorMiddleware:
    """
    A middleware class that exports scope to arbitrarily access.
    """

    def __init__(self, app: ASGIApp, ) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        token = scope.set(scope)
        await self.app(scope, receive, send)
        scope.reset(token)
```
```python
from starlette.middleware.globalscope import scope
...
scope.get()  # yeah
```

Better understanding my motivation, here is the session store property I need to patch and where the self instance is not much of use:
```python
class Root(object):
    def __init__(self):
        self._loaded = False

    @lazy_property
    def session_store(self):
        ...
```

Please let me know if I should do a PR, should this idea be generic and useful enough...

**Comment by blaggacao** [comment]
Maybe export an immutable copy in order to not suck too much...

**Comment by lovelydinosaur** [comment]
Yup I've certainly considered a ContextVar middleware that eg. makes the `request` globally available. At the moment I'd rather see any approach onto this as a third party package or code sample, since I'm not ready to take a firm view on how any API ought to look here just yet.
