### ISSUE TITLE
Some general questions

### ISSUE THREAD

**Issue by Midnighter** [Kludex/starlette#77]
I'm not sure this is the best place to ask these, so feel free to point me somewhere else.

1. I wonder what the recommended way is for request validation and response serialization, i.e., I'd love to use something like [marshmallow](https://marshmallow.readthedocs.io/) but maybe you have a different recommendation.
2. What is the recommended way to access the running event loop? `asyncio.get_event_loop()`? (I'm developing on Python 3.6.)
3. What would you recommend for spawning a thread or process pool executor? Simply `from concurrent.futures import ThreadPoolExecutor`? Would it be possible to maintain such a pool on the app rather than spawning one each time a request is made (which seems like a terrible idea).

**Comment by songww** [comment]
1. Starlette is only web framework. (apistar)[https://github.com/encode/apistar] is a toolkit for that.
2. You don't need to care how loop is runing. Starlette is a web framework, not a web server. Maybe you'd like to use Starlette with (uvicorn)[https://github.com/encode/uvicorn].
3. Starlette do not need  thread or process pool executor too.

**Comment by lovelydinosaur** [comment]
1. Marshmallow, API Star, or whatever.
2. Yes.
3. Yes, an executor instance on the app might be reasonable. You could just use a single global instance for now tho.
