### ISSUE TITLE
Question: is it better to return an empty {} or raise JSONDecodeError for "await req.json()"

### ISSUE THREAD

**Issue by kemingy** [Kludex/starlette#788]
Currently, `await request.json()` will raise JSONDecodeError if the HTTP request body is empty. This is due to `json.loads(b'')`.

Is it better to return an empty `{}` instead of raising a JSONDecodeError?

I find this when I'm developing the validation tool for starlette([spectree](https://github.com/0b01001001/spectree)). When I'm trying to validate JSON data in the request, it raises this exception. I already fixed it by using `json.loads(await request.body() or '{}')`([detail](https://github.com/0b01001001/spectree/pull/20/commits/15d569f411d1c0b0b746fab65abdacff94286ba3)).

But I guess this part should be done by users. So if the users want to get data from the JSON body, they need to `try: await request.json()` or parse the `request.body()`. Otherwise, they may get an exception (although it doesn't affect the service). That seems not very elegant.

**Comment by dmontagu** [comment]
I personally think the current behavior is correct, and have a strong preference for it.

A body of `"{}"` explicitly signifies an empty JSON object, and is absolutely different from an empty body `""`. It seems far less consistent to me to convert the empty body into a valid JSON object; no other string is handled this way. Moreover, why prefer `{}` over `[]` or `None`?

In general, I don't think it makes sense to try to validate JSON data unless you have good reason to believe you will 1) receive a non-empty body, and 2) that body will be formatted using JSON (note: non-JSON bodies *are* common: form data and/or multi-part). And if you have the ability to deal with non-JSON bodies (which starlette absolutely does need to be able to handle, and which *will* raise `JSONDecodeError`s if you try to call `json()` on them), I don't see why this case should be treated specially.

I think it would probably be better to rework your validation logic to not check `.json()` in cases where the request may contain non-JSON-decodable data, or at least to explicitly handle the `JSONDecodeError`.

**Comment by kemingy** [comment]
Thanks for your explanation.

I agree `"{}"` is not good for the empty body, `None` is better.

For the rest, I personally think it depends on how people are using starlette for. If they treat it as a low-level framework(a ASGI toolkit), it's resonable to raise a `JSONDecodeError` (they probably will check the body and format first). But if they use it as a micro-service framework like flask, they may feel confused about this exception when they are trying to call `json()`.

I know starlette can be used for these two ways. Maybe it's better to raise an exception for an invalid JSON body.

**Comment by lovelydinosaur** [comment]
*Ideally* we ought to have request parsing that depends on the `Content-Type` passed to the request, raising *handled* exceptions that return 415 for unsupported content types, and 400 for malformed content.

* https://httpstatuses.com/400
* https://httpstatuses.com/415

Endpoint could would access the passed content with `request.data`. The behavior on an empty request body would depend on the Content-Type. If no Content-Type is set then the request is valid and `request.data` would return `None`. If the Content-Type was set to `application/json` but no request data was included then a 400 response would be returned.
