### ISSUE TITLE
response headers support custom encoding 

### ISSUE THREAD

**Issue by 0b1Kenobi** [Kludex/starlette#790]
Hi~ When i try to return a `FileResponse` with Chinese filename, i got such error:

```
UnicodeEncodeError: 'latin-1' codec can't encode character '\u6708' in position 32: ordinal not in range(256)
```

Then i found all header items will be encode with `latin-1`, after i change it manually to `utf-8`, my problem was solved.

e.g.

- responses.Response.init_headers, line 63
```python
raw_headers = [
    (k.lower().encode("latin-1"), v.encode("latin-1"))
    for k, v in headers.items()
]
```

So may be it should encode with `self.charset` or give a custom parameter so that i can choose encoding to `utf-8`?

Thx for the great project~

**Comment by CyberQin** [comment]
#792 only solves FileReponse,but it still a problem in streamreponse.
