### ISSUE TITLE
[QUESTION] Relative Path

### ISSUE THREAD

**Issue by victoraugustolls** [Kludex/starlette#795]
Hi!

I looked through the docs but might have missed something.

Is it possible to extract the relative path from a `Request`?
If I have a route like `/users/{id}`, I would like to get exactly this value, and not the absolute path with the `id` value.

Thanks!

**Comment by lovelydinosaur** [comment]
Sure thing... `request.url.path`

**Comment by victoraugustolls** [comment]
Actually this returned the full path, like `/users/123` instead of `/users/{id}`.
@tomchristie

**Comment by lovelydinosaur** [comment]
Right, I see what you're asking. (Tho that's not "absolute path" vs. "relative path".)
No there's not really a way to do that at the moment.
What's the use-case?

**Comment by victoraugustolls** [comment]
Grouping logs by path. In my use case, Microsoft Application Insights, which I need to set an operation name for them to group by it, and the path rule (?) would be the best way to do it.

Is this in the backlog or desirable to have in Starlette?

**Comment by lovelydinosaur** [comment]
> Is this in the backlog or desirable to have in Starlette?

There's this, which covers some similar ground... https://github.com/encode/starlette/issues/685

I think we'd eventually want to include something like a `request.route` property.

**Comment by victoraugustolls** [comment]
Seems to be pretty much my use case...
In any way, thanks for the help, hope Starlette implement this soon :)
Will try to look through the code to see if I can help also.

**Comment by victoraugustolls** [comment]
@tomchristie would you help me by pointing me to the right direction to help with this?

**Comment by BrikerMan** [comment]
@tomchristie @victoraugustolls Any updaye on this issue?

**Comment by victoraugustolls** [comment]
Hey @BrikerMan ! There is a PR (#804) but it is pretty much stuck.
