### ISSUE TITLE
how to use include one template in another template

### ISSUE THREAD

**Issue by invisement-old** [Kludex/starlette#796]
I could not figure out why {% include "anotherTemplate.html" %" does not work in templates.

**Comment by syrull** [comment]
Can you show what errors/messages do you get?

One possibility might be that your application does not know where to look for templates. In that case you have to have this line in your `app.py`:
`templates = Jinja2Templates(directory='templates')`

That would point to `{root (app.py) directory} / templates` for the template folder.
