### ISSUE TITLE
Resource-traversal routing 

### ISSUE THREAD

**Issue by jtrakk** [Kludex/starlette#797]
I'm mentioning this feature because I can imagine wanting it in the future, not because I actually need it right now.

One of the popular features of [Pyramid](https://pyramid.readthedocs.io/en/latest/index.html) is that it offers, in addition to regular url dispatch, the option of "traversal"-based routing. 

> A traversal uses the URL (Universal Resource Locator) to find a resource located in a resource tree, which is a set of nested dictionary-like objects. Traversal is done by using each segment of the path portion of the URL to navigate through the resource tree. You might think of this as looking up files and directories in a file system. Traversal walks down the path until it finds a published resource, analogous to a file system "directory" or "file". The resource found as the result of a traversal becomes the context of the request. Then, the view lookup subsystem is used to find some view code willing to "publish" this resource by generating a response.

For example, with 

```py
def get_root(request):
    return Resource({'a': Resource({'b': Resource({'c': Resource()})})})
```

Navigating to `/a/b/c` will return the innermost resource. Any object providing `__getitem__` can be used in the route lookup, as the nested `Resource`s are being used here.

The Pyramid docs on traversal are extensive:

- [Quick example](https://pyramid.readthedocs.io/en/latest/narr/hellotraversal.html)
- [Much ado about traversal](https://pyramid.readthedocs.io/en/latest/narr/muchadoabouttraversal.html)
- [Traversal details](https://pyramid.readthedocs.io/en/latest/narr/traversal.html)
- [Combining Traversal and URL Dispatch](https://pyramid.readthedocs.io/en/latest/narr/hybrid.html)
- [Resources](https://pyramid.readthedocs.io/en/latest/narr/resources.html)

**Comment by lovelydinosaur** [comment]
Sure thing. This looks a *bit* similar to Starlette's `Mount`, eg...

```python
routes = [
    Mount("a", routes=[Mount("b", routes=[Route("c", endpoint)])])
]
```

In any case, looks interesting, but we'd def. want to defer any different styles here to third party packges.
