### ISSUE TITLE
Dangerous example regex for CORS Middleware?

### ISSUE THREAD

**Issue by josephbuckley** [Kludex/starlette#800]
Looking at the docs for CORS Middlware here: https://www.starlette.io/middleware/#corsmiddleware , under the `allow_origin_regex` attribute, the example value is `https://.*\.example\.org`.

However, based on the handler code for this at https://github.com/encode/starlette/blob/ab86530eddfcf56e0f7e5ca56f6ab69c15594a7d/starlette/middleware/cors.py#L90 , it appears `https://www.example.org.hacker.com` would pass as a valid origin, right?

It seems like the example should be `https://.*\.example\.org$`, yes?

**Comment by lovelydinosaur** [comment]
I don’t recall if it’s automatically anchored. Might be?

**Comment by josephbuckley** [comment]
Huh, I don't follow you.

Either the documentation needs to be updated to show a safe example, or (the better solution), would be to update https://github.com/encode/starlette/blob/ab86530eddfcf56e0f7e5ca56f6ab69c15594a7d/starlette/middleware/cors.py#L90 to do `fullmatch` instead of `match`

**Comment by lovelydinosaur** [comment]
My question was if it was already a full match. (Which yeah, it really ought to be)

**Comment by josephbuckley** [comment]
I created a PR for this https://github.com/encode/starlette/pull/801
