### ISSUE TITLE
Set status code reactively in StreamingResponses?

### ISSUE THREAD

**Issue by nathanlcarlson** [Kludex/starlette#806]
If an error occurs during the streaming of the response body is it possible to set the status code to something other than the initially set status code? 

For example:
```python
@app.route('/a_route')
async def a_route(request):
  data = await get_some_data()

  async def streamer(data):
    done = False
    outputs = data['key']
    while not done:
      for output in outputs:
        yield output
      data = await get_more_data()
      outputs = data['key']
      done = len(outputs) == 0

  return StreamingResponse(streamer(data), status_code=200)
```
Errors could occur in `get_more_data()`, or even in `data['key']` if `'key'` happens to not be present, while streaming, but the response's status code is already set and sent as 200.

My understanding is that something similar could occur in a FileResponse as well, if an error occurs while reading from the file.

Is there simply something incorrect about this usage pattern? I admittedly don't have any suggestions to resolve this.

`starlette           0.13.0`

Thanks for any help.

**Comment by lovelydinosaur** [comment]
Nope. Not something you're able to do in HTTP.
Raise the exception, and the server will just prematurely break the connection, which clients will notice, and which is the best you can do.

**Comment by nathanlcarlson** [comment]
Thanks @tomchristie

**Comment by sm-Fifteen** [comment]
I know some application protocols will send a temporary status code before the headers, and then transmit a custom HTTP trailers with the actual returned status response after the response is complete, but that's outside of HTTP (so browsers wouldn't understand it) and the ASGI specification does define mechanisms for sending Trailers (see django/asgiref#141).

Once your headers have been sent and you begin sending your first chunk of body data, you can no longer go back on the status code you've sent, so you normally want to hold back from sending your headers until you know what the outcome is going to be (which is not unlike how the non-streaming `Response` does it). Like Tom said, once you do begin to stream, the best you can do in case of error is to just cut the connection short, such as by raising an exception.

Consider the file streaming example: Your status code is meant to indicate whether or not the user can access the file/ressource. Once that's done, all that's left is to send the file over, at which point the only thing that could stop you is an I/O error, which the server can't really do much about.

**Comment by nathanlcarlson** [comment]
I opted to pre-`yield` a bit of information that indicates how much more real output to expect in the stream. This information happens to be available in my use case. Clients for my application will just have to be aware of this.
```python
@app.route('/a_route')
async def a_route(request):
  data = await get_some_data()

  async def streamer(data):
    yield how_much_output_to_expect # <--- here
    done = False
    outputs = data['key']
    while not done:
      for output in outputs:
        yield output
      data = await get_more_data()
      outputs = data['key']
      done = len(outputs) == 0

  return StreamingResponse(streamer(data), status_code=200)
```
