### ISSUE TITLE
Question, would like to use dashes instead of underscores in some path parameters

### ISSUE THREAD

**Issue by Subaku** [Kludex/starlette#809]
Coming over from [this issue](https://github.com/tiangolo/fastapi/issues/909) in the FastAPI repo. I ran into a problem declaring both path and query parameters in my views using dashes as is usually acceptable in urls and APIs. I learned a trick to get around it for query parameters but it looks like the `starlette.routing.PARAM_REGEX` disallows such a thing. Just wondering if there's a valid reason for this? Maybe just convention?

Thanks!

**Comment by lovelydinosaur** [comment]
`PARAM_REGEX` isn't relevant here - that's the regex that's used to match the path components, and is resticted to valid Python variable names. (Nothing to do with what characters it will capture from the path.)

Eg `Route("/{username:str}", user_page)`

Your original question against FastAPI was valid. Fast API automatically maps your `QueryParam` annotation onto an expected query parameter, and evidently defaults to underscores as a convention. I've no idea if it also supports switching to hyphens or not.

**Comment by fullstackwebdev** [comment]
@Subaku did you ever find a fix? I have a need to host a POST that accepts a dash and I'm stuck, saw your other ticket. Sorry for commenting on an old issue..
