### ISSUE TITLE
CORSMiddleware is not working

### ISSUE THREAD

**Issue by ghost** [Kludex/starlette#810]
So, I went through documentation and I made this test application, to see if the CORSMiddleware even works. Well, apparently it doesn't work at all, the headers are not being sent and the OPTIONS request still returns 405.

Is it just me misunderstanding something and if so, what exactly? If it's not just me, then I think something is broken here.

I would really appreciate some TIP on that, since I rewrote one of my API wrappers to starlette and it doesn't really work, because of cors ;-;

My application code
```python
from starlette.applications import Starlette
from starlette.responses import JSONResponse, PlainTextResponse
from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware
from starlette.exceptions import HTTPException


middleware = [
    Middleware(CORSMiddleware, allow_origins=['*'], allow_methods=["GET", "OPTIONS"],
               allow_headers=["Token", "Origin", "X-Requested-With", "Content-Type", "Accept"])
]

app = Starlette(middleware=middleware)


@app.route('/')
async def homepage(request):
    return JSONResponse(content={"message": "hi"})


@app.route('/test')
async def test(request):
    return JSONResponse(content={"test": "the test route"})

```

Here's results of the request to root:
![Postman_e6qkuwYQR2](https://user-images.githubusercontent.com/51153795/73184297-a6755180-4135-11ea-8bae-3a666431d5eb.png)
![image](https://user-images.githubusercontent.com/51153795/73184431-d4f32c80-4135-11ea-91ac-33b85f22f542.png)

**Comment by Turall** [comment]
I have same problem.

**Comment by lovelydinosaur** [comment]
I'd suggest looking through https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS closely as a first pass if you're having any issues with CORS support.

The outgoing request needs to include an "Origin" header in order to prompt CORS headers in the response.
