### ISSUE TITLE
Deprecation warning due to invalid escape sequences in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [Kludex/starlette#822]
Deprecation warnings are raised due to invalid escape sequences in Python 3.8 . Below is a log of the warnings raised during compiling all the python files. Using raw strings or escaping them will fix this issue.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Wall -m py_compile {}

./tests/middleware/test_cors.py:180: DeprecationWarning: invalid escape sequence \.
  allow_origin_regex="https://.*\.example.org",
```

**Comment by JayH5** [comment]
Fixed in #1043
