### ISSUE TITLE
Set-Cookie header should not be sent every time

### ISSUE THREAD

**Issue by JokerQyou** [Kludex/starlette#828]
I've noticed once the builtin `SessionMiddleware` is used and you've got something stored in session, the `Set-Cookie` header will be included in the response headers every time (related starlette code [here](https://github.com/encode/starlette/blob/5f4fc85541f44013d1ed40fb77eb772db50fe02b/starlette/middleware/sessions.py#L53)), even when the session data is not changed at all.

I think this header should only be sent back to the client when the session data is modified. As far as I know, Flask is behaving as expected, see their code [here](https://github.com/pallets/flask/blob/200ce9bd39c70a7782ef8ace0338ad71dbdb175d/src/flask/sessions.py#L278).

**Comment by JokerQyou** [comment]
Major problem is: `Set-Cookie` header being sent upon every response would invalidate the `max-age` setting, since each time the client receives this header, it extends the age of the session cookie.

**Comment by lovelydinosaur** [comment]
> Set-Cookie header being sent upon every response would invalidate the max-age setting, since each time the client receives this header, it extends the age of the session cookie.

I think that's probably a reasonable default behaviour for us right now.

(Ie. sessions expire after 2 weeks of inactivity, but interacting with the site extends the session lifetime)

**Comment by JokerQyou** [comment]
I agree that this is probably a reasonable default behavior, but maybe we can add an option to turn it off. It does not fit well to the regular "remember me" flow of user sign-in.
If a user signed in with "remember me for 7 days" option, and because the user actively uses the website everyday, eventually the "remember me" option becomes useless.
Of course we can always add more code in the business layer, but expiring the session cookie is the most intuitive one.

**Comment by lovelydinosaur** [comment]
That's reasonable. We could probably consider pull requests adding an `always_refresh` configuration to the class, or something similar to that.
