### ISSUE TITLE
Incorrect MIME type for templated javascript module imports

### ISSUE THREAD

**Issue by jbsetton** [Kludex/starlette#829]
Greetings all,
I cannot seem to find where one explicitly defines mime types for imports. My browser is blocking all javascript module imports due to the server serving them as (“text/plain”). I realize this is a simple configuration issue, but I cannot seem to find where to set it. Any assistance provided is greatly appreciated. The console error shown below with my python 'app'.
I am running Win10 x64, Firefox 73.0 (64-bit), Python 3.7, uvicorn 0.11.2, and starlette 0.13.1. 
I also posted this in the uvicorn issues.

![image](https://user-images.githubusercontent.com/40573975/74674149-9ca7a280-5165-11ea-96d7-0b56c76fffe7.png)

```python 
from starlette.applications import Starlette
from starlette.staticfiles import StaticFiles
from starlette.responses import HTMLResponse
from starlette.templating import Jinja2Templates
import uvicorn
from random import randint

port = randint(49152,65535)

templates = Jinja2Templates(directory='templates')

app = Starlette(debug=True)
app.mount('/static', StaticFiles(directory='statics'), name='static')


@app.route('/')
async def homepage(request):
    template = "index.html"
    context = {"request": request}
    return templates.TemplateResponse(template, context)


@app.route('/error')
async def error(request):
    """
    An example error. Switch the `debug` setting to see either tracebacks or 500 pages.
    """
    raise RuntimeError("Oh no")


@app.exception_handler(404)
async def not_found(request, exc):
    """
    Return an HTTP 404 page.
    """
    template = "404.html"
    context = {"request": request}
    return templates.TemplateResponse(template, context, status_code=404)


@app.exception_handler(500)
async def server_error(request, exc):
    """
    Return an HTTP 500 page.
    """
    template = "500.html"
    context = {"request": request}
    return templates.TemplateResponse(template, context, status_code=500)


if __name__ == "__main__":
    uvicorn.run("app-567:app", host='0.0.0.0', port=port, access_log=True, http='h11', loop='asyncio', reload=True)
```

**Comment by jbsetton** [comment]
I think the _mimetypes_ standard library on windows doesn't properly locate the correct dictionary of all known types resulting in some files being mischaracterized as ("text/plain"). To get around this issue, I forcibly imported, initiated and added keys to _mimetypes_ 
```
import mimetypes
mimetypes.init()
```
and here:
```
@app.route('/')
async def homepage(request):
	mimetypes.add_type('application/javascript', '.js')
	mimetypes.add_type('text/css', '.css')
	mimetypes.add_type('image/svg+xml', '.svg')
	template = "index.html"
	context = {"request": request}
	return templates.TemplateResponse(template, context, media_type='text/html')
```
And the resulting web app correctly serves the files as the appropriate MIME content type.

**Comment by lovelydinosaur** [comment]
> I think the mimetypes standard library on windows doesn't properly locate the correct dictionary of all known types resulting in some files being mischaracterized as ("text/plain"). To get around this issue, I forcibly imported, initiated and added keys to mimetypes

Okay, so a useful thing to do here would be to start by confirming that.

Want to try opening up python in a console, and just using...

```python
from mimetypes import guess_type

print(guess_type("something.js"))
print(guess_type("something.css"))
print(guess_type("something.svg"))
```

If there *is* an issue with mimetypes support being pretty unreliable, then we could take a look at including some defaults for basic HTML related content.

**Comment by Xevion** [comment]
While looking for solutions to a related problem concerning content types and the `mimetypes` module, I found this issue.
[This issue](https://github.com/pallets/flask/issues/1045) from the Flask web framework details a investigation to why the `mimetypes` module was being unreliable. Very interesting.

**Comment by carc1n0gen** [comment]
If on windows, it's a windows registry issue.  See the issue linked by @Xevion above me for more information about the registry.  On windows, python relies fully on the registry for the mime types 

EDIT additional info:

I had a similar issue at one point for just css files.  I had to edit the windows registry key `HKEY_CLASSES_ROOT/.css/Content Type` back to `text/css` because the VIsualStudio (**Not** visual studio code) installer had messed it up.  I only blame VisualStudio because I work on flask apps every day, and it happened right after installing VisualStudio.
