### ISSUE TITLE
Channel to discuss contribution/feature ideas?

### ISSUE THREAD

**Issue by Kamforka** [Kludex/starlette#830]
Hi folks,

I'm just interested if there is an official channel to discuss enhancements and new features for starlette other than github issues?

Is there an already established Slack/Discord/Gitter channel for such purposes?

If not then I think it would totally make sense to share PoCs and premature ideas in one of those rather than polluting the threads in here?

What do you think?

**Comment by lovelydinosaur** [comment]
Yup absolutely... https://gitter.im/encode/community

Tho we *really* need to start linking to it from READMEs and docs

**Comment by lovelydinosaur** [comment]
Also https://discuss.encode.io/

**Comment by lovelydinosaur** [comment]
We're live... https://www.starlette.io/
