### ISSUE TITLE
Authentication Middleware Default Required

### ISSUE THREAD

**Issue by jimcarreer** [Kludex/starlette#831]
Is there anyway I can default all endpoints to require authentication instead of explicitly requiring it on every endpoint?  I mean a use case for most applications is that only a small subset of endpoints **do not** require authentication, and I haven't yet found documentation that lets me say "by default an endpoint should require authentication, and only when annotated with `@somedecorator` should a  no authentication be allowed".  This was extremely easy to do in flask.

**Comment by lovelydinosaur** [comment]
Discussed in chat here... https://gitter.im/encode/community?at=5e4d0192a0aa6629f5daad41
