### ISSUE TITLE
Add `allow_origin_regex` to CORSMiddleware.

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#84]
It'd be helpful if `CORSMiddleware` supported an `allow_origin_regex`, so that users could do...

```python
# Enforce a subdomain CORS policy
app.add_middleware(CORSMiddleware, allow_origin_regex="(http|https)://*.example.com")
```

Or...

```python
# Enforce an HTTPS-only CORS policy.
app.add_middleware(CORSMiddleware, allow_origin_regex="https://*")
```

The string should be compiled to a regex by the middleware and matches should be anchored to the start/end of the origin string.

**Comment by lovelydinosaur** [comment]
Could be a good one for contributions.

**Comment by alexbotello** [comment]
Perhaps we could add a `matches` method?
```python
def matches(self, scope, origin):
    self.allow_origins = []
    regex = re.compile(self.allow_origin_regex)
    match = regex.match(origin)
    
    if match:
        self.allow_origins.append(origin)
        self.simple_headers["Access-Control-Allow-Origin"] = origin
        return functools.partial(self.simple_response, scope=scope, origin=origin)
    return PlainTextResponse(
        "Disallowed CORS origin", status_code=400,
    )
```
Then we can call it before preflight_response after the origin check
```python
if origin is not None:
    if self.allow_origin_regex is not None:
        return self.matches(scope=scope, origin=origin)
```

**Comment by lovelydinosaur** [comment]
I guess this line `if requested_origin in self.allow_origins:` should be:

`if self.is_allowed_origin(origin)`

Then we can have a `is_allowed_origin(origin: str) -> bool` method which defaults to `origin in self.allowed_origins or self.origin_regex.match(origin)` or something like that.

**Comment by alexbotello** [comment]
Ah, I see. That's a much better idea. I'll try it out and submit a PR soon.
