### ISSUE TITLE
Return 401 on authentication error

### ISSUE THREAD

**Issue by Colin-b** [Kludex/starlette#840]
Shouldn't the default return code on authentication failure be a 401 instead of a 400? https://github.com/encode/starlette/blob/78f7095d7e254940fe242e72055f3d0d7883b405/starlette/middleware/authentication.py#L52

Unless this is because you cannot know what to send back in WWW-Authenticate header ?

**Comment by lovelydinosaur** [comment]
It's using a 400 there since it's for an error condition (400), rather than authentication failed condition (403).

Could possibly go either way here, but it'd need some thinking over, and it's probably reasonable enough at the moment.

**Comment by jketcham** [comment]
This is an oldy, but for what it's worth, I would vote to default the error code returned for exceptions (in the authentication middleware) to be 401. 

Or perhaps in the `default_on_error` method, there could be a check that the exception is an instance of an `AuthenticationError` before returning a 401.
