### ISSUE TITLE
Unclear how to add middleware to a subset of routes

### ISSUE THREAD

**Issue by akdor1154** [Kludex/starlette#844]
Middleware seems to be designed to apply to my app as a whole and not to certain routes.

Use case 1: I'd like to have CORS behaviour be different depending on which route gets hit (frontend or api). Presently this seems impossible (unless I'm mistaken?)
Use case 2: (you may consider this one to be a bit dodgy): I'd like to write my auth layer as a custom middleware and not using Starlette's Auth system, and I don't want to have to re-implement the @requires system.

EDIT: Sorry, looks like a dupe of #587 .

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/844">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/844/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/844/pledge.svg">
</picture>
</a>

**Comment by lovelydinosaur** [comment]
Yeah we don't currently have any mechanism to support this.
Not really sure if we should, or what it would look like if we did.

Will close this in favour of #587 for now.
