### ISSUE TITLE
@requires with @app.route order matters

### ISSUE THREAD

**Issue by rostrovsky** [Kludex/starlette#846]
When `@requires` decorator is used along with `@app.route`, their order matters. Wrong order causes lack of authorization check.

I am using Starlette `0.13.2`

**Works correctly:**
```python
@app.route("/data", methods=["GET"])
@requires("authenticated")
async def data(request):
    # ...
```
**Doesn't work (allows unauthorized access):**
```python
@requires("authenticated")
@app.route("/data", methods=["GET"])
async def data(request):
   # ...
```

I am not sure if this is something that can be easily fixed. If not maybe it should be marked as warning in documentation.

**Comment by lovelydinosaur** [comment]
Yup indeed - that is awkward.

We're no longer documenting the `@app.route()` style anywhere in the docs, in favour of the declarative routing style. I'd recommend users switch to that wherever possible.

https://www.starlette.io/routing/
