### ISSUE TITLE
Add `UJSONResponse`

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#85]
Should we consider dropping the implicit use of `ujson`, and instead include a `UJSONResponse` class so that it needs to be used *explicitly* instead? I'd tend to think that by default you'll want to prefer using the stdlib `json` since it's a bit tighter on it's behaviour when eg. handling unexpected types.

It might well make sense to only use `ujson` explicitly (so eg. users can switch to it if they have particular known endpoints that're already well-tested but have a non-insignificant serialization overhead).

(In micro-benchmarking ujson is super important, but in real use-cases it generally isn't.)

**Comment by Midnighter** [comment]
I definitely support that idea. Might even try my hands on a PR. In my opinion, being explicit (1) follows the Zen of Python and (2) means that it's an opt-in feature. The downside possibly being that starlette is maintaining code that few people use?

**Comment by lovelydinosaur** [comment]
> The downside possibly being that starlette is maintaining code that few people use?

Not really concerned. Oughta just be a JSONResponse subclass with an overridden render method.

**Comment by jeffbuttars** [comment]
I prefer rapidjson myself. So a nice way to drop in a JSON parser of choice would be great.
