### ISSUE TITLE
Distributing `LICENSE.md` using `data_files` can be problematic.

### ISSUE THREAD

**Issue by slavaGanzin** [Kludex/starlette#850]
Hello. While installing in virtualenv I got:
```
pip install starlette

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/LICENSE.md'
Consider using the `--user` option or check the permissions.
```

Why in the hell you should write your license in my /usr?

**Comment by lovelydinosaur** [comment]
> /usr/LICENSE.md WTF? 

Nope, not an acceptable way to frame the issue.
Try a more professional tone in the future, please.

We [reference 'LICENSE.md' in our setup.py here](https://github.com/encode/starlette/blob/master/setup.py#L50).

It's unclear why that would install under `/usr`, and I've not been able to see other issues with projects installing from `data_files`. Installing into a virtualenv or presumably with `--user` would resolve the issue, but you shouldn't be having to do that.

We'll clearly need to change how the LICENSE is distrbuted along with the source. With REST framework we're using `MANIFEST.in` and `setup.cfg` for the configuration, which is a bit verbose. For something more minimal perhaps it'd be worth us considering switching to flit.

Which eg. FastAPI are using https://github.com/tiangolo/fastapi/blob/master/pyproject.toml

**Comment by samuelcolvin** [comment]
I had the same frustration, but it turns out there's no way around adding a `MANIFEST.in` file (at least when distributing with `setup.py` etc.).

It's annoying but much simpler than a wholesale move to `pyproject.toml` and friends.

**Comment by PhotonQuantum** [comment]
Well, I believe this **is** a mistake in packaging.
If you try to install this package in virtualenv, you will get
``` shell script
$ python -m venv venv
$ source ./venv/bin/activate
$ pip install starlette
$ ls venv
  bin ... LICENSE.md ... pyvenv.cfg
```
And if you install this package with `--user`, you get
``` shell script
$ pip install --user starlette
$ ls ~/.local
  lib share ... LICENSE.md
```
I assume that it's not the intended behaviour.

And this package is creating file conflicts on Archlinux:
``` shell script
# building python-starlette and python-uvicorn from aur...
$ makepkg
...
$ sudo pacman -U python-starlette-*.tar.gz python-uvicorn-*.tar.gz
...
/usr/LICENSE.md exists in both 'python-starlette' and 'python-uvicorn'.
```
, which indicates that `uvicorn` has the same packaging issue.

**Comment by tonybenoy** [comment]
I think #895 solved this. @tomchristie could you maybe do a minor release?

**Comment by lovelydinosaur** [comment]
Yup - Done as 0.13.3.

**Comment by tonybenoy** [comment]
Awesome! Thanks @tomchristie
