### ISSUE TITLE
Cancel or stop a StreamingResponse

### ISSUE THREAD

**Issue by keepsimple1** [Kludex/starlette#854]
Is there a way to cancel (i.e. stop) a `StreamingResponse` ?

For example, a client requests for a video resource with `range 0-999999/1000000` header, and the server sends back a `StreamingResponse`.  The client might cancel the request, sends a new request with a different `range 46000-500000/1000000`.  Is there a way to stop the 1st `StreamingResponse`?   Assuming the same HTTP connection has been used (particularly in using QUIC).

**Comment by oczkers** [comment]
If i'm not mistaked after [this commit](https://github.com/encode/starlette/commit/3de541cfe299a2a6a3741937633c81ad99d65a6a) if client closes connection server stops streaming also, whole request gets closed.

**Comment by lovelydinosaur** [comment]
Thanks @oczkers, yup. Closed via #839
