### ISSUE TITLE
Selective Signing - Session Middleware

### ISSUE THREAD

**Issue by AndTheDaysGoBy** [Kludex/starlette#855]
Am I correct in that the session middleware does not allow for selective encryption? I do not think so due to https://github.com/encode/starlette/blob/f9fad62b45380c6a3d0105bdc25d45342caa010b/starlette/middleware/sessions.py#L55 but I though I'd ask.
E.g. I want to return a token and a username to my frontend application, i.e. `request.session = {'username': 'Bob', 'token': 'random'}`. I want my frontend application to be able to render the username on the screen, however, it has no access to this value (since it's encrypted).
I could give my frontend the secret key used by the backend, but that sort of defeats the purpose of signing, in my view.

**Comment by lovelydinosaur** [comment]
Indeed yup. Easiest way around is probably to use response cookies for that functionality, rather than the session itself.
