### ISSUE TITLE
UJSONResponse and JSONResponse produce different results

### ISSUE THREAD

**Issue by Spacehug** [Kludex/starlette#856]
UJSONResponse uses `ujson.dumps(content, ensure_ascii=False)`, but default for ujson is to also escape forward slashes. The result is that UJSONResponse and JSONResponse produce different results:
```
>>> import json
>>> import ujson
>>> s = "https://google.com/"
>>> print(json.dumps(s))
"https://google.com/"
>>> print(ujson.dumps(s))
"https:\/\/google.com\/"
```

`escape_forward_slashes=False` can be added to UJSONResponse to fix that:
```
class UJSONResponse(JSONResponse):
    media_type = "application/json"

    def render(self, content: typing.Any) -> bytes:
        assert ujson is not None, "ujson must be installed to use UJSONResponse"
        return ujson.dumps(content, ensure_ascii=False, escape_forward_slashes=False).encode("utf-8")
```

**Comment by em92** [comment]
Any usecase of running json.dump with string argument?

**Comment by Spacehug** [comment]
@em92 I am.. unsure how to answer. https://github.com/encode/starlette/blob/master/starlette/responses.py#L153-L171
shows that JSONResponse and UJSONResponse use .dumps()

So each time we return either JSONResponse or UJSONResponse from HTTPEndpoint, .dumps is being called, usually on a dictionary:
```
>>> import json
>>> import ujson
>>> data = {"message": "https://google.com/"}
>>> json.dumps(data)
'{"message": "https://google.com/"}'
>>> ujson.dumps(data)
'{"message":"https:\\/\\/google.com\\/"}'
```

**Comment by lovelydinosaur** [comment]
There'll be a bunch of other cases where the output or behavior differs too.

I'd really like us to drop `UJSONResponse`, in favour of allowing third party pacakges or snippet examples for non-stdlib JSON implementations.

**Comment by rugleb** [comment]
ujson has not been updated for a long time and is hopelessly outdated. What about or [orjson](https://github.com/ijl/orjson)?

**Comment by lovelydinosaur** [comment]
@rugleb - Yup, there's nothing much to implementing an ORJSONResponse, eg... https://github.com/tiangolo/fastapi/blob/master/fastapi/responses.py

(Although as with UJSONResponse I'd actually rather see these outside the core Starlette pacakge)

**Comment by rugleb** [comment]
> @rugleb - Yup, there's nothing much to implementing an ORJSONResponse, eg... https://github.com/tiangolo/fastapi/blob/master/fastapi/responses.py
> 
> (Although as with UJSONResponse I'd actually rather see these outside the core Starlette pacakge)

I agree, but what about `dumps` param like in [aiohttp](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_response.py#L711)?

**Comment by rugleb** [comment]
> ujson has not been updated for a long time and is hopelessly outdated. What about or [orjson](https://github.com/ijl/orjson)?

WOW! [ujson](https://github.com/ultrajson/ultrajson) is alive! [v2.0.0](https://github.com/ultrajson/ultrajson/releases/tag/2.0.0)!

**Comment by lovelydinosaur** [comment]
Given that `UJSONResponse` is in a "we ought to drop this from core" I'd like to close this off.
Third party implementations would be most welcome.
