### ISSUE TITLE
Return a TemplateResponse  with an `url_for` from middleware

### ISSUE THREAD

**Issue by phineas0fog** [Kludex/starlette#859]
Hello all :)

I want to make a middleware that redirect to the login page if the request has no session (with the session middleware).

So I do this:

```python
class AuthMiddleware(BaseHTTPMiddleware):
    async def __call__(self, scope, receive, send):

        request = Request(scope, receive=receive)

        return templates.TemplateResponse("login.html", {
            "request": request,
            "errormsg": "You had to login to continue"
        })

```

But I got this error: 
```
<path_to_venv>/starlette/requests.py", line 136, in url_for
    router = self.scope["router"]
KeyError: 'router'
```

So what I need to do to make the `url_for` working from here ?

**Comment by erewok** [comment]
Try this:

```python
if "app" in scope:
    scope['app'].url_path_for("login")
```

**Comment by erewok** [comment]
There's also a [`redirect` kwarg](https://www.starlette.io/authentication/#permissions) for the `requires` decorator, which you can use:

```python
from starlette.authentication import requires


@requires("authenticated", redirect="login")
async def some_protected_endpoint(request):
   ...
```

**Comment by erewok** [comment]
Closing this one. Let us know in the community discussion if you still need assistance: https://gitter.im/encode/community
