### ISSUE TITLE
QueryParams support for parameter without value

### ISSUE THREAD

**Issue by bendikro** [Kludex/starlette#860]
[QueryParams](https://github.com/encode/starlette/blob/852181a5c0aa25c5e14574a21acdb3c10acb7839/starlette/datastructures.py#L380) currently supports only query parameters with a value, however, query parameters without a value are still be valid and should be supported?

```
#!/usr/bin/env python
from starlette.datastructures import QueryParams

with_value = QueryParams('param=value')
print("with_value:", with_value)

without_value = QueryParams('param')
print("without_value:", without_value)
```
Result:
```
with_value: param=value
without_value:
```

Expected result:
```
with_value: param=value
without_value: param
```

Any comments on this?

**Comment by lovelydinosaur** [comment]
Yup, that's surprising - ought to map to an equievelent of `{"param": ""}`

**Comment by lovelydinosaur** [comment]
I suppose it works properly with eg. `param=`, but it also ought to work in the case you've provided.

**Comment by bendikro** [comment]
@tomchristie 
Umm...it seems I wasn't testing with the latest code. This was already fixed in https://github.com/encode/starlette/pull/672
