### ISSUE TITLE
How is the table created in the database documentation example?

### ISSUE THREAD

**Issue by gduverger** [Kludex/starlette#861]
In the database documentation (https://github.com/encode/starlette/blob/master/docs/database.md), I fail to understand where is the table actually created. When I try to reproduce the example (with `sqlite`), I get: `sqlite3.OperationalError: no such table: notes`. I'm probably missing an obvious piece. Help would be greatly appreciated. Thanks.

**Comment by gduverger** [comment]
By looking at the Test documentation (https://github.com/encode/starlette/blob/6a65461c6e13d0a55243c19ce5580b1b5a65a770/docs/database.md#test-isolation), it looks like I need to run the following line to create the tables:

    engine = create_engine(url)
    # sqlalchemy.create_database(url)
    metadata.create_all(engine)

Is there a recommended way to integrate those in a Starlette app workflow?

**Comment by lovelydinosaur** [comment]
At the moment I'd probably recommend looking at Alembic for creating tables and migrations. There's some docs about the here: https://www.starlette.io/database/#Migrations
