### ISSUE TITLE
Is it possible to disable access logging on certain endpoints?

### ISSUE THREAD

**Issue by taybin** [Kludex/starlette#864]
I have a /health endpoint that is checked every minute and it bloats the logs.  I'd like to turn off that off, but keep logging the accesses to other endpoints (and especially any exceptions).  Is that possible currently?

**Comment by erewok** [comment]
I had the same issue, so I switched `gunicorn` and `uvicorn` loggers to `warn`:

```
[logger_gunicorn]
level=WARNING
handlers=access_handler
propagate=0
qualname=gunicorn

[logger_uvicorn]
level=WARNING
handlers=access_handler
propagate=0
qualname=uvicorn
```

In my own custom loggers used by my app, I have a logging config like this:

```python
PRODUCTION_LOGGING_CONFIG = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {"json": {"class": "my_app.plumbing.loggers.MyJsonLogFormatter"}},
    "handlers": {
        "info": {"level": "INFO", "class": "logging.StreamHandler", "formatter": "json"},
        "warn": {"level": "WARNING", "class": "logging.StreamHandler", "formatter": "json"}
    },
    "loggers": {
        "": {"handlers": ["info"], "level": "INFO", "propagate": False,},
        "uvicorn": {"handlers": ["warn"], "level": "INFO", "propagate": False,},
    },
}
```

**Comment by taybin** [comment]
@erewok Does that disable all the logging at the INFO level?

**Comment by erewok** [comment]
No, because the root-level logger is still at INFO:

```
"": {"handlers": ["info"], "level": "INFO", "propagate": False,},
```

Also, for completeness, I instantiate it in my app like this:

```python
import logging.config
logging.config.dictConfig(PRODUCTION_LOGGING_CONFIG)
```

**Comment by taybin** [comment]
@erewok I'm sorry, I'm just not seeing where you specify the endpoint to not log in the config(s).

**Comment by erewok** [comment]
Apologies, but I probably misunderstood. You want to keep access logging but just not log for `/health`? My mistake: I turned off access logging entirely because my application has a lot of other logs inside the endpoints and also have logs from our reverse proxy for access.

**Comment by taybin** [comment]
Well, now I know to look at uvicorn's logging instead of starlette's.  Thanks, @erewok!

**Comment by taybin** [comment]
Closing this in favor of https://github.com/encode/uvicorn/pull/515.

**Comment by euri10** [comment]
It's totally possible
Just do something like this

 
```
class HealthCheckFilter(logging.Filter):
    def filter(self, record):
        return record.getMessage().find("/healthcheck") == -1
```
then use it in your logging dict or yaml with
```
filters:
  healthcheck_filter:
    "()": applog.utils.HealthCheckFilter
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        filters:
            - healthcheck_filter
        stream: ext://sys.stdout
```

**Comment by HarrySky** [comment]
@euri10 your great solution can be implemented like that as well :smile: 

```python
class EndpointFilter(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:
        return record.getMessage().find("/endpoint") == -1

# Filter out /endpoint
logging.getLogger("uvicorn.access").addFilter(EndpointFilter())
```

Will leave it here for reference in case there are people who don't want to deal with log config file

**Comment by petit-aigle** [comment]
### More precision for filtering
**For completing the solution of @euri10**

`record.getMessage()` return all the chain of the message who will be logger, which can sometimes complicate filtering.
Example  `record.getMessage().find("/")  == -1` if i want to filter the route '/', all paths will be excluded.

**Below is a solution to filter with more precision**
_In this example, we want to exclude "/" and "/robots.txt" only for the GET method_
```python
class HealthCheckFilter(logging.Filter):
    def filter(self, record):
        # remote_address = record.args[0]
        request_method = record.args[1]
        query_string = record.args[2] # complete query string (so parameter and other value included)
        # html_version = record.args[3]
        # satuts_code = record.args[4]

        return request_method == 'GET' and not query_string in [
            "/",
            "/robots.txt",
        ]
```

In my case I only need request_method and query_string, the other values in comment will probably be useful to you ;)

**Comment by richarddevers** [comment]
The generic version of what @euri10 and @HarrySky proposed:
```python
import logging
import typing as t


class EndpointFilter(logging.Filter):
    def __init__(
        self,
        path: str,
        *args: t.Any,
        **kwargs: t.Any,
    ):
        super().__init__(*args, **kwargs)
        self._path = path

    def filter(self, record: logging.LogRecord) -> bool:
        return record.getMessage().find(self._path) == -1

uvicorn_logger = logging.getLogger("uvicorn.access")
uvicorn_logger.addFilter(EndpointFilter(path="/livez"))
uvicorn_logger.addFilter(EndpointFilter(path="/readyz"))

```

**Comment by johnthagen** [comment]
@richarddevers's [solution](https://github.com/encode/starlette/issues/864#issuecomment-1254987630) worked great for me.

In my case, I needed to filter logs from websocket connections, which required changing the logger name to `"uvicorn.error"`:

```py
uvicorn_logger = logging.getLogger("uvicorn.error")
```

- https://github.com/encode/uvicorn/blob/3924ef4d48a5778d3465666bb898245dbfbf8fe5/uvicorn/protocols/websockets/wsproto_impl.py#L61
- https://github.com/encode/uvicorn/blob/3924ef4d48a5778d3465666bb898245dbfbf8fe5/uvicorn/protocols/websockets/wsproto_impl.py#L274

**Comment by doglex** [comment]
Another Way
``` python
import logging
from uvicorn.config import LOGGING_CONFIG

class MyFilter(logging.Filter):
    def filter(self, record):
        return record.getMessage().find("/my_endpoint") == -1

LOGGING_CONFIG["filters"] = {'f1': {'()': MyFilter}}
LOGGING_CONFIG["handlers"]["access"]['filters'] = ['f1']
```

**Comment by paikend** [comment]
```Python

import logging

class EndpointFilter(logging.Filter):
    _allowed_methods = {
        "GET",
        "POST",
        "PUT",
        "PATCH",
        "DELETE",
        "HEAD",
        "OPTIONS",
        "TRACE",
    }

    def __init__(self, exclude_path: str, exclude_method: str):
        if not exclude_path.startswith("/"):
            raise ValueError("exclude_path must start with '/'")
        if exclude_method not in self._allowed_methods:
            raise ValueError(f"Invalid method: {exclude_method}")

        self.exclude_path = exclude_path
        self.exclude_method = exclude_method

    def filter(self, record: logging.LogRecord) -> bool:
        if record.args and len(record.args) >= 3:
            method = record.args[1]
            path = record.args[2]
            if path == self.exclude_path and method == self.exclude_method:
                return False
        return True

logging.getLogger("uvicorn.access").addFilter(
    EndpointFilter(exclude_path="/health", exclude_method="GET")
)
```
