### ISSUE TITLE
[bug] Invalid cookie name leads to exception

### ISSUE THREAD

**Issue by aviramha** [Kludex/starlette#866]
When handling a request with an invalid cookie name (does not conform to RFC2109) starlette raises an exception. i.e iam/cookiename
This is because Starlette uses Python's stdlib cookie library, which is very strict.
I do understand the strictness, but in real life scenarios you receive such malformed cookies and I want to handle those requests.
My suggestion for a solution would be to catch those exceptions and ignore the invalid cookie. 
** EDIT **
I just realized stdlib is used for the whole cookie header, hence can't ignore only one cookie.
I'll create a PR for ignoring the whole cookie on such case, but maybe we should create our own Cookie/Morsel class and override the methods to ignore such error in the inbound case?

**Comment by florimondmanca** [comment]
I’m always a bit wary of encouraging broken behaviors... Eg even Django just ignores invalid cookies, preventing developers from processing them: https://github.com/django/django/commit/30bdabb2b0

Can you solve your use case with a custom middleware that converts the broken cookie into a valid one?

**Comment by aviramha** [comment]
> I’m always a bit wary of encouraging broken behaviors... Eg even Django just ignores invalid cookies, preventing developers from processing them: [django/django@30bdabb](https://github.com/django/django/commit/30bdabb2b0)
> 
> Can you solve your use case with a custom middleware that converts the broken cookie into a valid one?

Thanks for your feedback. I assume a middleware is OK if I want to process invalid cookie.
Do you have any feedback on the PR itself maybe? Right now in case of invalid cookie it ignores it.
