### ISSUE TITLE
Get response body in Middleware

### ISSUE THREAD

**Issue by rugleb** [Kludex/starlette#874]
How do I get the response body from the `StreamingResponse` object in middleware?

Simple example:
```
class AccessMiddleware(base.BaseHTTPMiddleware):

    async def dispatch(
        self,
        request: Request,
        handler: base.RequestResponseEndpoint,
    ) -> Response:
        response: StreamingResponse = await handler(request)

        binary = b''
        async for data in response.body_iterator:
            binary += data
        body = binary.decode()
        
        print(body)

        return response  # Here body is empty
```
Is it possible to copy the `response.body_iterator` generator?  
What is the best way to solve the problem of extracting final data (`response body`) and further post-processing?

Thanks.

**Comment by lswest** [comment]
I had the same question recently. Unfortunately, you can't copy a generator in Python. Instead, I just created a new response in my return statement (`return JSONResponse(content=jsonBody, status_code=response.status_code)`). Doesn't seem ideal, but it works. In my case it was json, so I converted the bytes object to string then ran it through `json.loads`.

Hopefully this will work for you? Bonus info - make sure this middleware comes before the gzip one (if you're using it) otherwise you won't be able to parse the body.

**Comment by rugleb** [comment]
Hi, @lswest! I solved my problem in the same way, also did not come up with anything better. I'm not sure there's a more elegant solution. Here is my complex solution: [pastebin](https://pastebin.com/C7xit64J).

**Comment by Ronserruya** [comment]
Not sure if this is still relevant, but I also made a custom middleware that allows access to the response body, it just changes the response type from streaming response to json response (pretty much a copy-paste from the existing method, just the final lines are different )

https://gist.github.com/Ronserruya/75cd899307393fc1825b9c5cdb038187

**Comment by RadoslawB** [comment]
> Hi, @lswest! I solved my problem in the same way, also did not come up with anything better. I'm not sure there's a more elegant solution. Here is my complex solution: [pastebin](https://pastebin.com/C7xit64J).

No longer valid pastebin

**Comment by rugleb** [comment]
> > Hi, @lswest! I solved my problem in the same way, also did not come up with anything better. I'm not sure there's a more elegant solution. Here is my complex solution: [pastebin](https://pastebin.com/C7xit64J).
> 
> No longer valid pastebin

I don't remember exactly what was there, but [here is an example](https://github.com/rugleb/Vertical/blob/master/vertical/app/middlewares.py#L152) of how I used it in my project

**Comment by guaccc** [comment]
@rugleb I can't figure out why but sometimes the bytes returned in the body don't properly decode and throw an error like `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 5: invalid continuation byte`

Did you run into that or any idea what could cause it or how to debug? Strangely it sometimes works as expected and shows the json result but without any modification...

**Comment by BC30138** [comment]
Just because such solution not stated yet, but it's worked for me:

```python
from typing import Callable, Awaitable

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import StreamingResponse
from starlette.concurrency import iterate_in_threadpool

class LogStatsMiddleware(BaseHTTPMiddleware):
    async def dispatch(  # type: ignore
        self, request: Request, call_next: Callable[[Request], Awaitable[StreamingResponse]],
    ) -> Response:
        response = await call_next(request)
        response_body = [section async for section in response.body_iterator]
        response.body_iterator = iterate_in_threadpool(iter(response_body))
        logging.info(f"response_body={response_body[0].decode()}")
        return response

def init_app(app):
    app.add_middleware(LogStatsMiddleware)
```

`iterate_in_threadpool` actually making from iterator object async Iterator

If you look on implementation of `starlette.responses.StreamingResponse` you'll see, that this function used exactly for this

**Comment by AmmarAhmadKhan** [comment]
> Just because such solution not stated yet, but it's worked for me:
> 
> ```python
> from typing import Callable, Awaitable
> 
> from starlette.middleware.base import BaseHTTPMiddleware
> from starlette.requests import Request
> from starlette.responses import StreamingResponse
> from starlette.concurrency import iterate_in_threadpool
> 
> class LogStatsMiddleware(BaseHTTPMiddleware):
>     async def dispatch(  # type: ignore
>         self, request: Request, call_next: Callable[[Request], Awaitable[StreamingResponse]],
>     ) -> Response:
>         response = await call_next(request)
>         response_body = [section async for section in response.body_iterator]
>         response.body_iterator = iterate_in_threadpool(iter(response_body))
>         logging.info(f"response_body={response_body[0].decode()}")
>         return response
> 
> def init_app(app):
>     app.add_middleware(LogStatsMiddleware)
> ```
> 
> `iterate_in_threadpool` actually making from iterator object async Iterator
> 
> If you look on implementation of `starlette.responses.StreamingResponse` you'll see, that this function used exactly for this

response_body[0].decode() Gives error if we return some fields with value of true or false and says "name true is not defined". How to get rid of this issue ?
