### ISSUE TITLE
Move app specific attributes from HTTPConnection to a mixin

### ISSUE THREAD

**Issue by alex-oleshkevich** [Kludex/starlette#879]
Currently HTTPConnection class includes methods like "user", "auth", "app" which depend on Starlette's infrastructure. It needs some middleware to set appropriate keys to the scope.

I suggest moving `app`, `session`, `auth`, `user` from HTTPConnection class into a separate mixin. Then we can add this mixin to HTTP and WebSocket request classes separately. 

This will let other frameworks inherit HTTPConnection and add own implementations of these features or keep request API clean if they don't need it.

If it makes sense I'll be happy to PR it.

**Comment by lovelydinosaur** [comment]
Thanks, but I'm not really in favour of the indirection that'd add.

By all means let's ensure that they're well documented, and have sensible fallback behaviours.

Also worth checking out our new contribution guidelines... https://github.com/encode/.github/blob/master/CONTRIBUTING.md
