### ISSUE TITLE
Relative path used for Jinja2Templates and StaticFiles

### ISSUE THREAD

**Issue by wh6b** [Kludex/starlette#882]
Hello,
Is it normal that relative paths used to declare Jinja2Templates(directory='relative/path') and StaticFiles('relative/staticdir') are inherited of current directory from which I start the application and not the starlette application directory ?

To fix it i wrote,
```python
parent_dir_path = os.path.dirname(os.path.realpath(__file__))
os.chdir(parent_dir_path)
```
and I can declare relative path from the application directory to be independant of OS current directory 
But is this behavior really wished ?

(if details needed  I launch starlette webapp inside a shell script with 
```bash
$ uvicorn myapp:my_app_Starlette_variable
```
myapp is the /src/app/app package  and my my_app_Starlette_variable is inside a __init__.py )

**Comment by lovelydinosaur** [comment]
Either way works, so I'm okay with it being documented as-is for now.
