### ISSUE TITLE
Add simple CDN example for static files

### ISSUE THREAD

**Issue by hnykda** [Kludex/starlette#884]
Hi, 

I am struggling with a simple task: "serve my static files from CDN (say, public google cloud storage)". In Django, I would simply do:
```
STATIC_URL = "https://googleapis..."
```

but I can't figure out how to deal with this in starlette (I am using fastapi)

Related:
* https://github.com/encode/starlette/issues/843
* https://github.com/encode/starlette/issues/873

**Comment by lovelydinosaur** [comment]
I'd suggest including `STATIC_URL` in your template contexts, and using `{STATIC_URL}/whatever.css` in the template.

You'll probably also want to do some config setup so that in development you serve from `http://127.0.0.1/statics` and include StaticFiles in that case.

**Comment by hnykda** [comment]
Thanks, that was my backup plan, I was hoping for solution with `url_for`. But understandable, thanks.

Do you think it would be worth it to add it into docs to static files section? Should I do a PR?
