### ISSUE TITLE
synchronous startup function blocking on a future hangs when TestClient is used as a context manager

### ISSUE THREAD

**Issue by cjw296** [Kludex/starlette#885]
Here's a brief reproducer:

```
def test_async_startup_hangs():

    async def foo():
        pass

    def blocking_foo():
        coro = foo()
        loop = asyncio.get_event_loop()
        future = asyncio.run_coroutine_threadsafe(coro, loop)
        return future.result()

    app = Starlette(on_startup=[blocking_foo])

    with TestClient(app) as client:
        pass
```

The test hangs on entering the context inside the blocking stuff inside `future.result`.

If I just do:

```
app = Starlette(on_startup=[foo])
```

...then `foo` isn't run at all by the `with TestClient` block.

**Comment by cjw296** [comment]
Right, so it seems like the intention is to support async startup callables, so this issue becomes much more of an edge case. I've filed the more important problem under https://github.com/encode/starlette/issues/886

**Comment by florimondmanca** [comment]
I think this can be closed, since as you mentioned async startup callables should be called directly, without any thread wrapping.

**Comment by cjw296** [comment]
Not so sure, it's definitely not important, but there's still an edge case here where blocking on a future doesn't appear to work in a startup function.

**Comment by Kludex** [comment]
At the time this issue was created, Starlette was still didn't have `anyio` as dependency. Today, you can run blocking code with [`anyio.to_thread`](https://anyio.readthedocs.io/en/stable/threads.html?highlight=to_thread#running-a-function-in-a-worker-thread).
