### ISSUE TITLE
We need named routes

### ISSUE THREAD

**Issue by nandoflorestan** [Kludex/starlette#896]
As far as I can see, Starlette does not support named routes.

Named routes are probably the first feature I look for in a web framework.  I trust everyone here is familiar with the reason (basically decoupling URLs from everything else and making URLs easy to change), but if not, here's an explanation:
https://stackoverflow.com/a/52231573

**Comment by erewok** [comment]
I am using named routes extensively in my Starlette projects. [See the docs](https://www.starlette.io/routing/#reverse-url-lookups)

**Comment by nandoflorestan** [comment]
Thank you!

(Note to self: do not open tickets at 3 AM)
