### ISSUE TITLE
Compliance with ASGI specification.

### ISSUE THREAD

**Issue by Dnomin** [Kludex/starlette#906]
I recently started reading ASGI documentation and in the middlewares section I read that middleware should never modify the scope object.

[docs#middlewares](https://asgi.readthedocs.io/en/latest/specs/main.html#middleware)
 
>When middleware is modifying the scope, it should make a copy of the scope object before mutating it and passing it to the inner application, as changes may leak upstream otherwise. 

But in [session middleware](https://github.com/encode/starlette/blob/master/starlette/middleware/sessions.py#L43):

```python
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):  # pragma: no cover
            await self.app(scope, receive, send)
            return

        connection = HTTPConnection(scope)
        initial_session_was_empty = True

        if self.session_cookie in connection.cookies:
            data = connection.cookies[self.session_cookie].encode("utf-8")
            try:
                data = self.signer.unsign(data, max_age=self.max_age)
                scope["session"] = json.loads(b64decode(data))
                initial_session_was_empty = False
            except (BadTimeSignature, SignatureExpired):
                scope["session"] = {}
        else:
            scope["session"] = {}
```

You are not making a copy of the object.

Am I misunderstood something?

**Comment by lovelydinosaur** [comment]
Yep *strictly speaking* we're disregarding the spec in that area.
I'm okay with that, as there's a pragmatism/purity trade-off here.
