### ISSUE TITLE
New 3th party middleware for OpenTracing.io

### ISSUE THREAD

**Issue by acidjunk** [Kludex/starlette#910]
Thanks for a great project. Porting some older Flask app to FastAPI/Starlette as we speak.

As in some app's we used the tracing functionality of https://github.com/opentracing-contrib/python-flask and there didn't seem to exist an complete implementation for Starlette:

https://github.com/acidjunk/starlette-opentracing and https://pypi.org/project/Starlette-OpenTracing/

Feel free to close this ticket. I can cook up a PR if you want to add it to the Starlette Docs (section 3th party middleware)

**Comment by lovelydinosaur** [comment]
That's fantastic! Yes, please do open a PR adding it to the 3rd party docs.
