### ISSUE TITLE
Global configuration inside app

### ISSUE THREAD

**Issue by rohithkodali** [Kludex/starlette#914]
i'm looking for a way where we store some global values and use them in multiple classes,

tornado has a similar on tornado.web.Application
https://www.tornadoweb.org/en/stable/guide/structure.html#the-application-object

it can store variables and methods in it, which can be accessible in the entire app, is there anything similar available in starlette.

thanks in advance for the help.

**Comment by em92** [comment]
https://www.starlette.io/applications/

Use `app.state`
