### ISSUE TITLE
Sample required in docs for periodic timers

### ISSUE THREAD

**Issue by realsby** [Kludex/starlette#915]
I saw some hints in this issue https://github.com/encode/starlette/issues/202 , but it's not enough for me to see the big picture. I believe it's very important to have periodic tasks in a framework so if starlette have this feature you should put a sample into the docs.

**Comment by targyz** [comment]
@realsby I've been looking for solution for periodic tasks too, and after reading #202 issue I came up with this kind of implementation

```
import asyncio
from starlette.applications import Starlette


async def update_status():

    while True:
        # set sleep time before next task run

        await asyncio.sleep(3)

        # your task code goes here
        # e.g: await some_remote_api_call()

        print('task is running')


async def startup_event():
    loop = asyncio.get_event_loop()
    loop.create_task(update_status())


app = Starlette(
    on_startup=[startup_event],
)
```

Not sure if this one is a right way to do the job, but it works pretty good in my app.

**Comment by realsby** [comment]
@targyz thanks for sharing, that's enough for me.

but I still believe that, there is a huge value to have a simple periodic task feature in a framework which use cron expressions and should be very easy to register a function with a python decorator etc..

**Comment by targyz** [comment]
@realsby While framework itself does not support cron-like task scheduling, it is possible to use seasoned third-party package like APScheduler for scheduling and running simple lightweight tasks in event loop. 

```
from apscheduler.triggers.cron import CronTrigger
from starlette.applications import Starlette
from apscheduler.schedulers.asyncio import AsyncIOScheduler


async def cron_job():
    print('task is running')


async def startup_event():
    scheduler = AsyncIOScheduler()
    # run every minute
    scheduler.add_job(cron_job, CronTrigger.from_crontab('* * * * *'))
    scheduler.start()

app = Starlette(
    on_startup=[startup_event],
)
```


For heavy CPU/IO-bound tasks I would recommend to use Celery/Huey/RQ

**Comment by lovelydinosaur** [comment]
We'll add some docs if/when we've got a scheduling API.
Having `lifespan=...` instead of `on_startup`, `on_shutdown` will be an improvement in this area in any case, since it helps make it clearer where you'd want to start if you want to add some ongoing background processing. https://github.com/encode/starlette/pull/799

**Comment by tomchristie** [comment]
We'll add some docs if/when we've got a scheduling API.

Having `lifespan=...` instead of `on_startup`, `on_shutdown` will be an improvement in this area in any case, since it helps make it clearer where you'd want to start if you want to add some ongoing background processing. https://github.com/encode/starlette/pull/799

**Comment by choucavalier** [comment]
@lovelydinosaur reading your last comment, what is the recommended way to implement @targyz 's cron scheduling with lifespans?

**Comment by lovelydinosaur** [comment]
Hey Valentin, thanks so much for asking. I'm not in a position to be able to offer support currently.

If you do spend some time on this and have useful feedback please feel free to add any helpful pointers in this thread.

Wishing you well. ✨

**Comment by choucavalier** [comment]
Thanks for your reply @lovelydinosaur, for future reference, I decided to use https://github.com/dymmond/asyncz which deals with starlette lifespans very nicely (thanks @tarsil ❤️)

**Comment by tarsil** [comment]
> Thanks for your reply [@lovelydinosaur](https://github.com/lovelydinosaur), for future reference, I decided to use https://github.com/dymmond/asyncz which deals with starlette lifespans very nicely (thanks [@tarsil](https://github.com/tarsil) ❤️)

Any time 😊. We have recently created AsyncMQ if you are interested to have a look. Different cases than AsyncZ though
