### ISSUE TITLE
Did you know Netflix uses Starlette?

### ISSUE THREAD

**Issue by retnikt** [Kludex/starlette#917]
Off-topic, but I recently discovered @Netflix's [Dispatch](https://github.com/Netflix/dispatch), and poking around in the source I discovered that the app is written with (FastAPI and) Starlette! I thought you might like to know so you could use it for promotion. (if you didn't already know they used it)

**Comment by lovelydinosaur** [comment]
Yup I'd seen that, good stuff eh?
Much credit to @tiangolo for the fantastic work on top of Starlette there.
And yeah, we might do some more promo stuff in the README at some point.
