### ISSUE TITLE
Unsupport Form-style Query

### ISSUE THREAD

**Issue by abersheeran** [Kludex/starlette#936]
https://tools.ietf.org/html/rfc6570#section-3.2.8

url: `http://127.0.0.1:8000/query?name=alice&name=bob`

I want to get `["alice", "bob"]` from `request.query_params["name"]`, but only get `"bob"`.

**Comment by lovelydinosaur** [comment]
Try `request.query_params.getlist(...)`.

**Comment by abersheeran** [comment]
I don't think using `get_list` is a good way.

```python
from pydantic import BaseModel

class Query(BaseModel):
    name: List[str]

Query(**request.query_params)
```
This will throw an error. 


Perhaps when `self._dict` is generated, we should merge the list instead of using the last value to overwrite all previous values. Like this:

```python
self._dict: Dict[str, Union[List[str], str]] = {}
for k, v in self._list:
    if k in self._dict:
        if isinstance(self._dict[k], list):
            cast(List, self._dict[k]).append(v)
        else:
            self._dict[k] = [cast(str, self._dict[k]), v]
    else:
        self._dict[k] = v
```

**Comment by lovelydinosaur** [comment]
> I don't think using get_list is a good way. [...] This will throw an error.

Right, but in contrast if we had `request.query_params` return a list always, then this would fail...

```python
from pydantic import BaseModel

class Query(BaseModel):
    name: str

Query(**request.query_params)
```

And if we had `request.query_params` return a list for 2+ items, then your example would fail in the single item case.

**Comment by lovelydinosaur** [comment]
Related projects that take a similar approach as us to a multidict interface...

* https://werkzeug.palletsprojects.com/en/1.0.x/datastructures/#werkzeug.datastructures.MultiDict
* https://multidict.readthedocs.io/en/latest/multidict.html#multidict.MultiDict.getall

**Comment by abersheeran** [comment]
Just define the model as follows. `self._dict` can handle the case of one element or multiple elements.

```python
from pydantic import BaseModel

class Query(BaseModel):
    name: Union[str, List[str]]

Query(**request.query_params)
```

It is indeed important to follow consistent usage in other frameworks. Maybe we can define a multi_dict to implement the code I mentioned earlier? So that it can be used like below

```python
Query(**request.query_params.multi_dict())
```

But this is not important, just a suggestion. Because the user can also implement a function to deal with.

**Thank you very much for your reply.** This inspired me to improve my code.

**Comment by lovelydinosaur** [comment]
> Maybe we can define a multi_dict to implement the code I mentioned earlier?

Possibly - take a look at Werkzeug & multidict, and if you think that there's an interface that they're providing similar to that, which our interface doesn't, then there'd be a good case for it.

**Comment by abersheeran** [comment]
https://werkzeug.palletsprojects.com/en/1.0.x/datastructures/#werkzeug.datastructures.MultiDict.to_dict

This has a similar implementation.

**Comment by lovelydinosaur** [comment]
Gotcha. Okay, well we could accept a PR for a `to_dict(flat=[False|True])` interface, sure.
