### ISSUE TITLE
Trigger lifespan shutdown once startup fails

### ISSUE THREAD

**Issue by krzada** [Kludex/starlette#939]
Hi, when startup tasks are raising some exceptions, there is only "lifespan.startup.failed" message being sent to ASGI to prevent from further processing:
```
        except BaseException:
            if first:
                exc_text = traceback.format_exc()
                await send({"type": "lifespan.startup.failed", "message": exc_text})
            raise
```

Isn't better to await there shutdown to clear everything up like database connections (disconencting defined within shutdown) for instance?
```
        except BaseException:
            if first:
                exc_text = traceback.format_exc()
                await send({"type": "lifespan.startup.failed", "message": exc_text})
                await self.shutdown() # <----------------
            raise
```

**Comment by lovelydinosaur** [comment]
"Isn't better to"

No, I don't think we want to issue the `shutdown` message unless we've successfully started up.

From a framework POV Starlette's upcoming `lifespan` interface is a sensible way to make sure that startup/shutdown context properly unwinds in exception cases. https://github.com/encode/starlette/pull/799

Here's a quick example with an HTTPX client, and a database instance, that'll unwind one or both contexts if exceptions occur during startup.

```python
client = httpx.AsyncClient()
database = databases.Database(...)

async def lifespan(app):
    async with database:
        async with client:
            yield
```
