### ISSUE TITLE
Option to enforce CORS server-side

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#94]
Like most CORS implementations, we leave enforcement strictly as a browser concern, and just make sure that we're setting the correct headers for the browser to deal with that.

If we wanted we *could* strictly enforce the policy server-side too. That might be useful for eg. ensuring that it's easier to test, that developers get logs that reflect any cors failures, etc...

We do some similar checks in `preflight_response`, which *does* provide useful informative responses, either 400 or 200.

If we add server-side enforcement, then I think it should probably be optional, but default to being on. `enforce_server_side=True`.

We'd want to use the same sort of checking, and useful errors as we currently do in `preflight_response`, and accumulate the different error types (origin, method, headers, credentials).

Also worth noting that `preflight_response` doesn't currently check for the existence of `cookies` against `allow_credentials`. (It doesn't strictly need to but if we're going to add server-side enforcement then it ought to be used in both places.)

**Comment by alexbotello** [comment]
I think I’m partial for allowing enforcement to be strictly a browser concern. The accidental server-side enforcement was an oversight on my part. 

However, if it’s only going to be optional then maybe it should be off by default.

**Comment by lovelydinosaur** [comment]
Let's just close this off from the moment, since it's not significantly on our radar.

**Comment by lovelydinosaur** [comment]
(And since our handling is correct and in-line with most other implementations)
