### ISSUE TITLE
WebSocket max connection pool size ?

### ISSUE THREAD

**Issue by ysde** [Kludex/starlette#940]
Hi I'm using fastapi and have a server that accept websockt connections.

I'm testing how many connections (connected and not closed) that server can take.
 
I found out that when my client connections reached to 241, then the server stopped accepting new connections. Adding more client connection will directly close, but there is no messages or exceptions on the server, completely silent on the server side.

Is there any settings of the websocket's connection pool size?
I didn't find it on the document.

Or how can I increase the number of websocket connections (connected and not closed) that server can take.

Thank you very much.

**Comment by lovelydinosaur** [comment]
Is anyone else able to replicate this?
I'd expect typical numbers to be far higher than this - is there other evidence to suggest lowish limits like this, or is it possibly some other environmental factor that's problematic?

**Comment by leonh** [comment]
It's difficult to know for sure without a standardised test. But I have been stress testing websockets and found similar issues at 250-400 connections (artillery.io). Maybe its a problem in my code.....but problems arise when the rate of incoming new connections is faster than the rate at which the server can accept. The server process becomes totally stuck. Some implementation of a 503 error would help or back pressure handling / buffering to create a resilient service. I tired to limit_concurrency with config setting of Uvicorn, but it does not work in regards to websocket connections (is that expected behaviour?). I have setting limit_concurrency =10 but also have 200 open websocket connections, which seems counter intuitive to me.

**Comment by jhallard** [comment]
If this can really only handle ~200 websocket connections at one time that is a big deal, that's not nearly enough to make a production-level service around. Can anyone confirm that this is the case?

For reference, I've connected 2500+ clients to a single container running Tornado before without issue.

**Comment by jhallard** [comment]
Just wanted to report back that I'm running some tests on my (relatively modest) local system and I can easily have 1000 simultaneous websocket connections without breaking a sweat. I spin up a bunch of threads and make the thousand connections in 30 seconds or so so the rate is quite high. If anyone has any questions we can discuss my code.

**Comment by leonh** [comment]
That sounds promising, I had written off using Starlette for websockets stuff but maybe its time to reconsider. I would be interested to see your test code, config. Wondering what point does it start breaking a sweat? Are you broadcasting messages out to connected clients during the 30 second arrival period? My test involved sending the number of connected clients to all previously connected clients after each client's arrival & disconnection. Also, a "churn period" when new clients arriving and older ones are disconnecting.

**Comment by jhallard** [comment]
Unfortunately my code is for my company so I can't share it directly, I can try to come up with a minimum reproducible example for demo purposes. I will say that the functionality of the service I'm building is unique, we aren't broadcasting out to all connected clients, only ever one at a time. Essentially, I'll have 2000+ connected websocket clients and then I expose an API that allows you to send a message to a connected client via an API endpoint. Doing this, I can easily connect 2000+ websocket clients and send 200k+ messages to them from 50+ workers who are generated random messages without any hiccups at all.

**Comment by abersheeran** [comment]
Uh, dealing with the websocket pool should be a problem with ASGI servers such as uvicorn. Maybe it shouldn't be discussed under starlette.

**Comment by lovelydinosaur** [comment]
Seconding @abersheeran here.
