### ISSUE TITLE
is it possible to limit number of backgroundTask executes concurrently ?

### ISSUE THREAD

**Issue by icefluo** [Kludex/starlette#943]
I want to add more tasks to backgoundtask queue and limit concurrent execution

**Comment by lovelydinosaur** [comment]
You'll need to use `asyncio`'s primitives to provide any additional locking.

You need to be a bit careful about taking that approach in case you end up with an ever-growing backlog of long lived background tasks, so consider a timeout on acquiring any semaphore limits.
