### ISSUE TITLE
Consider removing `request.user` from HTTPConnection?

### ISSUE THREAD

**Issue by abersheeran** [Kludex/starlette#946]
#901 #875 

Perhaps extension of Request should be allowed instead of built-in `request.user` and the like.
Most of the time, users need their own authentication framework rather than using starlette, which will confuse the type hint. And, they are not used frequently, but there are many issues related to them. Deleting them may allow everyone to focus on the core functions.

@tomchristie What do you think?

**Comment by erewok** [comment]
Just one person's opinion, but I actually like the design of authentication in Starlette, and I like having the `request.user` attribute availabile. We use it a lot in our projects and it's convenient and flexible for us.

**Comment by abersheeran** [comment]
@erewok I don't mean to remove it completely, but to exist in the form of an extended request. This allows the user to freely choose whether to use it or not.

**Comment by lovelydinosaur** [comment]
This is probably better off as a chat than an issue. 😀

https://gitter.im/encode/community 

It’s already pretty open-ended, frameworks can control if and how they populate it.

**Comment by Kludex** [comment]
Ok, so... We should probably have discussions like this on GitHub issues/discussions instead of Gitter.

I'm without any reference about this :cry:
