### ISSUE TITLE
Background Thread created by WebSocketTestSession should exit when close() is called

### ISSUE THREAD

**Issue by devxpy** [Kludex/starlette#947]
Hello!

I've been trying to write tests for a starlette websocket API. 

Only one problem - the server isn't written in a way to exit nicely when a websocket is closed. 
As a result, the tests just sit there, because `websocket_connect()` won't exit until the server does.

By looking at the source, I figured that `WebSocketTestSession` is waiting for the session thread (`_run()`) to complete.

Can we please make it so that it stops the server when `close()` is called?

---

I've cobbled together a small [commit](https://github.com/devxpy/starlette/commit/41907e863220b8b34f6bcc0d8f3a8d1241ded8eb) to make this work. If you're on board with this change, I'd love to upstream this.

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/947">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/947/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/947/pledge.svg">
</picture>
</a>

**Comment by grutts** [comment]
I _think_ this is what is causing our issues as well. Every test case that runs adds another thread which sticks around, and the test suite hangs at the end. 

@devxpy I tried to use the TestClient class from your branch but I was still getting the hanging issue. Does it still work for you locally with the latest Starlette?

Anyway, it would be great if #948 could go in!

**Comment by seanwu1105** [comment]
Here is a minimal example for the issue with latest starlette: https://github.com/seanwu1105/starlette-ws-test-issue

There is no way to test a long-running WebSocket with `TestClient` now. Have not checked if https://github.com/encode/starlette/pull/948 solves the issue as it depends on an outdated starlette.
