### ISSUE TITLE
Credentialed CORS standard requests should not respond with wildcard origins

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/starlette#95]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Credentialed_requests_and_wildcards 

If a standard request is made, that includes any cookie headers, then CORSMiddleware *ought* to strictly respond with the requested origin, rather than a wildcard.

This is actually potentially a bit fiddly since we maybe also need to make sure to *set or add* Vary: Origin in those cases, in order to ensure correct cacheability.

**Comment by alexbotello** [comment]
Sounds good.

Also, on the subject of the `Vary: Origin` header, it looks like we should be setting that header for specified origins as well.

From https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#The_HTTP_response_headers

> If the server specifies a single origin rather than the "*" wildcard, then the server should also include Origin in the Vary response header — to indicate to clients that server responses will differ based on the value of the Origin request header.

**Comment by lovelydinosaur** [comment]
Gotcha, yup. Setting the Vary header on *standard* responses is complicated by the fact that it may *already* be set, so you need to make so to add-or-include "Origin" in the header value. I guess we should probably start by only considering the no credentialed "wildcard" origins part of this.

**Comment by lovelydinosaur** [comment]
Cool. Possibly use `has_cookie = "cookie" in request_headers` just to avoid any Falsey-evaluating edge cases. Also, vary: origin ought to get set in *any* case except "self.allow_all_origins".

**Comment by alexbotello** [comment]
Okay, I’ll put a PR in at some point today when I have time.
