### ISSUE TITLE
UI Progress Bar

### ISSUE THREAD

**Issue by devsetgo** [Kludex/starlette#951]
I have been looking around and so far have not found a solution to add a progress bar to an application I am building.

I have a simple form that allows a user to input a long list of "lookups". I then loop over each request (using httpx) and then provide a final list of values back. This usually takes less than a few seconds, but could also be longer. So I would like to add a simple progress bar on the UI to let the user know it is still running.

Does someone have a tip or solution on how they think I could add a progress bar to the UI?

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/starlette/issues/951">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/starlette/issues/951/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/starlette/issues/951/pledge.svg">
</picture>
</a>

**Comment by lovelydinosaur** [comment]
Heya!

Probably worth taking this to the chat room https://gitter.im/encode/community or StackOverflow. We’re (gradually) trying to keep the GitHub “Issues” specifically for bugs and planned feature work on the project itself.

Thanks so much! 💚
