### ISSUE TITLE
Config class cannot work with reused variables (${VAR_NAME})

### ISSUE THREAD

**Issue by rappongy** [Kludex/starlette#955]
Facing issue with env file where variables are reused with syntax `${VAR_NAME}`.

### .env
```
ROOT_HOST=0.0.0.0

MONGO_HOST=${ROOT_HOST}
MONGO_PORT=27017

MONGO_URL=${MONGO_HOST}:${MONGO_PORT}
```
### config.py
```
from starlette.config import Config

config = Config('.env')

MONGO_HOST = config('MONGO_HOST', cast=str)
```

`MONGO_HOST` should be "0.0.0.0" but not "${ROOT_HOST}" literally.

## My context
Python 3.6
Starlette 0.13.2

**Comment by lovelydinosaur** [comment]
Indeed - We don’t support that.

**Comment by rappongy** [comment]
Simpliest workaround to use [python-dotenv](https://pypi.org/project/python-dotenv/) package and load configs from environment directly and not from env file.

```
from dotenv import load_dotenv

# loading vars from .env file
load_dotenv(verbose=True)

# skipping argument '.env'
config = Config()
```
