### ISSUE TITLE
Unable to access info.context['background']

### ISSUE THREAD

**Issue by austincollinpena** [Kludex/starlette#957]
I'm hoping to avoid any use of Celery at the moment. In the docs there are two ways to add background tasks:

Via Graphene: https://www.starlette.io/graphql/

```python
class Query(graphene.ObjectType):
    user_agent = graphene.String()

    def resolve_user_agent(self, info):
        """
        Return the User-Agent of the incoming request.
        """
        user_agent = request.headers.get("User-Agent", "<unknown>")
        background = info.context["background"]
        background.add_task(log_user_agent, user_agent=user_agent)
        return user_agent
```

Via a JSON response: https://www.starlette.io/background/
```python
async def signup(request):
    data = await request.json()
    username = data['username']
    email = data['email']
    task = BackgroundTask(send_welcome_email, to_address=email)
    message = {'status': 'Signup successful'}
    return JSONResponse(message, background=task)
```

Does anyone know of a way to add tasks to Starlette's background with Ariadne? I am unable to return a JSONResponse in my resolver, and I do not have access to a info.context["background"]. The only thing I have attached to my context is my request object.

**Comment by bartek** [comment]
Do you by chance have an example how this would look with Ariadne? Or how you would expect it to function? I'm not particularly familiar with it and I imagine that might be the case for others.

**Comment by austincollinpena** [comment]
@bartek I don't see this being any different than with Graphene. If during the resolver of a mutation we want to execute a task in the background and return something, I'd like to be able to:

For example if I'm trying to send an authentication email it could look roughly like this:

```python
@mutation.field("authenticateEmail")
async def send_authentication_email(user, obj, info):
    email = user["email"]
    tasks = BackgroundTasks()
    tasks.add_task(mail("authenticate"))
    return True


async def mail(type: string):
    if type === "authenticate":
        send_the_email()
```

**Comment by austincollinpena** [comment]
Got the first part thanks to [Benwis](https://spectrum.chat/ariadne/general/how-to-use-background-tasks-with-starlette~74d56970-5676-4484-8586-a9384e5f4d56?m=MTU5MDk1Njc0NjE2Nw==) on spectrum.

1. Middleware:

```
@app.middleware("http")
async def dispatch(request: Request, call_next: RequestResponseEndpoint) -> Response:
    # Available as info.context["request"].state.background in your resolver. 
    request.state.background = None
    response = await call_next(request)
    if request.state.background:
        background_task = BackgroundTask(request.state.background)    
        response.background = background_task
    return response
```

2. In the resolver:

```
@query.field("getUser")
@check_authentication
async def resolve_get_user(user, obj, info):
    request = info.context["request"]
    request.state.background = testFunc
    return True


async def testFunc():
    print('I did it!')
```

However, could you help with:

1. Passing through an argument to testFunc
2. Adding multiple tasks

When calling ```request.state.background = testFunc("foo")```, (with the testFunc accepting an argument), I get: ```TypeError: the first argument must be callable```

I'm assuming the solution to #1 will help with #2 as well.

**Comment by austincollinpena** [comment]
**Solved**

Middleware:

```python
class BackgroundTaskMiddleware(BaseHTTPMiddleware):
    async def dispatch(
            self, request: Request, call_next: RequestResponseEndpoint
    ) -> Response:
        request.state.background = None
        response = await call_next(request)
        if request.state.background:
            response.background = request.state.background
        return response
```

Resolver:
```python
@query.field("getUser")
@check_authentication
async def resolve_get_user(user, obj, info):
    task = BackgroundTasks()
    task.add_task(test_func)
    task.add_task(testing_func_two, "I work now")
    request = info.context["request"]
    request.state.background = task
    return True


async def test_func():
    await asyncio.sleep(10)
    print("once!!")


async def testing_func_two(message: str):
    print(message)
```

The functions still execute synchronously, but because they're background tasks I'm not too worried.
