### ISSUE TITLE
[Feature Request] Routing with decorators

### ISSUE THREAD

**Issue by Chaostheorie** [Kludex/starlette#962]
I have recently started developing an application with starlette. But after working with Flask I kinda missed the routing with decorators. I wondered if it would be possible to create a decorator similar to Flask for routes. Starlette allows to add routes with `Starlette.add_route`. If you combine this with the parameters given in Flask's implementation (args: url, kwargs: method(s)) it shouldn't be impossible. Is there a reason against such a implementation of routing? And if not could this be implemented to make routing easier, please.

Regards,
Cobalt

**Comment by wkpn** [comment]
do you mean routing like `@app.route(...)`? if yes, it has been available for a long time. take a look at [this example](https://github.com/encode/starlette-example/blob/master/app.py)

**Comment by Chaostheorie** [comment]
This was what I meant. But this should be added to the routing section on starlette.io. thanks for the help

**Comment by lovelydinosaur** [comment]
It's been deprecated for quite a while, and the deprecation will eventually escalate into warning before being removed.

Yup, decorators for routing are an alternative style, that we *could* be promoting, but we're not. It doesn't fit in with the Starlette's design style, and having alternate differing ways to do things leads to fragmentation so I don't want to include it in addition to existing API.

**Comment by Chaostheorie** [comment]
@tomchristie So it shouldn't be used in a new project?

**Comment by lovelydinosaur** [comment]
It shouldn't no. It's deliberately no longer documented API.

**Comment by derryspann** [comment]
@tomchristie I understand your point. The route decorators has allowed me to transition from Flask to Starlette with very little overhead.
I'd hate to see that feature deprecated but I understand that users can write their own decorator system to adopt that pattern. Tough call though.

**Comment by MrPigss** [comment]
as @[hyperking](https://github.com/hyperking) said:
>users can write their own decorator system to adopt that pattern.

That is exactly what I have done.
[decoRouter](https://github.com/MrPigss/DecoRouter) brings back this functionality for those who want it.
Check it out and let me know what you think!
