### ISSUE TITLE
[Question] starlette websocket behavior

### ISSUE THREAD

**Issue by Chaostheorie** [Kludex/starlette#965]
Recently I've started developing an application (game backend server) with starlette and I'm considering using websockets for bidirectional communication. This server has (best case) a running websocket with each player and the websockets are grouped via rooms. This means though that a websocket may be open for around 20-45 minutes. Are starlette websockets able to free the corresponding thread/ worker if an request from the player is awaited?

Thanks in advance,
Cobalt

**Comment by erewok** [comment]
While I would say you should give it a try, I think a better place for this question/discussion would probably be the community gitter board at [gitter.im/encode/community](https://gitter.im/encode/community) where you may encounter people who have done similar things. Alternately, or in addition, you may also try StackOverflow, where there is a [Starlette tag](https://stackoverflow.com/questions/tagged/starlette) with some activity.

For the moment we are trying to limit Github issues to things relevant to the project that require fixing.

Thanks!
