### ISSUE TITLE
Overriding graphiql request path when behind proxy

### ISSUE THREAD

**Issue by DrPyser** [Kludex/starlette#970]
Currently, it does not seem possible to serve the graphiql client from the graphql app, behind a proxy that might modify the request url path. 

For example, my application defines an endpoint at `/graphql`, and my proxy exposes my application api under path prefix `/api/myapp`. The proxy strips the path prefix before forwarding the request, so that my application doesn't have to define all its endpoints using the proxy's routing prefix.

The GraphQLApp uses the `request.url.path` to generate the graphiql client. 
https://github.com/encode/starlette/blob/4e2f301426d47cbe2bf3c5854e1a2276b9635a9e/starlette/graphql.py#L142-L144

This path will not be valid from outside the proxy(since it does not include the path prefix), and the resulting client code doesn't work. The proxy routing prefix must be added to the request path to generate valid client code.

A simple way to address this would be to add a parameter to the GraphQLApp constructor to specify the client-side path prefix for the api.
https://github.com/encode/starlette/blob/4e2f301426d47cbe2bf3c5854e1a2276b9635a9e/starlette/graphql.py#L23-L30
```
class GraphQLApp:
    def __init__(
        self,
        schema: "graphene.Schema",
        executor: typing.Any = None,
        executor_class: type = None,
        graphiql: bool = True,
        graphiql_path_prefix=""
    ) -> None:
     self.graphiql_path_prefix = graphiql_path_prefix
     ...

    async def handle_graphiql(self, request: Request) -> Response:
        external_path = self.graphiql_path_prefix + request.url.path
        text = GRAPHIQL.replace("{{REQUEST_PATH}}", json.dumps(external_path))
        return HTMLResponse(text)
```

**Comment by DrPyser** [comment]
Alternatively, the "external_path" can be reconstructed in a middleware and stored as a `request.state.external_path` attribute. The GraphQLApp can then check that attribute.

**Comment by olgeni** [comment]
[comment removed] User error 🤠 it was an unrelated case.

**Comment by DrPyser** [comment]
Actually, ASGI spec 2.0 includes `root_path` in the scope?
https://asgi.readthedocs.io/en/latest/specs/www.html#connection-scope
> root_path (Unicode string) – The root path this application is mounted at; same as SCRIPT_NAME in WSGI. Optional; defaults to "".

Maybe this can be used instead? Not sure how a user would set this value. I assume this is the ASGI server's responsibility to offer an interface for it.

**Comment by johncrisostomo** [comment]
I am also having this issue as my app is behind an Apigee Edge proxy.

**Comment by JayH5** [comment]
Thank you for filing this issue. We have decided to deprecate GraphQL support within Starlette itself so I am going to close this issue. See #619.
