### ISSUE TITLE
Consider using https://github.com/aio-libs/multidict?

### ISSUE THREAD

**Issue by abersheeran** [Kludex/starlette#972]
Consider optional use of https://github.com/aio-libs/multidict, just like `python-multipart`.

@tomchristie What do you think? If you are interested, I think I can implement it.

**Comment by lovelydinosaur** [comment]
We've already got a multidict implementation in Starlette, so not really clear what this'd buy us.

**Comment by abersheeran** [comment]
This library uses C to get higher performance.
