### ISSUE TITLE
Get and stop Background Task

### ISSUE THREAD

**Issue by mikkelam** [Kludex/starlette#973]
Hi

Is there a way to get a background task and cancel it? I'm not able to figure it out by reading the documentation

Thanks

**Comment by retnikt** [comment]
No, the task is just immediately executed once the request finishes. You can, however, create your own background task system using [`asyncio` Tasks](https://docs.python.org/3/library/asyncio-task.html#creating-tasks), which can then be cancelled using the `.cancel()` method.

So you go from this:
```python
async def background_task():
    await do_something()

async def route(request):
    return Response("data", background=background_task())
```

to this:
```python
import asyncio

background_tasks = []

async def background_task():
    await do_something()

async def route(request):
    task = asyncio.create_task(background_task())
    background_tasks.append(task)  # now you have stored the task and can cancel it when you want
    return Response("data")
```

**Comment by mikkelam** [comment]
Thanks @retnikt, much appreciated 🙌
