### ISSUE TITLE
scope['app'] is overwritten without checking if it already exists 

### ISSUE THREAD

**Issue by leonh** [Kludex/starlette#977]
Hiya

I'm using the app lifecycle (on_startup) to dynamically modify a FastAPI app instance.  I notice that the scope['app'] is always being overridden. Which means that modifications in that happen in on_startup are lost by the time my endpoint handler is called.

starlette/applications.py is called multiple times during a request-response cycle.

```
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        scope["app"] = self
        await self.middleware_stack(scope, receive, send)

```

should this altered be to preserve an already set scope["app"] ?

i.e.
```
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if "app" not in scope:
            scope["app"] = self
        await self.middleware_stack(scope, receive, send)

```

I notice that in starlette/routing.py scope["router"] is checked for existence before being set.
Is there a good reason for scope["app"] to be rewritten on each call?

**Comment by lovelydinosaur** [comment]
I'm going to close this as stale.

But we do need to do an audit of what additional info we're adding to the `scope` and where. We're not in line with the ASGI spec here, and it'd be good to at least *document* the extra stuff we're including, and ideally namespace it all. That'll all need some careful discussion and thinking about.
