### ISSUE TITLE
When raise exception I got graphql error

### ISSUE THREAD

**Issue by Bunlong** [Kludex/starlette#982]
I just move from using `responder` library to `starlette`. I got the graphql error when I raise exception.

Server:

```js
app = Starlette(debug=True, routes=[
    Route('/', show_version),
    Route('/healthz', check_health),
    Route('/graphql', GraphQLApp(schema=schema)),
])

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=9090)
```

Schema:

```
...

raise Exception('Something wrong')

...
```

Error:

![Screenshot from 2020-06-24 13-40-48](https://user-images.githubusercontent.com/1308397/85509501-55a05100-b620-11ea-895b-615e7471d703.png)

What I expect is it return error message `Something wrong` with `the http status 200` instead of error above. Thanks!

**Comment by chrisbrake** [comment]
I've run into this issue as well.

This appears to be the code responsible.
https://github.com/encode/starlette/blob/e4307065ea6dbe708fba9643d14fe7adfff06d46/starlette/graphql.py#L112-L118

Looks to be more or less original to the implementation here, it came along with this commit: https://github.com/encode/starlette/commit/315a21be85607e43f980e16080637b550d25e5a5.

Maintainers, would an acceptable solution be to add an option to specify the status code to use when errors exist?
With the default being the current behavior of course.

**Comment by JayH5** [comment]
Thank you for filing this issue. We have decided to deprecate GraphQL support within Starlette itself so I am going to close this issue. See #619.
