### ISSUE TITLE
[Feature] Display `locals()` and `globals()` in 500 page

### ISSUE THREAD

**Issue by abersheeran** [Kludex/starlette#983]
In DEBUG mode, the error page displays variables like Sentry, which should make it easier to resolve the error.

![image](https://user-images.githubusercontent.com/25364828/85678052-b1d7a380-b6fa-11ea-9791-bd1e136bbc30.png)

@tomchristie What do you think?

**Comment by lovelydinosaur** [comment]
Let's close this off with the same take as https://github.com/encode/starlette/pull/1386

There's lots of scope for third party packages for improved error handlers.
