### ISSUE TITLE
Context Values

### ISSUE THREAD

**Issue by MabaKalox** [Kludex/starlette#987]
Why I can't add context values to GraphQLApp.handle_graphql? I mean something like that:
graphql_app.handle_graphql(request=request, context_values={'db_session': session})

**Comment by chrisegner** [comment]
Looks like another request for #591 (which is closed but contains a workaround)

**Comment by JayH5** [comment]
Thank you for filing this issue. We have decided to deprecate GraphQL support within Starlette itself so I am going to close this issue. See #619.
