### ISSUE TITLE
[Feature] Reason for websocket.close

### ISSUE THREAD

**Issue by Chaostheorie** [Kludex/starlette#991]
I've recently started actively developing with websockets in starlette. When closing a websocket you can provide a code e.g. 1000, 1008 … to tell the client the basic reason. But the websocket protocol allows the developer to also give UTF-8-encoded data as a complementary description/ reason. This would be useful in multiple cases such as mentioning the specific violitioan for code 1008 (POLICY VIOLIATION). [Websockets](https://websockets.readthedocs.io/en/stable/api.html?highlight=reason#websockets.protocol.WebSocketCommonProtocol.close) supports this too and their [implementation](https://websockets.readthedocs.io/en/stable/_modules/websockets/protocol.html#WebSocketCommonProtocol.close) could maybe help.

Specification: [https://tools.ietf.org/](https://tools.ietf.org/html/rfc6455#section-5.5.1)

**Comment by Chaostheorie** [comment]
Created basic implementation in #992

**Comment by abersheeran** [comment]
https://asgi.readthedocs.io/en/latest/specs/www.html#close-send-event

This is not in the ASGI protocol, so it cannot be achieved.

**Comment by lovelydinosaur** [comment]
Thanks @abersheeran yup seems correct to me too.

"code" is part of the ASGI spec, but "reason" isn't. If the ASGI spec evolves there at some point, then we could consider it.

**Comment by Armster15** [comment]
["reason" has been added to the ASGI spec.](https://github.com/django/asgiref/pull/235) Will this library add it now as well?

**Comment by Chaostheorie** [comment]
The code from #992 should still be able to be used … Well, up for grabs

**Comment by Kludex** [comment]
Should we wait it to be release on the ASGI website? In any case, PR is more than welcome. Thanks @Chaostheorie :)

**Comment by Armster15** [comment]
The `reason` attribute is also on the ASGI documentation https://asgi.readthedocs.io/en/latest/specs/www.html#close-send-event

**Comment by Kludex** [comment]
When I wrote my comment, it was not :)

They just fixed the docs (I asked them the reason :sweat_smile:).
