### ISSUE TITLE
Feature request: Add after_startup and before_shutdown events

### ISSUE THREAD

**Issue by drjackild** [Kludex/starlette#993]
Hi there!

There is a common situation when you need to make some operations after application startup. For example - when you want to create models before each test case. For now, there is no way to make it happen in Starlette if your ORM needs to be already initialized before model creation.

```python
@pytest.fixture()
def client(event_loop):
    """
    Make a 'client' fixture available to test cases.
    """
    # Our fixture is created within a context manager. This ensures that
    # application startup and shutdown run for every test case.
    with TestClient(app) as test_client:
        event_loop.run_until_complete(database.gino.create_all())
        yield test_client
        event_loop.run_until_complete(database.gino.drop_all())
```
gets:
```
ERROR tests/api/test_item_types.py::test_item_types - gino.exceptions.UninitializedError: Gino engine is not initialized.
```

On the other hand, we have Sanic, which has this signal, and such behavior as above is not a problem at all. I hope we can discuss this point and probably define some signals inside Starlette. Thanks!

**Comment by lovelydinosaur** [comment]
So you, ought to be able to use the `on_startup` and `on_shutdown` events in the same way. I realise they're not semantically exactly *before startup* etc., but you can control the order of events that happen within them, so the effect ought to be the same, no?

**Comment by Garito** [comment]
The point is to run code only once no matter how many workers there are

**Comment by lovelydinosaur** [comment]
I haven't seen a sufficient rationale of why `on_startup`/`on_shutdown` isn't already sufficient.
