### ISSUE TITLE
How to use url_for in tests

### ISSUE THREAD

**Issue by PeterJCLaw** [Kludex/starlette#995]
From what I can see in the docs, the `url_for` method is only provided as part of an incoming `Request` object. This means that tests need to either create their own lookup mechanism or hard-code the urls they're working with.

It would be great if there was a way to use url reversing in tests in order to both support easier creation of placeholdered urls as well as avoiding needing to hard-code urls in tests.

**Comment by erewok** [comment]
Do you have an `Starlette` application instance available in your tests? If so, you may be able to use `app.url_path_for` to reverse URLs. 

Here's a link to the method defined on the `Starlette` class (it calls out to `url_path_for` on the `Router` object): https://github.com/encode/starlette/blob/a42657db527f17ed5f310e00b71c9e76e9063e02/starlette/applications.py#L97

You can see examples of this in use in the routing tests: https://github.com/encode/starlette/blob/f12e237da5ff4e19531d71340b2208f613206882/tests/test_routing.py#L154

Here's an absolute URL in a test as well: https://github.com/encode/starlette/blob/f12e237da5ff4e19531d71340b2208f613206882/tests/test_routing.py#L227

**Comment by PeterJCLaw** [comment]
Aha, thanks. I'd missed that in the routing docs.
