### ISSUE TITLE
[feature request] Graphql file upload

### ISSUE THREAD

**Issue by himat** [Kludex/starlette#996]
It's essential to support file upload when using the graphql module in starlette.
Some people have tried to add it to this project, but it hasn't been approved which is bad.
https://github.com/encode/starlette/pull/215
https://github.com/encode/starlette/pull/615

**Comment by JayH5** [comment]
Thank you for filing this issue. We have decided to deprecate GraphQL support within Starlette itself so I am going to close this issue. See #619.
